### ISSUE TITLE
Reposition cursor to bottom-right corner when resizing

### ISSUE THREAD

**Issue by hertg** [leftwm/leftwm#1003]
### Describe the enhancement

When resizing a window, the cursor should automatically jump to the windows' bottom right corner (like in dwm).

This prevents the awkward situation where the cursor is no longer hovering the window that is being resized, and prevents the issue where a window can not be made any smaller if the cursor already reached the top-left corner of the screen during resize.

### How important is this enhancement to you?

Would be nice to have

### How important do you think is this enhancement for the average LeftWM user?

Would probably be nice to have

**Comment by VuiMuich** [comment]
In general I like this idea, just want to leave a note for potential implementors, to be mindful about how to update the cursor while resizing, as this might easily feel jiggerish.

**Comment by hertg** [comment]
We could also make the behavior configurable `disable_cursor_reposition_on_resize` (or something shorter) for people that don't want that.
