### ISSUE TITLE
Unable to navigate around workspaces. 

### ISSUE THREAD

**Issue by b4skyx** [leftwm/leftwm#102]
I'm unable to get ``FocusWorkspacePrevous`` and ``FocusWorkspaceNext`` working due to which I can't switch workspaces through key bindings. 

Also, is there a log of errors for leftwm? Whenever there is an error in configuration file, it rolls back to the default config without a notification.

**Comment by lex148** [comment]
LeftWM has several ways to log. I would recommend logging with journald. It is definitely the easiest option. To do this you will need to compile with the journald feature
```
cargo build --features=journald
```
This will be very minimal logging by default. You can edit the file 
./src/bin/leftwm-worker.rs
to enable (trace / debug / ...) logging

As for  ``FocusWorkspacePrevous`` and ``FocusWorkspaceNext`` would you please double check your config file for me. I believe by default these two do NOT use the mod key, so the key combo would be 
```
(Ctrl + Left) or (Ctrl + Right)
```

**Comment by b4skyx** [comment]
Are the window tags and workspaces different things? Cause, `Mod+#` seems to be switching tags without any issues while `Mod+Left` or `Mod+Right` isn't moving the tag from left to right. 
I tried running leftwm in an xfce4 session and my number of workspaces was replaced by number of tags, so I assumed they were the same.

Also, I'm having issues in setting a conky widget. It appears as a window rather than as a dock staying on the back. I tried changing the conky class in config but no leads. Is there a template to be used in `$config/leftwm/themes/current/up` for conky  to set it properly instead?

**Comment by lex148** [comment]
Yes there is a difference. You can think of workspaces as the equivalent to monitors. For example I have two monitors and two workspaces. These workspaces don't change while LeftWM is running. Tags are like a virtual desktop in gnome. Tags holds a collection of windows.  Mod+(1-9) Tells LeftWM to make the current workspace display a different tag.


Here is a silly theme I made a while back that uses conky. It should have a good working conky config.
[https://github.com/lex148/leftwm_themes/tree/master/tng](https://github.com/lex148/leftwm_themes/tree/master/tng)

**Comment by b4skyx** [comment]
Ah thanks. After tweaking a little, I got things working.
