### ISSUE TITLE
Borders are 1px bigger than theme config

### ISSUE THREAD

**Issue by TH3-S4LM0N** [leftwm/leftwm#1030]
### Describe the bug

Read #1029 first for a bit of context

I have a config with borders at 1px and a program I made to show quick window info. It's intended to be 1280x720.
```
---Window Debug Info---
Requested 1280x720
Physical 1278x718
```
But as you can see it's 2 pixels smaller.

### OS / Distro

Arch

### LeftWM Check

```text
:: LeftWM version: 0.4.1
:: LeftWM git hash: 438b073
:: Enabled features: default journald-log lefthk lefthk-core tracing-journald
:: Checking feature dependencies . . .
    -> journald-log OK
    -> lefthk OK
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```
```

**Comment by RGFTheCoder** [comment]
There are borders on both sides of the window, so 1px on the left and 1px on the right is 2px overall horizontal space.
