### ISSUE TITLE
Blank screen!

### ISSUE THREAD

**Issue by nurmohammed840** [leftwm/leftwm#1034]
### Describe the bug

I just install [leftwm](https://github.com/leftwm/leftwm) with cargo install.

And login to leftwm, It display nothing (blank purple-ish color  screen) and mouse cursor.

How do I quit ? And reload i3wm back ?

### Steps to reproduce (optional)

- `cargo install leftwm`
- copy `leftwm.desktop` file into `/usr/share/xsessions` dir
- logout from `i3wm` and load `leftwm`

### OS / Distro

Endeavour OS (Arch)

**Comment by VentGrey** [comment]
The `README.md` file states the following:

> You should now see LeftWM in your list of available window managers. At this point, expect only a simple black screen on login. For a more customized look, install a theme.

LeftWM doesn't come with a “minimal” rice out-of-the box. It's bare-bones, your keybinds and not much more.

If you want to quit leftwm use the default keybind: <kbd>Mod + Shift + X</kbd>

You'll be able to select i3 from your login manager. If you are not using a login manager, edit your `xinit` file.

If you want a starting point for LeftWM, consider installing any [community theme](https://github.com/leftwm/leftwm-community-themes) you find suitable for your needs :), or you can try to learn to rice it from scratch.

**Comment by hertg** [comment]
As already pointed out, that is expected behavior so I'll close this.
Thanks @VentGrey for chiming in so fast :)
