### ISSUE TITLE
Ubuntu 22.04 Blank Screen

### ISSUE THREAD

**Issue by slsxo** [leftwm/leftwm#1047]
### Describe the bug

After startup shows gray blank screen and mouse cursor. Shortcuts not working.
![Screenshot from 2023-03-13 22-52-50](https://user-images.githubusercontent.com/104219168/224830411-8267e908-dbaf-4d69-89b3-fcc89baffac3.png)

### Expected behavior (optional)

Error should be shown atleast.

### OS / Distro

Ubuntu 22.04

### LeftWM Check

```text
:: LeftWM version: 0.4.1
:: LeftWM git hash: NONE
:: Enabled features: default journald-log lefthk lefthk-core tracing-journald
:: Checking feature dependencies . . .
    -> journald-log OK
    -> lefthk OK
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK 
:: Checking theme . . .
    -> Theme OK
```

**Comment by VentGrey** [comment]
Does `~/.xsession-errors` show anything relevant? None of the default keybinds work?

**Comment by VuiMuich** [comment]
@slsxo did switching to PopOS solve the issue for you?

**Comment by slsxo** [comment]
@VuiMuich Unfortunately no, same behavior. 
Leftwm installed via cargo, it comes without themes tho, so i used one of yours, Epitaph to be exact, leftwm-check passes, but still all i am seeing is a blank gray screen and a cursor, .xsession-errors empty. 
Gimme some hints where i can put my eyes on, maybe it's just  something wrong with me.

**Comment by VentGrey** [comment]
If you installed the pinned version from leftwm-theme. That's an old version which prolly doesnt work 😅 that theme needs some post-install things to get running.

**Comment by VuiMuich** [comment]
> @VuiMuich Unfortunately no, same behavior. 
> 
> Leftwm installed via cargo, it comes without themes tho, so i used one of yours, Epitaph to be exact, leftwm-check passes, but still all i am seeing is a blank gray screen and a cursor, .xsession-errors empty. 
> 
> Gimme some hints where i can put my eyes on, maybe it's just  something wrong with me.

I see. Can you launch a Terminal with `DISPLAY=:0 gnome-terminal`?

**Comment by VentGrey** [comment]
@VuiMuich I tested my theme on two VM's and I don't know if this can be ruled as a theme bug or not. Without some dependencies if you install Epitaph from `leftwm-theme` two things can happen apparently.

1- Leftwm exits to the session manager since the `up` script didn't run properly.
2- The script continues it's execution for whatever reason and a blank screen does show up, however, both default and Epitaph keybinds work properly.

I could `set -euo pipefail` on those scripts to ensure "proper" failure :sweat_smile:

**Comment by VuiMuich** [comment]
@VentGrey hmm, your theme is pretty well documented, so failing from missing dependencies is not entirely a bug imo, as it is debatable whats more troubling: starting a broken session or refusing to start a session at all.
If you know your ways around, both are equally fixable and if you are new to `leftwm` both are equally frustrating :stuck_out_tongue_winking_eye: 

@slsxo as VentGrey pointed out, you might be missing dependencies for this theme. A very minimal theme simply to test if your WM is basically is working is `serika`.
