### ISSUE TITLE
nixpkgs package broken since version 4.0.0

### ISSUE THREAD

**Issue by thled** [leftwm/leftwm#1049]
### Describe the bug

The distributed package of LeftWM for the Nix package manager does not patch the binary for the new hotkey management.
As a result you cannot use hotkeys.

I opend a [PR](https://github.com/NixOS/nixpkgs/pull/197018) to fix this a while ago but there seems to be no active maintainers. Is someone here able to review/merge my PR over there?

### Expected behavior (optional)

I can use hotkeys with the standart installation using the Nix package manager.

### OS / Distro

NixOS

### LeftWM Check

```text
-
```

**Comment by Eskaan** [comment]
@VuiMuich @hertg maybe one of you two wants to review the one-line change over there? It looks fine to me, not only including the `leftwm*` but also the `left*` binaries like lefthk-worker.

**Comment by hertg** [comment]
I have no idea how nixos works. Does that rule just apply to our binaries anyway? If not, I'm not sure we can claim any binary that starts with `left*` lol

**Comment by VuiMuich** [comment]
I just commented on the PR pining one of the last contributors who merged another PR :stuck_out_tongue:

**Comment by VuiMuich** [comment]
> I have no idea how nixos works. Does that rule just apply to our binaries anyway? If not, I'm not sure we can claim any binary that starts with `left*` lol

But this just is relevant to any binary in the build directory, no?
