### ISSUE TITLE
Create a community-themes repo for easier themes/customizations.

### ISSUE THREAD

**Issue by b4skyx** [leftwm/leftwm#105]
Creating a separate repository comprising of community built themes/setups would be a good way of showcasing the capabilities and creativity of different users.
The community themes repo could be maintained using sub-modules or pull request based for users who want their themes to be added to provide version consistency.

**Comment by PVautour** [comment]
I'd be very interested in this. I worked a bit on a theme that I think would be worth sharing [here](https://github.com/PVautour/leftwm-theme-orange-forest)

I'm not super familiar with submodules, bit i could alway give it a try if the main project devs dont want the have to manage it.

**Comment by lex148** [comment]
Ok, I think this is a GREAT idea. I really can't wait to see what you come up with!

Here is the start of the repo:
[https://github.com/leftwm/leftwm-community-themes](https://github.com/leftwm/leftwm-community-themes)

**Comment by lex148** [comment]
If you guys would prefer the submodules route we could do that instead of direct inclusion. 
I will leave that up to you.

**Comment by b4skyx** [comment]
Oh neat. I'll be making a pr with a customization of mine in a while.
I personally prefer the submodules as the issues would be easier to address imo.

**Comment by lex148** [comment]
> Oh neat. I'll be making a pr with a customization of mine in a while.
> I personally prefer the submodules as the issues would be easier to address imo.

I think I agree

**Comment by PVautour** [comment]
Thanks for taking care of it guys and/or gals! I'm sorry i could get to it earlier. Ill just tweak a few things on mine and ill be sure to add it to the repo!

**Comment by PVautour** [comment]
@b4skyx This issue can probably be closed now :)
