### ISSUE TITLE
Floating windows dragged over workspace border move to the first tag 

### ISSUE THREAD

**Issue by Eskaan** [leftwm/leftwm#1054]
### Describe the bug

Moving floating windows over the workspace border makes them move to the first tag. I think it only happens after half of the window went over (estimate), which hints to me that there is some wrong math in the code. 

### Expected behavior (optional)

The window should stay on the tag as long as part of it is visible.

### Steps to reproduce (optional)

1. Get floating window
2. Drag floating window near border of the screen
3. Let go
4. Floating window moves to the first tag

### Relevant log output (optional)

```text
(no related logs printed)
```

### OS / Distro

Arch Linux 6.2.9-zen1-1-zen 

### LeftWM Check

```text
:: LeftWM version: 0.4.1
:: LeftWM git hash: 224807f-modified
:: Enabled features:  journald-log lefthk
:: Checking feature dependencies . . .
    -> journald-log OK
    -> lefthk OK
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```

**Comment by VuiMuich** [comment]
Was this report a reaction to a mention of this on discord or is this an independent report?

**Comment by Eskaan** [comment]
I experienced it myself multiple times by now (confusing if you don’t expect it and the window is gone). I filed this as a reaction on the mention in another issue here on GitHub.

**Comment by VuiMuich** [comment]
Oh, that was it.. at least I remembered to have it read elsewhere :wink:
