### ISSUE TITLE
Media keys can't be bound

### ISSUE THREAD

**Issue by dlip** [leftwm/leftwm#1057]
### Describe the bug

`ERROR: Key `XF86AudioPlay` is not valid for keybind`

### Expected behavior (optional)

Media keys should be a valid key to bind to eg.

- XF86AudioPlay
- XF86AudioNext
- XF86AudioPrev
- XF86AudioStop
- XF86AudioLowerVolume
- XF86AudioRaiseVolume
- XF86AudioMute
- XF86MonBrightnessUp
- XF86MonBrightnessDown

### OS / Distro

nixos

### LeftWM Check

```text
:: LeftWM version: 0.4.0
:: LeftWM git hash: NONE
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
ERROR: Key `XF86AudioLowerVolume` is not valid for keybind Keybind { command: Execute, value: "pactl set-sink-volume @DEFAULT_SINK@ -5% && volnoti-show $(pamixer --get-volume)", modifier: Some(List(["modkey"])), key: "XF86AudioLowerVolume" }
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```

**Comment by VuiMuich** [comment]
Please refer to this list of Keysyms: https://github.com/leftwm/lefthk/blob/76da11c962df6351a364aad7f456c94953a06f6b/lefthk-core/src/xkeysym_lookup.rs#L1053

**Comment by dlip** [comment]
That works, thanks!

**Comment by Oreolek** [comment]
Seconded. You could add some aliases so people wouldn't have to search for this and dig into the source code linked from Github issues. `XF86AudioLowerVolume` is much more widespread spelling than `XF86XK_AudioLowerVolume`

**Comment by VuiMuich** [comment]
> Seconded. You could add some aliases so people wouldn't have to search for this and dig into the source code linked from Github issues. `XF86AudioLowerVolume` is much more widespread spelling than `XF86XK_AudioLowerVolume`

Actually this might work:
```
…
"XF86XK_AudioPlay" | "XF86AudioPlay" => Some(XF86XK_AudioPlay),
…
```
