### ISSUE TITLE
Suggestion for leftwm to act like XMonad in terms of configuration.

### ISSUE THREAD

**Issue by Joe23232** [leftwm/leftwm#106]
@lex148  Hey man I wanted to give a suggestion,with XMonad, it allows the user to configure it the way they like it through the haskel language. So like XMonad is essentially a high level library which allows users to easily script their own window manager out of XMonad. I wanted to suggest like if leftwm could do the same thing where it can be configured through the config.toml file while the user has the ability to use Rust (using high level functions) to modify leftwm even further if they so please to do so?

**Comment by lex148** [comment]
This is a very interesting thought. because rust is compiled instead of interpreted like Haskel It might be a little harder to do, but I will put some thought into how it could be accomplished

**Comment by Joe23232** [comment]
Yes this is true but I believe in order for it to be truly cusotmisable it should have such a feature.

**Comment by adimit** [comment]
@lex148 Just to clear out some misconceptions here: Haskell is not interpreted, it's AOT-compiled, just like Rust. XMonad is compiled, and runs from its binary.

**Comment by Stanislav-Lapata** [comment]
@Joe23232 You can probably [penrose](https://github.com/sminez/penrose)

**Comment by Joe23232** [comment]
Oh yeah I have heard of it.

**Comment by MarkuBu** [comment]
You can add something like rhai to leftwm

https://crates.io/crates/rhai

**Comment by Joe23232** [comment]
@MarkuBu Does that add overhead
?

**Comment by MarkuBu** [comment]
What type of overhead do you mean? It obviously adds some overhead and it might not be the fastest scripting language. 

It is not compiled like LuaJIT, but it is written in Rust and the syntax is similar to Rust.

**Comment by Joe23232** [comment]
I see, thanks

**Comment by AeroNotix** [comment]
I see a few people have wanted a feature like this in LeftWM.

Does it have to be that complicated, e.g. by added an embedded interpreter?  I added a very braindead simple configuration option, `load_from_exec` in https://github.com/AeroNotix/leftwm/commit/da7946fdd9caf9d64aeff666d04a54838e9fbd86 which executes the command in that configuration string and interprets the stdout of that command as TOML.

I know the linked commit is lacking some error handling, and logging for when the executed command has issues - or doesn't return proper TOML, would be interested if a "dyanmic config" for leftwm would be accepted in this form? If so, I can continue hacking on it to make it more solid.

I too, find tinkering with the toml files quite tedious. There are huge blocks of repetitive sections, especially around tag key binds, application launcher binds, etc.

Now, is the solution dynamic configuration, or is the solution simpler configuration itself? TOML, I know is "standard" in Rust, but it does get quite verbose to represent simple constructs. Anyway, perhaps that conversation is not for this issue.

Willing to open a PR with the above to do more work on it.

**Comment by VuiMuich** [comment]
Inspired by the discussion over at [eww](https://github.com/elkowar/eww/discussions/171) I wanted to start a discussion (btw: thx @lex148 for activating this feature) about a config language switch along with #292. 
From what I have learned in eww's discussion `dhall` could be an interesting candidate for leftwm.

**Comment by hertg** [comment]
I'm closing this for now, as we near the integration of `ron` with #793
