### ISSUE TITLE
Field codes from Exec string are not removed when autostarting an app

### ISSUE THREAD

**Issue by realGWM** [leftwm/leftwm#1061]
### Describe the bug

Field codes from Exec string are not removed when autostarting an app, which leads to field code passed to the application being started (which is not desirable as applications may try to do something with the argument, for example to open it as a link in case of a browser).
![before](https://user-images.githubusercontent.com/19240800/235694038-ec6020c6-0579-4840-910f-6d4b5d148dc9.png)

### Steps to reproduce (optional)

Add a desktop entry to autostart folder with Exec string that contains '%u' field code or similar, for example `Exec=/usr/lib/librewolf/librewolf %u`.

### OS / Distro

EndeavourOS

### LeftWM Check

```text
:: LeftWM version: 0.4.1
:: LeftWM git hash: 3723a8e
:: Enabled features:  journald-log lefthk
:: Checking feature dependencies . . .
    -> journald-log OK
    -> lefthk OK
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
ERROR: No theme folder or symlink `current` found.
```

**Comment by realGWM** [comment]
>     * ~What is a "field code"~
>       nvm. I [found it](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables).
>       What exactly is `%u` supposed to expand to here? I would think that you just want it to start librewolf, right?

* I don't know what exactly is the intention of `%u` in this example (although I would guess this is for URLs intended to be opened by the browser?), as the desktop entry for librewolf comes from the installed package (not written by me). What I want is for librewolf to be autostarted when starting LeftWM, so I copied (or symlinked) its desktop entry file to autostart folder. It works but with the annoyance of librewolf trying to open `/home/me/%u` "link" (which I could easily fix of course by modifying the desktop entry file, but I don't think this is appropriate solution as I would need to edit all such files).

>     * Why just leave the _field code_ out of the exec string?

Well, it's not explicitly specified, but I think this is what should be done when there's nothing to expand field codes to? "A number of special field codes have been defined which will be expanded by the file manager or program launcher when encountered in the command line"

**Comment by Eskaan** [comment]
Ah, I understand now. So this is the (not we-specific) xdg-autostart folder. And you use it by linking desktop files into there. Guess we‘ll have to find a regex that removes the arguments.

Thanks for answering my questions :)

**Comment by VuiMuich** [comment]
> Ah, I understand now. So this is the (not we-specific) xdg-autostart folder. And you use it by linking desktop files into there. Guess we‘ll have to find a regex that removes the arguments.
> 
> 
> 
> Thanks for answering my questions :)

How about this?
```regex
r"\s%[fFuUdDnNickvm].*?"gm
```
