### ISSUE TITLE
Keybinds stop working after keyboard layout change

### ISSUE THREAD

**Issue by bzgec** [leftwm/leftwm#1063]
### Describe the bug

I am currently using two keyboard layouts. However, when I switch between layouts, the keybindings stop working. It appears that leftwm only recognizes the layout with which it was initially started. I have noticed that if I change the keyboard layout (and the shortcuts stop working), I can run the `leftwm command SoftReload`command to make them work with the new layout.

Is there an alternative to using the `leftwm command SoftReload` command?

### Expected behavior (optional)

Shortcuts work with new keyboard layout without running `leftwm command SoftReload`.

### Steps to reproduce (optional)

1. Switch keyboard layout (change position of keys eq. switch `y` and `z`).
2. Use shortcut with `y` or `z` key - this keybind doesn't work.
3. Run `leftwm command SoftReload`
4. Use shortcut with `y` or `z` key - now this keybind works.

### OS / Distro

Linux arch 6.3.1-arch1-1

### LeftWM Check

```text
:: LeftWM version: 0.4.1
:: LeftWM git hash: 438b073
:: Enabled features: default journald-log lefthk lefthk-core tracing-journald
:: Checking feature dependencies . . .
    -> journald-log OK
    -> lefthk OK
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```

**Comment by VuiMuich** [comment]
Sorry, that this was left unanswered for so long! :bow:

How do you switch layouts?
I am using two layouts as well, one `custom` (called `vou` by Maximilian Schillinger) and `de/T3`. I start my system with T3 and switch with `xkb-switch custom` in an autostart script.
For me the keybinds stay always the same (like the `de` layout) and I actually like it this way, so the muscle memory doesn't need to be aware of the current layout.

For reference here is my locales:
```sh
~ >>> localectl
System Locale: LANG=en_GB.UTF-8
               LC_TIME=de_DE.UTF-8
               LC_MONETARY=de_DE.UTF-8
               LC_PAPER=de_DE.UTF-8
               LC_ADDRESS=de_DE.UTF-8
               LC_MEASUREMENT=de_DE.UTF-8
    VC Keymap: vou
   X11 Layout: de,custom
    X11 Model: pc105
  X11 Variant: T3,vou
  X11 Options: grp:ctrls_toggle
```

**Comment by bzgec** [comment]
I am currently using the regular `si` layout as well as a custom layout called [si_colemak](https://gitlab.com/bzgec/keymap/-/blob/master/xkb/symbols/si_colemak). To enable the custom layout, I copied the `si_colemak` file to `/usr/share/X11/xkb/symbols/`. I switch between these layouts using a custom script that essentially calls `setxkbmap si` or `setxkbmap si_colemak`.

The reason for switching layouts is that on my laptop, I prefer using `si_colemak`. However, when I connect my laptop to a custom keyboard that has the same layout as `si_colemak`, but the host PC needs to be set to `si` in order for it to function correctly.

**Comment by bzgec** [comment]
I have made some adjustments in my configuration. Instead of setting the keyboard layout in the `up` script, I now set it manually after booting up. After that, I reload leftwm, and it seems to work fine for both my laptop keyboard (`si_colemak`) and my custom keyboard (`si`). I no longer need to manually change the layout when switching from laptop to custom keyboard.
