### ISSUE TITLE
Window spawns on last tag

### ISSUE THREAD

**Issue by MaKaNu** [leftwm/leftwm#1065]
### Describe the bug

For a few applications popup windows are spawning always on the last tag even if the parent window is on another tag. Example for this is `virt-manager`. If I want to delete a VM the software asks if I really want to delete  it. This Window is spawned on my tag number 9.

Is this a similar issue as with size-hints?

### Expected behavior (optional)

The popup should spawn on the same tag as the parent window.

### Steps to reproduce (optional)

1. right click on an existing VM
2. select delete
3. and ... nice could not reproduce it now. I reproduced this several times before and now nothing.

## EDIT
Okay finally. I had a mistake with reproduction yesterday.

1. right click on an existing VM
2. select delete
3. Accept delete options.
4. ...and switch to the last workspace to accept the delete warning.

I gathered with xprop the 3 different windows which are opened at this moment:

**virt-manager**
```bash
_NET_WM_USER_TIME(CARDINAL) = 13214442
_NET_WM_DESKTOP(CARDINAL) = 1
WM_STATE(WM_STATE):
		window state: Normal
		icon window: <field not available>
_NET_WM_STATE(ATOM) =
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x100000b
		bitmap id # of mask for icon: 0x1000013
		window id # of group leader: 0x1000001
_GTK_THEME_VARIANT(UTF8_STRING) =
XdndAware(ATOM) = BITMAP
_NET_WM_ICON(CARDINAL) =
_NET_WM_OPAQUE_REGION(CARDINAL) = 0, 0, 2554, 1404
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 16777225, 16777226
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x1000008
WM_CLIENT_LEADER(WINDOW): window id # 0x1000001
_NET_WM_PID(CARDINAL) = 22017
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "latitude7430-lit-01"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 327 by 140
		program specified base size: 0 by 0
		window gravity: Center
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "virt-manager", "Virt-manager"
WM_ICON_NAME(STRING) = "Virtual Machine Manager"
_NET_WM_ICON_NAME(UTF8_STRING) = "Virtual Machine Manager"
WM_NAME(STRING) = "Virtual Machine Manager"
_NET_WM_NAME(UTF8_STRING) = "Virtual Machine Manager"
```

**delete-options**
```bash
_NET_WM_DESKTOP(CARDINAL) = 1
WM_STATE(WM_STATE):
		window state: Normal
		icon window: <field not available>
_NET_WM_STATE(ATOM) =
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x1000308
		bitmap id # of mask for icon: 0x100030e
		window id # of group leader: 0x1000001
_GTK_THEME_VARIANT(UTF8_STRING) =
XdndAware(ATOM) = BITMAP
_NET_WM_ICON(CARDINAL) =
_NET_WM_OPAQUE_REGION(CARDINAL) = 0, 0, 519, 350
WM_TRANSIENT_FOR(WINDOW): window id # 0x1000007
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 16777990, 16777991
_NET_WM_USER_TIME(CARDINAL) = 13206491
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x1000305
WM_CLIENT_LEADER(WINDOW): window id # 0x1000001
_NET_WM_PID(CARDINAL) = 22017
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "latitude7430-lit-01"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		program specified minimum size: 519 by 350
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "virt-manager", "Virt-manager"
WM_ICON_NAME(STRING) = "Delete Virtual Machine"
_NET_WM_ICON_NAME(UTF8_STRING) = "Delete Virtual Machine"
WM_NAME(STRING) = "Delete Virtual Machine"
_NET_WM_NAME(UTF8_STRING) = "Delete Virtual Machine"
```
**delete-warning-message**
```bash
_NET_WM_DESKTOP(CARDINAL) = 8
WM_STATE(WM_STATE):
		window state: Normal
		icon window: <field not available>
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MODAL, _NET_WM_STATE_SKIP_TASKBAR
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x1000935
		bitmap id # of mask for icon: 0x100093b
		window id # of group leader: 0x1000001
_GTK_THEME_VARIANT(UTF8_STRING) =
XdndAware(ATOM) = BITMAP
_NET_WM_ICON(CARDINAL) =
_NET_WM_OPAQUE_REGION(CARDINAL) = 0, 0, 422, 198
WM_TRANSIENT_FOR(WINDOW): window id # 0x1000304
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 16779571, 16779572
_NET_WM_USER_TIME(CARDINAL) = 13201963
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x1000932
WM_CLIENT_LEADER(WINDOW): window id # 0x1000001
_NET_WM_PID(CARDINAL) = 22017
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "latitude7430-lit-01"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		program specified minimum size: 422 by 198
		program specified maximum size: 422 by 198
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "virt-manager", "Virt-manager"
WM_ICON_NAME(STRING) =
_NET_WM_ICON_NAME(UTF8_STRING) =
WM_NAME(STRING) =
_NET_WM_NAME(UTF8_STRING) =
```

Similar behaviour is happening with GIMP if I want to override a file.
##

The Issue might be that I use this crappy dell dock with displaylink, which behaves strange from time to time.

Maybe discuss further in Discord?

### OS / Distro

Linux arch-dell-latitude7430 6.3.3-arch1-1

### LeftWM Check

```text
:: LeftWM version: 0.4.1
:: LeftWM git hash: 438b073
:: Enabled features: default journald-log lefthk lefthk-core tracing-journald
:: Checking feature dependencies . . .
    -> journald-log OK
    -> lefthk OK
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
WARN: TOML as config format is about to be deprecated.
      Please consider migrating to RON or contact the theme creator about this topic.
      Note: make sure the `up` script is loading the correct theme file.
ERROR: File not found: theme.ron

Theme is slightly updated Ascent don't where the repo moved to
```

**Comment by esmaeilytabar** [comment]
I have the exact same problem too. I have 10 tags and my windows spawn at tag number 6 examples of those are like virt-manager or qemu or firefox (overwriting a file while saving a download). Also quick thanks to all you leftwm developers and maintainers I have been loving Leftwm as my window manager for nearly a year now 💚.

**Comment by MaKaNu** [comment]
@esmaeilytabar sounds excatly the same issue I have. Still need to test but the issue might be caused by the missing entries:

```bash
WM_ICON_NAME(STRING) =
_NET_WM_ICON_NAME(UTF8_STRING) =
WM_NAME(STRING) =
_NET_WM_NAME(UTF8_STRING) =
```

**Comment by MaKaNu** [comment]
New Example of this bug:

In Thunderbird Calender if a meeting is opened (not edit) the meeting window is launched on last workspace. here are the xprop values with removed icons:

**Thunderbird**
```bash
_NET_WM_USER_TIME(CARDINAL) = 321493
_NET_WM_DESKTOP(CARDINAL) = 5
WM_STATE(WM_STATE):
		window state: Normal
		icon window: <field not available>
_NET_WM_STATE(ATOM) =
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x1c0003d
		bitmap id # of mask for icon: 0x1c00043
		window id # of group leader: 0x1c00001
_GTK_THEME_VARIANT(UTF8_STRING) =
WM_WINDOW_ROLE(STRING) = "3pane"
XdndAware(ATOM) = BITMAP
_NET_WM_OPAQUE_REGION(CARDINAL) = 0, 0, 2554, 1404
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 29360187, 29360188
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x1c0003a
WM_CLIENT_LEADER(WINDOW): window id # 0x1c00001
_NET_WM_PID(CARDINAL) = 1664
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "latitude7430-lit-01"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 95 by 95
		program specified maximum size: 16384 by 16384
		program specified base size: 95 by 95
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "Mail", "thunderbird"
WM_ICON_NAME(COMPOUND_TEXT) = "11. Juni – 8. Juli 2023 - Mozilla Thunderbird"
_NET_WM_ICON_NAME(UTF8_STRING) = "11. Juni – 8. Juli 2023 - Mozilla Thunderbird"
WM_NAME(COMPOUND_TEXT) = "11. Juni – 8. Juli 2023 - Mozilla Thunderbird"
_NET_WM_NAME(UTF8_STRING) = "11. Juni – 8. Juli 2023 - Mozilla Thunderbird"
```
**Meeting Window**
```bash
_NET_WM_DESKTOP(CARDINAL) = 8
WM_STATE(WM_STATE):
		window state: Normal
		icon window: <field not available>
_NET_WM_STATE(ATOM) =
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x1c00300
		bitmap id # of mask for icon: 0x1c00306
		window id # of group leader: 0x1c00001
_GTK_THEME_VARIANT(UTF8_STRING) =
WM_WINDOW_ROLE(STRING) = "EventSummaryDialog"
XdndAware(ATOM) = BITMAP
_NET_WM_OPAQUE_REGION(CARDINAL) =
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 29360894, 29360895
_NET_WM_USER_TIME(CARDINAL) = 337672
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x1c002fd
WM_CLIENT_LEADER(WINDOW): window id # 0x1c00001
_NET_WM_PID(CARDINAL) = 1664
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "latitude7430-lit-01"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 513 by 0
		program specified maximum size: 16384 by 16384
		program specified base size: 513 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "Calendar", "thunderbird"
WM_ICON_NAME(STRING) = "Prüfung Modellbildung und Simulation (DT)"
_NET_WM_ICON_NAME(UTF8_STRING) = "Prüfung Modellbildung und Simulation (DT)"
WM_NAME(STRING) = "Prüfung Modellbildung und Simulation (DT)"
_NET_WM_NAME(UTF8_STRING) = "Prüfung Modellbildung und Simulation (DT)"
```

My prognose, that it might be an issue with the missing entries seems proven wrong. I noticed something else by comparing the xprops: 

`_NET_WM_DESKTOP(CARDINAL)` seems the variable which locates the window in the corresponding workspace. Maybe a comparison of the parent windows  `_NET_WM_DESKTOP(CARDINAL)` might help here?

**Comment by Silicasandwhich** [comment]
found another occurrence of this bug in nautilus, whenever it tries to display an error window (such as when trying to connect to a nonexistent network drive), that error displays on the last tag. here's the xprops (minus icons):

**Nautilus**

```
_NET_WM_USER_TIME(CARDINAL) = 5826761
_NET_WM_DESKTOP(CARDINAL) = 0
WM_STATE(WM_STATE):
		window state:
		icon window: <field not available>
_NET_WM_STATE(ATOM) =
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x340002c
		bitmap id # of mask for icon: 0x3400033
		window id # of group leader: 0x3400001
_GTK_THEME_VARIANT(UTF8_STRING) = "dark"
XdndAware(ATOM) = BITMAP
_GTK_WINDOW_OBJECT_PATH(UTF8_STRING) = "/org/gnome/Nautilus/window/1"
_GTK_APPLICATION_OBJECT_PATH(UTF8_STRING) = "/org/gnome/Nautilus"
_GTK_UNIQUE_BUS_NAME(UTF8_STRING) = ":1.433"
_GTK_APPLICATION_ID(UTF8_STRING) = "org.gnome.Nautilus"
_NET_WM_OPAQUE_REGION(CARDINAL) = 0, 0, 1902, 1028
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 54525962, 54525963
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x3400009
WM_CLIENT_LEADER(WINDOW): window id # 0x3400001
_NET_WM_PID(CARDINAL) = 70267
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "silicasystem76"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 691 by 328
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "org.gnome.Nautilus", "Org.gnome.Nautilus"
WM_ICON_NAME(STRING) = "Home"
_NET_WM_ICON_NAME(UTF8_STRING) = "Home"
WM_NAME(STRING) = "Home"
_NET_WM_NAME(UTF8_STRING) = "Home"
```

**Error Window**


```
_NET_WM_DESKTOP(CARDINAL) = 3
WM_STATE(WM_STATE):
		window state:
		icon window: <field not available>
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MODAL, _NET_WM_STATE_SKIP_TASKBAR
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x3400599
		bitmap id # of mask for icon: 0x340059f
		window id # of group leader: 0x3400001
_GTK_THEME_VARIANT(UTF8_STRING) = "dark"
XdndAware(ATOM) = BITMAP
_NET_WM_OPAQUE_REGION(CARDINAL) = 0, 0, 539, 127
WM_TRANSIENT_FOR(WINDOW): window id # 0x3400008
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 54527383, 54527384
_NET_WM_USER_TIME(CARDINAL) = 5970886
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x3400596
WM_CLIENT_LEADER(WINDOW): window id # 0x3400001
_NET_WM_PID(CARDINAL) = 70267
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "silicasystem76"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		program specified minimum size: 539 by 127
		program specified maximum size: 539 by 127
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "org.gnome.Nautilus", "Org.gnome.Nautilus"
WM_ICON_NAME(STRING) =
_NET_WM_ICON_NAME(UTF8_STRING) =
WM_NAME(STRING) =
_NET_WM_NAME(UTF8_STRING) =
```
the same four values as in the first case are empty, but given that the thunderbird instance of the bug doesn't have these empty values, i don't think that's the problem here. one other thing i tested was manually setting ```_NET_WM_DESKTOP(CARDINAL)``` property using ```xprop```, but it didn't have any effect, and it reset to the normal value on a softreload. one thing im testing rn is just setting the tag of the child to the parent when it first gets set up, ill report back after i compile and test that.

**Comment by Silicasandwhich** [comment]
okay, that fixed it for nautilus and virt-manager (for the sake of clarity, the change i made can be found [here](https://github.com/Silicasandwhich/leftwm/tree/last_tag)). however, it did not fix the problem for thunderbird, and im honestly not sure why... it's probably worth testing other applications on both branches to see if they fail, and what they have in common with thunderbird here.

**Comment by MaKaNu** [comment]
Really? Gurke? Hahaha

**Comment by VuiMuich** [comment]
> Really? Gurke? Hahaha

That was probably me, it's my goto "meaningless generic test word" closely followed by "Affensalat" 

(For our fellow adventurers not speaking German: Gurke 🥒, Affensalat 🐒🥗)

**Comment by Silicasandwhich** [comment]
so ive taken some time to think it over, and i have some theories on what's going on, and they're necessarily mutually exclusive:

1. thunderbird may not be properly parenting its windows. one indicator of this is that, even on a different window manager (like sway), the meeting notification list appears on the active tag rather than the tag with thunderbird on it. why exactly this would be causing the meeting list to appear on the last tab, im not sure, but it would explain why the band-aid fix of just moving the window after it's created isn't working
2. the two that were fixed were "dialog windows," as in a warning/error sign, some text, and a few buttons. these are the kind that appears for confirmation or an error message, and (if im understanding the code base correctly) i believe that leftwm distinguishes these from normal windows (see [window_type.rs](https://github.com/leftwm/leftwm/blob/main/leftwm-core/src/models/window_type.rs)). to test this out, we should test other applications that generate dialogue boxes to see if they experience the same problem (such as libreoffice when trying to close an unsaved document). This still doesn't explain the thunderbird window, but i think there might be an underlying issue with the way leftwm handles dialog boxes that is causing the issue, with the manual moving on creation just being a bandaid fix to that problem. the most probable place for this to happen imo is in ```window_changed_handler``` in window_handler.rs, which is the only place I can find that changes the tag of a window when it is a dialogue box.

Either way, i think we need to find more programs that don't work with the band-aid fix to figure out why thunderbird isn't, so we can figure out if this is a thunderbird problem or a leftwm problem.

**Comment by Silicasandwhich** [comment]
ok, so ive tested some more dialogue boxes on the current stable release, and most of them work. However, the ones that do all have values for those last four properties.

closing audacity with unsaved file:
```
WM_ICON_NAME(STRING) = "Save changes to <untitled>?"
_NET_WM_ICON_NAME(UTF8_STRING) = "Save changes to <untitled>?"
WM_NAME(STRING) = "Save changes to <untitled>?"
_NET_WM_NAME(UTF8_STRING) = "Save changes to <untitled>?"
```

closing arronax with unsaved file:
```
WM_ICON_NAME(STRING) = "Save now?"
_NET_WM_ICON_NAME(UTF8_STRING) = "Save now?"
WM_NAME(STRING) = "Save now?"
_NET_WM_NAME(UTF8_STRING) = "Save now?"
```

there's plenty more like this, but either way, i think my dialogue boxes theory is wrong. currently, im thinking that the empty values are causing the problem with virt-manager and nautilus, and the thunderbird issue is another thing entirely. as corroboration, here's the xprops of a thunar dialog window that has the same problem:

```
_NET_WM_DESKTOP(CARDINAL) = 2
WM_STATE(WM_STATE):
		window state:
		icon window: <field not available>
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MODAL, _NET_WM_STATE_SKIP_TASKBAR
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x4c01d80
		bitmap id # of mask for icon: 0x4c01d86
		window id # of group leader: 0x4c00001
_GTK_THEME_VARIANT(UTF8_STRING) =
XdndAware(ATOM) = BITMAP
_NET_WM_ICON(CARDINAL) = 	Icon (48 x 48):
_NET_WM_OPAQUE_REGION(CARDINAL) = 0, 0, 564, 127
WM_TRANSIENT_FOR(WINDOW): window id # 0x4c00007
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 79699326, 79699327
_NET_WM_USER_TIME(CARDINAL) = 30878065
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x4c01d7d
WM_CLIENT_LEADER(WINDOW): window id # 0x4c00001
_NET_WM_PID(CARDINAL) = 202327
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "silicasystem76"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		program specified minimum size: 564 by 127
		program specified maximum size: 564 by 127
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "thunar", "Thunar"
WM_ICON_NAME(STRING) =
_NET_WM_ICON_NAME(UTF8_STRING) =
WM_NAME(STRING) =
_NET_WM_NAME(UTF8_STRING) =
```

the thunar window is also fixed by the change.

**Comment by Silicasandwhich** [comment]
did a quick hack to the code to let me see the internal structs of windows. here's what i gathered:

**Thunderbird Main Window**
```rust
Window { handle: XlibHandle(81788985), transient: None, visible: false, can_resize: true, is_floating: false, must_float: false, floating: None, never_focus: false, urgent: false, debugging: false, name: Some("Mozilla Thunderbird"), legacy_name: Some("Mozilla Thunderbird"), pid: Some(239933), type: Normal, tag: None, border: 1, margin: Margins { top: 10, right: 10, bottom: 10, left: 10 }, margin_multiplier: 1.0, states: [MaximizedVert, MaximizedHorz], requested: Some(Xyhw { x: 0, y: 0, h: 1028, w: 1902, minw: 95, maxw: 16384, minh: 95, maxh: 16384 }), normal: Xyhw { x: 0, y: 0, h: 0, w: 0, minw: -999999999, maxw: 999999999, minh: -999999999, maxh: 999999999 }, start_loc: None, container_size: None, strut: None, res_name: Some("Mail"), res_class: Some("thunderbird") }

```

**Meeting Window**
```rust
Window { handle: XlibHandle(81789451), transient: None, visible: false, can_resize: true, is_floating: false, must_float: false, floating: None, never_focus: false, urgent: false, debugging: false, name: Some(""), legacy_name: Some(""), pid: Some(239933), type: Dialog, tag: Some(4), border: 1, margin: Margins { top: 10, right: 10, bottom: 10, left: 10 }, margin_multiplier: 1.0, states: [], requested: Some(Xyhw { x: 0, y: 0, h: 1, w: 490, minw: 490, maxw: 16384, minh: 0, maxh: 16384 }), normal: Xyhw { x: 0, y: 0, h: 0, w: 0, minw: -999999999, maxw: 999999999, minh: -999999999, maxh: 999999999 }, start_loc: None, container_size: None, strut: None, res_name: Some("Calendar"), res_class: Some("thunderbird") }

```

**Edit Window**
```rust
Window { handle: XlibHandle(81789509), transient: None, visible: false, can_resize: true, is_floating: false, must_float: false, floating: None, never_focus: false, urgent: false, debugging: false, name: Some("Edit Item"), legacy_name: Some("Edit Item"), pid: Some(239933), type: Dialog, tag: None, border: 1, margin: Margins { top: 10, right: 10, bottom: 10, left: 10 }, margin_multiplier: 1.0, states: [], requested: Some(Xyhw { x: 0, y: 0, h: 74, w: 10, minw: 10, maxw: 16384, minh: 74, maxh: 16384 }), normal: Xyhw { x: 0, y: 0, h: 0, w: 0, minw: -999999999, maxw: 999999999, minh: -999999999, maxh: 999999999 }, start_loc: None, container_size: None, strut: None, res_name: Some("Calendar"), res_class: Some("thunderbird") }
```

something's definitely doing wrong here, and im not sure what it is. the most obvious thing to me is that windows with the same PID should spawn on the same tag, but this could lead to edge cases, like if you have the thunderbird main window on one tag and the thunderbird edit window on the other tag, and it spawns the view window. either way, there's something going on with parenting, as the ```transient``` values for the meeting window and edit window should point to the main window as they are children of it. for example, the nautilus error message:
```rust
Window { handle: XlibHandle(79694030), transient: Some(XlibHandle(79691784)), visible: false, can_resize: true, is_floating: false, must_float: false, floating: Some(Xyhw { x: 0, y: 0, h: 127, w: 542, minw: -999999999, maxw: 999999999, minh: -999999999, maxh: 999999999 }), never_focus: false, urgent: false, debugging: false, name: Some(""), legacy_name: Some(""), pid: Some(242594), type: Dialog, tag: Some(4), border: 1, margin: Margins { top: 10, right: 10, bottom: 10, left: 10 }, margin_multiplier: 1.0, states: [Modal, SkipTaskbar], requested: Some(Xyhw { x: 0, y: 0, h: 127, w: 542, minw: 542, maxw: 542, minh: 127, maxh: 127 }), normal: Xyhw { x: 0, y: 0, h: 0, w: 0, minw: -999999999, maxw: 999999999, minh: -999999999, maxh: 999999999 }, start_loc: None, container_size: None, strut: None, res_name: Some("org.gnome.Nautilus"), res_class: Some("Org.gnome.Nautilus") }
```

leftwm gets the transient values directly from xlib, and i doubt that's the problem since i3 doesn't have this problem. however, im noticing something interesting with the tags on the problem windows (nautilus and thunderbird meeting): they have tag values of 4 (my config's last tag), while the other ones have a value of zero. This is strange, as I am getting the window info here before the ```setup_window``` function is called in ```window_handler.rs```, meaning that unless the window has a predefined tag, it should have a tag of None. I'm gonna try setting the tag to None directly before the predefined windows are set up to see if that fixes the problem.

**Comment by Silicasandwhich** [comment]
i think i might have found it. setting the tag to None directly before setting up pre-defined windows doesn't fix thunderbird. However, I noticed that I had a window_rule that moves Weston windows to tag 4 (```rust	(window_title: "Weston.*", spawn_on_tag: 4),```). When I changed this value to 3, the thunderbird meeting window started spawning on tag 3, and when i removed it entirely, the meeting window worked as normal. Now, doing this had no effect on virt-manager or nautilus, those still require the previous fix. However, this just seems like a problem with how the config parser is matching window titles.

@MaKaNu does your leftwm config file have any similar window rules?

**Comment by Silicasandwhich** [comment]
yep, i just made a quick change to the parser and now it works flawlessly. @MaKaNu try running leftwm from [this branch](https://github.com/Silicasandwhich/leftwm/tree/last_tag) of my fork and see if it works. if it does, ill make a PR to the main repo

**Comment by VuiMuich** [comment]
> yep, i just made a quick change to the parser and now it works flawlessly. @MaKaNu try running leftwm from [this branch](https://github.com/Silicasandwhich/leftwm/tree/last_tag) of my fork and see if it works. if it does, ill make a PR to the main repo

I wouldn't mind if you'd opened your branch as `draft` PR right now, actually that would make it more convenient to track progress even if it doesn't work immediatelly.

**Comment by Silicasandwhich** [comment]
alright, sounds good

**Comment by MaKaNu** [comment]
Setted up a Test VM with my Config and my theme I am using. Sadly it doesn't worked out. And yes to the question if I have spawn rules:

```
( window_class: "thunderbird", spawn_on_tag: 6 )
```

and a few more.

I uncommented them and the window spawned centered above thunderbird. So  yes the `spawn_on_tag` creates similiar issue. Using `window_title` instead `window_class` seems not a good approach for Thunderbird since the title is changed multiple time. Maybe this is also an issue how Thunderbird it self call the windows? sadly the windows are not new process forks so that needs to be tracked inside of X11?

**Comment by VuiMuich** [comment]
@Silicasandwhich the latest commits in #1093 are considering this, right?

**Comment by Silicasandwhich** [comment]
yeah, the latest commits in #1093 should have fixed the issue.
