### ISSUE TITLE
AUR PKGBUILDs use incorrect systemd detection

### ISSUE THREAD

**Issue by eclairevoyant** [leftwm/leftwm#1070]
### Describe the bug

Both the leftwm and leftwm-git PKGBUILDs incorrectly use `ps` to detect if we should build for systemd. This is incorrect because when building in a clean chroot ([as is expected](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot) for Arch packaging in general), systemd is not necessarily running, even if the target system does in fact use systemd. We may also utilise a non-systemd system to build packages for a systemd target.

### Expected behavior (optional)

The PKGBUILD should be split into separate packages so that the user can choose which one they want to install.

### OS / Distro

Arch Linux

### LeftWM Check

```text
n/a, as this is reporting an issue with build scripts
```

**Comment by eclairevoyant** [comment]
I also want to point out that the PKGBUILDs in general should be [following the Rust package guidelines](https://wiki.archlinux.org/title/Rust_package_guidelines) which they currently do not.

**Comment by hertg** [comment]
Hey, I remember your username from the `eww` package in the AUR :) Is your proposal to make a package split similar to how you did with [`eww-git`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=eww-git)?

*btw. the issue I had with eww-git and paru resolved itself, it worked suddenly. Might have been a caching issue or something.*

---

@VuiMuich That task is up to us since we are the only ones that maintained our AUR packages after Lex. I am rather unfamiliar with our builds because I haven't worked much on it since we introduced all the feature flags. Would happily give you the lead on that one and take a reviewing role if that's ok with you.

**Comment by VuiMuich** [comment]
@eclairevoyant: Patch definitely welcome.
I guess you would address both the issue with the missing `-t` in the manpage install and the compliance with rust package guidelines, right?
As you appear quite experienced with the AUR, what's your suggested way to apply the patch?
Post the diff here and one of us commits it to the package repo? Iirc the AUR doesn't have something like merge requests, right?

**Comment by eclairevoyant** [comment]
Sure, I can handle those. I'll post a patch that can be applied with `git am` (i.e. it would mark me as the author and you as the committer). Unfortunately AUR does not have PR/MR functionality atm

**Comment by eclairevoyant** [comment]
Okay here's the patch, assuming you're in the git directory with the `leftwm-git` PKGBUILD you can apply with `git am path/to/patch/file`:

https://gist.githubusercontent.com/eclairevoyant/eea796a5c2ece58223940e3d94dd82d9/raw/43eaeddcaefbf7d933e4cedc103f93d0c45d342c/0001-Split-package-into-systemd-non-systemd-versions.patch

I wasn't really creative with the naming, so I can change that if needed. I added a `.gitignore` and addressed all the points @VuiMuich mentioned above / made changes to comply with general guidelines as well (e.g. description shouldn't have package name in it, lines should be <100 characters). If you're happy with these changes I'll post a second patch for the `leftwm` PKGBUILD.

**Comment by VuiMuich** [comment]
As the differences in the git and fixed release versions are too big as to be easily modified in the patch it would indeed nice if you could provide a patch for this as well.

The one for the git package should be already live..

**Comment by eclairevoyant** [comment]
Sure, I'll write up a patch for the other package, just wanted to confirm if you were happy with the changes. I'll post the other patch within a couple days.

**Comment by VuiMuich** [comment]
Just one thing I realized: when searching for `leftwm-git` with paru now there is no result. Can we somehow link to the two packages available under this pkgbase?

**Comment by VuiMuich** [comment]
@eclairevoyant we don't mean to rush you, but we are about to release a version bump. Do you think you are up to put the patch together? Otherwise we will manually adopt the changes from the `-git` version to the release based one.

Also as mentioned above, it would be nicer if `leftwm-git` would return search results with aur helpers, if there is no "symlinking" possibilty I would actually prefer to revert `leftwm-systemd-git` to `leftwm-git` and only destinct the `non-systemd` packages.

**Comment by eclairevoyant** [comment]
searching `paru leftwm git` will bring up this package, but paru doesn't search `pkgbase` I guess. Feel free to rename the packages per your needs, like I said I wasn't too creative with the naming - just make sure to also update the name of the associated package function.

Working on the patch now and I will post today.

**Comment by eclairevoyant** [comment]
https://gist.githubusercontent.com/eclairevoyant/507ab8d12df99592fbfe09173249b971/raw/3b21a1bf6a39f5dac89565fec5819f6b104444ca/0001-Split-package-into-systemd-non-systemd-versions.patch

The default systemd package is simply called "leftwm" here based on your comment above

**Comment by VuiMuich** [comment]
Thanks for all your work and shared knowledge, @eclairevoyant!

I'll educate myself on release signing, but I agree that this would a good idea to do.

**Comment by eclairevoyant** [comment]
Signing the commit is fine, then you can use `https://github.com/leftwm/leftwm.git?signed#commit=[ref]` in the source for the stable package (replacing `[ref]` of course with the commit hash).

There is also the option to sign tags but I haven't looked into that honestly, maybe that's just overkill.

**Comment by VuiMuich** [comment]
Signing tags is actually not that hard, you just use `git tag -s -u <local key ID> <tag name>`. We just need to figure out how to (force) push, the signed Tag commit over the unsigned one.

Also will look into the validation process for the tarball.

Thanks again, for all your work and information input!

**Comment by eclairevoyant** [comment]
Sorry if I wasn't clearer: if you sign release commits you can use that to _replace_ the tarball source in the PKGBUILD. Even non-git packages can use git sources (we just have to pin to a specific release commit).

Of course you're welcome to sign the tarball as well, but that's not necessary for the PKGBUILDs.

**Comment by eclairevoyant** [comment]
Just to give concrete examples of PKBUILDs: 

* If you go the signed tag route: https://github.com/eclairevoyant/aur-packages/blob/main/python-aiomultiprocess/PKGBUILD

* If you go the signed tarball route: https://github.com/eclairevoyant/aur-packages/blob/main/zrythm/PKGBUILD
