### ISSUE TITLE
Deprecated proc-macro-hack invalidates current model for specificying Git Hash in leftwm-check for non-git distributions of leftwm

### ISSUE THREAD

**Issue by mautamu** [leftwm/leftwm#1081]
### Describe the bug

Deprecated proc-macro-hack invalidates current model for specificying Git Hash in leftwm-check for non-git distributions of leftwm; this is mentioned in #1075. 

### Expected behavior (optional)

If we're compiling leftwm-check
1. Not in a Git Repo, or in a damaged Git Repo
2. With GIT_HASH specified

Then the Git Hash compiled into leftwm-check ought to be the environmental variable's value

### Steps to reproduce (optional)

Compiling leftwm-check
1. Not in a Git Repo, or in a damaged Git Repo
2. With GIT_HASH specified

### OS / Distro

N/A, applies to all

### LeftWM Check

```text
:: LeftWM version: 0.4.1
:: LeftWM git hash: a6766ce-modified
:: Enabled features:  journald-log lefthk
:: Checking feature dependencies . . .
    -> journald-log OK
    -> lefthk OK
:: Checking for leftwm binaries . . .
    -> Binaries OK
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
ERROR: Could not parse theme file: 2:19: Expected option
```

**Comment by VuiMuich** [comment]
I don't yet understand the fallback options of the `git_version!()` macro, and/or I don't understand our previous implementation fully.
But afaict there is two stages of fallback: if no git hash can be determined it can report back the cargo_package_version and if that fails as well it will return the `fallback` string.
When was the `option_env!()` exactly being triggered?

**Comment by PopcornPaws** [comment]
I have a similar issue, not sure if it's relevant here as well. Upon running 'cargo install leftwm' (fresh Arch Linux installed) I get the following error originating from the 'option_env' macro in 'leftwm-check.rs:39:56'

```
error: expected ','

git_version::git_version!(fallback = option_env!("GIT_HASH").unwrap_or("NONE"))
```

I don't have 'GIT_HASH' listed among my environment variables, but that shouldn't be the issue right?

**Comment by Eskaan** [comment]
Version bump is done. @VuiMuich I assume this is fixed with that?
