### ISSUE TITLE
Ability to jump to next/previous non-empty workspace

### ISSUE THREAD

**Issue by simtd** [leftwm/leftwm#1083]
### Describe the feature

As far as I see there are no issues open describing this functionality.

This is a feature that bspwm has and also patches exist for dwm to add this functionality also. Basically it's the ability to press a hotkey to cycle through workspaces that has windows/clients on them. Both back and fourth. For my personal use case I have bound "super + ." to jump to the next non-empty workspace and "super + ," to go the other way in the window manager I use currently.

### How important is this feature to you?

My workflow is impaired without it

### How important do you think is this feature for the average LeftWM user?

Would probably be nice to have

**Comment by VuiMuich** [comment]
For reference on implementation, a similar optional `bool` value can be found in the `MoveWindowToPreviousTag` and `MoveWindowToNextTag` commands.

**Comment by Eskaan** [comment]
Above pr got merged and released in  [v0.4.2](https://github.com/leftwm/leftwm/releases/tag/0.4.2). Thanks for your contribution!
