### ISSUE TITLE
Floating windows are "always on top"

### ISSUE THREAD

**Issue by santibreo** [leftwm/leftwm#1094]
### Describe the bug

When I `ToggleFloating` any window, it stays on top of every other window in the workspace. If I have `ToggleFloating` multiple windows, the last I move/resize is the one on top.

### Expected behavior (optional)

The focused window must be on top of all other windows by default. Then if there is an `AlwaysOnTop` switch that you can activate on certain windows so they are on top of others even if they lose focus, that would be nice. 

### Steps to reproduce (optional)

1. Open 2 windows
2. Execute `ToggleFloating` on one of them
3. Move focus

### OS / Distro

Linux awesome 6.3.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 10 Jun 2023 00:35:35 +0000 x86_64 GNU/Linux

### LeftWM Check

```text
:: LeftWM version: 0.4.1
:: LeftWM git hash: c6cbca6e
:: Enabled features: lefthk sys-log
:: Checking feature dependencies . . .
    -> lefthk OK
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```

**Comment by VuiMuich** [comment]
I agree almost with this request: imo tiled windows should always be in a layer below floating windows, otherwise floating windows kind of "might get lost" behind a big tile.

But floating vs floating should indeed restack when moving focus.

I therefore don't see this as a bug actually, but more as an enhancement.

**Comment by NicTanghe** [comment]
Hi, plz include over full-screen Windows 2.

**Comment by BKSalman** [comment]
> Hi, plz include over full-screen Windows 2.

@NicTanghe please try out the new `ToggleMaximized` command added in #1121 it could be what you actually want
