### ISSUE TITLE
Derive output of leftwm-command --list from BaseCommand enum

### ISSUE THREAD

**Issue by Silicasandwhich** [leftwm/leftwm#1095]
### Describe the enhancement

Currently, the output of leftwm-command --list is hardcoded, which for now is fine, but as more commands are added, it leaves another opportunity for documentation to fall behind. If we could instead derive this list from the BaseCommand enum, we could ensure that this list is always up to date. This is probably a pretty low priority, dev-facing only sort of change, but i feel like it'd definitely be helpful in the future.

### How important is this enhancement to you?

Would be nice to have

### How important do you think is this enhancement for the average LeftWM user?

I don't know, may be a niche edge-case

**Comment by VuiMuich** [comment]
Thanks for formulating this quick thought from the discord message and wording it so well.

Just another thought that might rise the importance a little bit: the set of commands available in the wayland compositor might vary significantly, so deriving the subcommands help message should be useful for that as well.

**Comment by VuiMuich** [comment]
I'll start researching the `clap` docs to see, what is possible here...

**Comment by Eskaan** [comment]
I think something like this might work:

```rust
impl BaseCommand {
  const COUNT: u8 = 10;
  pub fn gen_names() -> Vec<String> {
    let names = Vec::new();
    for i in 0..COUNT {
      names.push(unsafe { men::transmute(i) });
    }
  }
  names
} 
```
This would of course need a unit test to guarantee count is the actual count op enum options.

**Comment by Eskaan** [comment]
~~Just so I can drop this issue from my notification list,~~ I did some testing and it looks like there is no way to catch a segfault in Rust, which would be needed.

Just as I am writing this, I noticed I think I did not try by spawning a new process, I just tried threads. I might come back after I find a way to ensure program safety.
