### ISSUE TITLE
Black screen for XComposite window capture on OBS

### ISSUE THREAD

**Issue by Syudagye** [leftwm/leftwm#1100]
### Describe the bug

When capturing a window with OBS using the XComposite capture source, if the window is not on the same tag as OBS, is will result in a black output.

### Expected behavior (optional)

Proper window capture, even if the window is not on the currently focused tag.

### Steps to reproduce (optional)

1) Spawn a window that you want to capture and OBS
2) Add the XComposite source to your source list in obs, and select the desired window.
3) See the result when OBS is on the same tag as your captured window, and when it's not

### OS / Distro

Linux archbtw 6.3.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 10 Jun 2023 00:35:35 +0000 x86_64 GNU/Linux

### LeftWM Check

```text
:: LeftWM version: 0.4.2
:: LeftWM git hash: 8ad3204-modified
:: Enabled features:  journald-log lefthk
:: Checking feature dependencies . . .
    -> journald-log OK
    -> lefthk OK
:: Checking for leftwm binaries . . .
    -> Binaries OK
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```

**Comment by Syudagye** [comment]
I think this could be related to using XUnmapWindow/XMapWindow when showing/hiding a window ([here](https://github.com/leftwm/leftwm/blob/3fcd9e8df104000846ad09bb54f48ecf1299b851/display-servers/xlib-display-server/src/xwrap/window.rs#L212)). I've seen a [similar issue in i3](https://github.com/i3/i3/issues/1925), which was not fixed.

Do you think it could be possible to hide a window without mapping/unmapping it, so it's content would still be available to applications like obs ?

**Comment by VuiMuich** [comment]
Does OBS somehow signal the window (or dieplayserver) that it's (some window is) being recorded?

I believe the `unmap` just happens to save resources, so if we know which window is being recorded we could try to simple suppress the `unmap`.
I agree with your open question if the window still becomes hidden from the screen, but we could also try to park it at a pixel position that is outside the render area and make sure we can't accidentally focus the window there.

**Comment by kyleguarco** [comment]
This problem has been plaguing me too; It's super hard to share screens on Discord if the window is unmapped. It seems like the windows also get unmapped when the current layout is `Monocle` and the window you're trying to share is hidden behind the focused window.

Is this something that can be hacked around in `leftwm`? Other forums I read on this state that "hacks" are the only way around this in X11.

I wanna see if windows can be "marked" to prevent unmapping but still be hidden when switching tags. I introduced a `ToggleMarked` command in [my branch][1].

[1]: https://github.com/kyleguarco/leftwm/tree/issue_1100

**Comment by Syudagye** [comment]
hack/workaround found for xmonad: https://github.com/T-X/xmonad-config/commit/bc31fd1821a0f58c612cad6fcaca5dbc3795089f

**Comment by Syudagye** [comment]
Well, `dwm` seems to already handle this issue properly by moving the windows out of the viewport to hide them:

```c
void
showhide(Client *c)
{
    if (!c)
        return;
    if (ISVISIBLE(c)) {
        /* show clients top down */
        XMoveWindow(dpy, c->win, c->x, c->y);
        if ((!c->mon->lt[c->mon->sellt]->arrange || c->isfloating) && !c->isfullscreen)
            resize(c, c->x, c->y, c->w, c->h, 0);
        showhide(c->snext);
    } else {
        /* hide clients bottom up */
        showhide(c->snext);
        XMoveWindow(dpy, c->win, WIDTH(c) * -2, c->y);
    }
}
```
