### ISSUE TITLE
Cannot bind numpad to tag switching / moving

### ISSUE THREAD

**Issue by f0ff886f** [leftwm/leftwm#1114]
### Describe the bug

For example, I have this in my `config.ron`:

```rust
        (command: GotoTag, value: "1", modifier: ["modkey"], key: "1"),
        (command: GotoTag, value: "1", modifier: ["modkey"], key: "KP_1"),
```

I would expect pressing modkey and KP_1 to go to tag 1. modkey and just 1 on the regular number row works fine.

Nothing happens when I use the numpad. If I run `xev`, I do see `KP_1` events when pressing numpad 1.

### Expected behavior (optional)

I should be able to bind `KP_*` to `GotoTag` commands and use my numpad to navigate tags.

### Steps to reproduce (optional)

Add

```rust
        (command: GotoTag, value: "1", modifier: ["modkey"], key: "KP_1"),
```

to your config, try to navigate to tag 1 with the numpad.

### OS / Distro

Linux zhA 6.4.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 03 Aug 2023 16:02:01 +0000 x86_64 GNU/Linux

### LeftWM Check

```text
:: LeftWM version: 0.4.2
:: LeftWM git hash: 357aea5
:: Enabled features:  journald-log lefthk
:: Checking feature dependencies . . .
    -> journald-log OK
    -> lefthk OK
:: Checking for leftwm binaries . . .
    -> Binaries OK
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```

**Comment by VuiMuich** [comment]
You could try to add `Num_Lock` as an additional modifier.

**Comment by kyleguarco** [comment]
I'm guessing this is an issue with how [`lefthk`][1] handles key-grabbing. I had to rewind `lefthk` to commit `eb6f564`, which was when the crate was last version `0.1.8` to compile and play around with it on `leftwm`'s master branch (current commit dffd5813a923f8da7f58afdd5163a336d7382bbc).

`Num_Lock` (a.k.a `Mod2` or `Num_Lock`) is ignored as a modifier by `lefthk` [in the source code][2]. All the `KP_*` keys [are converted to the correct keysym and keycode][3].

This doesn't seem to be a problem unique to `leftwm`, as [`i3`][4] and [`dwm`][5] have also had this problem. In both cases, binding the numlock-off alternative keys (`KP_END`, `KP_DOWN`) worked, **and it works here as well**.

Running this command tells us what `KP_*` keys are on keycodes 80-90 (the ones we're trying to bind). You'll notice that the numlock-off and numlock-on keys have the same keycode.
```
~$ xmodmap -pke | grep "KP_"
keycode  63 = KP_Multiply KP_Multiply KP_Multiply KP_Multiply KP_Multiply KP_Multiply XF86ClearGrab
keycode  79 = KP_Home KP_7 KP_Home KP_7
keycode  80 = KP_Up KP_8 KP_Up KP_8
keycode  81 = KP_Prior KP_9 KP_Prior KP_9
keycode  82 = KP_Subtract KP_Subtract KP_Subtract KP_Subtract KP_Subtract KP_Subtract XF86Prev_VMode
keycode  83 = KP_Left KP_4 KP_Left KP_4
keycode  84 = KP_Begin KP_5 KP_Begin KP_5
keycode  85 = KP_Right KP_6 KP_Right KP_6
keycode  86 = KP_Add KP_Add KP_Add KP_Add KP_Add KP_Add XF86Next_VMode
keycode  87 = KP_End KP_1 KP_End KP_1
keycode  88 = KP_Down KP_2 KP_Down KP_2
keycode  89 = KP_Next KP_3 KP_Next KP_3
keycode  90 = KP_Insert KP_0 KP_Insert KP_0
keycode  91 = KP_Delete KP_Decimal KP_Delete KP_Decimal
keycode 104 = KP_Enter NoSymbol KP_Enter
keycode 106 = KP_Divide KP_Divide KP_Divide KP_Divide KP_Divide KP_Divide XF86Ungrab
keycode 125 = KP_Equal NoSymbol KP_Equal
keycode 129 = KP_Decimal KP_Decimal KP_Decimal KP_Decimal
```

So for now, just bind the alternative keys. Maybe this is something that will be fixed? I have some more playing around to do with this.

[1]: https://github.com/leftwm/lefthk
[2]: https://github.com/leftwm/lefthk/blob/eb6f564/lefthk-core/src/xkeysym_lookup.rs#L30C40-L30C40
[3]: https://github.com/leftwm/lefthk/blob/eb6f564/lefthk-core/src/xkeysym_lookup.rs#L133
[4]: https://unix.stackexchange.com/questions/566566/binding-numpad-keys-on-i3-dont-work
[5]: https://www.reddit.com/r/suckless/comments/h0c5il/numpad_keys_not_working_in_dwm/

**Comment by VuiMuich** [comment]
Of course!
This totally makes sense, if we would not ignore NumLock, we would have to add it in basically every keybind, as for most users it is always on.

I guess your workaround is to simple to make adding some logic to only check NumLock state for keybinds that bind some `KP_*` worth the effort. 
But adding this to the wiki would be helpful.

**Comment by f0ff886f** [comment]
Thank you all!

Just in case anyone wants a quick shortcut to get the numpad bound to the regular positions, here is the config:

```rust
        (command: GotoTag, value: "1", modifier: ["modkey"], key: "KP_End"),
        (command: GotoTag, value: "2", modifier: ["modkey"], key: "KP_Down"),
        (command: GotoTag, value: "3", modifier: ["modkey"], key: "KP_Next"),
        (command: GotoTag, value: "4", modifier: ["modkey"], key: "KP_Left"),
        (command: GotoTag, value: "5", modifier: ["modkey"], key: "KP_Begin"),
        (command: GotoTag, value: "6", modifier: ["modkey"], key: "KP_Right"),
        (command: GotoTag, value: "7", modifier: ["modkey"], key: "KP_Home"),
        (command: GotoTag, value: "8", modifier: ["modkey"], key: "KP_Up"),
        (command: GotoTag, value: "9", modifier: ["modkey"], key: "KP_Prior"),
        (command: MoveToTag, value: "1", modifier: ["modkey", "Shift"], key: "KP_End"),
        (command: MoveToTag, value: "2", modifier: ["modkey", "Shift"], key: "KP_Down"),
        (command: MoveToTag, value: "3", modifier: ["modkey", "Shift"], key: "KP_Next"),
        (command: MoveToTag, value: "4", modifier: ["modkey", "Shift"], key: "KP_Left"),
        (command: MoveToTag, value: "5", modifier: ["modkey", "Shift"], key: "KP_Begin"),
        (command: MoveToTag, value: "6", modifier: ["modkey", "Shift"], key: "KP_Right"),
        (command: MoveToTag, value: "7", modifier: ["modkey", "Shift"], key: "KP_Home"),
        (command: MoveToTag, value: "8", modifier: ["modkey", "Shift"], key: "KP_Up"),
        (command: MoveToTag, value: "9", modifier: ["modkey", "Shift"], key: "KP_Prior"),
```

**Comment by kyleguarco** [comment]
While I was looking at this, [I noticed that `LockMask` and `Mod2Mask` are ignored as modifiers][1], but why not both?

The code defines this `Vec` of modifiers
```rust
// By the way, `mods` could be a statically sized array instead,
// since we know the entries beforehand and aren't changed.
let mods: Vec<u32> = vec![
    modifiers, // Take default modifier
    modifiers | xlib::Mod2Mask, // Modifier with NumLock on
    modifiers | xlib::LockMask, // Modifier with CapsLock on
];
```
But there should be a fourth entry
```rust
    modifiers | xlib::Mod2Mask | xlib::LockMask, // Modifier with Both NumLock and CapsLock
```
added. I tested this on version 0.4.2 and, in fact, I can't open a terminal with both the NumLock and CapsLock on.

[1]: https://github.com/leftwm/lefthk/blob/eb6f5646b24e9d64b2f79a363b28ef7311ddd4d4/lefthk-core/src/xwrap.rs#L130

**Comment by kyleguarco** [comment]
> Of course! This totally makes sense, if we would not ignore NumLock, we would have to add it in basically every keybind, as for most users it is always on.
> 
> I guess your workaround is to simple to make adding some logic to only check NumLock state for keybinds that bind some `KP_*` worth the effort. But adding this to the wiki would be helpful.
> 
> Thanks @kyleguarco for looking into this!
> 
> Also I'd say this technically is not a bug, as this is an explicit design choice for the sake of code simplification. Therefore I remove the bug flag.

I've made [changes][1] to the wiki. How does it look?

[1]: https://github.com/leftwm/leftwm/wiki/Config#keybind

**Comment by VuiMuich** [comment]
> I've made [changes](https://github.com/leftwm/leftwm/wiki/Config#keybind) to the wiki. How does it look?

Awesome, thanks! I just added the above config snippet in the Troubleshooting page and linked to it from your new bullet point

> While I was looking at this, [I noticed that `LockMask` and `Mod2Mask` are ignored as modifiers](https://github.com/leftwm/lefthk/blob/eb6f5646b24e9d64b2f79a363b28ef7311ddd4d4/lefthk-core/src/xwrap.rs#L130), but why not both?
> 
> The code defines this `Vec` of modifiers
> 
> ```rust
> // By the way, `mods` could be a statically sized array instead,
> // since we know the entries beforehand and aren't changed.
> let mods: Vec<u32> = vec![
>     modifiers, // Take default modifier
>     modifiers | xlib::Mod2Mask, // Modifier with NumLock on
>     modifiers | xlib::LockMask, // Modifier with CapsLock on
> ];
> ```
> 
> But there should be a fourth entry added:
> 
> ```rust
>     modifiers | xlib::Mod2Mask | xlib::LockMask, // Modifier with Both NumLock and CapsLock
> ```
> 
> I tested this on version 0.4.2 and I can't open a terminal with both the NumLock and CapsLock on. I can't use any of the bindings with both on, in fact.

While I was writing a PR for `atuin` I was experiencing something similar, where in match arms or-patterns with more then one or would not work, but I never came around to investigate it further.

But maybe we should move further discussion over to lefthk.

@f0ff886f I guess your issue is safe to be considered `solved`, right? Otherwise feel free to reopen.

**Comment by f0ff886f** [comment]
It is indeed, I didn't know if you were still tracking any documentation work so I didn't want to touch it. I confirm that it works fine and is much much easier now to work with leftwm :)
