### ISSUE TITLE
leftwm crashes after incorrect dmenu command

### ISSUE THREAD

**Issue by FenixAlive** [leftwm/leftwm#112]
If I write some incorrect command to dmenu who is supposed to run in terminal like vim or vifm, leftwm crashes and i cannot do anything but kill the process from another tty console. This only happends in leftwm. In dwm and i3 it only ignore the command.

my dmenu_path:
```
#!/bin/sh

cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/dmenu_run"

[ ! -e "$cachedir" ] && mkdir -p "$cachedir"

IFS=:
if stest -dqr -n "$cache" $PATH; then
	stest -flx $PATH | sort -u | tee "$cache"
else
	cat "$cache"
fi
```
my dmenu_run:
```
#!/bin/sh
`dmenu_path | dmenu -fn 'monospace-19' -nb '#232323' -nf '#f4f4f4' -sb '#ec3759'` && eval "exec $exe"
```
I am using a vanilla leftwm installed from AUR in Archlinux without theme nor bar.

Regards

**Comment by VuiMuich** [comment]
@FenixAlive I tried to reproduce by running `gurke` as `background` and `gurke-term` as `terminal` from dmenu, but could not reproduce.
Is the issue still producible for you, then please feel free to reopen this isuue.
