### ISSUE TITLE
Personal settings layout_definitions in config.ron are just ignored

### ISSUE THREAD

**Issue by thealio** [leftwm/leftwm#1127]
### Describe the bug

Hi
The parameters to layout_definitions defined by the users are just ignored

Example

 (name: "CenterMainBalanced", 
  flip: None, 
  rotate: North, 
  reserve: None, 
  columns: (flip: None, rotate: North, main: (count: 1, size: 0.5, flip: None, rotate: North, split: Vertical), stack: (flip: None, rotate: North, split: Vertical), second_stack: (flip: None, rotate: North, split: Vertical))),

I setted the splits Vertical , but it still splits Dwindle , as it was in the default config.ron
And the same happens for all the parameters

### Expected behavior (optional)

The parameters for layout_definitions should be variated as user's settings

### OS / Distro

Arch Linux 6.1.46-1-lts

### LeftWM Check

```text
:: LeftWM version: 0.4.2
:: LeftWM git hash: 0.4.2-11-g5d18b901
:: Enabled features:  journald-log lefthk
:: Checking feature dependencies . . .
    -> journald-log OK
    -> lefthk OK
:: Checking for leftwm binaries . . .
    -> Binaries OK
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
ERROR: Key `XF86AudioRaiseVolume` is not valid for keybind Keybind { command: Execute, value: "amixer set Master 10%+", modifier: Some(List([""])), key: "XF86AudioRaiseVolume" }
ERROR: Modifier `` is not valid for keybind Keybind { command: Execute, value: "amixer set Master 10%+", modifier: Some(List([""])), key: "XF86AudioRaiseVolume" }
ERROR: Key `XF86AudioLowerVolume` is not valid for keybind Keybind { command: Execute, value: "amixer set Master 10%-", modifier: Some(List([""])), key: "XF86AudioLowerVolume" }
ERROR: Modifier `` is not valid for keybind Keybind { command: Execute, value: "amixer set Master 10%-", modifier: Some(List([""])), key: "XF86AudioLowerVolume" }
ERROR: Key `XF86AudioMute` is not valid for keybind Keybind { command: Execute, value: "amixer -D pulse set Master 1+ toggle", modifier: Some(List([""])), key: "XF86AudioMute" }
ERROR: Modifier `` is not valid for keybind Keybind { command: Execute, value: "amixer -D pulse set Master 1+ toggle", modifier: Some(List([""])), key: "XF86AudioMute" }
ERROR: Key `XF86AudioPlay` is not valid for keybind Keybind { command: Execute, value: "playctl play-pause", modifier: Some(List([""])), key: "XF86AudioPlay" }
ERROR: Modifier `` is not valid for keybind Keybind { command: Execute, value: "playctl play-pause", modifier: Some(List([""])), key: "XF86AudioPlay" }
ERROR: Key `XF86AudioNext` is not valid for keybind Keybind { command: Execute, value: "playctl next", modifier: Some(List([""])), key: "XF86AudioNext" }
ERROR: Modifier `` is not valid for keybind Keybind { command: Execute, value: "playctl next", modifier: Some(List([""])), key: "XF86AudioNext" }
ERROR: Key `XF86AudioPrev` is not valid for keybind Keybind { command: Execute, value: "playctl previous", modifier: Some(List([""])), key: "XF86AudioPrev" }
ERROR: Modifier `` is not valid for keybind Keybind { command: Execute, value: "playctl previous", modifier: Some(List([""])), key: "XF86AudioPrev" }
ERROR: Key `XF86AudioStop` is not valid for keybind Keybind { command: Execute, value: "playerctl stop", modifier: Some(List([""])), key: "XF86AudioStop" }
ERROR: Modifier `` is not valid for keybind Keybind { command: Execute, value: "playerctl stop", modifier: Some(List([""])), key: "XF86AudioStop" }
ERROR: Key `XF86MonBrightnessUp` is not valid for keybind Keybind { command: Execute, value: "xbacklight -inc 10", modifier: Some(List([""])), key: "XF86MonBrightnessUp" }
ERROR: Modifier `` is not valid for keybind Keybind { command: Execute, value: "xbacklight -inc 10", modifier: Some(List([""])), key: "XF86MonBrightnessUp" }
ERROR: Key `XF86MonBrightnessDown` is not valid for keybind Keybind { command: Execute, value: "xbacklight -dec 10", modifier: Some(List([""])), key: "XF86MonBrightnessDown" }
ERROR: Modifier `` is not valid for keybind Keybind { command: Execute, value: "xbacklight -dec 10", modifier: Some(List([""])), key: "XF86MonBrightnessDown" }
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```

**Comment by thealio** [comment]
> Is this now fixed with the config being correctly serialized, or is there still something broken for you here?

Hi
unfortunately , This bug is still present for me

**Comment by thealio** [comment]
also , when you open lots of widows, some windows went "over the monitor

To reproduce , try to open 14 or more  windows on the CenterMainBalanced.

The ideal behavior is , in my opinion, to split also the upper stacks windows.

Also, adding an option to limit the number of opened windows in the layout , and open the exceeded windows in the next workspace (or in a given by the user one ) , could be a great feature for the future.

**Comment by VuiMuich** [comment]
:thinking: I might be wrong, believe the intention of the layout_definition would be to define own layouts and not to change/override the builtin layouts. Could you test to Prepend `My` to each (and also in the layout array)?

**Comment by thealio** [comment]
> 🤔 I might be wrong, believe the intention of the layout_definition would be to define own layouts and not to change/override the builtin layouts. Could you test to Prepend `My` to each (and also in the layout array)?

Maybe I've just not clear how it works, I apologize

Can you provide an example ?
Thanks in advance

**Comment by VuiMuich** [comment]
This is some little example layout_definition I keed dragging in my config since testing the feature during review, maybe this helps you:
```rust
    layouts: [
        "MainAndDeck",
        "Monocle",
        "CenterMainFluid",
        "Foo",        
        // "LeftWiderRightStack",
    ],
    layout_definitions: [
    (
        name: "Foo",
        flip: None,
        rotate: North,
        reserve: ReserveAndCenter,
        columns: (
            flip: None,
            rotate: North,
            main: Some(Main(count: 1, size: 0.4, flip: None, rotate: North, split: Some(Horizontal))),
            stack: (flip: None, rotate: North, split: Some(Vertical)),
            second_stack: Some(SecondStack(flip: None, rotate: North, split: Horizontal)),
        )
    ),
    ],
```
But as just metioned by Erik from Arcolinux in the discussions, a update on the docs is actually overdue.

**Comment by thealio** [comment]
> This is some little example layout_definition I keed dragging in my config since testing the feature during review, maybe this helps you:
> 
> ```rust
>     layouts: [
>         "MainAndDeck",
>         "Monocle",
>         "CenterMainFluid",
>         "Foo",        
>         // "LeftWiderRightStack",
>     ],
>     layout_definitions: [
>     (
>         name: "Foo",
>         flip: None,
>         rotate: North,
>         reserve: ReserveAndCenter,
>         columns: (
>             flip: None,
>             rotate: North,
>             main: Some(Main(count: 1, size: 0.4, flip: None, rotate: North, split: Some(Horizontal))),
>             stack: (flip: None, rotate: North, split: Some(Vertical)),
>             second_stack: Some(SecondStack(flip: None, rotate: North, split: Horizontal)),
>         )
>     ),
>     ],
> ```
> 
> But as just metioned by Erik from Arcolinux in the discussions, a update on the docs is actually overdue.

Hi,
I tested this layout, it works as expected.

But, a specific documentation for layouts' editing it's absolutely needed

See  #1132
