### ISSUE TITLE
Improve manpage

### ISSUE THREAD

**Issue by VuiMuich** [leftwm/leftwm#1129]
This really should be an issue to be tracked.
### Discussed in https://github.com/leftwm/leftwm/discussions/1128

<div type='discussions-op-text'>

<sup>Originally posted by **thealio** August 24, 2023</sup>
Hi
I notice that the manpage misses some information about how to configure.

For example, a  in the layout section , the layouts are still reported without double quotes. and the layout_definition settings are not reported.

I'd like to see a more updated and complete manpage, so the user can use it as a guide for configure leftwm, even without  log to the github page</div>

**Comment by VentGrey** [comment]
I think I added some of those features in my old PR, if needed, I can re-write the manpage or add those sections :) just let me know what would be nice to have, and I'll submit a PR.

**Comment by VuiMuich** [comment]
That would be nice, if you could give this a shot.
