### ISSUE TITLE
Swap tags behavior

### ISSUE THREAD

**Issue by fversaci** [leftwm/leftwm#1135]
### Describe the feature

There exist `SwapWindowTop` and `SwapTags`, but I cannot find command to switch the focus between the last two used tags.  This is a commonly desired feature when switching between two applications, so it would be great to have it (unless it already exists and I just can't find it...).

### How important is this feature to you?

Would be nice to have

### How important do you think is this feature for the average LeftWM user?

Would probably be nice to have

**Comment by fversaci** [comment]
I noticed a similar behavior: when attempting to switch to the currently active workspace (e.g., pressing ALT+3 on workspace 3), it actually goes to the previous one. However, it might be more convenient to have a designated key that works regardless of the current workspace.

**Comment by nemalex** [comment]
I think this is what you are searching for https://github.com/leftwm/leftwm/wiki/Config#returntolasttag

**Comment by fversaci** [comment]
Thanks, I had missed that! It works perfectly :)
