### ISSUE TITLE
Build warning

### ISSUE THREAD

**Issue by 0323pin** [leftwm/leftwm#1139]
### Describe the bug

```
   Compiling leftwm-macros v0.4.2 (/home/pin/leftwm/leftwm-macros)
warning: unused variable: `level`
 --> leftwm/src/bin/leftwm-log.rs:7:9
  |
7 |     let level = matches.get_count("verbose");
  |         ^^^^^ help: if this is intentional, prefix it with an underscore: `_level`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: `leftwm` (bin "leftwm-log") generated 1 warning (run `cargo fix --bin "leftwm-log"` to apply 1 suggestion)
    Finished release [optimized] target(s) in 6m 38s
```
The good news is, I'm back running LeftWM from git-HEAD :smile: 
This time on Linux, though. Void musl

### Steps to reproduce (optional)

Build from the latest git-commit

### OS / Distro

Linux muslbox 6.3.13_1 #1 SMP PREEMPT_DYNAMIC Tue Jul 25 00:19:40 UTC 2023 x86_64 GNU/Linux

### LeftWM Check

```
:: LeftWM version: 0.4.2
:: LeftWM git hash: 0.4.2-21-g020ce3a
:: Enabled features: lefthk sys-log
:: Checking feature dependencies . . .
    -> lefthk OK
:: Checking for leftwm binaries . . .
    -> Binaries OK
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```

**Comment by VuiMuich** [comment]
I suspect `ssd-log` is not making use of this variable for some reason.

**Comment by 0323pin** [comment]
> I suspect `ssd-log` is not making use of this variable for some reason.

That's fine. I just wanted to let you know about the warning.
... and that I'm once again running the dev version 😉

**Comment by Eskaan** [comment]
@0323pin yeah, that is a case that I didn't consider. Anyways, could you tell me how the syslog gets printed. (Is it the same as the file log? I could use that regex to filter then).

**Comment by 0323pin** [comment]
@Eskaan Right now, I get the same as I did on NetBSD,

```
[Mon Sep 04 18:20] pin@muslbox ~$ leftwm-log
cat: /var/log/syslog: No such file or directory
```

creating the file silences the warning but, nothings gets logged.

**Comment by Eskaan** [comment]
Yeah, atm we do a `cat /var/log/syslog`, I didn't implement it so I don't exactly know what it does (and I don't use syslog myself).

**Comment by 0323pin** [comment]
@hertg ?
