### ISSUE TITLE
switch between desktops/tags

### ISSUE THREAD

**Issue by Valerioooo** [leftwm/leftwm#114]
I have used leftwm for the past week and I love it!
But there is a thing that I think is missing: the function to switch between tags with the arrow keys. I think this is a key feature that could be implemented to make this WM even more amazing.

**Comment by mautamu** [comment]
Howdy, I was wanting something similar and wrote b75a3e4 to implement this. My new config.toml file (relevant lines only) is:
`[[keybind]]
command = "FocusNextTag"
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey"]
key = "Left"`

Is this what you were after as well, Valerioooo?

May I submit a PR to make this a feature for everyone?

**Comment by lex148** [comment]
Absolutely I would Love A PR

**Comment by Valerioooo** [comment]
> Is this what you were after as well, Valerioooo?
YESSSS!
This is very funny, I was already making changes to the code in my version to add support for that.
 Thanks man.
