### ISSUE TITLE
ToggleMaximized hides docked windows

### ISSUE THREAD

**Issue by vesdev** [leftwm/leftwm#1162]
### Describe the bug

The ToggleMaximized command hides docked windows, in my case polybar.

I'm guessing it is related to
https://github.com/leftwm/leftwm/commit/4621dab374084fac6022a5e148a4aa8620ce15ec

havent looked too much into it, but the last commit i was on where it worked is
https://github.com/leftwm/leftwm/commit/963acf9b53d8fc508ad4d5f0fce9991d825149ff

### Expected behavior (optional)

polybar should remain visible

### OS / Distro

NixOS

### LeftWM Check

```text
:: LeftWM version: 0.4.2
:: LeftWM git hash: 4621dab
:: Enabled features:  journald-log lefthk
:: Checking feature dependencies . . .
    -> journald-log OK
    -> lefthk OK
:: Checking for leftwm binaries . . .
    -> Binaries OK
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```

**Comment by VuiMuich** [comment]
Thanks for reporting.
I believe #1060 might fix this, but it has merge conflicts I haven't have time to look into.

Also maybe @Eskaan would have a better opinion rn if the commit you are suspecting is the true culprit.

**Comment by Eskaan** [comment]
I just checked, it’s not due to the commit you mentioned, but I can reproduce the issue and will try to find the one that made the change. Now that I’m back on main I can reproduce it tho.
