### ISSUE TITLE
Toml Colors File for Alacritty

### ISSUE THREAD

**Issue by Mediacom99** [leftwm/leftwm#1171]
### Describe the feature

Hey guys I was wondering if anyone added a toml colors file. I wanted to do it but I can't figure out the most efficient way. Can you help ? Maybe just point me to the right direction and I'll take it from there, like should I write it a script for it ? Thank you very much!

### How important is this feature to you?

It is just an idea

### How important do you think is this feature for the average LeftWM user?

I don't know, may be a niche edge-case

**Comment by Eskaan** [comment]
Do I understand you correctly that you want to change your Alacritty config based on the selected theme?

**Comment by Mediacom99** [comment]
Yes I would like to change my Alacritty colors config by using a colors.toml file that contains the current colors generated by pywal

**Comment by 0323pin** [comment]
If you build `alacritty` from git, _I.e._ the dev version, currently 0.13.0, the config file is in `toml`. I run this version and if you want an example feel free [to grab what you want](https://codeberg.org/pin/netbsd/raw/branch/main/.config/alacritty/alacritty.toml).

Now, please be aware that the release versions (<0.13.0) do not support configuration in `toml`.

**Comment by Mediacom99** [comment]
Thank you very much.

**Comment by 0323pin** [comment]
I think we can close this now.
