### ISSUE TITLE
release 0.5.0 still reports version 0.4.2

### ISSUE THREAD

**Issue by adamcstephens** [leftwm/leftwm#1177]
### Describe the bug

Using tag 0.5.0 I get the following version:

```
─❯ ./result/bin/leftwm --version
leftwm 0.4.2
```

### Expected behavior (optional)

I expect it to return 0.5.0.

### OS / Distro

nixos unstable

### Additional System Information (optional)

Looks like the version was missed here at a minimum: https://github.com/leftwm/leftwm/blob/4eddb185b32e1ede707497fcf5705290341ac74f/leftwm/Cargo.toml#L3

### LeftWM Check

```text
n/a
```

**Comment by nemalex** [comment]
This could be the source of the problem https://github.com/leftwm/leftwm/blob/4eddb185b32e1ede707497fcf5705290341ac74f/leftwm/Cargo.toml#L3

**Comment by VuiMuich** [comment]
basically #1178 fixed this, but I want to keep this open until it is clear if we can amend the crates.io release, or if we need to bump to 0.5.1 in order to fix it for good.
