### ISSUE TITLE
Separate leftwm(bin) target from the leftwm crate

### ISSUE THREAD

**Issue by Eskaan** [leftwm/leftwm#1190]
## What and how

I think we could separate the leftwm(bin) binary target from the leftwm crate. It itself only starts child processes and depends on about two functions from the util mod, one of them bein exclusively used by leftwm(bin) and the other being a simple `Vec::retain` shortcut for the `Vec<Child>` wrapper.

## Why

This should improve compile times, especially on multi-threading hardware, but also because it's one binary less to compile for the usual changes (6 less when changing only leftwm(bin)).

Anyone against this development change? I'd open a pr in a few days otherwise.

**Comment by VuiMuich** [comment]
Sounds reasonable to me.
I am wondering how much this would affect packaging, or is this just a thing that matters during (re-) compilation?
Nevertheless I am curious enough to discuss further details in the PR review.
