### ISSUE TITLE
Unable to use with a portrait monitor

### ISSUE THREAD

**Issue by leftbones** [leftwm/leftwm#1208]
### Describe the bug

My setup is a main landscape monitor and a second portrait monitor off to the left. The portrait monitor has to be rotated in software, it doesn't have any built in options for portait mode. With the XFCE display settings, I can rotate the monitor just fine, but when I boot into leftwm instead, it doesn't respect this rotation. I looked around at the config options and didn't see anything for rotating, is this possible?

### OS / Distro

Void Linux x86_64 6.6.10_1

### LeftWM Check

```text
:: LeftWM version: 0.4.2
:: LeftWM git hash: unknown
:: Enabled features: lefthk sys-log
:: Checking feature dependencies . . .
    -> lefthk OK
:: Checking for leftwm binaries . . .
    -> Binaries OK 
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK 
:: Checking theme . . .
    -> Theme OK 
```
```

**Comment by leftbones** [comment]
Just now I was able to get things in the right orientation by using `arandr` to move things around, but I'm still curious if there is something in the leftwm config I can do about this.

**Comment by barkyq** [comment]
You could load the command line program `xrandr` in your `.xinitrc` script to automatically fix the orientation.

**Comment by Eskaan** [comment]
Exactly. Leftwm is only a window manager, it has nothing to do with the display resolution and orientation.
The X display server (the one leftwm talks to) has the (x)randr interface to change those settings.

I think arandr has an option to export the current settings as a xrandr command btw.
