### ISSUE TITLE
`default_height` and `default_width` in theme.ron are not used when `ToggleFloating`

### ISSUE THREAD

**Issue by barkyq** [leftwm/leftwm#1212]
### Describe the bug

Whenever I toggle a window to floating it is always in 800 x 600 format.

### Expected behavior (optional)

The configuration options in theme.ron should be applied

### Steps to reproduce (optional)

toggle a window to floating

### OS / Distro

Linux vivobook 6.6.8 #3 SMP PREEMPT_DYNAMIC Wed Dec 27 20:37:25 EST 2023 x86_64 GNU/Linux

### LeftWM Check

```text
:: LeftWM version: 0.5.1
:: LeftWM git hash: 0.5.1-18-g346f289-modified
:: Enabled features:  journald-log lefthk
:: Checking feature dependencies . . .
    -> journald-log OK
    -> lefthk OK
:: Checking for leftwm binaries . . .
    -> Binaries OK
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```

**Comment by Eskaan** [comment]
Could you paste your theme.ron, please?

**Comment by barkyq** [comment]
Yes pretty sure theme.ron is loaded correctly

```rust
(
    default_width: 1000,
    border_width: 2,
    margin: (18, 18, 18, 18),
    focused_border_color: "#FF0000",
    default_border_color: "#00FF00",
    floating_border_color: "#0000FF",    
)
```

default_width is not applied when `ToggleFloating`. I tried changing border size and colors and they do after `SoftReload`
