### ISSUE TITLE
UI scaling realy weird when launching unreal editor

### ISSUE THREAD

**Issue by NicTanghe** [leftwm/leftwm#1222]
### Describe the bug

Launching the unreal editor the UI is so large that i need to move  the top left corner outside of the screen to be able to c all ui.

### Expected behavior (optional)

scaling is same as on gnome

### Steps to reproduce (optional)

download [unreal 5.3.2 ](https://www.unrealengine.com/en-US/linux)
extract zip
open editor

### OS / Distro

22.04.1-Ubuntu

### LeftWM Check

```text
❯ leftwm-check
:: LeftWM version: 0.5.1
:: LeftWM git hash: 0.5.1
:: Enabled features:  journald-log lefthk
:: Checking feature dependencies . . .
    -> journald-log OK
    -> lefthk OK
:: Checking for leftwm binaries . . .
    -> Binaries OK
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
ERROR: Multiple commands bound to key combination modkey + l:
    -> (List(["modkey"]), "l")
    -> FocusWorkspaceNext
Help: change one of the keybindings to something else.

:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```

**Comment by Eskaan** [comment]
Are you sure you have you screen's resolution set right?
I suggest you take a look at what's selected in `xrandr` for that.

Besides, the error in the config shouldn't be related but will cause leftwm to fall back to default settings (suggest you fix that too).

**Comment by NicTanghe** [comment]
After running the program on gnome once, it was normally scaled.
