### ISSUE TITLE
Scratchpad commands should support arguments

### ISSUE THREAD

**Issue by akosfekete** [leftwm/leftwm#1223]
### Describe the enhancement

Due to the changes in #1216, scratchpad commands do not seem to take arguments. E.g. `mpv` works fine, but `mpv test.mp4` doesn't seem to work.

I have multiple scratchpads that launch chromium instances in kiosk mode with a specific data directory and URL. I use these as apps effectively (e.g. for Youtube music). Here's an example scratchpad config:
`name: "yt_music", value: "chromium --user-data-dir=\"/home/black/etc/yt_music_chromium\" --kiosk --disable-session-crashed-bubble \"https://music.youtube.com\""`

This worked fine for me. Once started, pressing the key combination for the associated `ToggleScratchpad` command hid the browser and the music kept playing in the background.

This is very useful for me, so I reverted the changes locally to `child_process.rs` to get it to work again.
I think it would be useful to support arguments in general. 

I guess the value of the Scratchpad config's `name` parameter could be split and passed to the `args` to builder method, but that seems a bit weird. Also, arguments could be passed to the Scratchpad config as a config parameter, if that makes sense.

### How important is this enhancement to you?

My workflow is impaired without it

### How important do you think is this enhancement for the average LeftWM user?

Would probably be nice to have

**Comment by Eskaan** [comment]
@mautamu might this be the reason why we had everything wrapped in `sh -c` instead of executing it directly?

[See these lines in the diff](https://github.com/leftwm/leftwm/pull/1216/files#diff-6ab26373f3e163eecf7f1312e1e14fcb953638707869723570a82885505fe9dcL169-R169)

**Comment by mautamu** [comment]
@Eskaan Yep, that makes sense for why we had wrapped everything in `sh -c`. I think that @akosfekete's fork makes sense so I created https://github.com/leftwm/leftwm/pull/1225. Let me know if there are any concerns with the approach.

**Comment by akosfekete** [comment]
Thanks @mautamu  for updating the docs and creating the PR!

I also think now that updating the config might not be the best approach. I'm assuming most users use release versions, so it will break more users' scratchpad when the next version is released. I guess parsing and splitting the command would compatible with the original scratchpad config (although it felt less "clean")

@Eskaan using sh worked fine for all my scratchpad configs, but would it be possible to use it without reintroducing #958 ?

**Comment by Eskaan** [comment]
POSIX-compliant command parsing is difficult, but there are small libraries that could do that for us, like https://crates.io/crates/shlex. I am currently searching if we already have such a library in our dependency tree (for clap) that we could re-use as we're already compiling it for something.
