### ISSUE TITLE
LeftWM Fails to Run in Arch Linux

### ISSUE THREAD

**Issue by d4140n-4h3-1** [leftwm/leftwm#1235]
### Describe the bug

This was a fresh Arch Linux build before I installed XFCE. Anytime I tried to run LeftWM, all I receive is what looks like an endless wave of error messages. Is it a bug, or am I doing something wrong? 

### OS / Distro

Linux IdeaPad-S145 6.7.6-hardened1-1-hardened

### LeftWM Check

```text
:: LeftWM version: 0.5.1
:: LeftWM git hash: 0.5.1-25-gaa22175
:: Enabled features:  journald-log lefthk
:: Checking feature dependencies . . .
    -> journald-log OK
    -> lefthk OK
:: Checking for leftwm binaries . . .
    -> Binaries OK 
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK 
:: Checking theme . . .
ERROR: No theme folder or symlink `current` found.
```

**Comment by mautamu** [comment]
Welcome, fellow adventurer! That does not sound like leftwm's configuration is correct. A few questions to start:
1. How are you trying to start leftwm? `startx` is the ideal approach (uses .xinitrc file containing `exec dbus-launch leftwm`), running `leftwm` in the command line won't properly start the xserver with that configuration.
2. What's in your .xinitrc file? May need to confirm it has appropriate variables for Arch as mentioned [here](https://github.com/leftwm/leftwm?tab=readme-ov-file#starting-with-startx-or-a-login-such-as-slim)
3. What error message is it sending to the terminal? 
4. Any output to journald (`journalctl -u leftwm-worker`)?
5. Did you have xorg-server installed prior to installing XFCE?

**Comment by phpwutz** [comment]
hello fellow traveler,

i managed to get leftwm installed and running on latest arch using the "lightdm" and "leftwm" packages available on AUR, hope that helps!

**Comment by d4140n-4h3-1** [comment]
I got it figured out. Liking it so far, but I have one other issue I am about it make.
