### ISSUE TITLE
Directional Window movement

### ISSUE THREAD

**Issue by marianomarciello** [leftwm/leftwm#1242]
### Describe the feature

This topic is connected with  #771.
In #771 deals with both Directional Focus and Directional Window movement.
I would like to divide the concept of Directional Focus and Directional Window movement.
This feature will be related to the Directional Window movement.
The main idea is that the user can swap the current focused window with another window in 4 different directions: `North`, `South`, `East`, `West`. 

This feature will allow some users (me included) to use more often leftwm because it will be more similar to other wm (e.g i3, dwm).

For any additional details and for more contest please refer to #771.

I would like to implement this feature, any suggestion will be appreciated.
Thanks for your time.

### How important is this feature to you?

Would be nice to have

### How important do you think is this feature for the average LeftWM user?

Would probably be nice to have

**Comment by mautamu** [comment]
Thanks for the callout @0323pin. Marking this as resolved in #1240; @marianomarciello feel free to re-open if needed.
