### ISSUE TITLE
How to start an application?

### ISSUE THREAD

**Issue by lengyijun** [leftwm/leftwm#125]
Hello, I'm new to leftwm and I used to use AwesomeWM. 
I have problem how to start an application?

In Awesome, there is two way:
1. win+r: Run prompt on the bar
2. Right click on the window: a menu bar will display

**Comment by mautamu** [comment]
If you have dmenu installed, the default is:
`Modkey (which is Windows key) + p` will start dmenu

If you have alacritty installed, it can be used to launch a programme as well:
`Modkey+Shift+Return`.

You can also map keys to open specific things. For me, I have one to start Firefox, for example:
~/.config/leftwm/config.toml:
```
[[keybind]]
command = "Execute"
value = "firefox-developer-edition"
modifier = ["modkey", "Shift"]
key = "f"
```

**Comment by lengyijun** [comment]
Thx. dmenu is I'm looking for.
