### ISSUE TITLE
Remove obsolete "max_window_width" variable

### ISSUE THREAD

**Issue by hertg** [leftwm/leftwm#1259]
The `max_window_width` variable is still present in some parts of the code, but I am pretty sure that it no longer has any use after #1000 was merged. It should be removed from the code, after checking that it really isn't used any longer, and also be removed from the wiki.

**Comment by jasonmokk** [comment]
Hello, can I work on this issue?

**Comment by mautamu** [comment]
Sure thing @jasonmokk, much appreciated!

**Comment by nickwe3** [comment]
please remove from the wiki, was trying to make it work with max_window_width...

**Comment by mautamu** [comment]
Added removal notice. Thanks for the catch @nickwe3
