### ISSUE TITLE
Issues starting with LeftWM on Guix

### ISSUE THREAD

**Issue by johnlepikhin** [leftwm/leftwm#1261]
### Describe the feature

Hi there,

I'm trying to start with LeftWM on GuixSD, which is actually NiX-like Linux. There is no nightly Rust, so with cargo it compiled without leftwm-config. In README, section OpenBSD, I've read that in this case leftwm-config wouldn't be compiled and at first start leftwm will generate the default config. But actually it's not. Probably because there is no journald in Guix:

> $ leftwm
> sh: line 1: /tmp/mattermost-desktop-5.5.1-linux-x64/mattermost-desktop: No such file or directory
> thread 'thread 'mainmain' panicked at ' panicked at /home/evgenii/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leftwm-0.5.1/src/utils/log/journald.rs/home/evgenii/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leftwm-0.5.1/src/utils/log/journald.rs::1515::1010:
> :
> Couldn't setup journald-logger. Are you sure journald is running?: Os { code: 2, kind: NotFound, message: "No such file or directory" }Couldn't setup journald-logger. Are you sure journald is running?: Os { code: 2, kind: NotFound, message: "No such file or directory" }
> 
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Leftwm crashed due to an unexpected error.
> Please create a new issue and post its log if possible.
> 
> NOTE: You can restart leftwm with `startx`.
> Failure: No such entity

I also checked config example https://github.com/leftwm/leftwm/blob/main/examples/config-with-comments.ron and found no option to switch to logger like sys-log or file-log.

The next step was to try to compile without journald support. Unfortunately, it failed:

> $ cargo install --no-default-features -F sys-log,file-log,xlib,x11rb,lefthk leftwm
>    Updating crates.io index
>  Installing leftwm v0.5.1
> ...
> Caused by:
>  none of the selected packages contains these features: x11rb, xlib

So, it looks like there are several issues which blocks me to try leftwm :) Any workarounds are welcome.

### How important is this feature to you?

LeftWM is unusable without it

### How important do you think is this feature for the average LeftWM user?

I don't know, may be a niche edge-case

**Comment by Eskaan** [comment]
I don't think the x11rb backend has been released yet (should be coming soon), so you just need to remove those two feature flags to compile the current release.
`cargo install --no-default-features -F sys-log,file-log,lefthk leftwm`

Do you want leftwm to log to both a file and sys-log or just one of them? It currently tries to log to all enabled features.

**Comment by johnlepikhin** [comment]
It helped, thank you!

According to documentation, I need to compile with xlib or x11rb: "You need to select at least one backend feature (*) for leftwm to build". Closing the issue, probably it is just a minor documentation bug.

**Comment by Eskaan** [comment]
It's the current documentation, based on the current revision on the main branch. You can also read the documentation at the time of the last release here: https://github.com/leftwm/leftwm/tree/0.5.1
