### ISSUE TITLE
Dead link in README related to default layouts

### ISSUE THREAD

**Issue by AnthonyMichaelTDM** [leftwm/leftwm#1299]
The README contains a dead link related to the default layouts,

https://github.com/leftwm/leftwm/blob/a5aa9c3e02a2851f6905914ef099e46fe7264238/README.md?plain=1#L582C1-L582C109

It should probably be changed to point to https://github.com/leftwm/leftwm-layouts/blob/main/leftwm-layouts/src/layouts/defaults.rs, and the wording adjusted to no longer refer to an enum.

Maybe:

```md
The default layouts are [all of the kinds defined here](https://github.com/leftwm/leftwm-layouts/blob/main/leftwm-layouts/src/layouts/defaults.rs).
``` 

or something like that

**Comment by mautamu** [comment]
Good catch!

Think the proposed fix makes sense.

**Comment by AnthonyMichaelTDM** [comment]
alright I'll open a PR
