### ISSUE TITLE
How to configure polybar systray?

### ISSUE THREAD

**Issue by MiraculousMoon** [leftwm/leftwm#132]
I have encountered a wired problem about polybar systray like this: 
![图片](https://user-images.githubusercontent.com/61657399/96152629-55192680-0f3f-11eb-949f-7c6db901809b.png)

![图片](https://user-images.githubusercontent.com/61657399/96158890-95c86e00-0f46-11eb-9232-325e7fb9dbda.png)

This is my config: [my polybar config](https://raw.githubusercontent.com/MiraculousMoon/nord-solar/master/bspwm/polybar/config)

But this phenomenon is not just appear with my config. It also appear when I try one of the example themes [leftwm-soothe](https://github.com/b4skyx/leftwm-soothe/tree/986a1afede9daa77ac05e90af96ed22a0b8a3fb9).

![图片](https://user-images.githubusercontent.com/61657399/96157851-66653180-0f45-11eb-8a15-db68c9e84f25.png)

**Comment by MiraculousMoon** [comment]
Is the polybar viewed as a window in Leftwm? It will be close when I press Mod+Shift+q without any other windows.
How can I avoid it?

**Comment by lengyijun** [comment]
> Is the polybar viewed as a window in Leftwm? It will be close when I press Mod+Shift+q without any other windows.
> How can I avoid it?

Same in https://github.com/leftwm/leftwm/issues/127

**Comment by lex148** [comment]
@lengyijun i have pushed a fix for the polybar closing issue [here](https://github.com/leftwm/leftwm/commit/86cb32d53065cb1b3c4bc588bd88cd99d0196944). I think that #127 is a different issue.

@MiraculousMoon I am a bit unsure as to what you are seeing. Are you seeing multiple issue, or just the closing issue?

**Comment by MiraculousMoon** [comment]
> 
> 
> @lengyijun i have pushed a fix for the polybar closing issue [here](https://github.com/leftwm/leftwm/commit/86cb32d53065cb1b3c4bc588bd88cd99d0196944). I think that #127 is a different issue.
> 
> @MiraculousMoon I am a bit unsure as to what you are seeing. Are you seeing multiple issues, or just the closing issue? I just pushed the update for the closing issue.

I mean I encountered two problems.
The first is the weird systray of polybar. As you can see, the systray is blurry just like something overrides it. But in fact, the same config of polybar can run well. So I suspect it's Leftwm's problem.
The Second is the bug that you fixed.

**Comment by MiraculousMoon** [comment]
> @lengyijun i have pushed a fix for the polybar closing issue [here](https://github.com/leftwm/leftwm/commit/86cb32d53065cb1b3c4bc588bd88cd99d0196944). I think that #127 is a different issue.
> 
> @MiraculousMoon I am a bit unsure as to what you are seeing. Are you seeing multiple issues, or just the closing issue? I just pushed the update for the closing issue.

Now I find this phenomenon disappeared. But I do nothing:)
