### ISSUE TITLE
Alt (Mod1) can't be used with keybinds

### ISSUE THREAD

**Issue by rypervenche** [leftwm/leftwm#133]
When trying to add a keybind for ctrl+alt+l, the Alt key doesn't get recognized. Trying to use the key combination results in nothing happening, but ctrl+l will trigger the keybind.

```
altkey = "Mod1"
[[keybind]]
command = "Execute"
value = "slock"
modifier = ["altkey", "Control"]
key = "l"
```

**Comment by mautamu** [comment]
https://github.com/leftwm/leftwm/blob/d0c55a73758583c0650c4162d01af6d4f44a758f/src/utils/xkeysym_lookup.rs
```
[[keybind]]
command = "Execute"
value = "slock"
modifier = ["Control", "Alt"]
key = "l"
```

**Comment by rypervenche** [comment]
Oh! Silly me. Thanks for the quick response. I'll browse the code before submitting future Issues.

**Comment by lex148** [comment]
You should NOT have to go read a code file to figure out how to do something. Stuff like this helps us know where we need to improve our documentation. 

If you have any other questions we are happy to help,
-Lex Childs

**Comment by lex148** [comment]
I have updated the Wiki to help point out this list of keys for people in the future.
[https://github.com/leftwm/leftwm/wiki/Config](https://github.com/leftwm/leftwm/wiki/Config)
