### ISSUE TITLE
set floating window to center

### ISSUE THREAD

**Issue by samurailostinjapan** [leftwm/leftwm#140]
i have several windows that are floating that i want to be centered when launched.
Usually in the configuration file of twm there are rules to configure this action.
How can i configure this?

Thanks!

**Comment by lex148** [comment]
LeftWM currently doesn't have rules like this to control applications when they start. This sounds like a good feature to add.

**Comment by fedoranvar** [comment]
yes, that's a good feature, I've used it in bspwm, for creating new terminal window in float.

one of the things it helped me, was calling external editor (neovim) for qutebrowser.
