### ISSUE TITLE
Project CI

### ISSUE THREAD

**Issue by piotrmaks** [leftwm/leftwm#141]
Is there any CI for this project? If not would you like to start one? I'd be happy to help with PR for GH Actions/Cirrus CI jobs (depending on which provider you prefer).

Usually I go with:
- RUSTFLAGS=-Dwarnings
- RUSTDOCFLAGS=-Dwarnings
- cargo build --all-targets --all-features
- cargo test --all-targets --all-features
- cargo clippy --all-targets --all-features
- cargo fmt -- --check

**Comment by piotrmaks** [comment]
@lex148 ?

**Comment by lex148** [comment]
My apologies, these last couple weeks have been a little time consuming in my life, And i missed your message. Absolutely I'm interested!, and would appreciate your help.

**Comment by lex148** [comment]
I don't have a preference, and would want to lean on your advice here.

**Comment by piotrmaks** [comment]
@lex148 could you check in repository settings if GitHub Actions are enabled? For some reason it doesn't start for a draft PR I have started.

**Comment by lex148** [comment]
I can confirm they are enabled.
