### ISSUE TITLE
Is there a way to resize windows with a keybinding?

### ISSUE THREAD

**Issue by cjwyett** [leftwm/leftwm#144]
DWM has MOD+L/H to make the master window bigger/smaller. Is there something i could do to replicate this in Left?

P.S. Love the project.

**Comment by lex148** [comment]
The closest that currently exist in LeftWM is resizing/moving the window by holding the mod key and pressing the Left/Right mouse buttons to move/resize windows. This feature has gotten a lot of love in the last release so if you aren't on latest you might want to check it out. 

That being said, if there is enough interest in being able to resize/move without the mouse then lets add it.

**Comment by cjwyett** [comment]
@lex148 Movement is easy enough for now via combinations of Mod+Arrow and Mod+Ret. I would just really like to be able to quickly move X (below) for different tasks.   
```
+---------X-------+
|         |       |
|         |       |
|         |       |
|         +-------+
|         |       |
|         |       |
|         |       |
+---------X-------+
```
As [DWM](https://dwm.suckless.org/dynamic_window_management/) put eloquently: 

>  The number and nature of windows you work with changes all the time, and a dynamic window manager lets you adapt to that and always efficiently use your precious screen real estate... you might want to have a patch someone emailed you in view while you look at some code, or edit a configuration file while you look at a man page or website. Dynamic window management lets you mix and match on the fly to always have the windows you need in view, and only the windows you need, without the need to reserve extra space which you may or may not end up using.

**Comment by KevinNThomas** [comment]
I agree that resizing windows with keybindings would be great, it's a function I use all the time on other WMs.

**Comment by theguy147** [comment]
I just implemented this for myself but it's the first time for me to modify rust code so its probably very bad style and not respecting some rust no-go's. as an inspiration I added a PR but somebody who knows what they are doing should probably redo that if others are interested :)

here is the PR: #158
