### ISSUE TITLE
can't use the Return key

### ISSUE THREAD

**Issue by scarab5q** [leftwm/leftwm#145]
I thought I set the terminal keybinding to mod + return and the MoveWindowTop keybinding to mod + shift + return but I accidentally set the modifier in MoveWindowTop to `"modkey, Shift"` instead of `"modkey", "Shift"`. This meant that my Return key couldn't be used on its own as it would just call MoveWindowTop. I manged to fix it (holding shift with return worked enough of the time for me to enter certain things into my terminal) but I was wondering if there could be some kind of error message that could send a notification via dunst or something when the config file fails to parse a modifier ? Or somekind of backup theme or config that could be used if an error was detected. The error was really annoying and fiddly to find and I will probably not be the last person to accidentally do something like this.

**Comment by carrascomj** [comment]
I don't know how [alacritty](https://github.com/alacritty/alacritty) implements it, but a feature like that would be pretty cool.
Basically, if the config is written with invalid syntax, it yells at the user.

![image](https://user-images.githubusercontent.com/46683255/102413248-ee72c080-3ff4-11eb-88ac-943f992e42ee.png)

**Comment by VuiMuich** [comment]
Closing this, as we have a sane fallback to default config and also have `leftwm check` to test for config-errors.
