### ISSUE TITLE
WM doesn't respect Lemonbar

### ISSUE THREAD

**Issue by fedoranvar** [leftwm/leftwm#149]
Good day to you!
Thank you for your time and efforts into this project! 

I have a problem with status bars:

1. Downloaded WM from cargo (ver. 0.25)
2. Pulled basic lemonbar theme
3. Edited it for showing lemonbar only on one monitor
4. Windows overlapping lemonabar

(lemonbar in red area)
![image](https://user-images.githubusercontent.com/52028706/101561969-27ed6f80-39e8-11eb-9f0e-f01f47062434.png)

edited `themes/current/up`
```bash
#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


if [ -x "$(command -v picom)" ]; then
    picom --experimental-backend -b
fi

#set the theme.toml config
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe


# MONITOR=HDMI-2 polybar -c ~/.config/polybar/config.ini main &

#boot lemonbar and pipe the status of left into it

   leftwm-state -w 0 -t $SCRIPTPATH/template.liquid | lemonbar -o HDMI-2 -F#FFFFFFFF -B#AA222222&
```

Before I was trying it with polybar - same story.  simillar to https://github.com/leftwm/leftwm/issues/69

**Comment by fedoranvar** [comment]
UPD:

On one monitor it's working good, but with multiple monitors - not

**Comment by lex148** [comment]
hey @fedoranvar sorry for the slow response. 

So i'm trying to work through your issue but I need a little more info. 

Looking at the screen shot you sent; it looks like lemonbar is running and there is a second bar on top of lemonbar. Is this correct? 

Do you know if polybar is still running somehow? 

Here is what I get when I run your config from above: 
![Screenshot from 2020-12-09 16-01-15](https://user-images.githubusercontent.com/442031/101694075-2d72a600-3a38-11eb-98c6-b789bd530d96.png)

**Comment by fedoranvar** [comment]
@lex148 
> Do you know if polybar is still running somehow?

Nope. I have removed it.

Here is the output:
![image](https://user-images.githubusercontent.com/52028706/101701643-1f0ca480-3aa1-11eb-9e1f-ce17fe056493.png)

I've noticed, that WM does respect lemonbar but only for one monitor (I have two monitors 4:3 and 16:9), so it gets settings for 4:3(1280x1024), and tries to apply it for 16:9 (1360x768) in other words:

for 4:3 monitor lemonbar placed on height 1024 and it creates the gap for that height
![image](https://user-images.githubusercontent.com/52028706/101702300-68112880-3aa2-11eb-98ec-d4ce8eef2f57.png)
 and for some reason lemonbar applies this settings and for 16:9 monitor but it's height 768, so virtually gap placed on 1024 height, and that's why i think windows on 16:9 monitor hover lemonbar
    
![image](https://user-images.githubusercontent.com/52028706/101702273-5d569380-3aa2-11eb-88fe-5f0f082fe7f6.png)

**Comment by lex148** [comment]
Ok I have a working theory as to what is going on. Would you mind trying something on your side before I create a fix?

LeftWM does support monitors of different sizes, but I think the theme is written in such a way that it expects the monitors to be vertically aligned at the top. 

somthing like this:
```raw
|-------|   |-------|   
|       |   |       |
|-------|   |       |
            |-------| 
```

not like this:
```raw
            |-------| 
|-------|   |       |
|       |   |       |
|-------|   |-------|   
```

This absolutely needs to  be fixed, but i'm not sure its your issue. 

Would you mind giving it a try and seeing what happens?
