### ISSUE TITLE
Can't get WM to fit screen

### ISSUE THREAD

**Issue by voider1** [leftwm/leftwm#151]
```
             /////////////                wesleygahr@pop-os
         /////////////////////            -----------------
      ///////*767////////////////         OS: Pop!_OS 20.04 LTS x86_64
    //////7676767676*//////////////       Host: MS-7C37 1.0
   /////76767//7676767//////////////      Kernel: 5.8.0-7630-generic
  /////767676///*76767///////////////     Uptime: 2 days, 2 hours, 50 mins
 ///////767676///76767.///7676*///////    Packages: 3009 (dpkg), 11 (flatpak), 4 (snap)
/////////767676//76767///767676////////   Shell: fish 3.1.0
//////////76767676767////76767/////////   Resolution: 5120x1440
///////////76767676//////7676//////////   DE: GNOME
////////////,7676,///////767///////////   WM: Mutter
/////////////*7676///////76////////////   WM Theme: Pop
///////////////7676////////////////////   Theme: Pop-dark [GTK2/3]
 ///////////////7676///767////////////    Icons: breeze-dark [GTK2/3]
  //////////////////////'////////////     Terminal: Neovim Terminal
   //////.7676767676767676767,//////      CPU: AMD Ryzen 7 3700X (16) @ 3.600GHz
    /////767676767676767676767/////       GPU: NVIDIA GeForce RTX 2070 Rev. A
      ///////////////////////////         GPU: NVIDIA GeForce GTX 1050 Ti
         /////////////////////            Memory: 21500MiB / 32099MiB
             /////////////
```

Hey, I'm trying to run LeftWM on my ultra widescreen monitor, it's 49" 5120x1440. However, when I log in it has the wrong resolution and when I change it in Nvidia Settings, it makes the view port smaller and leaves a lot of my screen unused. Should I try to change the resolution a different way?

**Comment by mautamu** [comment]
Howdy!

Does `xrandr -s 5120x1440` force everything to work, or does it produce the same results as in the Nvidia Settings?

Failing that, It appears left pulls from xlib on screen dimensions. What does `xrandr` state for your "current" display status when in leftwm? What does leftwm-state state for your "workspaces" values at that time?

The manual workspace settings are in the config file, documented at 
https://github.com/leftwm/leftwm/blob/3c6d79787f6b9c35882859cc9758084e2f1651c0/README.md#workspaces and are another alternative.

**Comment by piotrmaks** [comment]
I have the same issue using `xrandr`. Only after I restart `leftwm-worker` it gets an update - seems like screen dimensions are checked only once at a startup.

**Comment by voider1** [comment]
@piotrmaks Is right, the viewport is extended, but everything seems to be scaled weirdly too. Everything is way too big for the resolution I'm on.

**Comment by VuiMuich** [comment]
@voider1 is this issue still true?

If so, please reopen.

**Comment by raistdev** [comment]
Same issue here
