### ISSUE TITLE
Centos Stream / 8 Copr package

### ISSUE THREAD

**Issue by NicTanghe** [leftwm/leftwm#156]
Im not the biggest expert in linux and i`d feel more confterable if there was a centos stream package for using it. i realy dont want to use gnome.

**Comment by epyonavenger** [comment]
There appears to be a Copr package available: https://copr.fedorainfracloud.org/coprs/atim/leftwm/

Does that not work?

**Comment by NicTanghe** [comment]
![image](https://user-images.githubusercontent.com/13624265/105745360-775b1100-5f3e-11eb-9697-2fe1e4a2b643.png)
Those are for fedora not Centos stream

**Comment by epyonavenger** [comment]
Ok, but an RPM is an RPM. If you've got the pre-requisites, should probably work? I'm not sure which would map to which, but could grab one of each and give it a go round. Worst case, doesn't work, and you just uninstall.

**Comment by NicTanghe** [comment]
I`m pretty sure it goos looking for things in certain locations wich aren`t there but somewhere else when you are on a different os.
The dev told me how to just build using rust i think i`ll do that.
