### ISSUE TITLE
Update wiki page with new commands

### ISSUE THREAD

**Issue by KevinNThomas** [leftwm/leftwm#159]
I didn't realize that the commands `FocusNextTag` and `FocusPreviousTag` existed until seeing them in the code because they weren't on the wiki page. I think it would be nice to have those commands added to the wiki page.

I added them to my fork of the wiki page, along with a few other missing commands (and some re-ordering) if you are interested: https://github.com/KevinNThomas/leftwm-wiki/blob/WikiConfigUpdate/Config.md

**Comment by lex148** [comment]
This is awesome thanks, I am very interested! 
Can you make a Pull Request for your changes?

**Comment by KevinNThomas** [comment]
Sweet! Unfortunately I don't think there's a way to make a Pull Request to a Wiki page?

**Comment by lex148** [comment]
no problem, I will just update it with your changes. 
thanks again for your !
