### ISSUE TITLE
Dvorak keyboard does not trigger the commands

### ISSUE THREAD

**Issue by Arash-Afshar** [leftwm/leftwm#163]
Change the layout using `setxkbmap dvorak`, then triggering a command for opening dmenu does not work. I tried both `Mod4 + p` (pressing the physical key with label `r` on it) and `Mod4 + l` (the physical key with the label `p` on it). Neither worked.

btw, I am interested in helping fix this but I'd need some help with getting started. If you can point me to a location in the code and how to view the debug logs, I'll get started on it :)

**Comment by lex148** [comment]
Thats great, its awesome you want to help.
Here is where I would start: [https://github.com/leftwm/leftwm/blob/master/src/command_builder.rs](https://github.com/leftwm/leftwm/blob/master/src/command_builder.rs)
This is where keyboard events get translated into actions for LeftWM to act on. 

Debugging a window manager can be rather tricky. There are better ways if you want to really do a lot of work in LeftWM, but simplest is probably the following. 

1) symlink the executables from `target/debug` to somewhere that everyone can access like `/usr/bin` (see the manual setup proccess )
1b) you can verify with `which leftwm-worker` 
2) build with the journald enabled `cargo build --features=fournald` 
3) set the log level you want to see in `src/bin/leftwm-worker.rs` LINE: 165  default is only logging to info

You are now all ready to go:
You can watch the logs with `journalctl -f`
To see your changes make a change in code, compile with `cargo build --features=fournald`
The worker process auto restarts, so just kill it and you will see the latest compiled version. 
`pkill leftwm-worker` 

If your keybindings are working :) `Mod+Shift+R` keeps the state you are in so its a little better then just using pkill

Good luck and have fun!

**Comment by Arash-Afshar** [comment]
So it turned out it works with dvorak keyboard. The problem was "changing" the keyboard layout. So when I change the layout and kill the `left-worker` it works fine, because it picks up the current layout. I'll look into why changing layout is problematic when I have a chance.

**Comment by oukemi** [comment]
I also have the same problem with a bepo keyboard.. .

**Comment by VuiMuich** [comment]
if this issue still persists after the fix in #481 please reopen

**Comment by seungjin** [comment]
I am a Colemak layout user. 
Leftwm does not pick up my colemak layout - means it does not trigger command (ie. modkey+p dose not do any). 
If I do `setxkbmap -layout us -variant colemak` and `leftwm-command SoftReload` in terminal, it makes my colemak layout keys binds work. 

Seems they had the similar issue with Dvorak before.. 
Like to reopen it @VuiMuich

**Comment by seungjin** [comment]
Seems my ibus daemon is the one block Colemak keys to LeftWm. 
Turning off ibus with LeftWM + Colemak works like expected. 
My apologies.
