### ISSUE TITLE
Feature Request: ENV Variables in configuration

### ISSUE THREAD

**Issue by xphoenixd** [leftwm/leftwm#166]
Coming from awesome, i'm really missing the ability to simply use env vars in the configs. For example, a keybind that opens $TERM instead of the  terminal in the config. I don't know rust, so sadly I can't submit a PR with it :(

**Comment by lex148** [comment]
This sounds like a very reasonable request. let me see what I can do

**Comment by lex148** [comment]
Ok, so I just tested this and it is already working. I added the following to my config file and it started the program I set to `$TEST_EDIT` when I pressed (Mod+Shift+p).  I don't see how this can be useful however. ENV variables are specific to a process. If you set the ENV variables in a terminal you are setting it only in that terminal. The only way I could see this working is if you set it way up the chain when the computer boots. You wouldn't be able to modify those settings without restart. Am I missing something here? 

``` 
# ~/.config/leftwm/config/toml

[[keybind]]
command = "Execute"
value = "$TEST_EDIT"
modifier = ["modkey", "Shift"]
key = "p"
```

**Comment by xphoenixd** [comment]
Oh. That makes sense, I should've tried it. A use case for me would be to open $TERM, which is exported in my .zshrc, instead of what I'm using because I like switching terminals often. It isn't useful for everyone but I like it :) Also, sorry for the bad title, I should've said something like "exported variables".
