### ISSUE TITLE
Hide Polybar ?

### ISSUE THREAD

**Issue by NicTanghe** [leftwm/leftwm#167]
How whould i setup toggeling polybar whith the windows knowing that when polybar is hidden they can use more space ?

**Comment by lex148** [comment]
In your polybar config you will need the following settings:
```
;to prevent LeftWM from reserving screen space for the bar
override-redirect = true 
;to use polybar-msg
enable-ipc =true
```

You will need to now add commands to hide/show the page in the config
~/.config/leftwm/config.toml

```
[[keybind]]
command = "Execute"
value = "polybar-msg cmd show"
modifier = ["modkey"]
key = "u"

[[keybind]]
command = "Execute"
value = "polybar-msg cmd hide"
modifier = ["modkey", "Shift"]
key = "u"
```
