### ISSUE TITLE
go to the last selected tag?

### ISSUE THREAD

**Issue by RegenJacob** [leftwm/leftwm#169]
Hello i have a question is it possible to have a keybind that goes to the last selected tag?
like in dwm?

**Comment by lex148** [comment]
Is `Mod+w` what you are looking for?  If not I would be happy to add it? could you please describe what you are looking for a bit more?

**Comment by RegenJacob** [comment]
On dwm you can tab between tags lets say you are in tag 4 and you go to another tag like 3 and you press the keybind you go back to tag 4 and so on.

when i press `Mod+w` nothing happens for me idk if i do not understand that or something else.

**Comment by lex148** [comment]
Thanks for reporting this. This was an error on our part. `Mod+w` should be doing exactly what you describe. There was a problem with the logic that prevented it from working with only one monitor. A fix has been pushed. If you are using the git version in AUR you should see the fix now.
