### ISSUE TITLE
Switching tags fails when in fullscreen applications.

### ISSUE THREAD

**Issue by aTosser** [leftwm/leftwm#170]
While using dwm, I got rather accustomed to being able to switch tabs out of fullscreen applications such as games. When a game is running leftwm ignores requests to switch to another tag (via Mod + tag #) Bug or feature?

**Comment by blackCauldron7** [comment]
I can reproduce the issue too.

**Comment by mautamu** [comment]
Hmm, I know we now have Monocle layout and #174, but I still think this is a bug. Perhaps a floating rework is in order? The two big issues seem to be:
1. Floating windows can stack over one another (do we want to have some offset to make sure this isn't the case?)
2. Floating windows are not stickied to a particular workspace.

**Comment by blackCauldron7** [comment]
imo floating windows should be sticked to particular workspace.

If you want to add non stickiness functionality to windows maybe make it a keybinding in the config file rather than making that layout specific. I can think of use cases for sticky windows in tiling layouts as well.

**Comment by VuiMuich** [comment]
Iirc it is possbile the Goto-Workpace command works in the background of a fullscreen window, but the window stays on top.

Like open  a video and go to fullscreen  on tag 1, switch to tag 2 hit ESC to exit fullscreen should present you tag 2. (Have not tried multi-monitor setups yet).

**Comment by nickzana** [comment]
Multi-monitor user here. The behavior is a little difficult to reason about and describe, but I'll give it my best shot.

Here's a few different paths and their results:

### Switch on same monitor
1. `GoToTag` A on Monitor 1
2. `GoToTag` B on Monitor 2
3. Open fullscreen video in Workspace A on Monitor 1
4. `GoToTag` C on Monitor 1
Result: Same as single monitor behavior, workspace on Monitor 1 changes but video stays on top until full screen mode is exited

<details>
<summary> Personal Opinion </summary>
This seems like undesired behavior to me. Coming from dwm, I would expect the fullscreen video window to be invisible until a Monitor opens Workspace A
</details>


### Switch to Monitor 2's Workspace
1. `GoToTag` A on Monitor 1
2. `GoToTag` B on Monitor 2
3. Open fullscreen video in Workspace A on Monitor 1
4. `GoToTag` B on Monitor 1
Result: Fullscreen video moves to monitor 2, Monitor 1 switches to Workspace B and Monitor 2 switches to Workspace A
<details>
<summary>Personal Opinion</summary>
This seems like desirable behavior. dwm has seperate sets of tags for different monitors, so I lack any expectation for how this command should behave. Perhaps others experienced with different window managers could provide some input?
</details>

### Execute Command `SwapTags`
Exact same behavior as "Switch to Monitor 2's Workspace"

**Comment by VuiMuich** [comment]
Indeed is case two, how leftwm would handle tags normally.

And I agree case one is at least undesired behaviour and I think it might be related that a fullscreen window is forced to be floating, which actually is a nice trick to get the fullscreen on top of everything.
