### ISSUE TITLE
Focusing in 4 directions

### ISSUE THREAD

**Issue by i-am-olep** [leftwm/leftwm#171]
In any other tiling WM I used (i3, herbstluft, qtile, bsp, ...) one can focus windows in four directions: up, down, left, right.
As far as I can understand, now leftwm let's one focus only using up and down.

It would be way more comfortable for my standard workflow to be able to move even left and right, because I usually have three or more windows opened in the same workspace, and having to cycle through many of them going only up and down is quite tedious and time wasting.

I'm FREAKINGLY enjoying leftwm (the name is also a plus) and adding this feature would let me stick with it happily.

**Comment by egolep** [comment]
There are any workarounds?

**Comment by TornaxO7** [comment]
> LeftWM is a list-based tiling window manager, this means that windows are stored in a list, so there are only two possible directions to move through the windows: up/down. It sounds like what you want is a tree-based tiling window manager (like the ones you mentioned).

Isn't it possible to abstract the window-management out to provide either a list-based or a tree-based tiling window managar (or even just implement the tree-based window-management since i3 does the same I guess)?

**Comment by VuiMuich** [comment]
I still believe the proposal of #771 would be more feasible to implement.

Closing this one as it is indeed a dupe and the newer one seems to be the more promising one.
