### ISSUE TITLE
Maximize Window with keybinding

### ISSUE THREAD

**Issue by blackCauldron7** [leftwm/leftwm#174]
I switched from awesome wm it had a feature to maximize the current focused window with a keybinding. Is it possible to do this in leftwm?

**Comment by lex148** [comment]
Absolutely! We have had a bit of discussion about adding this but haven't decided on exactly what we want yet. 

The two ideas that have been floating around are:
1) a full screen mode like how you can resize windows when holding mod and dragging. 
you would just toggle it on/off per window.
2) add a full screen layout. the layout would only show the main window and it would fill the screen.

What do you think?

**Comment by blackCauldron7** [comment]
I already implemented the second idea you are talking about with the command line utility wmctrl and the keybindings in the config toml.

And i cant understand what you mean by the 1st

And i meant by maximize not fullscreen rather i meant the window will take all the available space on the workspace other than the bar.

And lastly thanks for this amazing application totally love it.I just love rust rewrites.

**Comment by VuiMuich** [comment]
I think option 1 means something like toggle fullscreen when you drag a window to the top-edge of a screen. (Similiar to what Windows7/8/10 does)

@blackCauldron7 would you mind to share your keybind snippet?

**Comment by blackCauldron7** [comment]
@VuiMuich 

Personally i never use a mouse in a tiling wm so i wouldnt want that feature but i think it would have helped me if i was transitioning to a tiling wm and this was my first so i think that would be cool.

### Snippet

```
[[keybind]]
command = "Execute"
value = "wmctrl -r :ACTIVE: -b toggle,fullscreen"
modifier = ["modkey"]
key = "f"
```

**Comment by VuiMuich** [comment]
I agree once one transitioned to tilinWM using a mouse to arrange windows feels awkward :D

Thansk for the share, works great. Obviously this should remein a workaround, since it comes with a variety of little issues, link when putting one of many winows in fullscreen the layout of the remaining windows changes and the are visible through transparent windows.

Haha, when I stumbled on the behaivour of #170 I was not sure if this was an intended feature or a bug.

**Comment by blackCauldron7** [comment]
i agree that keybinding is a hacky workaround that i dont like too much imo there should be something like this:

```
[[keybind]]
command = "ToggleFullscreen"
modifier = ["modkey"]
key = "f"
```

**Comment by VuiMuich** [comment]
also there shoul probably an option if the fullscreen should respect the bar(s) or be truly full screen

**Comment by blackCauldron7** [comment]
@VuiMuich i think there should be two different options like in other wms like

Toggle Fullscreen
AND
Toggle Max/Monocle

**Comment by VuiMuich** [comment]
thats what I meant. Missed the term monocle while writing.

**Comment by nickzana** [comment]
I believe this could be partially achieved with a "SetLayout" command, wherein the keybind could look more something like this:

```toml
[[keybind]]
command = "SetLayout"
value = "Monocle"
modifier = ["modkey"]
key = "f"
```

I've made a potential sample implementation here: [https://github.com/nickzana/leftwm/tree/add-set-layout-command](https://github.com/nickzana/leftwm/tree/add-set-layout-command)

My biggest concern is that it adds an additional 2 locations to maintain the master list of layouts (to make 5 total). The existing 3 are all in `src/layouts/mod.rs`:
<details>
<summary> Redundant code </summary>

``` rust
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub enum Layout {
    MainAndVertStack,
    MainAndHorizontalStack,
    GridHorizontal,
    EvenHorizontal,
    EvenVertical,
    Fibonacci,
    CenterMain,
    CenterMainBalanced,
    Monocle,
}
```
```rust
pub const LAYOUTS: [Layout; 9] = [
    Layout::MainAndVertStack,
    Layout::MainAndHorizontalStack,
    Layout::GridHorizontal,
    Layout::EvenHorizontal,
    Layout::EvenVertical,
    Layout::Fibonacci,
    Layout::CenterMain,
    Layout::CenterMainBalanced,
    Layout::Monocle,
]
```

```rust
  pub fn update_windows(&self, workspace: &Workspace, windows: &mut Vec<&mut &mut Window>) {
      match self {
          Self::MainAndVertStack => main_and_vert_stack::update(workspace, windows),
          Self::MainAndHorizontalStack => main_and_horizontal_stack::update(workspace, windows),
          Self::GridHorizontal => grid_horizontal::update(workspace, windows),
          Self::EvenHorizontal => even_horizontal::update(workspace, windows),
          Self::EvenVertical => even_vertical::update(workspace, windows),
          Self::Fibonacci => fibonacci::update(workspace, windows),
          Self::CenterMain => center_main::update(workspace, windows),
          Self::CenterMainBalanced => center_main_balanced::update(workspace, windows),
          Self::Monocle => monocle::update(workspace, windows),
      }
  }
```

And the two I added:

```rust
// TODO: Perhaps there is a more efficient way to impl FromStr using serde
impl FromStr for Layout {
    type Err = ();
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "MainAndVertStack" => Ok(Layout::MainAndVertStack),
            "MainAndHorizontalStack" => Ok(Layout::MainAndHorizontalStack),
            "GridHorizontal" => Ok(Layout::GridHorizontal),
            "EvenHorizontal" => Ok(Layout::EvenHorizontal),
            "EvenVertical" => Ok(Layout::EvenVertical),
            "Fibonacci" => Ok(Layout::Fibonacci),
            "CenterMain" => Ok(Layout::CenterMain),
            "CenterMainBalanced" => Ok(Layout::CenterMainBalanced),
            "Monocle" => Ok(Layout::Monocle),
            _ => Err(()),
        }
    }
}
```

```rust
  #[test]
  fn test_from_str() {
      let layout_strs: [&str; 9] = [
          "MainAndVertStack",
          "MainAndHorizontalStack",
          "GridHorizontal",
          "EvenHorizontal",
          "EvenVertical",
          "Fibonacci",
          "CenterMain",
          "CenterMainBalanced",
          "Monocle",
      ];

      assert_eq!(layout_strs.len(), LAYOUTS.len());

      for (i, layout) in LAYOUTS.iter().enumerate() {
          assert_eq!(layout, &Layout::from_str(layout_strs[i]).unwrap());
      }
  }
```
</details>

**Comment by VuiMuich** [comment]
A command to specifically set a designated layout is indeed a great idea!

But I think full screen windows and monocle layout should be two different things in the end.
For example a very stylish monocle layout IMO is, with a 20-30% margin around the single window.
A full screen should be actually covering status bars etc.
And a maximized window should use the whole desktop area (configurable with or without margins).

Since requested layouts tend to get more and more complex and having special layout specific logic and interaction needs, like special ways to focus (monocle, deck-layout) or spawn windows (bspwm layout), it might be time to think about a layout handler to clean up several areas of code.

**Comment by blackCauldron7** [comment]
Just a thought bspwm's layout handling works great why not take inspiration from there like they have options like:
```
borderless_monocle: bool,
gapless_monocle: bool,
gap_size: int,
etc..
```

**Comment by nickzana** [comment]
So then, ideally, would each layout have its own config options? And would it be possible to have multiple instances of the same layout with different configs? 

For example, something like: 
``` toml
[[mono_gap]]
layout = "Monocle"
gap_size = 20

[[mono_gapless]]
layout = "Monocle"
gap_size = 0
```
Imo it would be weird to have a bunch of layout-specific config held as a field of the `Config` type instead of with the `Layout` itself.

**Comment by blackCauldron7** [comment]
No bspwm doesn't have config specific to layouts its just that the gap and border one made only sense with monocle thats why it was named like that. For example all layouts have the same gap size, border width etc. in bspwm except fullscreen ofcourse.
