### ISSUE TITLE
Cannot start LeftWM

### ISSUE THREAD

**Issue by tommasoxd** [leftwm/leftwm#176]
![16127744933516497767378228056594](https://user-images.githubusercontent.com/60621057/107197168-d6675e00-69f3-11eb-805e-869f4e108875.jpg)
When I try to start a LeftWM instance it returns this error. How I can fix?

**Comment by EmanuelBoehm** [comment]
You get this error because you're starting leftwm without a X server.
Go into you ~/.xinitrc and start leftwm in the last line using the command 'exec dbus-launch leftwm'
After that you can start leftwm with 'startx'

**Comment by tommasoxd** [comment]
> You get this error because you're starting leftwm without a X server.
> Go into your ~/.xinitrc and start leftwm in the last line using the command 'exec dbus-launch leftwm'
> After that you can start leftwm with 'startx'

Thanks for the fix, it works. I've another question, how I can auto-start apps at the startup with LeftWM?

**Comment by mautamu** [comment]
LeftWM will autostart anything defined in a .desktop file in your ~/.config/autostart folder, and it will also run your current theme's "up" script. You're likely looking for the autostart method, so just add a file called (app name).desktop with the following, replacing (app name) and (/path/to/application) as needed:
_.config/autostart/(appname).desktop_
```
[Desktop Entry]
Version=1.0
Type=Application
Encoding=UTF-8
Name=(app name)
Exec=(/path/to/application)
Terminal=false
StartupNotify=true
```
Thats it! LeftWM should start that application on next startup (it won't re-run the application if you just soft reset LeftWM with MOD+SHIFT+R).

If you need it to restart with MOD+SHIFT+R or whenever your theme boots (such as a bar), add it to your config's up file (substantial portions omitted for brevity). 
_.config/leftwm/themes/current/up_
```bash
#!/bin/bash
# Set background
...
/path/to/application #<---- likely the best place to put your application, but depends on the application
# Conky
...
```

**Comment by tommasoxd** [comment]
Thanks so

> LeftWM will autostart anything defined in a .desktop file in your ~/.config/autostart folder, and it will also run your current theme's "up" script. You're likely looking for the autostart method, so just add a file called (app name).desktop with the following, replacing (app name) and (/path/to/application) as needed:
> _~/.config/autostart/(appname).desktop_
> 
> ```
> [Desktop Entry]
> Version=1.0
> Type=Application
> Encoding=UTF-8
> Name=(app name)
> Exec=(/path/to/application)
> Terminal=false
> StartupNotify=true
> ```
> 
> Thats it! LeftWM should start that application on next startup (it won't re-run the application if you just soft reset LeftWM with MOD+SHIFT+R).
> 
> If you need it to restart with MOD+SHIFT+R or whenever your theme boots (such as a bar), add it to your config's up file (substantial portions omitted for brevity).
> _~/.config/leftwm/themes/current/up_
> 
> ```shell
> #!/bin/bash
> # Set background
> ...
> /path/to/application #<---- likely the best place to put your application, but depends on the application
> # Conky
> ...
> ```
> 
> Edit: paths

Thank you so much for the reponse, I'll close this issue, thank you for your time.
