### ISSUE TITLE
Configuration: Floating window always on top.

### ISSUE THREAD

**Issue by aTosser** [leftwm/leftwm#179]
It would be convenient to have a configuration option for floating windows to always be on top of non-floating windows.

**Comment by hertg** [comment]
I think that currently is the default, right @AethanFoot?
But maybe adding a configuration to disable this would be a potential feature?

**Comment by hertg** [comment]
I'm closing this, as this seems to be the default behavior now anyway. I don't think we need to convert this into another feature request that (like allowing to disable that behavior) just as an excuse to leave the issue open.
