### ISSUE TITLE
Right Click Menu.

### ISSUE THREAD

**Issue by dariusity** [leftwm/leftwm#185]
Hi, first of all I really enjoy experimenting and tinkering with this WM and thanks to all the devs. Will there be any right click menu implemented in the near future? Or is there any third party I can use as a replacement? Cheers.

**Comment by mautamu** [comment]
What sorts of things would you like to see in a right-click menu? I'm assuming this is the type where you right click on a non-windowed area and see some generics (logout, help, shortcuts, . . . )?

**Comment by dariusity** [comment]
You're absolutely on the point. My alacritty seem to be unable to fix it's size properly when sharing the screen with another window

**Comment by lex148** [comment]
So there aren't any plans to add a right click menu directly within LeftWM, but adding the ability to wire up something like rofi to be your right click menu sounds like a must.

**Comment by dariusity** [comment]
It's not a compulsory for me, like I said in the first post I am still adapting to the new way of utilizing the new environment. I would still ask regardless, who does not like convenience if they do not have to trade it for some performance?

**Comment by VuiMuich** [comment]
> adding the ability to wire up something like rofi to be your right click menu sounds like a must.

this sounds like a good idea
though I would suggest to avoid making it a default binding since a tiling WM still should encourage to work as mousefree as possible imo

**Comment by VuiMuich** [comment]
I guess with `leftwm command` being quite 'feature complete' it should be quite straight forward to create a rofi/dmenu/morc-menu/eww widget etc. with bindings for leftwm commands.
---
Any PRs with examples are very welcome.
