### ISSUE TITLE
There should be a way to soft reload

### ISSUE THREAD

**Issue by lex148** [leftwm/leftwm#20]
currently leftwm only hard reloads everything. soft reload should keep the state of all windows

**Comment by lex148** [comment]
LeftWM now has two ways to do the reloading a HardReload and a SoftReload. Because your config was created before this fix you will need to change it from HardReload to SoftReload in the file ~/.config/leftwm/config

Please change the section:
[[keybind]]
command = "Execute"
value = "pkill leftwm-worker"
modifier = ["modkey", "Shift"]
key = "r"

To:
[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Shift"]
key = "r"

**Comment by Dsantra92** [comment]
This piece of information should be included in the [config page](https://github.com/leftwm/leftwm/wiki/Config) of the wiki.

**Comment by mautamu** [comment]
@Dsantra92 which piece of information in particular is missing? Both hard and soft reload have definitions therein.
