### ISSUE TITLE
background

### ISSUE THREAD

**Issue by r1bbi** [leftwm/leftwm#200]
Using the basic_polybar and following the wiki i can change the theme but apparently the background doesn't load.
Much love for your work I hope I can help soon.

**Comment by AethanFoot** [comment]
Have you installed feh, which is used to set the background

**Comment by r1bbi** [comment]
## [SOLVED]
I tought it was but evidently I was wrong, I'm sorry.
Thank you.

**Comment by AethanFoot** [comment]
No worry I have done same thing many times before
