### ISSUE TITLE
Issue with soft reload + brave browser

### ISSUE THREAD

**Issue by AethanFoot** [leftwm/leftwm#202]
I have mentioned this in #186, but I thought I should give it its own issue.
What happens is if you soft reload with brave open on you primary monitor, and then try and drag a tab it immediately moves to a new window. This can be fixed by then moving the browser to a different workspace and back. Vid:

https://user-images.githubusercontent.com/63980259/108501717-9c2a7600-72a9-11eb-9988-f0dc590aac7f.mp4

**Comment by mautamu** [comment]
Did this get fixed recently?

have noticed it occasionally on FF too.

**Comment by AethanFoot** [comment]
It seems to be working on my system now, Im not sure if it was a brave update or something.

**Comment by AethanFoot** [comment]
Actually it is still happening, it seems to have narrowed the times it happens. And I think I found a common thing that may be related (can you try just to check).
It appears that when reloaded that the _NET_WM_DESKTOP if wrong for the window in some cases, e.g. if the browser is open on tag 1, but tag 1 is on workspace 2 (so when reloaded the browser resets to workspace 1), the reported desktop is 1 (tag 2). Another example is when the browser is on tag 2 on workspace 2, when reloaded the desktop reports as 0 (tag 1) instead of 1 (tag 2). Hopefully that makes sense however it is strange if that alone is the issue, but I am going to do more testing.
Thanks.
