### ISSUE TITLE
leftwm(-worker?) frozen after systemctl suspend and hibernate

### ISSUE THREAD

**Issue by VuiMuich** [leftwm/leftwm#203]
as title says after a ```systemctl suspend``` or ```systemctl hibernate``` leftwm workspaces and window handling is frozen.
Polybar and qutebrowser stil work (to a certain degree, like can switch tags by clicking on them and navigate opened websites and switch open tabs, but cannot create new tabs).
With a custom script in the polybar it is sometimes possible to launch a terminal which takes command input but has no visible window.
A ```killall leftwm-worker``` gets everything back running properly. (Until the next sleep :stuck_out_tongue_winking_eye: )

This appeared after I updated the AUR package leftwm-git today in the morning, so I guess it is possibly related to yesterdays merges?

**Comment by mautamu** [comment]
Was able to produce as well, reverting b193e49 resolved this for me.

**Comment by VuiMuich** [comment]
> Was able to produce as well, reverting [b193e49](https://github.com/leftwm/leftwm/commit/b193e49e8ec4f4e413729c7037250e12afc04884) resolved this for me.

Yup, this helped on my machine as well.
So maybe we should rais the attention of the PR #193 to this issue, right?

**Comment by piotrmaks** [comment]
Could you folks try https://github.com/leftwm/leftwm/pull/205? It should fix the issue.

**Comment by mautamu** [comment]
Absolutely, give me a few minutes

**Comment by mautamu** [comment]
Thank you so much @piotrmaks! Tested it both with light-locker and systemctl suspends and it works.
