### ISSUE TITLE
Renaming a tag while it is "busy": true makes it "busy": false

### ISSUE THREAD

**Issue by VuiMuich** [leftwm/leftwm#207]
Open at least one window (tried alacritty, pavucontrol and ffplay) on a tag (eg. "5").
Rename the tag in config.toml (eg to "debug") and softreload.
The tag appears now empty (leftwm-state reports also "busy": false, as mentioned in title) but the processes stay alive and are back on this tag after reverting the renaming.
Also I always get this Error Message in the Polybar modules-left area, but not sure if related:
![leftwm_polybar_error](https://user-images.githubusercontent.com/4779365/108785525-e5145000-7571-11eb-8f35-00d572741c2d.png)
I was not able to catch this anywhere else then this screenshot, yet. And after a few seconds the tags properly launch.

(BTW: is it possible, that leftwm-state -n is no different then without the flag?)

**Comment by carrascomj** [comment]
Maybe someone can verify it, but I beliieve that this problem is not directly related to leftwm-state. After you change the tags and reloads, leftwm does not move the windows to an existing tag if they were in a now _renamed_ tag (I think they are not renamed, they are different tags which happen to be in the same ordinal position). 

I think it would be interesting to change that behaviour on reload, but what should we do with the orphaned windows? Should we move them to the active tag or try to match them by order somehow to the renamed tag? Suggestions?

**Comment by mautamu** [comment]
An interesting question. I think the behaviours I’d expect to be possible are:
1. Keep the window on the same ordinal position
2. Move the window to the first tag in the sequence
3. Move the window to the currently open tag (I believe this usually redirects to tag 1, which would give the same behaviour as 2)

I suspect 2 would be easiest to implement.

Thoughts?

**Comment by VuiMuich** [comment]
I can reproduce this on a virtual machine with lemonbar instead of polybar.
Here I have some outputs of leftwm-state:

```json
...
{"window_title":"fish /home/vuimuich","workspaces":
[{"h":1440,"w":2560,"x":0,"y":0,"layout":"MainAndVertStack","index":0,"tags":[
{"name":"1","index":0,"mine":false,"visible":false,"focused":false,"busy":true},
{"name":"2","index":1,"mine":false,"visible":false,"focused":false,"busy":true},
{"name":"3","index":2,"mine":false,"visible":false,"focused":false,"busy":true},
{"name":"4","index":3,"mine":true,"visible":true,"focused":true,"busy":true},
{"name":"5","index":4,"mine":false,"visible":false,"focused":false,"busy":false},
{"name":"6","index":5,"mine":false,"visible":false,"focused":false,"busy":false},
{"name":"7","index":6,"mine":false,"visible":false,"focused":false,"busy":false},
{"name":"8","index":7,"mine":false,"visible":false,"focused":false,"busy":false},
{"name":"9","index":8,"mine":false,"visible":false,"focused":false,"busy":false}]}]}
...
{"name":"four","index":3,"mine":true,"visible":true,"focused":true,"busy":false},
{"name":"five","index":4,"mine":false,"visible":false,"focused":false,"busy":false},
...
{"name":"four","index":3,"mine":false,"visible":false,"focused":false,"busy":false},
{"name":"five","index":4,"mine":true,"visible":true,"focused":true,"busy":false},
...
{"name":"4","index":3,"mine":true,"visible":true,"focused":true,"busy":true},
{"name":"5","index":4,"mine":false,"visible":false,"focused":false,"busy":false},
...
{"name":"4","index":3,"mine":false,"visible":false,"focused":false,"busy":true},
{"name":"5","index":4,"mine":true,"visible":true,"focused":true,"busy":false},
...
```
**Note: tag 4 has one window with alacritty, tag 5 is empty, created a keybind with `leftwm-state -q >> ~/leftwm-state.log`.
For readability I truncated all invariant lines after the first execution and added a few linebreaks.**

**Comment by VuiMuich** [comment]
sorry I totally missed out on everything beyond "can confirm" :facepalm: 

Maybe state.save(&Manager) could check if the loaded configdiffers from the config.toml on disk?

Option 2 is a valid workaround.

**Comment by carrascomj** [comment]
I would also go with Option 2 since it is easier.

**Comment by VuiMuich** [comment]
I believe I understand now, why this happens:
Windows don't actually live on a tag. but get the tag on which they should get shown on attached. Very much as 'tag' implies.
So during reload, the old tags get cloned to the windows and therefore the windows won't appear, but still exist in the background.

With this in mind I reconsider implementing option 1 should be the aim. And with something similar to #261 it might not even be too difficult.
I guess that's what I'm gonna try next.
