### ISSUE TITLE
Allow separate modifier key to be set for mouse events

### ISSUE THREAD

**Issue by AethanFoot** [leftwm/leftwm#215]
Allow the user to set a separate modifier key when moving a window with the mouse (and for in the future if resizing a window with the mouse gets added). The reason I suggest this is so I can use I can use a key on my mouse as a modifier (I have one set for ctrl for crouching in games), so you could just use one hand.

**Comment by VuiMuich** [comment]
Irrc Modkey+rightclick is resizing, right?

**Comment by AethanFoot** [comment]
Yes I did not know that

**Comment by AethanFoot** [comment]
I will add that the resizing with the mouse should be able to resize windows while they are in tiling mode. Currently it forces floating mode and resets the size once put back in tiling.

**Comment by VuiMuich** [comment]
Agree, in general resizing windows feels a bit limited, not that I would need it often, but sometimes it would be neat.

Btw: is In-/DecreaseMainWidth working for you?

**Comment by VuiMuich** [comment]
Oh, it need a value field like:
```toml
[[keybind]]
command = "IncreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "h"
```
(This should be mentioned in the wiki, i guess.)
