### ISSUE TITLE
Documentation on how multi-monitor key bindings work

### ISSUE THREAD

**Issue by JudahGoldstein** [leftwm/leftwm#222]
I for the life of me can't figure out how to use multiple screens on a sensible way, when I switch workspaces (mod+#) or try to move things to another workspace (mod+shift+#) things don't work how I expect them too at all, jumping from screen to screen, ending up in completely different workspaces on other screens, etc... 
Some documentation or at least someone exposing it to me would be much appreciated, thanks!

**Comment by AethanFoot** [comment]
Leftwm has shared workspaces. Which means if monitor 1 is on workspace 1 and monitor 2 is on workspace 2, if you switch to workspace 2 on monitor 1 they will swap.

**Comment by JudahGoldstein** [comment]
There any way to separate the workspaces? Or is it stuck as a shared system.

**Comment by AethanFoot** [comment]
No there isn't a way to separate them. I don't think there is a max you can set, so you could make more and only use certain ones on each monitor (but it may become a bit awkward).
