### ISSUE TITLE
KeepassXC Autotype popup not Showing

### ISSUE THREAD

**Issue by speatzle** [leftwm/leftwm#223]
After Switching to LeftWM i have noticed that i am unable to use KeepassXC's Auto-Type Popup it just never opens, but you can see that the current Window temporary looses focus when attempting to open it via shortcut.

**Comment by lex148** [comment]
I pushed an update about 2 days ago that forces all modals popup and floating windows to the top. Would you please check that this is still an issue with the latest version of LeftWM. Please let me know and I will investigate if you are still having problems.

**Comment by speatzle** [comment]
i just pull master and reinstalled, sadly it still wont show.

**Comment by lex148** [comment]
ok, thanks for checking. I will take a look

**Comment by pauschuu** [comment]
These are the properties of the KeePassXC Auto-Type Window when it appears in dwm:
```
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_USER_TIME(CARDINAL) = 4779576
_NET_WM_STATE(ATOM) = _NET_WM_STATE_ABOVE, _NET_WM_STATE_STAYS_ON_TOP
WM_TRANSIENT_FOR(WINDOW): window id # 0xe00006
_NET_WM_ICON(CARDINAL) =
_NET_WM_ICON_NAME(UTF8_STRING) =
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = "Unlock Database - KeePassXC"
_NET_WM_NAME(UTF8_STRING) = "Unlock Database - KeePassXC"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x26, 0x1e, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0xe00008
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		window id # of group leader: 0xe00008
WM_CLIENT_MACHINE(STRING) = "<redacted>"
_NET_WM_PID(CARDINAL) = 75567
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 14680130
WM_CLASS(STRING) = "keepassxc", "KeePassXC"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST, _NET_WM_CONTEXT_HELP
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 290, 507
		user specified size: 700 by 445
		program specified minimum size: 700 by 445
		window gravity: Static
```

Don't know if this helps, but have to start somewhere right? :)

Another idea that came to my mind is:
KeePassXC is using window titles to determine which entries it will show. Could something mess with its ability to determine the window titles?

~ a KeePassXC user who'd like to switch to leftwm for good

If you need anything tested don't hesitate to ask, I can easily switch between leftwm and dwm and test whatever necessary.

**Comment by pauschuu** [comment]
Or (another idea) the way KeePassXC tries to listen to its global Auto-Type shortcut doesn't work because of the key event not bubbling through to KeepassXC for some reason?

**Comment by pauschuu** [comment]
> Another idea that came to my mind is:
> KeePassXC is using window titles to determine which entries it will show. Could something mess with its ability to determine the window titles?

I think that's it.
When you're in KeePassXC editing an entry and click on the "Auto-Type" section, you can add so called "Window Associations".

Usually you can click the drop-down menu named "Window title:" and it shows all titles of all currently existing windows.
Not so in leftwm, here the list is empty.

So whatever KeePassXC does to get all the existing window titles doesn't work in leftwm.

**Comment by VuiMuich** [comment]
Is the KeePassXC window listed with:
```shell
xprop -root _NET_CLIENT_LIST |
              pcregrep -o1 '# (.*)' |
              sed 's/, /\n/g' |
              xargs -I{} -n1 xprop -id {} _NET_WM_NAME
```

**Comment by pauschuu** [comment]
Yes the KeePassXC window is listed.

I think [this](https://github.com/keepassxreboot/keepassxc/blob/9c108b95100bfa3b172edcfd5754aa2e831a3221/src/autotype/xcb/AutoTypeXCB.cpp#L251) is the function that matches window titles in the current KeePassXC 2.6.6.

**Comment by hertg** [comment]
A lot has happened since this was reported, is it still an issue?

**Comment by TornaxO7** [comment]
@hertg I guess we can close this issue for the time being?

**Comment by hertg** [comment]
@TornaxO7 I guess so. 
please re-open if it still occurs.
