### ISSUE TITLE
increase size of floating window

### ISSUE THREAD

**Issue by JudahGoldstein** [leftwm/leftwm#227]
don't see any option to increase the size of or full-screen floating windows makes some things literally unusable

**Comment by mautamu** [comment]
Use modkey+right click-drag. I do think a fixed size keybinding could be in order as well.

**Comment by chaibronz** [comment]
how do you get a window to float? i couldn't find a keybinding for that.

**Comment by mautamu** [comment]
Mod + right click (or mod+ left click).
