### ISSUE TITLE
No Keybinds Are Working

### ISSUE THREAD

**Issue by DrakoDom** [leftwm/leftwm#228]
[ I'm using Void Linux and startx ]

I just got LeftWM installed about 30 minutes ago. I heard some nice things about it from people like DistroTube, so I thought I would take a look myself. But the past 30 minutes have been nothing but trying to troubleshoot my keybinds.

So far I haven't been able to get any keybindings whatsoever to work. I've compiled, setup all symlinks, and made sure my config.toml file exists. Within the config.toml file I've tried different consoles and Mod keys to make sure something wasn't up with LeftWM, but still nothing.

Some help would be nice.

**Comment by mautamu** [comment]
Good afternoon,

Do you have a foreign keyboard (not en-US)? 

What does your config.toml contain? 

Do keys work on anything within LeftWM (bars, other programs, etc)?

Are you able to access a TTY outside of LeftWM? 

Did you compile leftwm-check? 

(Sorry for the barrage of questions, trying to figure out what the problem is and what solutions are available).

**Comment by DrakoDom** [comment]
My keyboard is an en-US keyboard.

Here's what's in my config.coml
```
modkey = "Mod4"
workspaces = []
tags = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]
layouts = ["MainAndVertStack", "MainAndHorizontalStack", "GridHorizontal", "EvenHorizontal", "EvenVertical", "Fibonacci", "CenterMain", "CenterMainBalanced", "Monocle"]

[[keybind]]
command = "Execute"
value = "dmenu_run"
modifier = ["modkey"]
key = "p"

[[keybind]]
command = "Execute"
value = "st"
modifier = ["Shift"]
key = "Return"

[[keybind]]
command = "Execute"
value = "firefox"
modifier = ["modkey", "Shift"]
key = "b"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey", "Shift"]
key = "q"

[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "Execute"
value = "pkill leftwm"
modifier = ["modkey", "Shift"]
key = "x"

[[keybind]]
command = "MoveToLastWorkspace"
modifier = ["modkey", "Shift"]
key = "w"

[[keybind]]
command = "SwapTags"
modifier = ["modkey"]
key = "w"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "Up"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "Down"

[[keybind]]
command = "MoveWindowTop"
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "Up"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "Down"

[[keybind]]
command = "NextLayout"
modifier = ["modkey", "Control"]
key = "Up"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "Down"

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "Left"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "6"

[[keybind]]
command = "GotoTag"
value = "7"

modifier = ["modkey"]
key = "7"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "8"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "9"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "1"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "2"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "3"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "4"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "5"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = ["modkey", "Shift"]
key = "6"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = ["modkey", "Shift"]
key = "7"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = ["modkey", "Shift"]
key = "8"

[[keybind]]
command = "MoveToTag"
value = "9"
modifier = ["modkey", "Shift"]
key = "9"

```

I haven't tried running any software within LeftWM because of my keybindings issue.

I can access another TTY while im in LeftWM.

I did not compile leftwm-check. What should I run to do that?

**Comment by mautamu** [comment]
Hmm `leftwm-check` says the config file is valid, so that shouldn't be the issue. If you compiled from this git then it should include `leftwm-check` in the compilation directory $COMP_DIR/target/release/leftwm-check. You can try running that and see if it knows where your file is. Preferably use `-V` flag to see if the keybinds work for you. 

Another thing to check (I'm assuming void uses Runit or the like so no Journalctl) is to try to look for logs and to try to send commands to the leftwm sock file. (I'll look how to do that and get back to you).

**Comment by DrakoDom** [comment]
Running ``leftwm-check`` confirmed that my config file was in working order. I decided to run ``leftwm-state`` and ``leftwm-worker``, but they both resulted in an error that has to do with ``XdgRuntimeDirMissing``, which was the error that I got. I'm trying to determine what package I need to fix this.

**Comment by mautamu** [comment]
Ah yeah I had the same problem on Kiss Linux. You need systemd for it to generate that. Was working on a possible patch but dropped it. Workaround for me was to export an XDG_RUNTIME_DIR prior to starting LeftWM. 

@lex148 any ideas on a solution?

The behaviour on Kiss was just no theme though, I could still use keybinds. Still not sure what’s causing that. You do have libxinput, no?

**Comment by DrakoDom** [comment]
I do have libxinput installed (in void the package is xinput).

**Comment by lex148** [comment]
So I do have an Idea or two. @DrakoDom are ALL your keybindings not working, or are some of them working? 
The key section in the config is case sensitive, so can you check that you don't have Caps Lock on?

**Comment by DrakoDom** [comment]
None of the keybinds are working. I've already checked caps lock as well.

**Comment by mautamu** [comment]
Were you able to get XDG_DIRECTORIES to work?

**Comment by DrakoDom** [comment]
I'm going to try with Gentoo now. I was planning on trying Gentoo anyway, so I'll see how it goes.

**Comment by VuiMuich** [comment]
I had a short peak into void packages yesterday, there are some xdg_base_dir and xdg_user_firs packages. Not sure if these should be installened anyway by being dependencies of xorg or something, but this might be worth a look.

**Comment by DrakoDom** [comment]
I have no idea why, but I just got leftwm working with Gentoo today! I ran through the same process as I did while running Void, so I can't say for certain what went wrong.

But so far leftwm is probably in my Top 3 WMs.

**Comment by mautamu** [comment]
Glad to hear it @DrakoDom! Let us know if there's anything else you'd like changed or need help on!

**Comment by byfw** [comment]
I was having the same issue in void linux. it was fixed by enabling the dbus service and installing & enabling elogind.

**Comment by MadMarcsen** [comment]
Hi there,

so i'm having the same problem here on a fresh Gentoo installation.

Configuration is still at a minimum. I'm using SDDM as window manager but i use startx most if the time. Because i don't have a theme installed, i have a black screen with pointer, except i start xterm from xinitrc.

I merged with USE="-lefthk" and with USE="lefthk", then with .config/lefthk/config.ron as described in the documentation. 

Default hotkey should be Windows key, if i'm not totally wrong. But neither default bindings nor bindings from config work. 

Thing is, leftwm-check say's config is ok, but i receive thd following message;

`WARN: Ignoring checks on keybinds as you compiled for an external hot key daemon.`

Any idea what causes this?

Thanks in advance.

**Comment by VuiMuich** [comment]
The message from `leftwm-check` means that you need to use standalone `lefthk` or `sxhkd` or whatever hotkey daemon you want to use.
I am not familiar with the build options of the gentoo package, will have a look later.
The config for `lefthk` needs to be a bit different then the _internal_ config, as each command needs to be called with `leftwm-command ...`.
If you don't have a specific reason why you want robuste a standalone hotkey daemon, I would advise to look int build options to build with _internal `lefthk-worker` instance_.

**Comment by VuiMuich** [comment]
`~/.config/lefthk` directory is (should be - 99.999% sure) only needed for standalone `lefthk`.
Normally they keybind section of `~/.config/leftwm/config.ron` gets forwarded to `lefthk-worker`.
When you autostart a terminal you can type in it, correct?
Do you see a `lefthk-worker` process?

**Comment by MadMarcsen** [comment]
Hey,

so i removed `~/.config/leftahk`first.

When i start X, terminal works flawlessly. Also, when i activate sxhkd i can use leftwm without problems.

`ps aux` can't seem to find a process for lefthk-worker. When i start it from terminal, nothing happens. When i start it from xinitrc with `exec lefthk-worker`, `ps aux` show's it as [defunct].

So i compiled the latest version from git with `cargo build --profile optimized --no-default-features --features=lefthk,sys-log,` removed existing files and linked the new version to /usr/bin. Sadly, when is start X, nothing works. I don't see a cursor, only a black "x". Starting from cli with startx opens up a terminal, but i can't type anything in it. Also i can't see any output in syslog.

Should i still open a new issue?

**Comment by VuiMuich** [comment]
> Should i still open a new issue?

yes please.

`lefthk-worker` gets started by `leftwm`, when you start it directly, I have no idea what happens actually. Probably it then is a rogue session, that might lead to lots of unexpcted behavior.

Rest in the new issue...

**Comment by bthnakkurt** [comment]
This is still a life saver. I dont know which one fixed but it is working now.
