### ISSUE TITLE
Monitor issue with workspaces

### ISSUE THREAD

**Issue by jlorezz** [leftwm/leftwm#229]
Hey, i have been trying to change the layout of my monitors with xrandr. This worked perfectly fine but I am having issues with leftwm (blackscreens). I can see the mouse perfectly fine but the workspaces are not working. LMK if u need more details

**Comment by VuiMuich** [comment]
Are keybinds, like launching a terminal, working for you?
Have you a theme selected? Could you try using one of the basic_{polybar, lemonbar, xmobar} (depending on your preferred bar)?

**Comment by lex148** [comment]
@jlorezz if you change the resolution you need to tell LeftWM to reload. it doesn't watch the resolution for changes. you can do this by pressing `Mod+Shift+R`

**Comment by jlorezz** [comment]
> @jlorezz if you change the resolution you need to tell LeftWM to reload. it doesn't watch the resolution for changes. you can do this by pressing `Mod+Shift+R`

i have done that already. i am not new to this kind of stuff lol. But it's simply not loading the workspaces. i can see a black screen and the mouse so xrandr is perfectly working fine.

**Comment by VuiMuich** [comment]
> i am not new to this kind of stuff lol.

We are just trying to figure out what is happening on your machine. No one saying you're not knowing what you do.

My question one was trying to check if your config basically is working.  And question two was aiming at a possibly broken/incomplete theme.

Your description of a black screen with a mouse pointer fits the appearance of an un-themed Leftwm quite well. 

But let's try a different approach: do you have proper working workspaces before you change resolution with xrandr?

**Comment by jlorezz** [comment]
yep the workspaces worked perfectly fine but once I switch or turn on xrandr to get the layout of my monitors, and reload leftwm i get 2 blackscreens

**Comment by VuiMuich** [comment]
Ok. 
Maybe the Output of `leftwm-state` might give a hint.

**Comment by VuiMuich** [comment]
Also, do you get back your working workspaces when you change the resolution back?

**Comment by jlorezz** [comment]
> Also, do you get back your working workspaces when you change the resolution back?

yes that works. i can see all screens again.

**Comment by jlorezz** [comment]
it's not the resolution. it's simply the location of my screens. leftwm things they are besides each other like this: / / / but they are actually like this: (1 4k monitor at the top and 2 1080p at the bottom)
/
//

**Comment by jlorezz** [comment]
so every time I change the layout the black screens occur.

**Comment by jlorezz** [comment]
any idea?

**Comment by VuiMuich** [comment]
have you had any success with gathering the output of leftwm-state, while you are having a black screen?

**Comment by jlorezz** [comment]
yeah, it's a huge file. i'll make a code snippit

**Comment by jlorezz** [comment]
```
{"window_title":"fish /home/jlorezz","workspaces":[{"h":1080,"w":1920,"x":3840,"y":0,"layout":"MainAndVertStack","index":0,"tags":[{"name":"1","index":0,"mine":false,"visible":true,"focused":false,"busy":true},{"name":"2","index":1,"mine":true,"visible":true,"focused":false,"busy":true},{"name":"3","index":2,"mine":false,"visible":true,"focused":true,"busy":true},{"name":"4","index":3,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"5","index":4,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"6","index":5,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"7","index":6,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"8","index":7,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"9","index":8,"mine":false,"visible":false,"focused":false,"busy":false}]},{"h":1080,"w":1920,"x":5760,"y":0,"layout":"MainAndVertStack","index":1,"tags":[{"name":"1","index":0,"mine":true,"visible":true,"focused":false,"busy":true},{"name":"2","index":1,"mine":false,"visible":true,"focused":false,"busy":true},{"name":"3","index":2,"mine":false,"visible":true,"focused":true,"busy":true},{"name":"4","index":3,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"5","index":4,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"6","index":5,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"7","index":6,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"8","index":7,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"9","index":8,"mine":false,"visible":false,"focused":false,"busy":false}]},{"h":2160,"w":3840,"x":0,"y":0,"layout":"MainAndVertStack","index":2,"tags":[{"name":"1","index":0,"mine":false,"visible":true,"focused":false,"busy":true},{"name":"2","index":1,"mine":false,"visible":true,"focused":false,"busy":true},{"name":"3","index":2,"mine":true,"visible":true,"focused":true,"busy":true},{"name":"4","index":3,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"5","index":4,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"6","index":5,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"7","index":6,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"8","index":7,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"9","index":8,"mine":false,"visible":false,"focused":false,"busy":false}]}]}
{"window_title":"leftwm-state /home/jlorezz","workspaces":[{"h":1080,"w":1920,"x":3840,"y":0,"layout":"MainAndVertStack","index":0,"tags":[{"name":"1","index":0,"mine":false,"visible":true,"focused":false,"busy":true},{"name":"2","index":1,"mine":true,"visible":true,"focused":false,"busy":true},{"name":"3","index":2,"mine":false,"visible":true,"focused":true,"busy":true},{"name":"4","index":3,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"5","index":4,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"6","index":5,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"7","index":6,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"8","index":7,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"9","index":8,"mine":false,"visible":false,"focused":false,"busy":false}]},{"h":1080,"w":1920,"x":5760,"y":0,"layout":"MainAndVertStack","index":1,"tags":[{"name":"1","index":0,"mine":true,"visible":true,"focused":false,"busy":true},{"name":"2","index":1,"mine":false,"visible":true,"focused":false,"busy":true},{"name":"3","index":2,"mine":false,"visible":true,"focused":true,"busy":true},{"name":"4","index":3,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"5","index":4,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"6","index":5,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"7","index":6,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"8","index":7,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"9","index":8,"mine":false,"visible":false,"focused":false,"busy":false}]},{"h":2160,"w":3840,"x":0,"y":0,"layout":"MainAndVertStack","index":2,"tags":[{"name":"1","index":0,"mine":false,"visible":true,"focused":false,"busy":true},{"name":"2","index":1,"mine":false,"visible":true,"focused":false,"busy":true},{"name":"3","index":2,"mine":true,"visible":true,"focused":true,"busy":true},{"name":"4","index":3,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"5","index":4,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"6","index":5,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"7","index":6,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"8","index":7,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"9","index":8,"mine":false,"visible":false,"focused":false,"busy":false}]}]}
```

**Comment by jlorezz** [comment]
![image](https://user-images.githubusercontent.com/29343633/110526937-af956800-8116-11eb-9ad1-94eeccfc0e3b.jpeg)

**Comment by jlorezz** [comment]
exactly

**Comment by jlorezz** [comment]
wouldn't have been able to describe it better ty!

**Comment by AethanFoot** [comment]
Are you defining the 3 monitors as one whole screen, or are you defining them as three screens in xorg. As whenever I setup my two monitors as two different screens one goes black with a X cursor on it, so I setup my monitors in one screen (see #232 for the example). If they are separate screens are you using xinerama, which might fix the issue (haven't tried it out yet). Also to check what graphics driver do you have, as if you have nvidia they have an easy way to setup them up and save the config to xorg.conf.

**Comment by AethanFoot** [comment]
Do you have nvidia x server settings installed. If so go to the x server display configuration tab and move the monitors where you want, either graphical or with the settings. Then press apply and if you get a setup that works you can press save to x config file (you need to open nvidia settings as root to do so). If you want any help with the settings let me know and Ill try and suggest some things.

**Comment by jlorezz** [comment]
Yeah can u help me with the settings?

**Comment by AethanFoot** [comment]
Ye of course, to give you an idea here what I have:
![Screenshot from 2021-03-10 11 54 39](https://user-images.githubusercontent.com/63980259/110625668-9c76ac80-8197-11eb-9389-f29effd9d28e.png)
Go to the advanced tab to get more options.
I think you should be able to use one screen, so set all the screens to X screen 0.
Set the resolution to whatever is needed, and the refresh rate (as if you leave default xorg might not use the right refreshh rate)
Leave orientation.
The position can be set in the drop, but if you drag the ui elements it will update these for you.
The viewport* can be left alone unless you want a custom resolution, and panning can be left alone.
Set whichever monitor is primary, and I was recommended to select the force full composition pipeline options.
Then apply to make sure it works and the save to x config, which will give you a preview. You can save it under /etc/X11/xorg.conf.d/20-nvidia.conf to make sure you don't overwrite anything.

**Comment by VuiMuich** [comment]
I started digging in the code to see if this is somewhat intended behaviour, but I am slow at this.

But I got a second monitor hooked up to my laptop and can reproduce your issue.
I found out (using arandr) that if the bottom screen is shifted a bit to the right (so it does star at x=0) the workspace gets created properly (despite the bar not launching, but that's an issue with the up-script not passing the y-value to polybar).
Considering this, it might well be a bug that leftwm doesn't create the workspace with the correct coordinates.

**Comment by jlorezz** [comment]
Yep. with Nvidia it still reproduces this same issue.

**Comment by AethanFoot** [comment]
The issue seems to be different than what I thought, when placing my monitors on top of each other (on one xorg screen) I don't get any black screens but the wallpaper loads, polybar seems to load, be leftwm acts very strangely. A few examples is the window that is suppose to be on the top monitor appears with a small height (full width) at the top of the bottom monitor, the mouse cursor seems to enlarge every where on the screens except on when it is on a window (or bar etc.)

**Comment by jlorezz** [comment]
> The issue seems to be different than what I thought, when placing my monitors on top of each other (on one xorg screen) I don't get any black screens but the wallpaper loads, polybar seems to load, be leftwm acts very strangely. A few examples is the window that is suppose to be on the top monitor appears with a small height (full width) at the top of the bottom monitor, the mouse cursor seems to enlarge every where on the screens except on when it is on a window (or bar etc.)

same wallpapers seem to load but leftwm is just not working / registering the workspaces.

**Comment by VuiMuich** [comment]
It seems that when the screens have the same resolution leftwm can create the workspaces, but the windows get always placed on on the same monitor. 
When I add the y-value to the up-script and polybar-config the bars get produced correct, but the workspaces still overlap they just get rendered on the primary monitor instead of the monitor with +0+0.

When the monitors have different resolutions and the bars are created without y-offset, only the +0+0 Monitor can render the workspace, the other(s) are black. (Mouse rendering happens apparently on a completely independent level on the gpu, compare redshift issue with pointer not being affected by redshift).

**Comment by jlorezz** [comment]
So what can we do to solve this?

**Comment by VuiMuich** [comment]
I am afraid this is as far as I am able to help.
It might be intended behaviour as a workaround, since there are apparently several issues happening with vertical screen layouts.
Or it is actually a bug.
I think this might need the attention of @lex148, or maybe @mautamu since they are way more competent to get a grip of this.

At least we came to a point where it is pretty much clear what is happening, and how the issue can be reproduced, which is very relevant to fixing this issue

**Comment by mautamu** [comment]
I unfortunately only have two monitors with which to test this, but I do have a couple of suspects I think. Does the issue also occur when you attempt to resize the layout with [IncreaseMainWidth](https://github.com/leftwm/leftwm/wiki/Config#increasemainwidth)  and DecreaseMainWidth?

Can you winkey+Click-drag a window onto those monitors?

**Comment by VuiMuich** [comment]
> I unfortunately only have two monitors with which to test this, but I do have a couple of suspects I think. Does the issue also occur when you attempt to resize the layout with [IncreaseMainWidth](https://github.com/leftwm/leftwm/wiki/Config#increasemainwidth)  and DecreaseMainWidth?
> 
> 
> 
> Can you winkey+Click-drag a window onto those monitors?

I did all my testing so far with two screens (laptop+external) and arranging the layout in arandr. I'll try if floating windows can access these black screen area.

**Comment by VuiMuich** [comment]
Unfortunately I cannot reproduce the black screen issue anymore. Probably I am just missing to revert one parameter I changed during testing, but can't find which one it is.

On the upside I found a modification to the upscript that produces the polybars more consistent an all monitors (probably breaks ultra-wide screens with multiple workspaces on a single screen). Gonna PR this, when I find a way to do both: create bars based on monitors without any offset and produce bars for "subdevided ultrawide-screens".

Also noticed that sometimes (didn't find a reproducible pattern yet) leftwm limits the workspace of the bigger screen to the height of the smaller one. (No hints in `leftwm-state -q`, whatsoever)
Interesting observation: it is possible to drag floating windows to areas outside the workspaces (e.g. when changing layout but before soft-reload).

**Comment by AethanFoot** [comment]
I have made a video to hopefully demonstrate some of the weirdness (A side note to add that isn't clear is that the mouse is enlarged).

https://user-images.githubusercontent.com/63980259/111138727-306dbd00-8578-11eb-945b-36aa61cdcf68.mp4

**Comment by VuiMuich** [comment]
@jlorezz could you try the following in the config.toml
```toml
#workspaces = [] need to be removed or comented out
[[workspaces]]
x = 0
y = 0
height = 3840
width = 2160

[[workspaces]]
y = 2160
x = 0
height = 1080
width = 1920

[[workspaces]]
y = 2160
x = 1920
height = 1080
width = 1920
```

**Comment by jlorezz** [comment]
> @jlorezz could you try the following in the config.toml
> 
> ```toml
> #workspaces = [] 
> # the above line needs to be removed or comented out
> 
> [[workspaces]]
> x = 0
> y = 0
> height = 3840
> width = 2160
> 
> [[workspaces]]
> y = 2160
> x = 0
> height = 1080
> width = 1920
> 
> [[workspaces]]
> y = 2160
> x = 1920
> height = 1080
> width = 1920
> ```

i tried this. it's all offset. windows go accross monitors
it's not right.

**Comment by jlorezz** [comment]
but i can move my mouse up an down and see stuff on my bottom monitors. so it goes in the right direction but it's just the different values. idk why

**Comment by VuiMuich** [comment]
I think I know what you mean with windows across monitors, have been able to get some really weird workspace-behaviour, when trying to get polybars on all screens in a vertical setup. But when I ignore that only the monitor with +0+0 has a bar I can get my second monitor working properly. Possibly further screwed u with your tripple monitor setup.
I'm sorry, that this issue is kinda stuck..

**Comment by VuiMuich** [comment]
#339 could be also relevant for this.
At least it might help for one of the nastier polybar-hacks I tried to fix this.
The memory is a bit distant right now and I don't know when I would find some time to recreat my tests from march though..

**Comment by AethanFoot** [comment]
@jlorezz Sorry it has been awhile, however do have the time to test if the changes made in #381 have fixed your issues.
Thanks.
