### ISSUE TITLE
Can not focus keyboard on floating menu

### ISSUE THREAD

**Issue by JudahGoldstein** [leftwm/leftwm#231]
When using eclipse on arch the ctrl+f find and replace floating menu can be interacted with the mouse but not the keyboard unless the floating menu is moved to another screen with nothing below it. Makes eclipse pretty much unusable when debugging. 
The border color only switches to focused when there's nothing below the menu as well.

**Comment by mautamu** [comment]
Appears Eclipse (eclipse-rust 2:4.18-2) is susceptible to #154 as well (tagging #184).

It seems the mouse autofocuses on the find/replace window (#230?). Using `FocusWindowUp` puts and holds you on the find window (trying `FocusWindowUp` or `FocusWindowDown` from within the find window doesn't work).

**Comment by VuiMuich** [comment]
Closing this, as many fixes in that direction have been merged.
@JudahGoldstein if the issue persists, please reopne.
