### ISSUE TITLE
Workspace stuck in 1360x768

### ISSUE THREAD

**Issue by bescott9944** [leftwm/leftwm#232]
Hello
I'm have issues with LeftWm not changing resolution from 1360x768 to 1920x1080 on ky 32" hdmi tv. LeftWm is stuck in 1360x768 and when I use xrandr
to change the screen to 1920x1080 it still thinks it is in 1360x768 by the output below... 
YES Cinnamon and SpectrWm work as they should on the same monitor.Tv... Nothing changes but logging into LeftWm...
No matter what I do LeftWm will not set the screen right. What I mean the screen seams to switch to 1920x1080 (monitor says so) but
LeftWm's desktop is in the upper left (Not a pun) of the screen and the wallpaper is chopped up into like 6 areas. The desktop is about 2/3s across the top of the 32" screen and down from the top-left about half way. The screen is full but the desktop is all squished to the upper left of the screen....

I have tried several Themes and have the same issue.
This was installed from the Arch Repo and NOT the "Git" in the AUR...

I was reading Issue #229 and I issued the below command and got this out put...
`
Output of "leftwm-state" in a terminal
{"window_title":"Tilix: Stargazer-Endev: ~ | 167x37 | pts/0","workspaces":[{"h":768,"w":1360,"x":0,"y":0,"layout":"MainAndVertStack","index":0,"tags":[{"name":"","index":0,"mine":true,"visible":true,"focused":true,"busy":true},{"name":"","index":1,"mine":false,"visible":false,"focused":false,"busy":true},{"name":"","index":2,"mine":false,"visible":false,"focused":false,"busy":true},{"name":"","index":3,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"","index":4,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"","index":5,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"","index":6,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"","index":7,"mine":false,"visible":false,"focused":false,"busy":false}]}]}
{"window_title":"Tilix: leftwm-state","workspaces":[{"h":768,"w":1360,"x":0,"y":0,"layout":"MainAndVertStack","index":0,"tags":[{"name":"","index":0,"mine":true,"visible":true,"focused":true,"busy":true},{"name":"","index":1,"mine":false,"visible":false,"focused":false,"busy":true},{"name":"","index":2,"mine":false,"visible":false,"focused":false,"busy":true},{"name":"","index":3,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"","index":4,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"","index":5,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"","index":6,"mine":false,"visible":false,"focused":false,"busy":false},{"name":"","index":7,"mine":false,"visible":false,"focused":false,"busy":false}]}]}
`
I get this out put in 1368x768 or 1920x1080 no matter if I use Arandr or Xarndr
The above output is the same...

This is EndeavourOS Cinnamon as the base system and I usually run SpectrWm and DWM a bit... But I seen LeftWm on a video and liked what I seen...
Here is my INXI output...

`
Inxi - System Data Information:
============
System:
  Kernel: 5.11.2-arch1-1 x86_64 bits: 64 compiler: gcc v: 10.2.1 Desktop: N/A 
  Distro: EndeavourOS base: Arch Linux 
Machine:
  Type: Desktop Mobo: ASRock model: 970 Extreme4 serial: <filter> 
  UEFI: American Megatrends v: P2.80 date: 08/05/2015 
CPU:
  Info: 6-Core model: AMD FX-6300 bits: 64 type: MCP arch: Bulldozer rev: 0 
  L2 cache: 2 MiB 
  flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm 
  bogomips: 41922 
  Speed: 1424 MHz min/max: 1400/3500 MHz boost: enabled Core speeds (MHz): 
  1: 1424 2: 1717 3: 1396 4: 1389 5: 1397 6: 1394 
Graphics:
  Device-1: AMD RV730 PRO [Radeon HD 4650] vendor: Hightech Information System 
  driver: radeon v: kernel bus ID: 01:00.0 
  Display: x11 server: X.org 1.20.10 driver: loaded: ati,radeon 
  unloaded: fbdev,modesetting,vesa resolution: <missing: xdpyinfo> 
  Message: Unable to show advanced data. Required tool glxinfo missing. 
Audio:
  Device-1: AMD SBx00 Azalia vendor: ASRock driver: snd_hda_intel v: kernel 
  bus ID: 00:14.2 
  Device-2: AMD RV710/730 HDMI Audio [Radeon HD 4000 series] 
  vendor: Hightech Information System driver: snd_hda_intel v: kernel 
  bus ID: 01:00.1 
  Sound Server: ALSA v: k5.11.2-arch1-1 
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
  vendor: ASRock driver: r8168 v: 8.048.03-NAPI port: c000 bus ID: 07:00.0 
  IF: enp7s0 state: up speed: 100 Mbps duplex: half mac: <filter> 
Drives:
  Local Storage: total: 1.59 TiB used: 282.99 GiB (17.4%) 
  ID-1: /dev/sda vendor: Hitachi model: HDS721010CLA332 size: 931.51 GiB 
  ID-2: /dev/sdb vendor: Seagate model: ST3750640AS P size: 698.64 GiB 
  Message: No Optical or Floppy data was found. 
Partition:
  ID-1: / size: 95.62 GiB used: 17.86 GiB (18.7%) fs: ext4 dev: /dev/sda3 
  ID-2: /boot/efi size: 998 MiB used: 280 KiB (0.0%) fs: vfat dev: /dev/sda1 
  ID-3: /home size: 811.12 GiB used: 265.13 GiB (32.7%) fs: ext4 
  dev: /dev/sda4 
Swap:
  ID-1: swap-1 type: partition size: 7.81 GiB used: 0 KiB (0.0%) 
  dev: /dev/sda2 
Sensors:
  System Temperatures: cpu: 39.2 C mobo: N/A gpu: radeon temp: 65.0 C 
  Fan Speeds (RPM): N/A 
Info:
  Processes: 233 Uptime: 22h 00m Memory: 11.65 GiB used: 2.68 GiB (23.0%) 
  Init: systemd Compilers: gcc: 10.2.0 Packages: 1406 Shell: Zsh v: 5.8 
  inxi: 3.3.00 
________________
`
Any Ideas? The 1360x768 is just to big on this screen... :-(
LLAP
Bruce

This screen 1920x1080
![03-03-2021-23:04](https://user-images.githubusercontent.com/51040721/109910146-78860900-7c75-11eb-921f-7935c2619dc1.png)

This screen 1360x768
![03-03-2021-23:21](https://user-images.githubusercontent.com/51040721/109911147-876dbb00-7c77-11eb-9401-dab7304d4df5.png)

**Comment by AethanFoot** [comment]
If soft reloading doesn't work like suggested by lex in the other thread, have you setup a xorg.conf. I would of thought this would help as the screen size will be set before leftwm launches. Or you could try and run xrandr on an autostart before leftwm loads.

**Comment by VuiMuich** [comment]
Can you confirm you tried a soft-reload of leftwm with `modkey+Shift+R`?

leftwm does not update its state after xrandr (or arandr) automatically.

By "from arch repo" you probably mean the 'stable' [aur package](https://aur.archlinux.org/packages/leftwm/), right? 
I don't think there is currently an official arch package.
You might try the -git version in my experience it is pretty stable as well, though it updates more often of course.

**Comment by bescott9944** [comment]
> Can you confirm you tried a soft-reload of leftwm with `modkey+Shift+R`?
> 
> leftwm does not update its state after xrandr (or arandr) automatically.
> 
> By "from arch repo" you probably mean the 'stable' [aur package](https://aur.archlinux.org/packages/leftwm/), right?
> I don't think there is currently an official arch package.
> You might try the -git version in my experience it is pretty stable as well, though it updates more often of course.

Frist... Thanks for the replay!
1. Yes in ment the Arch repo and not the "AUR -git one"... This is the way I did it... "yay -S leftwm"... Lol
2. No I did not try modkey+Shift+R after setting the display with xrandr (or arandr) I just changed it back to 1360x768...

Ok so I reset the screen with xrander and got the same small screen and then I reset with the modkey+Shift+R and the screen resolution changed from the small squished in the upper left of the screen to the regular size screen. (Thanks the Screen Gods)
So that soft reset of modkey+Shift+R did work to fix the screen.
My question now is how do we do this automatically when starting LeftWm?
Thanks you for your help BTW!

**Comment by bescott9944** [comment]
> If soft reloading doesn't work like suggested by lex in the other thread, have you setup a xorg.conf. I would of thought this would help as the screen size will be set before leftwm launches. Or you could try and run xrandr on an autostart before leftwm loads.

Hello and thanks for the reply!
No I did not do a soft reset with modkey+Shift+R. Did not know I needed to... :-)
As I replied to VuiMuich I did try sitting again with xrandr and the soft reset did work and the 1920 screen is set proper.
No I do not have a xorg.conf as I have never need one I guess... Not sure what it is...

("Or you could try and run xrandr on an autostart before leftwm loads.")
Ok how would you go about that?
I have seen folks videos where they talk about a xorg.conf but never explain what it is or does...

But the reset worked so who do I get this done when starting LeftWm?
Thanks!
LLAP

**Comment by bescott9944** [comment]
So here is some more Information...
When I start EndeavourOS and I get to the LightDm screen my monitor is set buy the boot process as 1360x768.
When I go into Cinnamon DE or Spectrwm the screen changes to 1920x1080...
So LeftWm is using the LightDM settings? Where is Cinnamon DE getting its screen resolution settings?
Just thinking out loud...
Thanks...
LLAP

**Comment by AethanFoot** [comment]
Before I try and do a brief explanation I would recommend looking at the arch wiki page for xorg, https://wiki.archlinux.org/index.php/Xorg (I am happy to try and explain anything you are confused about). 
So when the xserver is started it will read configuration file /etc/X11/xorg.conf, and/or smaller configs in /etc/X11/xorg.conf.d/*.conf. This will be setting up various things from displays to peripherals, and is what most systems use when setting them up (except some DEs and WMs which you have experienced), including your display manager lightdm.
For an example this is my main config (where I have one other for keyboard):
```
Section "ServerLayout"
    Identifier     "Layout0"
    Screen      0  "Screen0" 0 0
    InputDevice    "Mouse0" "CorePointer"
    Option         "Xinerama" "0"
EndSection

Section "Files"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Mouse0"
    Driver         "mouse"
    Option         "Protocol" "auto"
    Option         "Device" "/dev/psaux"
    Option         "Emulate3Buttons" "no"
    Option         "ZAxisMapping" "4 5"
EndSection

Section "Monitor"
    # HorizSync source: edid, VertRefresh source: edid
    Identifier     "Monitor0"
    VendorName     "Unknown"
    ModelName      "Ancor Communications Inc VG248"
    HorizSync       30.0 - 160.0
    VertRefresh     50.0 - 150.0
    Option         "DPMS"
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "GeForce RTX 2070"
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth    24
    Option         "Stereo" "0"
    Option         "nvidiaXineramaInfoOrder" "DFP-5"
    Option         "metamodes" "DP-4: 1920x1080_144 +1680+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, DP-0: 1680x1050_60 +0+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}"
    Option         "SLI" "Off"
    Option         "MultiGPU" "Off"
    Option         "BaseMosaic" "off"
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection
```
Some of these options will be different for you as you are using amd, but I would expect there already is a config file which just needs tweaking a bit.

I am 100% where cinnamon get their display settings, but for example I know gnome have a display settings config which is saved in .config and overrides what xorg config you have (I'd guess cinnamon is very similar).

**Comment by bescott9944** [comment]
Ok @AethanFoot... I looked at the Arch Wiki per your link and some of it made sense some didn't but that is just me. Lol
I did get the jest of it and I have searched 4 computers and None of them have a xorg.conf. They are all Arch (like EndeavourOS & BTW build), MX, Mint and not one has one... ? They all have Cinnamon DE because I like the programs.
Now for your
> (I'd guess cinnamon is very similar).


I did find on all the systems this file in the .config folder called "cinnamon-monitors.xml"

`<monitors version="1">
  <configuration>
      <clone>no</clone>
      <output name="HDMI-0">
          <vendor>ELE</vendor>
          <product>0x3553</product>
          <serial>0x0000000f</serial>
          <width>1920</width>
          <height>1080</height>
          <rate>60.000000</rate>
          <x>0</x>
          <y>0</y>
          <rotation>normal</rotation>
          <reflect_x>no</reflect_x>
          <reflect_y>no</reflect_y>
          <primary>yes</primary>
      </output>
      <output name="VGA-0">
      </output>
      <output name="DVI-0">
      </output>
  </configuration>
</monitors>`

It shows that I am using my HDMI port and it is 1920x1080 and this is the only file I can find on all the computers that I can see that has this settings or any mention of the settings...
I have looked in /etc, /etc/x11, /usr/share/x11, there is no Xorg.config nore is there a mention of any anywhere.
None of the files in any of the X11 folder point to the screen settings either...

Now I read in the Wiki (per your link) that there is a command to run. This one...
`# Xorg :0 -configure
`
Should I run it?
There are several files in the X11 folders that start with numbers like /usr/share/X11/xorg.conf.d/10-amdgpu.conf and so on but nothing to do with monitors...

I ran several commands in the Wiki like lspci -v | grep -A1 -e VGA -e 3D, pacman -Ss xf86-video and the best I'm all good there... Lol
So I will wait for you response in the `# Xorg :0 -configure command...
Thanks for the help,,,

**Comment by AethanFoot** [comment]
Generating a skeleton config shouldn't cause any issues. However before doing check the amdgpu.conf as monitor often can be set with the gpu setup, if there is no monitor settings in there check out, https://openelec.tv/documentation/configuration/configuring-a-custom-xorg-conf, as it seems to layout a good skeleton for it (however i cant test it).

**Comment by VuiMuich** [comment]
In kind of a Hacks way you could try to add the `xrandr` in the up script just before the line 
```
echo "LoadLayout $SCRIPTDIR/theme.toml" > $XDG_RUNTIME_DIR/leftwm/command.pipe
``` 
(from the top of my head, will korrect for proper syntax later)

**Comment by bescott9944** [comment]
@AethanFoot here is the contents of the amdgpu.conf ...
`Section "OutputClass"
	Identifier "AMDgpu"
	MatchDriver "amdgpu"
	Driver "amdgpu"
EndSection`

A gpu setup? never seen one... :-\

I did run the Xorg :0 -configure but as Xorg :2 -configure and I got a xorg.conf.new and it has 2 monitor settings like this all commented out...
`Section "ServerLayout"
	Identifier     "X.org Configured"
	Screen      0  "Screen0" 0 0
	Screen      1  "Screen1" RightOf "Screen0"
	Screen      2  "Screen2" RightOf "Screen1"
	Screen      3  "Screen3" RightOf "Screen2"
	Screen      4  "Screen4" RightOf "Screen3"
	Screen      5  "Screen5" RightOf "Screen4"
	Screen      6  "Screen6" RightOf "Screen5"
	Screen      7  "Screen7" RightOf "Screen6"
	Screen      8  "Screen8" RightOf "Screen7"
	Screen      9  "Screen9" RightOf "Screen8"
	Screen     10  "Screen10" RightOf "Screen9"
	Screen     11  "Screen11" RightOf "Screen10"
	Screen     12  "Screen12" RightOf "Screen11"
	Screen     13  "Screen13" RightOf "Screen12"
	Screen     14  "Screen14" RightOf "Screen13"
	Screen     15  "Screen15" RightOf "Screen14"
	Screen     16  "Screen16" RightOf "Screen15"
	Screen     17  "Screen17" RightOf "Screen16"
	Screen     18  "Screen18" RightOf "Screen17"
	Screen     19  "Screen19" RightOf "Screen18"
	Screen     20  "Screen20" RightOf "Screen19"
	Screen     21  "Screen21" RightOf "Screen20"
	InputDevice    "Mouse0" "CorePointer"
	InputDevice    "Keyboard0" "CoreKeyboard"
EndSection

Section "Files"
	ModulePath   "/usr/lib/xorg/modules"
	FontPath     "/usr/share/fonts/misc"
	FontPath     "/usr/share/fonts/TTF"
	FontPath     "/usr/share/fonts/OTF"
	FontPath     "/usr/share/fonts/Type1"
	FontPath     "/usr/share/fonts/100dpi"
	FontPath     "/usr/share/fonts/75dpi"
EndSection

Section "Module"
	Load  "glx"
EndSection

Section "InputDevice"
	Identifier  "Keyboard0"
	Driver      "kbd"
EndSection

Section "InputDevice"
	Identifier  "Mouse0"
	Driver      "mouse"
	Option	    "Protocol" "auto"
	Option	    "Device" "/dev/input/mice"
	Option	    "ZAxisMapping" "4 5 6 7"
EndSection

Section "Monitor"
	Identifier   "Monitor0"
	VendorName   "Monitor Vendor"
	ModelName    "Monitor Model"
EndSection

`

and 21 of these at the bottom... :-)


`
Section "Device"
        ### Available Driver options are:-
        ### Values: <i>: integer, <f>: float, <bool>: "True"/"False",
        ### <string>: "String", <freq>: "<f> Hz/kHz/MHz",
        ### <percent>: "<f>%"
        ### [arg]: arg optional
        #Option     "Accel"              	# [<bool>]
        #Option     "SWcursor"           	# [<bool>]
        #Option     "EnablePageFlip"     	# [<bool>]
        #Option     "SubPixelOrder"      	# [<str>]
        #Option     "ZaphodHeads"        	# <str>
        #Option     "AccelMethod"        	# <str>
        #Option     "DRI3"               	# [<bool>]
        #Option     "DRI"                	# <i>
        #Option     "ShadowPrimary"      	# [<bool>]
        #Option     "TearFree"           	# [<bool>]
        #Option     "DeleteUnusedDP12Displays" 	# [<bool>]
        #Option     "VariableRefresh"    	# [<bool>]
	Identifier  "Card0"
	Driver      "amdgpu"
	BusID       "PCI:0:0:0"
EndSection

Section "Device"
        ### Available Driver options are:-
        ### Values: <i>: integer, <f>: float, <bool>: "True"/"False",
        ### <string>: "String", <freq>: "<f> Hz/kHz/MHz",
        ### <percent>: "<f>%"
        ### [arg]: arg optional
        #Option     "Accel"              	# [<bool>]
        #Option     "SWcursor"           	# [<bool>]
        #Option     "EnablePageFlip"     	# [<bool>]
        #Option     "SubPixelOrder"      	# [<str>]
        #Option     "ZaphodHeads"        	# <str>
        #Option     "AccelMethod"        	# <str>
        #Option     "DRI3"               	# [<bool>]
        #Option     "DRI"                	# <i>
        #Option     "ShadowPrimary"      	# [<bool>]
        #Option     "TearFree"           	# [<bool>]
        #Option     "DeleteUnusedDP12Displays" 	# [<bool>]
        #Option     "VariableRefresh"    	# [<bool>]
	Identifier  "Card1"
	Driver      "amdgpu"
	BusID       "PCI:0:2:0"
EndSection`

So that is confusing.... 
I looked the "openelec" link and I seen the part for a sample AMD xorg.conf... Should I make one? if so I assume it goes into the /etc/X11/xorg.conf... Right?
It looks kinda like yours more than the one X generated... How did you get your?

So thanks again for you kindness and help.
Bruce

**Comment by bescott9944** [comment]
> In kind of a Hacks way you could try to add the `xrandr` in the up script just before the line
> 
> ```
> echo "LoadTheme $SCRIPTDIR/theme.toml" > $XDG_RUNTIME_DIR/leftwm/command.pipe
> ```
> 
> But setting up xorg.conf.d surely is the proper way to go and probably would also lead to the login-screen being already in 1920x1080.

HaHaHa @VuiMuich I'm not beyond a little hacky tricks...
So that would be doing something like this?

`#!/bin/sh
xrandr --output VGA-0 --off --output DVI-0 --off --output HDMI-0 --primary --mode 1920x1080 --pos 0x0 --rotate normal`

Arandr created this for me and I use it to set the screen in SpectrWm in a bash file that Arandr made. I just run it as a autostart function in the spectrwm.conf and SpectrWm does the work... :-)
So I could add that file to the "UP" as a command right? 
Thanks again for your help!
Bruce

**Comment by bescott9944** [comment]
I want to apologize about forgetting about the Arandr script that I use to start SpectrWm.. That is needed information and it slipped my mind... Sorry folks!
Arandr created this for me and I use it to set the screen in SpectrWm in a bash file that Arandr made. I just run it as a autostart function in the spectrwm.conf and SpectrWm does the work... 
The bah file look like this"

`#!/bin/sh
 xrandr --output VGA-0 --off --output DVI-0 --off --output HDMI-0 --primary --mode 1920x1080 --pos 0x0 --rotate normal`

Sorry my bad...

**Comment by VuiMuich** [comment]
That looks like a promising hack, just execute your script kind of like this:
```bash
#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

#set screen resolution before leftwm theme gets loaded
path_to_/arandr_scritp

#boot compton or picom if it exists
if [ -x "$(command -v compton)" ]; then
  compton &> /dev/null & 
elif [ -x "$(command -v picom)" ]; then
  picom &> /dev/null & 
fi

#set the theme.toml config
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe
```
The not so optimal thing is, that you reset the screen resolution on every soft-reload of leftwm which might appear ugly and can happen quite frequent, when playing with keybinds.

**Comment by AethanFoot** [comment]
The config from openelec can go in amdgpu.conf or xorg.conf. I genersted mine mostly using nvidia settings, however amd doesnt seem to an up to date settings manager. This functionality may be available in a third party settings manager for amd, but im not sure on that. 
Once this is setup and working everything should be at the right resolution, so you could remove the xrandr command from spectrwm.

**Comment by bescott9944** [comment]
@AethanFoot I tried the config from openelec into a xorg.conf and placed it into the /etc/X11 folder and rebooted the computer which went ok and I landed at the LightDM screen, I checked the screen resolution on the monitor/tv with the "info" button and it was 1360x768. Not 1290x1080...
I did tried to log-into  LeftWm, SpectrWm would not load. Just got the wallpaper and that is it. I tried to go to Cinnamon and it loaded in Fall Back mode and the desktop kept crashing. So I went to a TTY and deleted the xorg.conf, rebooted and everything is ok now...
So that was a bust. Would have been nice if it worked. I could not find anything that was current for AMD Linux setup on AMDs site. it was all for older Linux in 2013 and earlier. Did not find anything else to use on the net either...
So I will live with the running xrandr and doing the soft reset. It will be a pain but oh well... :-(
Going to give @VuiMuich idea a shot...
Thanks for your help!

**Comment by bescott9944** [comment]
@VuiMuich I gave you settings idea a try as the xorg.conf did not work... 
The screen does load at 1920x1080 per the screen "info button" on the Tv/Monitor but the LeftWm desktop is still at 1360x768 like before. if you know what I mean, (Upper left of the screen)
Now if I do the "soft reset" the desktop goes to full 1920x1080. After the "soft reset" the polybar fills the screen as it should and everything renders full screen...
I wonder what the commands are used in the software are when you do the "soft reset" (Mod+Shift+R). Maybe this could be used in a script... :-) Just thinking out loud...
This does work but is a pain having to do a soft reset all the time but I guess I will live with it.
I did move the.

#set screen resolution before leftwm theme gets loaded
path_to_/arandr_scritp

to a few places in the UP file and it works best where you said to put it. So now I am at the point of what to do now... :-)
Sort of calling this a done deal unless some else has any ideas...

Thanks for your help!

**Comment by VuiMuich** [comment]
Too bad and please excuse for leading you on.
I thought the `LoadTheme`  would get ahold of the updated display size.

The `SoftReset` gets called by the leftwm-worker 'directly' and not via the command.pipe as the `LoadTheme`.

another hack might be calling arandr from `.xinitrc` before the `dbus-launch`

**Comment by AethanFoot** [comment]
He might need to put the command in a ~/.xprofile, as .xinitrc wont be called as he is using lightdm not startx

**Comment by VuiMuich** [comment]
oh, right forgot about the lightdm

**Comment by bescott9944** [comment]
@VuiMuich & @AethanFoot 
1. I'm not beyond trying whatever as long as it helps me get this working or not.
2. Helps others with the same issue... :-)
No I don't use a .xinitrc but I do have a ~/.xprofile... So would I use the bash script or use the xrandr command directly?
`xrandr --output VGA-0 --off --output DVI-0 --off --output HDMI-0 --primary --mode 1920x1080 --pos 0x0 --rotate normal`
which is what is in the bash script.

**Comment by bescott9944** [comment]
Sorry WRONG that is ~/.profile and NOT ~/.Xprofile...

**Comment by AethanFoot** [comment]
ye so create a .xprofile in your home folder and paste the command in there

**Comment by bescott9944** [comment]
@AethanFoot @VuiMuich  I created the ~/.xprofile and added the xrandr command and restarted Leftwm and it loaded in 1920x1080 per the xrandr command...
`Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 8192 x 8192
HDMI-0 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 760mm x 450mm
   1360x768      60.02 +
   1920x1080     60.00*   50.00    59.94    24.00    23.98  
   1920x1080i    60.00    50.00    59.94  
   1280x768      59.87  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    70.07    60.00  
   800x600       72.19    75.00    60.32  
   720x576       50.00  
   720x576i      50.00  
   720x480       60.00    59.94    59.94  
   720x480i      60.00    59.94  
   640x480       75.00    72.81    60.00    59.94  
   720x400       70.08  
VGA-0 disconnected (normal left inverted right x axis y axis)
DVI-0 disconnected (normal left inverted right x axis y axis)
`
YaY! WE did it... 
Thanks you all for your time, thoughts and help!
Thanks you!
Thanks you!

You can be sure I will pass this along if I ever see someone with this issue. I promise!
Yes I will remove the xrandr script from SpectrWm too...
So I guess we can close this unless you all have something else...

**Comment by bescott9944** [comment]
@AethanFoot @VuiMuich I created the ~/.xprofile and logged out of LeftWm and logged back in and Leftwm loaded at 1920x1080 and looks great! Xrandr also report this:
`creen 0: minimum 320 x 200, current 1920 x 1080, maximum 8192 x 8192
HDMI-0 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 760mm x 450mm
   1360x768      60.02 +
   1920x1080     60.00*   50.00    59.94    24.00    23.98  
   1920x1080i    60.00    50.00    59.94  
   1280x768      59.87  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    70.07    60.00  
   800x600       72.19    75.00    60.32  
   720x576       50.00  
   720x576i      50.00  
   720x480       60.00    59.94    59.94  
   720x480i      60.00    59.94  
   640x480       75.00    72.81    60.00    59.94  
   720x400       70.08  
VGA-0 disconnected (normal left inverted right x axis y axis)
DVI-0 disconnected (normal left inverted right x axis y axis)
`
So YaY! We did it!
Thank You, Thanks You!
Thanks you for all your thoughts, time and help!
I hope this helps others!
I promise I will pass this information along if I ever see anyone needing help with this type issue!
I also removed the xrandr script from SpectrWm and it loaded just fine too in 1920x1080... No more screen flicking when resetting it either.
So you fixed 2 things and once!
Thanks again!
I will close this unless you can think of anything else...
Live Long and Prosper!
LLAP

**Comment by bescott9944** [comment]
Thank you one and all!
