### ISSUE TITLE
Synology-drive application does not get tiled properly and becomes unusable+unclosable.  

### ISSUE THREAD

**Issue by rebuilt** [leftwm/leftwm#238]
![synology-window](https://user-images.githubusercontent.com/16025007/110615385-a8f90600-8193-11eb-8a55-e0ad92e56b86.png)

When launching synology-drive, the application window does not get tiled properly.  It overlays in front of any open application in a centered position.  I cannot interact with the synology-drive application in any way.  Button clicks are not registered.  I cannot close the window.  Super-Shift-q has no effect.  If I move to another workspace, the synology-drive window gets placed on that workspace as well.  The application is still automatically backing up my files correctly.  I just can't change settings or close the window.

**Comment by VuiMuich** [comment]
You could try to Super+Mousedrag to make it floating, this sometimes helps for me, when some pop up windows are handled wrong as maximized windows.

**Comment by mautamu** [comment]
Yes, I suspect #154 might be somewhat involved here. For some reason they're saying it should be rendered as a modal dialogue, when it probably should be a Normal window.

I think a fix for this might be a keypress that converts all window types to a Normal window. It might also be nice when toggling through FocusWindowNext/Previous to highlight modal or floating windows.  

```
xwininfo: Window id: 0x3e00005 "Synology Drive Client"

  Root window id: 0x19f (the root window) (has no name)
  Parent window id: 0x19f (the root window) (has no name)
     0 children.

  Absolute upper-left X:  480
  Absolute upper-left Y:  290
  Relative upper-left X:  480
  Relative upper-left Y:  290
  Width: 960
  Height: 526
  Depth: 24
  Visual: 0x20
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x22 (installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +480+290  -480+290  -480-264  +480-264
  -geometry 960x526+480+290

  Bit gravity: NorthWestGravity
  Window gravity: NorthWestGravity
  Backing-store hint: NotUseful
  Backing-planes to be preserved: 0xffffffff
  Backing pixel: 0
  Save-unders: No

  Someone wants these events:
      KeyPress
      KeyRelease
      ButtonPress
      ButtonRelease
      EnterWindow
      LeaveWindow
      PointerMotion
      ButtonMotion
      Exposure
      StructureNotify
      SubstructureNotify
      FocusChange
      PropertyChange
  Do not propagate these events:
  Override redirection?: No

  Window manager hints:
      Client accepts input or input focus: Yes
      Displayed on desktop 1
      Window type:
          Dialog
          Normal
      Window state:
          Modal
      Process id: 21620

  Normal window size hints:
      User supplied size: 660 by 496
      Program supplied minimum size: 660 by 496
      Program supplied maximum size: 660 by 496
      Program supplied window gravity: StaticGravity
  No zoom window size hints defined

  No window shape defined
  No border shape defined
```

**Comment by rebuilt** [comment]
![leftwm](https://user-images.githubusercontent.com/16025007/111343424-b3c40700-867b-11eb-8941-033e83da5145.gif)
@VuiMuich Thanks for telling me about turning it into a floating window.  It seems the modal window opened behind the primary window but I could not interact with it because the older window was in front.   Moving the window to the side made clear what was happening as you can see in the gif. 

It seems multiple modal dialogs get layered with oldest on top.  

I used cargo to build the project on March 9th.  I'm using Ubuntu.

**Comment by AethanFoot** [comment]
This same issue occurs with gimp dialogs, where the new ones spawn behind older ones.

**Comment by rebuilt** [comment]
Installed leftwm today on arch using cargo build.  It has the same behavior as the Ubuntu system where new modals get tiled behind old modals.  I'm dual booting so it's on the same hardware.

**Comment by rebuilt** [comment]
Thank you!   I'm so pumped this was fixed.
