### ISSUE TITLE
Incorrect tiling on vertical monitor

### ISSUE THREAD

**Issue by NChechulin** [leftwm/leftwm#239]
I use this setup of my monitors:
![](https://i.imgur.com/piXPc5c.png)

In the screenshot, the red box represents a new window. As you can see, it's tiled incorrectly for some reason.
If there are any data that may help to understand the problem, feel free to ask me to send it.

UPD: looks like I found the problem. LeftWM didn't assign each screen a separate workspace on startup. I tried moving the window to workspace 2 and since then everything worked as it should.

**Comment by VuiMuich** [comment]
thanks
