### ISSUE TITLE
thread 'main' panicked at 'Null pointer in display'

### ISSUE THREAD

**Issue by Kreyren** [leftwm/leftwm#242]
```console
kreyren@dreamon~$ leftwm 2>&1 | tee leftwm.log
thread 'main' panicked at 'Null pointer in display', /home/kreyren/.cargo/registry/src/github.com-1ecc6299db9ec823/leftwm-0.2.6/src/display_servers/xlib_display_server/xwrap.rs:67:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Mar 16 08:50:03.164 ERRO Completed with error: Any
sh: 1: hexchat: not found
sh: 1: $HOME/bin/scaler: not found
sh: 1: /usr/lib/protonmail/bridge/proton-bridge-launcher": not found
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted
Mar 16 08:50:05.166 INFO leftwm-worker booted!
thread 'main' panicked at 'Null pointer in display', /home/kreyren/.cargo/registry/src/github.com-1ecc6299db9ec823/leftwm-0.2.6/src/display_servers/xlib_display_server/xwrap.rs:67:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Mar 16 08:50:05.167 ERRO Completed with error: Any
...
Mar 16 08:50:17.180 ERRO Completed with error: Any
```

### Steps to reproduce
1. `cargo install leftwm`
2. `leftwm` (from TTY while no other WM is running)

**Comment by mautamu** [comment]
Have you tried the following?

```bash
dbus-launch leftwm
```

I think it might be prudent to also more gracefully exit on Null. Thoughts?

**Comment by nickzana** [comment]
For reference, this panic occurs in `src/display_servers/xlib_display_server/xwrap.rs` line 74:

``` rust
impl XWrap {
    pub fn new() -> XWrap {
        let xlib = xlib::Xlib::open().unwrap();
        let display = unsafe { (xlib.XOpenDisplay)(ptr::null()) };
        assert!(!display.is_null(), "Null pointer in display");

        let fd = unsafe { (xlib.XConnectionNumber)(display) };

        let (guard, _task_guard) = oneshot::channel();
```

@mautamu How would exiting more gracefully look? Provide a better error message, or avoid panicking?

**Comment by mautamu** [comment]
Good questions, and thanks for finding where it was, this is quite helpful. I looked into how other WMs/DEs handle it and it appears that they tend to give an abbreviated message about not being able to connect to a display:

Awesome
```
[timestamp]: awesome: main:687: cannot open display (error 5)
```

I3:
```
i3: Cannot open display
```

What happens now might be a bit concerning and appear to be an error in the code itself. Notwithstanding that, I think we might try to avoid panicking and just exit with an error, maybe:

```
LeftWM: Cannot open display. LeftWM should not be run directly from the terminal, try `dbus-launch leftwm`
```
Something like that feels a bit more Rusty to me, given the great error messages from Rustc and Cargo.

**Comment by Kreyren** [comment]
> Have you tried the following?
> 
> ```shell
> dbus-launch leftwm
> ```
> 
>
>
> I think it might be prudent to also more gracefully exit on Null. Thoughts? @mautamu 

Seems as same failure to me

```console
kreyren@dreamon~$ dbus-launch leftwm
Mar 17 09:00:09.506 INFO leftwm-worker booted!
sh: 1: hexchat: not found
sh: 1: $HOME/bin/scaler: not found
thread 'main' panicked at 'Null pointer in display', /home/kreyren/.cargo/registry/src/github.com-1ecc6299db9ec823/leftwm-0.2.6/src/display_servers/xlib_display_server/xwrap.rs:67:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Mar 17 09:00:09.507 ERRO Completed with error: Any
sh: 1: /usr/lib/protonmail/bridge/proton-bridge-launcher": not found
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted
Mar 17 09:00:11.509 INFO leftwm-worker booted!
thread 'main' panicked at 'Null pointer in display', /home/kreyren/.cargo/registry/src/github.com-1ecc6299db9ec823/leftwm-0.2.6/src/display_servers/xlib_display_server/xwrap.rs:67:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Mar 17 09:00:11.510 ERRO Completed with error: Any
Mar 17 09:00:13.511 INFO leftwm-worker booted!
...
```

**Comment by Kreyren** [comment]
> LeftWM should not be run directly from the terminal, try `dbus-launch leftwm` 

FWIW this was invoked from [SLiM](https://en.wikipedia.org/wiki/SLiM) using `/usr/share/xsession/leftwm.desktop` at first, but i am unable to capture logs from it thus the CLI from TTY.

**Comment by Kreyren** [comment]
>  awesome: main:687: 

FWIW recommend using `file:line_number` in leftwm too so that people who are not too familiar with the source code (like me) could find easily what is triggering the error.

**Comment by nickzana** [comment]
Ok, so, the specifics of the error message contents aside, should we panic, or implement some form of error propagation? 

The Rust Book provides this [guidance](https://doc.rust-lang.org/book/ch09-03-to-panic-or-not-to-panic.html)

> However, when failure is expected, it’s more appropriate to return a `Result` than to make a `panic!` call. Examples include a parser being given malformed data or an HTTP request returning a status that indicates you have hit a rate limit. In these cases, returning a `Result` indicates that failure is an expected possibility that the calling code must decide how to handle.

I would lean towards incorrectly starting LeftWM being an "expected failure" instead of something more `panic`-worthy, but I'm not sure what anyone else thinks. I also think moving error handling away from XWrap::new() and towards the more "high level" logic makes some sense and feels Rust-like. However, it seems like this part of the code base tends to use `.expect()`, `.unwrap()`, or `panic!()` over Result types.

I made a [branch](https://github.com/nickzana/leftwm/tree/xwrap_error_propogation) showing what the error propagation could look like (currently using unit type as error type as a placeholder) as an example.

**Comment by mautamu** [comment]
Looking over the branch, good work!

I am also moreso of the opinion that this qualifies as an "expected failure" that should probably be dealt with properly than that of the `panic!` failure. There are a few other places (command handling, for example) where passing a Result back could prove to be useful (e.g. for a notifier). 

Taking @Kreyren's notes into account, we might try:
```rust
            let line_info = format!("LeftWM: {}: {}: ", file!(), line!());
            println!("{}{}", line_info, concat!(
                r#"Cannot open display. \
                    Received Null pointer. \
                    LeftWM should not be run directly from the terminal. \
                    Try `dbus-launch leftwm`, \
                    or see "Starting with startx or a login such as slim" \
                    in the leftwm README for instructions on how to start leftwm."#
            ));
```

We could likely macro-ify this as well to save space and DRYS. (Apologies for getting back down into specifics again).

**Comment by Kreyren** [comment]
> I suppose we can try to see if any libraries are missing:
> 
> ```
> ldd /usr/bin/leftwm
> ldd /usr/bin/leftwm-worker
> ```
> - @mautamu 


```console
kreyren@dreamon:~$ ldd /usr/bin/leftwm
ldd: /usr/bin/leftwm: No such file or directory
kreyren@dreamon:~$ ldd /usr/bin/leftwm-worker
ldd: /usr/bin/leftwm-worker: No such file or directory
```

> I recall seeing a similar issue with KISS Linux because glibc was missing. @mautamu 

No package containing `glibc` in it's name is installed.

```console
kreyren@dreamon:~$ apt list --installed glibc
Listing... Done
```

**Comment by Kreyren** [comment]
> I'm operating under the assumption that other DEs/WMs can start successfully? @mautamu 

Yes, currently using xfce4 with Xfwm4.

![image](https://user-images.githubusercontent.com/11302521/111601155-61e1c500-87d2-11eb-8a7d-b665877f364b.png)

**Comment by Kreyren** [comment]
> Other things to try:
>
> ```
> # see if there's a display set
> echo $DISPLAY
> # see if Xorg gets started in the process:
> ps -ef | grep X
> ```
> @mautamu 

Invoking `dbus-launch leftwm` from TTY and then switching on another TTY has DISPLAY not set and `X` process not running.

**Comment by Kreyren** [comment]
Consulted with devuan about the missing glibc, we came to the conclusion that it is installed:

```
kreyren@dreamon:~$ apt list --installed | grep libc-bin
libc-bin/testing,unstable,now 2.31-9 amd64 [installed]
```

(stripped warn message)

**Comment by Kreyren** [comment]
also checking `ldd` agains leftwm:

```console
kreyren@dreamon:~$ command -v leftwm
/home/kreyren/.cargo/bin/leftwm
kreyren@dreamon:~$ ldd ~/.cargo/bin/leftwm
	linux-vdso.so.1 (0x00007ffe6cb97000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f66fc5d5000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f66fc5bb000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f66fc599000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f66fc455000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f66fc290000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f66fc65f000)
```

**Comment by VuiMuich** [comment]
I get one more lib listed:
```
librt.so.1 => /usr/lib/librt.so.1 (0x00007f68e9df9000)
```
and my ld-linux-x86-64 get pointed to /usr/lib64:
```
/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f68e9f14000)
```
but this might just be a distro-difference, as I am on Manjaro, right?

**Comment by Kreyren** [comment]
Seems to launch when using `startx` though O.o getting a black screen with a mouse cursor that i assume is leftwm?

**Comment by VuiMuich** [comment]
If you can use keybinds (e.g. to start a terminal) or get output of `leftwm-state -q`?
Have you set a theme?

**Comment by Kreyren** [comment]
@VuiMuich Just figured out how to use LeftWM seems fully functional, but it refuses to start from TTY nor SLiM

**Comment by VuiMuich** [comment]
Just to clarify:
You can use SLiM to start Xfce4, but not LeftWM?
You can start LeftWM with startx though?
Can you confirm you setup everything according to this repos README.md?

**Comment by AethanFoot** [comment]
From what I can read SLiM seems to use the .xinitrc, if this is correct can you show the contents of .xinitrc.
If you have setup it up as suggested with ```exec dbus-launch leftwm``` in your xinitrc it could be possible SLiM doesn't like this and requires it to be ```exec dbus-launch $1``` (this is just a wild thought).

**Comment by Kreyren** [comment]
My bad the WM starts from SLiM without major issues.

It confused me because it leaves the login manager's background on at all times and the text `Session: Leftwm` stays on the screen making it look like it launched X, but failed to launch the WM.

But it responds to commands and the mentioned text disappears once i drag a window on it. O.o

**Comment by AethanFoot** [comment]
Thats good, I would assume the screen isnt clearing/updating properly after launch (this could be an issue with SLiM as it is quite out of date). If it updates once a window moves over it have you tried a theme and seen whether the background loading also hides the ghost text.

**Comment by paulhersch** [comment]
> But it responds to commands and the mentioned text disappears once i drag a window on it. O.o

normal behavior for a WM when no background is set through programs like nitrogen, also appears on bspwm and i3 on first start.
