### ISSUE TITLE
Does not seem to read config file on startup

### ISSUE THREAD

**Issue by nimr0d** [leftwm/leftwm#244]
leftwm-check finds the config file and asserts that everything is ok. Moreover, loading the config file by running leftwm-theme works. So there is some issue that is causing leftwm to not load the config file at startup.

**Comment by mautamu** [comment]
Are keybindings not working or is the theme the issue? Or both?

**Comment by nimr0d** [comment]
Yeah, the keybindings do not work on startup, but they do after I apply a theme (since it reloads the config file).

**Comment by mautamu** [comment]
Very curious. How are you starting LeftWM? What permissions are on ~/.config/leftwm/config.toml?

**Comment by nimr0d** [comment]
I am starting it through the login screen with an xsessions desktop file. The permissions are rw for user and group, and r for others.

**Comment by mautamu** [comment]
Okay so those permissions are right. Hmm. Do you perhaps get red borders around windows prior to running leftwm-theme/restarting leftwm? Is SELinux installed? I'm assuming you're using the default Desktop file, in which case this might be distantly related to #242.

One other thing to try is to compile with journald:
```bash
cargo build --release --features=journald
```
And then shortly after starting leftwm check the logs:
```
journalctl -xe | grep "ERROR LOADING"
```
(Maybe try not piping into grep as well to see if there's anything else awry?)

Should likely add that detail to leftwm-check.

**Comment by VuiMuich** [comment]
If this is still relevant, feel free to reopen.
