### ISSUE TITLE
Some dialogs don't spawn centred

### ISSUE THREAD

**Issue by AethanFoot** [leftwm/leftwm#248]
Examples of these dialogs are ones spawned by a polkit agent, and the x file browser spawned when downloading something.
They tend to spawn at the top of my left monitor. Heres the xwininfo from the authentication window:
```
xwininfo: Window id: 0x8000fa "Authenticate"

  Root window id: 0x1e7 (the root window) (has no name)
  Parent window id: 0x1e7 (the root window) (has no name)
     1 child:
     0x8000fb (has no name): ()  1x1+-1+-1  +-1+-1

  Absolute upper-left X:  0
  Absolute upper-left Y:  0
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 525
  Height: 242
  Depth: 24
  Visual: 0x2b
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x800002 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +0+0  -3075+0  -3075-838  +0-838
  -geometry 525x242+0+0

  Bit gravity: NorthWestGravity
  Window gravity: NorthWestGravity
  Backing-store hint: NotUseful
  Backing-planes to be preserved: 0xffffffff
  Backing pixel: 0
  Save-unders: No

  Someone wants these events:
      EnterWindow
      Exposure
      VisibilityChange
      StructureNotify
      SubstructureNotify
      FocusChange
      PropertyChange
  Do not propagate these events:
  Override redirection?: No

  Window manager hints:
      Client accepts input or input focus: Yes
      Initial state is Normal State
      Displayed on desktop 1
      Window type:
          Dialog
      Window state:
          Above
          (unresolvable ATOM 0x0)
      Process id: 2084 on host aethan-ms7921

  Normal window size hints:
      Program supplied minimum size: 525 by 242
      Program supplied maximum size: 525 by 242
      Program supplied base size: 0 by 0
      Program supplied window gravity: NorthWestGravity
  No zoom window size hints defined

  No window shape defined
  No border shape defined
```

**Comment by mautamu** [comment]
Note for #184 

I have been experiencing a quite similar issue with the Splash screens after rewriting them in my branch. Most appear in the NW part of the screen. Tbqh I almost wonder if centering them there horizontally (ie N) would be better than centering them horizontally and vertically. But I digress. I believe Firefox and Thunderbird prompts also tend to do this as well. I think once we get the code in #184 cleaned up applying that to dialogs might help as well.

**Comment by mautamu** [comment]
So the issue is that dialogs don't always request a width/height, so LeftWM assumes one:
![Screenshot_2021-03-20_02-15-28](https://user-images.githubusercontent.com/2220164/111862255-2eae4b80-8922-11eb-8813-ca671c7b38aa.png)

For dialogs that behave normally, bf8dc59 is sufficient.

**Comment by AethanFoot** [comment]
For some reason this isn't working, the x and y values in the Xyhw seem reasonable (at least aren't 0,0) they just don't seem to be being applied to the window somewhere down the line. One note the height and width in the Xyhw are for some reason negative and don't seem to have any relation to the actual height and width, but I wouldn't of thought this would cause issues?
Here is what floating is being set to: `Leftwm floating: Xyhw { x: 576, y: 416, h: -836, w: -1155, minw: -999999999, maxw: 999999999, minh: -999999999, maxh: 999999999 }` with the actual height&width being 242&525 (actually that height is different to what leftwm is reporting for min/max)

**Comment by mautamu** [comment]
Ah that height and width appears to perhaps be the height and width of the workspace, likely the one passed back by center_halfed()? I’m still unsure why exactly it’s negative as well, if you look around #184 I chose to just .abs() around that issue. Any ideas whether that’s normal?

**Comment by AethanFoot** [comment]
Looking into it, the height and width are produced from 
```
    pub fn set_floating_exact(&mut self, value: Xyhw) {
        let mut new_value = value - self.normal;
        new_value.clear_minmax();
        self.floating = Some(new_value);
    }
```
Which takes the height/width of the window and subtracts the height/width of the workspace, which seems backwards as the size of the workspace will always be bigger than any window put in it?
From logs the floating value seems to get set correctly (with the wonky width/height), so I doesn't appear to me that it is anything within the splash/dialog if statement. So I can only assume it is somewhere in the manager being updated to it, which I currently don't have the knowledge of the code or rust to get too deep into.
