### ISSUE TITLE
IncreaseMainWidth/DecreaseMainWidth don't seem to work

### ISSUE THREAD

**Issue by jwnpoh** [leftwm/leftwm#249]
Hello, thanks for a nice WM!

As the title says, I can't seem to get the IncreaseMainWidth and DecreaseMainWidth commands to work. I've simply copied the sample config from the wiki into my config.toml and changed the keybinds. Am I missing something?

```
[[keybind]]
command = "IncreaseMainWidth"
value = "5"
modifier = ["modkey", "Control"]
key = "l"

[[keybind]]
command = "DecreaseMainWidth"
value = "5"
modifier = ["modkey", "Control"]
key = "h"
```

**Comment by mautamu** [comment]
Have you tried restarting LeftWM after updating the config? (mod+shift+r or `pkill leftwm`)? 

Some layouts also don't support it, so you might try a different layout.

**Comment by jwnpoh** [comment]
Thanks! The layout tip did the trick. So I've tried cycling through the different layouts; am I right to say that the "traditional" master-stack layout is the only one that supports these commands?

**Comment by mautamu** [comment]
Here are the ones that work for me:
- MainAndVertStack
- MainAndHorizontalStack

The ones that don't seem to work:
- GridHorizontal
- EvenHorizontal
- Even Vertical
- Fibonnaci
- CenterMain
- CenterMainBalanced
- Monocle

Most of these make sense, if you want an even grid then such a setting won't have effect. Monocle is just supposed to be fullscreen so it makes sense too. The Fibonacci and Center Main I'm not certain about, I don't think I used those when I used Awesome.


So yeah, I think you're right in saying that only the traditional master-stack layouts support them. If you have some ideas about how other commands should behave I'm sure we'd love to hear them!

**Comment by jwnpoh** [comment]
Hello, I didn't even realise that there are now so many different layouts! A little bit of reading up revealed that I had been on the aur version which may not be update with the latest version, so I reinstalled with the leftwm-git version instead and voila!

Unfortunately most of the time I have at most 3 windows open at a time, so many of these layouts aren't that relevant for me; can't contribute more in terms of suggestions. I wonder if this might be worth adding as a note to the wiki though? In addition to the "Note: This command requires a value field to be specified."

**Comment by mautamu** [comment]
Absolutely, I'll try putting a note into my copy of the wiki now. Thanks for the suggestion!
