### ISSUE TITLE
Fix wiki HardReload snippets

### ISSUE THREAD

**Issue by sfrique** [leftwm/leftwm#255]
Fix HardReload snippets
https://github.com/leftwm/leftwm/wiki/Config#hardreload

Currently, it has the `SoftReload` command.

**Comment by mautamu** [comment]
Howdy @lex148, 

I have updated mautamu/leftwm_wiki: Config.md to reflect this change. It also contains some great updates from @nickzana and @VuiMuich.

Best,
Mautamu

**Comment by mautamu** [comment]
Thank you @lex148, this is now fixed in the Wiki and can likely be closed.
