### ISSUE TITLE
Layout section for wiki

### ISSUE THREAD

**Issue by carrascomj** [leftwm/leftwm#266]
(I thought it would get met to fork the wiki or something instead of committing it directly, I don't understand how github wikis work, sorry about that.)

I added a section to the Wiki's config to select the preferred layouts instead of all of them (there are a lot now!). Please remove it/edit it if you don't like it, because I am not sure if the syntax is the cleanest you could get, although it works, though.

**Comment by VuiMuich** [comment]
@mautamu was so friendly to merge a pull-request on his fork of the wiki, when I added some instructions on liquid-files.
(Sorry mautamu if I pushed more wiki-merge work to you ;))

**Comment by mautamu** [comment]
Oh it's all good, I copied the stuff from that wiki over to this one. I thought I could also merge in authors and commit history, but apparently only "leftwm" (the organization) can do that. Apologies that those didn't transfer. Everything from mautamu/leftwm_wiki should be included in the wiki now though.

**Comment by carrascomj** [comment]
Wiki's looking great! Closing this.
