### ISSUE TITLE
Opinions requested: `inner margins`

### ISSUE THREAD

**Issue by VuiMuich** [leftwm/leftwm#270]
During testing for #259 I once again noticed that we have the margins between windows adding up.

I believe a more correct behaviour would be, if it is just the single margin between windows, but wanted to get your opinions, what you would desire to be correct.

And if we want to change this, would it be preferred to be hard-coded or configurable?

**Comment by AethanFoot** [comment]
I mentioned about this in #194, not really sure how one would go about doing this. It most definitely should be configurable, and maybe stored within the workspace?

**Comment by VuiMuich** [comment]
So you think this should be configurable per worksapce (or tag?)

**Comment by AethanFoot** [comment]
I would say per tag, as there wasn't any resistance to changing leftwm to tag centric at some point (at least yet).

**Comment by VuiMuich** [comment]
:grin:

**Comment by mautamu** [comment]
I think if we want to move to tag-centric, it'd be best to put #201 and #260 into one (I'd assume). We'd likely also want to increment to 0.3.x for compatibility reasons.
