### ISSUE TITLE
Feature Idea: `flip layout`

### ISSUE THREAD

**Issue by VuiMuich** [leftwm/leftwm#273]
Add the possibility to flip asymmetric layouts.

For some it might even make sense to flip not only horizontally but even vertically.

This could make sense both as config option, as well as command.

Horizontal Flip:
`MainAndVertStack`, `MainAndDeck`, `LeftWiderRightStack`, `CenterMain` and `CenterMainBalanced`, `Fibonacci`

Vertical Flip:
 `Fibonacci` and `MainHorizontalStack`

Both:
 `Fibonacci`

**Comment by AethanFoot** [comment]
I have been thinking about this recently. I imagine this should be easy enough, we could pass a bool (or two), something like should_reverse, into the layout. Then the main work would be handled by the individual layout. This would be implemented in a similar way to the increase/decrease main width works, so could be stored in the workspace (or tag for future) which would reverse every compatible layout for that workspace.
