### ISSUE TITLE
Intermittent: Polybar overwrites tags area with code from template.liquid

### ISSUE THREAD

**Issue by bmclean2** [leftwm/leftwm#275]
Seemingly randomly, and more frequently since the last few commits, polybar will overwrite the tags module with code directly from template.liquid. So I'll get the end of a line like this `%{A1:$SCRIPTPATH/change_to_tag {{workspace.index}} {{tag.index}}:}` printed to the screen on the bar, but with the variables completed. What I see is `H/change_to_tag 0 6:}` overwriting tags 1 through 6. I originally wondered if there was a typo in the file, but I can't spot one. It happens intermittently, but enough to be an annoyance. It is caused by both key bindings and mouse clicks, and doesn't seem to be related to the tag index. Problem exists on community themes as well.

**Comment by mautamu** [comment]
I’ve witnessed this as well. My suspicion is that it might be an unescaped parenthesis in the name of the window, as it seems to happen most often on tags with Firefox, Brave, or Thunderbird open.

**Comment by bmclean2** [comment]
Yes, I usually have both Firefox and Brave open, so that would explain things. The increasing frequency could just be a coincidence.

**Comment by VuiMuich** [comment]
As mentioned in #207 I observed something similar, but I believe that it is actually a different issue: polybar is faster with launching then leftwm-state can produce an parsable output and prints the returned error-message.
Also had this during crashes of leftwm-worker, for obvious reasons.

Maybe we should look for a way to make polybar to fallback to some default, if leftwm-state fails to return the correct output.

A possible solution should then be included in the troubleshooting and 'theming polybar' sections of readme and wiki.

**Comment by VentGrey** [comment]
I commented this on the official discord when the `_NET_CURREN_DESKTOP` bug happened. An easy way to trigger it is to copy the polybar example and "spam" the workspace change keybind (Hold <kbd>Super</kbd> + <kbd>2</kbd> for example) and you'll see the same strange formatting referred in #575.
