### ISSUE TITLE
Spawning Floating Windows Behind Open Windows in Virtualbox

### ISSUE THREAD

**Issue by Joe-Schulte** [leftwm/leftwm#277]
I was setting up a new VM in Virtualbox. When the "Hard disk file type" window spawned, it spawned behind the "Hard disk" window. It would be ideal to fix this if when a floating window spawned, it spawned above all other windows.

**Comment by VuiMuich** [comment]
I think #267 had a similiar fix. Haven't had a look at the code right now, but maybe this would be aplicable to floating windows as well, if it didn't already fix it.

**Comment by rebuilt** [comment]
I compiled and tested today.  The recent commits don't place floating windows on top.  

![virtualbox](https://user-images.githubusercontent.com/16025007/114518747-f6a7d900-9c3f-11eb-8eb7-69295ac57fe4.gif)
