### ISSUE TITLE
some windows do not redraw until clicked on 

### ISSUE THREAD

**Issue by lex148** [leftwm/leftwm#30]
I have only seen this on virt-manager way down in the bowels of dialogs.

steps to reproduce:
1) open virt-manager
2) open a VM
3) click details button in top menu
NOTE: window doesn't redraw to show details
4) mouse out of window
window redraws

expected window to redraw after step 3

**Comment by lex148** [comment]
Note: these step don't work anymore. I have seen this occasionally. keep an eye out and document any way to reprocess the issue

**Comment by NeoDarkFire** [comment]
I think I have this redraw issue in nvidia-settings, but only when the window is "too small".

For example, when I click on "PowerMizer" tab, the window doesn't redraw until I focus another window (or go to the tag I'm already using).
I don't have this issue when nvidia-settings takes the whole screen, but when I am on a problematic tab (like "PowerMizer") and I send nvidia-settings to a tag that has at least 2 windows already, then most of it will be rendered transparent until I focus another window.

Here's a screenshot of the window after the redraw, notice how the main content of the window is drawn behind the status text on the bottom left and the buttons on the bottom right, this is why I'm thinking that the window is "too small".
![screenshot](https://user-images.githubusercontent.com/33136710/102024825-9c336480-3d94-11eb-9911-7466f277399e.png)

**Comment by TornaxO7** [comment]
does this issue still exist?

**Comment by VuiMuich** [comment]
I don't really remrberbanyone reporting something similar. Gonna close for now, if someone experiences some related behavior please feel free to reopen.
