### ISSUE TITLE
Should floating windows retag as the are moved to a new screen

### ISSUE THREAD

**Issue by AethanFoot** [leftwm/leftwm#300]
I say this because of an issue where if I drag a window to my second monitor then if I switch the tag of the main monitor, the floating window window the gets hidden with the other windows on my main monitor.
Another example is with the same setup but I swap the tags on the monitors, then the floating window disappears (I presume is of screen) while all the other windows that were open are still open. I don't know if in this situation if I had a third monitor and set it up properly if the floating window would appear on the third monitor where the floating window would be off screen.
I hope this makes sense, Thanks.

**Comment by VuiMuich** [comment]
@hertg has your tag rework possibly touched related behaivour?

**Comment by hertg** [comment]
> @hertg has your tag rework possibly touched related behaivour?

I don't think so. I vaguely remember closing some logical errors in the window tagging methods, but nothing related to windows being moved across workspaces.

**Comment by VuiMuich** [comment]
I see.
At first Glace it doesn't look to hard to make dragging aware of workspace boundaries, right?
So this might be a `goid first issue`, what do you think?

**Comment by hertg** [comment]
Yeah should be pretty straightforward. I refactored some of the `window_move_handler` code while working on #569. There is some code already to figure out which workspace the floating window is currently on so that it snaps to the correct one.

**Comment by AethanFoot** [comment]
Completed in #807
