### ISSUE TITLE
RotateTag breaks layouts when using IncreaseMainWidth or DecreaseMainWidth

### ISSUE THREAD

**Issue by irmantas** [leftwm/leftwm#303]
Hi recent added (#293) RotateTag Command when activated breaks some of layouts if IncreaseMainWidth or DecreaseMainWidth was used.
Affected layouts:
Monocle
MainAndVertStack
MainAndDeck

maybe more these are most used by me :)

You can see behavior on my screen recording: https://youtu.be/GkW0C6F1TIE

**Comment by AethanFoot** [comment]
Will look into this now.
