### ISSUE TITLE
'xdotool windowactivate' swaps workspaces between two monitors

### ISSUE THREAD

**Issue by Zwo1in** [leftwm/leftwm#310]
Hi, I've found that `xdotool windowactivate` behaves strangely.
It looks like it swaps workspaces between two monitors when used. This came out when trying to use https://github.com/tadly/hideIt.sh in a theme. After changing `windowactivate` to `windowfocus`, hideIt works like a charm. 

To reproduce you can run `windowactivate` on your current terminal with:
```bash
xdotool getwindowfocus windowactivate
```
I'm using leftwm in version `0.2.7`

**Comment by VuiMuich** [comment]
I can confirm (on HEAD with PR 312) that this command causes leftwm to go to the last used workspace and focus on the window under the mouse cursor.

**Comment by Zwo1in** [comment]
> After changing windowactivate to windowfocus, hideIt works like a charm.

Just wanted to clarify, `hideIt.sh` works better if those calls are entirely removed :) Even focusing bars with hideIt.sh may cause strange focus issues that require workspace switching to be fixed.

**Comment by AethanFoot** [comment]
The reason for this is the "current_tag_swap" functionality, https://github.com/leftwm/leftwm/wiki/Config#tag-behaviour.
This can be disabled with disable_current_tag_swap = true, if that is your preferred behaviour.
