### ISSUE TITLE
Some programs have transparent borders on light wallpapers

### ISSUE THREAD

**Issue by Zwo1in** [leftwm/leftwm#313]
Hi,
I wanted to create a theme with a light wallpaper and I'm struggling with the issue that I can't see which `alacritty` is currently focused. It looks like some strange behavior is applied to borders, like some sort of opacity.

Take a look at this 'Dracula Rounded' theme with 2 alacritty instances opened:
![image](https://user-images.githubusercontent.com/34972409/116909399-72e07b80-ac44-11eb-8a31-b54f649e0962.png)

And with wallpaper set to something light:
![image](https://user-images.githubusercontent.com/34972409/116909497-93103a80-ac44-11eb-9b2d-3c83c4912382.png)
The focus remain unchanged.
I've created a wallpaper using light gray from top and dark gray from bottom, here is the result:
![image](https://user-images.githubusercontent.com/34972409/116920563-18025080-ac53-11eb-9a39-4a1a763a9f5f.png)

The strange thing is that most programs are not affected. Here is a gif presenting this:
Top row - affected: `alacritty Thunar Zathura`
Bottom row - not affected:  `gvim pcmanfm gimp` 
![borders](https://user-images.githubusercontent.com/34972409/116915536-70821f80-ac4c-11eb-9c35-7c8d67724842.gif)

Screen of terminal emulators as most of them are affected, the left one is focused (border should be solid green). It looks like only Xterm is handled correctly.
![image](https://user-images.githubusercontent.com/34972409/116913568-f2bd1480-ac49-11eb-9742-9847f0deb5bb.png)

**Comment by VuiMuich** [comment]
I am observing a similar issue quite some time, but did not report yet, as I am not sure if this isn't actually an issue of picom with experimental backends.
To me it looks similar to what a blend mode (maybe 'screen' or 'inverse multiply') would produce. Gonna give this some more triage in the next days..

**Comment by AethanFoot** [comment]
This appears to be an issue with picom (atleast on ibhagwan's branch). It seems to affect the same windows as another bug I have, where if rounded corners are enabled for windows all of the border turns white except the corners.

**Comment by VuiMuich** [comment]
I am currently using jonaburg/picom (wanted to try the animations for window/workspace change) which as far as I can tell is not directly related ibhagwans branch, but also has dual-kawase, so maybe this is, where to look for the origin of this issue.

**Comment by VuiMuich** [comment]
Maybe it is actually related to the WM: https://github.com/herbstluftwm/herbstluftwm/commit/696afd4f1e4bc7860e4478820f6c69bb06220c76

**Comment by AethanFoot** [comment]
Using the link @VuiMuich gave I quickly found this solution:
```
                    let mut bytes = color.to_be_bytes();
                    bytes[4] = 0xff;

                    color = u64::from_be_bytes(bytes);
```
which is added to update_window in xwrap, Ill make a pull request and can you guys test it?

**Comment by Zwo1in** [comment]
I've checked that and it solved the problem
