### ISSUE TITLE
# Error in wiki on Full Screen example

### ISSUE THREAD

**Issue by justin13888** [leftwm/leftwm#316]
The config example in the link below is incorrect.

https://github.com/leftwm/leftwm/wiki/Config#togglefullscreen

Malfunctioning snippet
```
[[keybind]]
command = "ToggleFullScreen"
modifier = ["modkey"]
key = "f"
```

**leftwm-check error message**
```
: Loading configuration . . .
Configuration failed. Reason: LeftError { inner: TomlParse(Error { inner: ErrorInner { kind: Custom, line: Some(279), col: 0, at: Some(4687), message: "unknown variant `ToggleFullScreen`, expected one of `Execute`, `CloseWindow`, `SwapTags`, `SoftReload`, `HardReload`, `GotoTag`, `FloatingToTile`, `MoveWindowUp`, `MoveWindowDown`, `MoveWindowTop`, `FocusNextTag`, `FocusPreviousTag`, `FocusWindowUp`, `FocusWindowDown`, `FocusWorkspaceNext`, `FocusWorkspacePrevious`, `MoveToTag`, `MoveToLastWorkspace`, `MouseMoveWindow`, `NextLayout`, `PreviousLayout`, `SetLayout`, `IncreaseMainWidth`, `DecreaseMainWidth`", key: ["keybind", "command"] } }) }
```

**Comment by justin13888** [comment]
FYI, I'm using version 0.2.7 from [Arch AUR](https://aur.archlinux.org/packages/leftwm/).

**Comment by mautamu** [comment]
I have updated the wiki to note that this command is for versions >=0.2.8 only.

If you would like to be able to use `ToggleFullScreen` sooner, the aur/leftwm-git package (or building from source) will have that functionality.

**Comment by justin13888** [comment]
Thanks for the help! I would love to help contribute to the source code and doc in the future so is there a contribution guide for this project?
