### ISSUE TITLE
Questions about whether some i3 features are in leftwm

### ISSUE THREAD

**Issue by retamaut** [leftwm/leftwm#317]
leftwm seems like an awesome new window manager which I'm giving a good try. However, being an i3 user (no offense), are the following features available:

1. Move/focus window left/right
2. [Binding modes](https://i3wm.org/docs/userguide.html#binding_modes)
3. Disable follow mouse focus (https://i3wm.org/docs/userguide.html#_focus_follows_mouse)
4. Start programs from window manager (exec and exec_always for i3wm)

I love the effort so far but the features I mentioned would be greatly appreciated. Please let me know if the features I mentioned are actually available. I would like to help contribute to the project but there aren't instructions on how others should contribute.

I also found some weird visual glitches which I'm not sure how to describe because it happens out of the ordinary. How do I get debug?

**Comment by mautamu** [comment]
Howdy, 
1. If you mean just switch which window is focused, `FocusWindowUp` and `FocusWindowDown` are what you're looking for (the naming is a bit confusing, but it refers not to the on-page placement but the order). If you want to physically move the focused window left/right/up/down (based again on order), `MoveWindowUp` and `MoveWindowDown` do that. Not all layouts necessarily have the same behavior in regards to these exact motions.
2. This would actually solve another issue that we have, I think I'll fork it into it's own issue.
3. I don't think this will be too hard to implement either, will take a look at this tomorrow.
4. LeftWM allows you to start programs in one of three ways:
    (1.) LeftWM executes everything in ~/.config/autostart/ on the first time it loads
    (2.) LeftWM executes everything in ~/.leftwm/theme/current/up every time it loads or reloads
    (3.) LeftWM allows you to set [Exec](https://github.com/leftwm/leftwm/wiki/Config#execute) keybindings. 
Sorry about being a bit vague, not too familiar with i3 so I'm not sure to which exec refers. I think `exec` in i3 autostarts, so you're likely looking for (1.) 

"Weird visual glitches" could refer to a lot of things. Most likely you see something like the following for a moment or two, or is it something else?
![image](https://user-images.githubusercontent.com/2220164/117222481-1eb6d200-add1-11eb-972b-6ecfc15e066c.png))

**Comment by retamaut** [comment]
Thanks for the good insight.

For 4., either (1) or (2) should work.

How should the community who use leftwm report visual glitches? You'd need the debug log, leftwm version, steps to reproduce, issue, expected behaviour, etc. I think there should be structured bug reports and instructions for reporting issues with all the information needed for devs to fix.

**Comment by retamaut** [comment]
For the visual glitches I was seeing, I couldn't see it after I updated from 0.2.7 to the latest git version. I will report if I see it again.

In case you are still curious what it was, the biggest one I noticed was that sometimes new windows initiated by applications (e.g. open file dialog) couldn't be seen and it causes some weird mouse interactions that make it impossible for you to close the invisible window and you have to kill the opened application.

**Comment by retamaut** [comment]
I will close this issue as my questions were clearly answered.

**Comment by AethanFoot** [comment]
I think we should add the methods of autostarting programs in the wiki. As some videos i have seen on leftwm, they didnt realize that programs in .config/autostart were launched (neither did i till now).
