### ISSUE TITLE
Documentation suggestion: Methods to autostart programs from leftwm

### ISSUE THREAD

**Issue by retamaut** [leftwm/leftwm#320]
As suggested by @AethanFoot, it would be a good idea to add to the documentation on how users could autostart programs from leftwm.

LeftWM allows you to start programs in one of three ways:
    (1.) LeftWM executes everything in ~/.config/autostart/ on the first time it loads
    (2.) LeftWM executes everything in ~/.leftwm/theme/current/up every time it loads or reloads
    (3.) LeftWM allows you to set [Exec](https://github.com/leftwm/leftwm/wiki/Config#execute) keybindings. 

_Originally posted by @mautamu in https://github.com/leftwm/leftwm/issues/317#issuecomment-833116568_

**Comment by VuiMuich** [comment]
@retamaut as you mentioned you would like to start contributing, if you would like actually add this to the wiki you could head over to @mautamu's [wiki fork](https://github.com/mautamu/leftwm_wiki) and open a PR there, he will then manually add this to the upstream wiki
