### ISSUE TITLE
Implement focus state machine

### ISSUE THREAD

**Issue by mautamu** [leftwm/leftwm#326]
Howdy,

As mentioned in #317, it would be nice to tell LeftWM not to update focus on hover (so-called "Sloppy Focus"). The implementations in the literature generally follow one of these patterns:

1. *Sloppy Focus.* Focus follows the mouse, hovering over a window brings it to focus. 
2. *Click-to-Focus.* Focus follows the mouse, but only clicks change focus.
3. *Driven Focus.* Focus disregards the mouse, only keyboard actions drive the focus.
4. *Event Focus.* Focuses when requested by the window/new windows. 

As discussed in #317, I have implemented (3) and (4) in #323. However, it would be nice if we could work to implement (2) and/or rewrite this as a state machine. An example might be similar to below:

```toml
#Config.toml
#default
focus_behaviour = "SloppyFocus"
focus_new_windows = false
```

```rust
enum FocusBehaviour {
    SloppyFocus,
    ClickToFocus,
    DrivenFocus,
}
```

I had tried to add this to #323 but ran into a number of weird issues. The relevant functions are listed here: https://github.com/c00kiemon5ter/monsterwm/issues/12.  When I implemented the suggested changes to xwrap.rs, leftwm either did not pass click events despite that issue, or it froze on click. 

Best,

Mautamu

**Comment by rigoletto-freebsd** [comment]
IDK if I should open a new issue or use this one!

After  #356 the default behavior seems to be working as expected, but once I add `focus_behaviour`  to the configuration file, and doesn't matter what behavior is chosen, the default behavior doesn't change at all and all custom configured key bindings stop working or return to default (when this is the case). ^^

Of course, as expected, `focus_tracks_mouse` doesn't work at all anymore.

Cheers!

**Comment by VuiMuich** [comment]
This very much looks like your config file is broken. 

Can you try `leftwm-check` to see if that's the case?

**Comment by mautamu** [comment]
If you want to double check what leftwm-check is reading, use -v flag. Am a bit behind the curve on updates rn (a bit busy), but in theory it should be listed towards the bottom.

**Comment by rigoletto-freebsd** [comment]
Yeah, you are right there is a config problem but just when I add `focus_manager`.

I think I'm misunderstanding the configuration. I'm using it in this way, e.g.

`focus_manager = Sloppy` or `focus_manager = ClickTo`[1].

Apparently `Driven` and `Event` weren't implemented yet.

[1] both also tried without capital letters.

Thank you.

**Comment by rigoletto-freebsd** [comment]
Ok, got it, I was missing the "" ->`focus_manager = "ClickTo"`. Now the custom keybindings are working again but changing the `focus_manager` doesn't actually changed the behaviour. ^^

Thanks!

**Comment by AethanFoot** [comment]
This is strange as they are all working on my system + event driven is currently handled by focus_new_windows as I can be applied across all modes (https://github.com/leftwm/leftwm/wiki/Config#focus-behaviour).
Thanks
