### ISSUE TITLE
EWW bar compatability

### ISSUE THREAD

**Issue by cadenhenrich** [leftwm/leftwm#327]
When using EWW to draw a bar, windows do not leave a gap at the top to compensate, and EWW just draws over windows. Is there a way to create a space at the top of the workspace for EWW to exist? Using the `margin` in the `theme.toml` file does not work since even using the vector format causes every window to have a large gap at the top, instead of the whole workspace just having the gap.

I've included a screenshot of what happens now.

![image](https://user-images.githubusercontent.com/62853938/117584264-f2a19680-b0d9-11eb-9e0b-4cbc66ffcbe5.png)

**Comment by mautamu** [comment]
It appears that https://github.com/elkowar/eww/issues/153 is what’s necessary to fix this fully, there’s likely a workaround on leftwm’s end, but I’m not sure off the top of my head what that might be. 

Might be useful to implement a configurable gutter at the top if there isn’t one already (on mobile atm to my ability to look into it is a bit restricted, will try to follow up later).

**Comment by VuiMuich** [comment]
A gutter might be a good idea, as this also would allow to have a 'floating' looking bar.
![2021-05-10-082627_2560x1440_scrot](https://user-images.githubusercontent.com/4779365/117615169-a56d0580-b169-11eb-8ba0-c1565d2d5a6d.png)
![2021-05-10-082559_2560x1440_scrot](https://user-images.githubusercontent.com/4779365/117615174-a69e3280-b169-11eb-8584-ad8c7a248d73.png)

**Comment by AethanFoot** [comment]
Another solution would be to give the workspace margins, which would allow you to set the gap for each edge of the workspace. This would also allow for consistent gaps around windows as you could split the gap you want between the window and workspace.

**Comment by cadenhenrich** [comment]
I use eww windows configured using their `<geometry>` tag to float where I want them to, and a custom script which uses `wmctrl` to manage switching the workspaces and updating the variables. Given the reminder about the templates, I might give that a go instead so the output comes directly from leftwm-- only problem would be figuring out how to update those variables only when I switch workspaces.

**Comment by VuiMuich** [comment]
That's a neat trick with the wmctrl script.

I started to look into it yesterday.
So far I managed to modify the `template.liquid` so `leftwm-state` returns basically the correct xml code for the buttons like in the example bar. But I am struggling to make the `<literal content="{{wmstate}}/>` parsable, it always fails at the start of the second button.


> only problem would be figuring out how to update those variables only when I switch workspaces.

if you setup a `script-variable` without an interval it grabs the tail of the script. `leftwm-state` will update a little more often then actually needed (window move, focus change etc.) but I don't think this should be an issue..

**Comment by cadenhenrich** [comment]
Ah, I didn't know about the tail thing with `script-variable`s. I was using `eww update` to update the bar in the script when I changed workspaces, so all the `mod+1-9` keys would trigger the script, which would change the workspace and update the variables. To get which workspace was selected I was parsing the output of `wmctrl` using `sed` and `awk`, which is probably not the best strategy

**Comment by VuiMuich** [comment]
Defninitly have to have a look at wmctl...

For `eww`  basically you can have literals like this
```xml
<def name="wmstate">
      <box orientation="h" class="workspaces" space-evenly="true" halign="center">
        <literal content='{{wmstate}}' />
      </box>
    </def>
```
with a variable:
```xml
  <script-var name="wmstate">~/.config/eww/scripts/getleftwmstate</script-var>
```
My `template.liquid` looks like this:
```liquid
{% assign mine_open = '<button class="ws-button-mine" onclick="wmctrl -s ' %}
{% assign visible_open = '<button class="ws-button-visible" onclick="wmctrl -s ' %}
{% assign busy_open = '<button class="ws-button-busy" onclick="wmctrl -s ' %}
{% assign close = '</button>' %}
{% assign middle = '">' %}
{% assign unoccupied = '<button class="ws-button" onclick="wmctrl -s ' %}

{% for tag in workspace.tags %}
{% if tag.mine %}
{{mine_open}}{{tag.name}}{{middle}}  {{ tag.name }}  {{close}}
{% elsif tag.visible  %}
{{visible_open}}{{tag.name}}{{middle}}  {{ tag.name }}  {{close}}
{% elsif tag.busy  %}
{{busy_open}}{{tag.name}}{{middle}}  {{ tag.name }}  {{close}}
{% else tag.visible  %}
{{unoccupied}}{{tag.name}}{{middle}} {{ "·" }} {{close}}
{% endif %}
{% endfor %}
```
which prints this with `leftwm-state -w 0 -t <path-to>/template.liquid`:
```xml
<button class="ws-button-busy" onclick="wmctrl -s Home">  Home  </button><button class="ws-button-busy" onclick="wmctrl -s Web">  Web  </button><button class="ws-button-mine" onclick="wmctrl -s Code">  Code  </button><button class="ws-button-busy" onclick="wmctrl -s Misc">  Misc  </button><button class="ws-button-busy" onclick="wmctrl -s 5">  5  </button><button class="ws-button-busy" onclick="wmctrl -s 6">  6  </button><button class="ws-button" onclick="wmctrl -s 7"> · </button><button class="ws-button" onclick="wmctrl -s 8"> · </button><button class="ws-button" onclick="wmctrl -s 9"> · </button>
```

**Comment by cadenhenrich** [comment]
Interesting, I'll definitely have to try that out as a method for IPC. Right now I just have a bunch of normal `<var>`s and I use this script to update them every time I switch tabs:
```bash
#!/bin/bash

CURRENT=$(($(wmctrl -d | rg "\*" | awk '{ print $1 }') + 1))
NEXT=$(($1 - 1))

wmctrl -s $NEXT

eww update -c ~/.config/leftwm/themes/current/ w$CURRENT="$CURRENT"
eww update -c ~/.config/leftwm/themes/current/ w$1="{$1}"
```

Keybinds in the `config.toml` are like
```toml
[[keybind]]
command = "Execute"
value = "changetag 1"
modifier = ["modkey"]
key = "1"
```
Though I will probably be switching to the `.liquid` files, much more efficient/expandable!

**Comment by VuiMuich** [comment]
As soon as I get this working I'll open a PR for a `basic_eww` theme.

**Comment by VuiMuich** [comment]
Quick Update, as I got I working just a few minutes ago.
This template.liquid gets parsed correctly by the `literal` tag:
```liquid
{% assign mine_open = '<button class="ws-button-mine" onclick="wmctrl -s ' %}
{% assign visible_open = '<button class="ws-button-visible" onclick="wmctrl -s ' %}
{% assign busy_open = '<button class="ws-button-busy" onclick="wmctrl -s ' %}
{% assign close = '</button>' %}
{% assign middle = '">' %}
{% assign unoccupied = '<button class="ws-button" onclick="wmctrl -s ' %}

{{'<box>'}}
{% for tag in workspace.tags %}
{% if tag.mine %}
{{mine_open}}{{tag.name}}{{middle}} {{ tag.name }} {{close}}
{% elsif tag.visible  %}
{{visible_open}}{{tag.name}}{{middle}} {{ tag.name }} {{close}}
{% elsif tag.busy  %}
{{busy_open}}{{tag.name}}{{middle}} {{ tag.name }} {{close}}
{% else tag.visible  %}
{{unoccupied}}{{tag.name}}{{middle}} {{ "·" }} {{close}}
{% endif %}
{% endfor %}
{{"</box>"}}
```
The trick is, that the liteal onle takes a _single_ element, so putting everything in a `<box>` tag solves this..
Gonna prepare a `basic_eww` template now..

**Comment by cadenhenrich** [comment]
Oh that's great! Given that `eww` is growing rapidly in popularity due to its modularity and extensibility it'll be good to have an example around.

Also, there should probably be more documentation and examples surrounding the `.liquid` files in the wiki, I was definitely very confused about them when I was first starting out with left, and I ended up circumventing them all together, missing out on a lot of great functionality because of it.

**Comment by iSparsh** [comment]
Wow, and to think I scrapped my leftwm config because I didn't know about any of this....

**Comment by VuiMuich** [comment]
Totally agree that `.liquid` parsing is quite the mystery, that's why I already have started to put in the wiki what I have learned s far, and definitely will expand, as this really needs better documentation, and maybe the `template-handler` needs to give some userfriendly error-messages.

@iSparsh tbh I had to ak quite a [bunch of questions](https://github.com/elkowar/eww/discussions/167) back to @elkowar to figure this out, but I didn't want to give up as I had the feeling eww is going to be great and it is :grinning:

**Comment by elkowar** [comment]
Quick reminder that while eww is rapidly growing, its also still rapidly changing. Specifically, a complete rework of the configuration syntax and structure is currently being worked on, so be ready for stuff to break.

On the happy side: no more XML soon

**Comment by VuiMuich** [comment]
Thanks for the heads up, I'm gonna plant a link to your repo and doc-page anyways will add this hint for possible breaking changes along.

**Comment by VuiMuich** [comment]
> On the happy side: no more XML soon

@elkowar by this do you mean there is no changes to xml to expected soon, or do you want to move away from xml for the config soon?
Is this on your dev branch?

**Comment by VuiMuich** [comment]
> ```
> {% assign mine_open = '<button class="ws-button-mine" onclick="wmctrl -s ' %}
> {% assign visible_open = '<button class="ws-button-visible" onclick="wmctrl -s ' %}
> {% assign busy_open = '<button class="ws-button-busy" onclick="wmctrl -s ' %}
> {% assign close = '</button>' %}
> {% assign middle = '">' %}
> {% assign unoccupied = '<button class="ws-button" onclick="wmctrl -s ' %}
> 
> {{'<box>'}}
> {% for tag in workspace.tags %}
> {% if tag.mine %}
> {{mine_open}}{{tag.name}}{{middle}} {{ tag.name }} {{close}}
> {% elsif tag.visible  %}
> {{visible_open}}{{tag.name}}{{middle}} {{ tag.name }} {{close}}
> {% elsif tag.busy  %}
> {{busy_open}}{{tag.name}}{{middle}} {{ tag.name }} {{close}}
> {% else tag.visible  %}
> {{unoccupied}}{{tag.name}}{{middle}} {{ "·" }} {{close}}
> {% endif %}
> {% endfor %}
> {{"</box>"}}
> ```


I noticed a little issue in the above template: in each case the first `{{tag.name}}` actually needs to be a `{{tag.index}}`, otherwise the buttons are off by one.
This is partially fixble in the our external command `SendWorkspaceToTag` with a `try` to convert the args to int and switch to tag index, otherwise switch to tag name.
