### ISSUE TITLE
Question: Executing applications from external program

### ISSUE THREAD

**Issue by HallowDance** [leftwm/leftwm#331]
Greetings,

I've recently started using LeftWM and I enjoy the layout and theming systems very much.

However, I can't seem to find if there is a command akin to i3wm's `i3 exec` for lauching programs that could be used in scripts?

I use newsboat as an RSS reader and I have a couple of macros for downloading pages as well as opening certain stuff in certain browses that I can't seem to replicate.

Thanks in advance.

**Comment by VuiMuich** [comment]
Do you want to use the pendant to `i3 exec` inside your macros? Or do you wnat to keybind the macros?

The latter can be done like [this](![image](https://user-images.githubusercontent.com/4779365/117970816-684f7180-b329-11eb-9adc-cdef8d80b8bd.png)):
```toml
[[keybind]]
command = "Execute"
value = "rofi -show run"
modifier = ["modkey"]
key = "p"
```

If you meant to use the macro to tell the WM to execute something I fail to see the benefit. Why not execute things directly from the macro, like `alacritty -e htop`?

**Comment by VuiMuich** [comment]
Hey I guess this answered your question?
I hope I didn't scare you away, had no intent to do so.

In fact you are very welcome and so was your request,
It would not be to hard to actually mirror the `Execute` command as a external command as well, if it turns out to be of actual use.

**Comment by HallowDance** [comment]
Hello, 

Yes, I replicated the behaviour of `i3 exec` by just redirecting all unneeded output to `/dev/null` in my macro, as to not mess up `newsboat` as well as disowning the process. Sorry for just closing the issue, you haven't scared me away at all!
