### ISSUE TITLE
ERROR: another window manager is already running

### ISSUE THREAD

**Issue by Qwart376** [leftwm/leftwm#332]
I recently installed LeftWM on Arco Linux (AUR git version) and config folder doesn't work at all. I've installed theme and rebooted, but there is nothing but my wallpaper from xcfc. Config files for keyboard also doesn't work (I've changed them multiple times and only old ones react).
When I run leftwm in terminal I get this:

`May 13 13:49:23.257 INFO leftwm-worker booted!
ERROR: another window manager is already running
/home/user/.config/conky/conky-sessionfile: line 1: conky: command not found

** (xfce4-clipman:2362): WARNING **: 13:49:23.409: Unable to register GApplication: An object is already exported for the interface org.gtk.Application at /org/xfce/clipman

(xfce4-clipman:2362): GLib-GIO-CRITICAL **: 13:49:23.409: g_application_get_is_remote: assertion 'application->priv->is_registered' failed

(xfce4-clipman:2362): GLib-WARNING **: 13:49:23.409: g_set_application_name() called multiple times
May 13 13:49:25.284 INFO leftwm-worker booted!
ERROR: another window manager is already running

** (xfce4-clipman:2362): WARNING **: 13:50:23.688: Status Icon is not embedded

(xfce4-clipman:2362): Gtk-CRITICAL **: 13:50:23.693: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed

`

**Comment by VuiMuich** [comment]
Welcome fellow adventurer,

- have you tried to use the default keybinding `Super+Shift+Enter` to launch a terminal?
- Can you launch a terminal from try with `DISPLAY=:0 xfce-term` (or any other terminal)
- What is the output of `leftwm-check` (either from tty or terminal emulator)?
- if there is no `~/.config/leftwm` folder, is it possible you have restrictive write permissions for `~/.config`

The output of `leftwm` on the `tty` is expected and normal if there is a running instance.

**Comment by Qwart376** [comment]
> Welcome fellow adventurer,
> 
> * have you tried to use the default keybinding `Super+Shift+Enter` to launch a terminal?
> * Can you launch a terminal from try with `DISPLAY=:0 xfce-term` (or any other terminal)
> * What is the output of `leftwm-check` (either from tty or terminal emulator)?
> * if there is no `~/.config/leftwm` folder, is it possible you have restrictive write permissions for `~/.config`
> 
> The output of `leftwm` on the `tty` is expected and normal if there is a running instance.

All default keybindings are working, but nothing changes when I edit the config.toml in /.config/leftwm/
```
Output of leftwm-checkl:
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
```

Something is wrong with Soothe theme. I installed the Forest and everything started working

**Comment by VuiMuich** [comment]
Soothe is a bit odd, as it has a `themes` subfolder as it comes along with some dotfiles for e.g. conky.
The softlink for `~/.config/leftwm/current` needs to point to this subfolder.
I use a heavy modified version of the soothe theme myself, I can tell it works but not as out of the box as other themes.

I have not tested how theme installation with `leftwm-theme` works but if this doesn't go smooth, maybe we need to find a way how it can handle obscure structures of themes.
