### ISSUE TITLE
How to add themes to community repo?

### ISSUE THREAD

**Issue by Qwart376** [leftwm/leftwm#334]
I'm rather new to github and there is no guide besides requiring the up and down script

**Comment by AethanFoot** [comment]
Heres a guide I made a bit ago, https://github.com/AethanFoot/leftwm-community-themes/wiki/Sharing, let know if you have any other questions.
Thanks

**Comment by Qwart376** [comment]
> Heres a guide I made a bit ago, https://github.com/AethanFoot/leftwm-community-themes/wiki/Sharing, let know if you have any other questions.
> Thanks

Many thanks
