### ISSUE TITLE
Windows orverlap polybar if there are more than one bar.

### ISSUE THREAD

**Issue by rigoletto-freebsd** [leftwm/leftwm#338]
Hello,

I'm trying to use two Polybar bars but once LeftWM is reloaded the bar initiated first get overlapped by every window.

Since this is my first LeftWM configuration I am re-using the Coffee theme `up` hence I'm starting Polybar with this:

```
if [ -x "$(command -v polybar)" ]; then
  pkill polybar
  monitors="$(polybar -m | sed s/:.*// | tac)"
  while read -r display; do
    MONITOR=$display polybar -c "$SCRIPTPATH/polybar.config" top &> /dev/null &
    MONITOR=$display polybar -c "$SCRIPTPATH/polybar.config" bottom &> /dev/null &
  done <<< "$monitors"
  exit 0
fi
```
I tried some variants, but always get the first initiated bar overlapped.

FreeBSD 13.0

![screenshot_1621190444](https://user-images.githubusercontent.com/43918328/118408754-66ade280-b676-11eb-9b71-28e93ca3dd19.png)

**Comment by rigoletto-freebsd** [comment]
A minor update. Starting Polybar directly from the command line works fine (no error) first, but when starting the second:

`error: Failed to restack bar window`

**Comment by VuiMuich** [comment]
This PR #329 has a gutter config option.
It might get merged soon.
If you want to try this bevore merge just know you need to add
```toml
[[gutter]]
side = "Top"
value = 24 #or what ever your bar height is
```

But I think we should try to get a better handling of complex bar setups, as this is a common source of issues.

**Comment by AethanFoot** [comment]
Can you check to see if the PR #339 fixes the issue?

**Comment by rigoletto-freebsd** [comment]
> Can you check to see if the PR #339 fixes the issue?

I will will just be able to try it tonight. Btw, I commited the LeftWM FreeBSD port to the tree yesterday.

Thanks!

**Comment by rigoletto-freebsd** [comment]
Yes, fixed nicely! Thanks!
