### ISSUE TITLE
Possible memory leak on pkill leftwm-worker

### ISSUE THREAD

**Issue by nathanleighsays** [leftwm/leftwm#34]
When I start a clean leftwm session, my memory footprint is around 500MB (running kubuntu). After several restarts of leftwm-worker during a theme developing session, that footprint inflates up to 3GB and closing all active programs doesn't decrease back down. Running htop shows considerably less memory in actual use than polybar or conky shows. This problem doesn't appear in i3 or Plasma sessions. It appears to be impacted most by heavy Chrome usage during restarts, but I haven't been able to determine if that's because it primarily affects Chrome or because Chrome just generally uses a lot of RAM and is the worst offender.

**Comment by lex148** [comment]
I want to look at this ASAP. Would you please get me a little more information. leftwm has three executables I would like to know which one is the problem. 

If you have htop installed you should be able to sort by memory usage. (F6, select PERCENT_MEM)

Do you see one of these guys at the top of the list? and how much memory is it using?
leftwm
leftwm-state
leftwm-worker
xorg

**Comment by nathanleighsays** [comment]
It looks like this was actually a problem on Chrome's end. Updating to the newest version appears to have solved it!

**Comment by nathanleighsays** [comment]
FWIW, leftwm, leftwm-state and leftwm-worker are pretty far down on the list. With Chrome closed, xorg is close to the top below MPD and Terminator.
