### ISSUE TITLE
No window focused when `focus_tracks_mouse = false`.

### ISSUE THREAD

**Issue by rigoletto-freebsd** [leftwm/leftwm#342]
Hello,

when `focus_tracks_mouse` is set to `false` no window is focused when they are started on a empty tag, unless some other action is taken like switching to another tag and back.

Thanks!

![screenshot_1621296675](https://user-images.githubusercontent.com/43918328/118571596-f1bdd400-b76d-11eb-8c13-c89a0ae659a0.png)

**Comment by VuiMuich** [comment]
I can have a look into this, together with a look at a possible solution for #328 later this week, but if anyone has a quicker fix feel free to push.

**Comment by AethanFoot** [comment]
Can you check whether #345 completely fixes the issue, it fixes the issue when changing focus between workspaces, but are there any other situations this occurs?

**Comment by AethanFoot** [comment]
I will add, that when focusing a tag the window under the cursor is focused (which doesn't feel right, we should probably focus the first window on the workspace that is displaying the tag). Also when both focus_tracks_mouse and focus_new_windows are both deactivated it is awkward to give a new window opened on an empty tag focus (should we focus a new window only when it is opened on an empty tag). Tagging #323.

**Comment by VuiMuich** [comment]
> should we focus a new window only when it is opened on an empty tag

👍

**Comment by rigoletto-freebsd** [comment]
I can't build it in here with the referenced patch, it fails with:

```
error: expected one of `.`, `;`, `?`, `}`, or an operator, found `Some`
   --> src/handlers/command_handler.rs:365:5
    |
363 |     Some(true)
    |               - expected one of `.`, `;`, `?`, `}`, or an operator
364 |     // This is required for those with focus_tracks_mouse = false
365 |     Some(focus_handler::focus_window(manager, &window.handle))
    |     ^^^^ unexpected token

error: aborting due to previous error

error: could not compile `leftwm`
```

**Comment by mautamu** [comment]
Uh try going to src/handlers/command_handler.rs line 363 and deleting Some(true)

**Comment by AethanFoot** [comment]
Thats strange as it is removed in my branch and the PR, maybe git didn't work well with merging.

**Comment by rigoletto-freebsd** [comment]
> Thats strange as it is removed in my branch and the PR, maybe git didn't work well with merging.

This is me to be blamed in here!
So, unfortunately the change didn't fixed the issue.

Thank you!

**Comment by AethanFoot** [comment]
@rigoletto-freebsd Just to let you know I will still be working on this.

**Comment by AethanFoot** [comment]
@rigoletto-freebsd, could you check to see if these changes help your situation: https://github.com/AethanFoot/leftwm/tree/fix_342.
Thanks

**Comment by rigoletto-freebsd** [comment]
@AethanFoot, unfortunately not but I think there is a small improvement, the supposedly focused terminal is functional now[1]; however Firefox for instance is not.

Thanks!

[1] but no borders or whatsoever.

**Comment by AethanFoot** [comment]
@rigoletto-freebsd would it be possible for you to send a clip to see if it gives a better idea of the issue. @mautamu do you have any other ideas of what to do?

**Comment by rigoletto-freebsd** [comment]
@AethanFoot, sure but I will just be able to do it at night; however I noticed the same behavior with `focus_tracks_mouse = true` albeit happening more discreetly.

On an empty tag/workspace[1], move the mouse pointer away (like on top of the bar), and open some windows. All windows will not be focused and not functional (can't write on anything) but once the mouse pointer is placed over any window they are proper focused - ever if the pointer is put away again.

I also noticed it stay focused at the last focused window of the last tag/workspace.  E.g. if the last focused window was a terminal and you try to write something on the new focused tag/workspace (with the window focus issue), everything you type will be at that terminal on the previous focused tag/workspace.

Apparently the focus doesn't automatically move to the newly focused tag/workspace.

[1] there should have no window opened after switching to this tag/workspace. It should be fully empty before switching to it.

**Comment by VuiMuich** [comment]
@rigoletto-freebsd while you already seem to be in testing-mode and this fix has a slight chance to be related (only a very slight chance as I actually think the bug might be in monocle-specific code), would you mind to try if you can or cannot reproduce the issue of #328 in the latest comment.

**Comment by rigoletto-freebsd** [comment]
@VuiMuich, no I can't reproduce it in here, but when I move some window to another tag it "take" the focus together and no window is focused on the present tag (unless I have the pointer on some window). Btw, I'm running the last commit.

**Comment by VuiMuich** [comment]
ok, thanks for testing!
Gonna try the latest commit of #350 then and see it's gone for me as well, or if I maybe have created some weird configurable corner-case.

**Comment by AethanFoot** [comment]
@rigoletto-freebsd Do you also have focus_new_windows disabled aswell? If not then the mouse and focus should move to a new window, if you do I think i know a possible solution.

**Comment by rigoletto-freebsd** [comment]
@AethanFoot yes, `focus_new_windows = false`, and I didn't had time to make the video yet. I will try to do it today, sorry about that.

Also, side question, is IA-32 supported? I received e-mails from the FreeBSD build system due to LeftWM failing to build on IA-32 and IDK if I should set it as non-supported or if I should open a bug report. ^^

Thanks!

**Comment by AethanFoot** [comment]
@rigoletto-freebsd Thats okay I know what the problem is, what ill do is make it so when a window is opened on a empty tag it will grab focus when focus_new_windows is disabled, does this sound like this suits this workflow?
With the 32 bit freebsd support the only limitation I would think is rust, as host tools (rustc, cargo, etc) arent supported for 32 bit freebsd (check this site for more detail https://doc.rust-lang.org/nightly/rustc/platform-support.html). @mautamu @lex148 are there any other reasons you guys can think of?

**Comment by rigoletto-freebsd** [comment]
@AethanFoot ok then, great!

This is the log from the cluster, in case you want to have a look:
[leftwm-0.2.7.37.log](https://github.com/leftwm/leftwm/files/6523848/leftwm-0.2.7.37.log)

Thanks!

**Comment by AethanFoot** [comment]
@rigoletto-freebsd Hopefully #350 now fixes your situation.
Thanks.

**Comment by rigoletto-freebsd** [comment]
@AethanFoot I think you fixed the thing, yeah! The only minor thing I would comment, but it may not be in the scope of this issue (or even actually be in this way by design), is when a window is moved to another tag the current tag have no window focused anymore.

Thanks you!

**Comment by AethanFoot** [comment]
@rigoletto-freebsd The last commit should have fixed this.
Thanks.

**Comment by rigoletto-freebsd** [comment]
@AethanFoot yes, that fixed thanks!

Would you mind of one more detail that become apparent now? If the focus is on some on window that is not on Top and you switch to another tag, when you switch back the focus was moved to the window on Top.

Thank you!

**Comment by AethanFoot** [comment]
@rigoletto-freebsd what I'll do with this is add it as a TODO, tomorrow I am going to open some issues which will cover some these quality of life improvements around these focus options.

**Comment by rigoletto-freebsd** [comment]
@AethanFoot, many thanks for your work!
