### ISSUE TITLE
Rename `.liquid` documentation 

### ISSUE THREAD

**Issue by mautamu** [leftwm/leftwm#344]
Howdy,

We ought to add another wiki page dedicated to .liquid files. 

Quoting 337, but this has been asked about a few times recently.

Best,
Mautamu
___

This is so good. Only reason I switched away from leftwm because I couldn't handle the liquid files and eww. Thanks for this! One more question though, is there any plan for more `.liquid` documentation (not exactly in this PR)

_Originally posted by @iSparsh in https://github.com/leftwm/leftwm/issues/337#issuecomment-842931303_

**Comment by VuiMuich** [comment]
Agree, and along with that, I think the hardest part in use with `.liquid` is figuring out, what the parser actually likes to process.
So it mostly would come down to document the parser/template_handler more obvious.

**Comment by AethanFoot** [comment]
Ye I would move the info in customizing themes to a dedicated .liquid page, and make the customizing themes page cover the details of theme.toml and the other smaller files. I have also just added a custom sidebar to the wiki to make navigation a bit easier and cleaner.

**Comment by VuiMuich** [comment]
Actually we could just rename it.
Initially I thought I would put in more theming documentation in this later and then decided to postpone this till our 'config breaking' changes are done, But as of now it just makes sense to have a dedicated `.liquid` page.

**Comment by VuiMuich** [comment]
I just opened a [PR in mautamu's wiki fork](https://github.com/mautamu/leftwm_wiki/pull/5), you are all wellcome to extensivley review this.

Also I'd like to invite @cadenhenrich and @iSparsh to test if the `eww` related part works for them as well.

**Comment by VuiMuich** [comment]
I recently updated the Wiki-Page, if the update is satisfactory, I believe we could close this issue.

**Comment by mautamu** [comment]
Good work @VuiMuich!
