### ISSUE TITLE
Build fail: not a git repository (leftwm_check.rs).

### ISSUE THREAD

**Issue by rigoletto-freebsd** [leftwm/leftwm#346]
Hello, it's me again!

When building LefWM in a live system (with git installed) it does build but doesn't build `leftwm-command`; however while building it on a clean/isolated envirolment[1] it fail to build with:

```
error: git describe failed with status 128: fatal: not a git repository (or any parent up to mount point /)
  --> src/bin/leftwm-check.rs:40:9
   |
40 |         git_version::git_version!()
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

error: could not compile `leftwm`
```
Full build log: [leftwm-0.2.7.37.log](https://github.com/leftwm/leftwm/files/6503407/leftwm-0.2.7.37.log)

Apparently `leftwm_check.rs` is running git on a non-git repository making it to fail. Currently we have the port building normally while faking the presence of the `git` binary.

[1] Poudriere, FreeBSD building system.

FreeBSD 13.0-RELEASE.

Thank you!

**Comment by mautamu** [comment]
The fix is to add a fallback to that macro. Will look into it a bit later.
