### ISSUE TITLE
Wine popups render incorrectly

### ISSUE THREAD

**Issue by nathanleighsays** [leftwm/leftwm#35]
Popup windows in programs running under Wine frequently appear as the wrong size. The most common instance is the height being too short and the width far too wide, often resulting in cut off buttons at the bottom of the popup and a large amount of black space to the right of the window. This issue has impacted every program I've run under Wine in LeftWM to varying degrees.

**Comment by mautamu** [comment]
Similar issue with Thunderbird's "account settings":
![curious-thunderbird-behaviour](https://user-images.githubusercontent.com/2220164/89816069-7575d080-db0b-11ea-8bad-26d2f4e58b10.png)

I think #96 mathias234@7ecb1d2 might be a solution? Will try to test it our later.

**Comment by hertg** [comment]
I don't think that's an issue anymore.
Please re-open if I'm wrong.
