### ISSUE TITLE
Not able to get window swallowing working

### ISSUE THREAD

**Issue by steveonlinux** [leftwm/leftwm#351]
Has anyone been able to work in swallowing functionality into this wm? I've tried using devour and other wm agnostic solutions that seem to be broken here.

**Comment by VuiMuich** [comment]
I am not sure if this wouldn't need at least #165 to be implemented.

**Comment by AethanFoot** [comment]
This is because devour uses XUnmapWindow which is not a send_event, and currently we don't handle these events. 
Heres a fix to devour using XWithdrawWindow (which is a send_event):
```C
/*
 * devour
 * X11 window swallower
 */

#include <X11/Xlib.h>
#include <stdlib.h>
#include <string.h>

#define UNSAFE_CHARS "`\"'()[]& "

void run_command(char **argv) {
  char arg_char;
  char *arg;
  char cmd[1024] = {0};

  while ((arg = *++argv)) {
    while ((arg_char = *arg++)) {
      if (strchr(UNSAFE_CHARS, arg_char))
        strcat(cmd, "\\");
      strncat(cmd, &arg_char, 1);
    }
    strcat(cmd, " ");
  }
  system(cmd);
}

int main(int argc, char **argv) {
  int rev;
  Window win;
  Display *dis = XOpenDisplay(0);
  int snum = DefaultScreen(dis);

  XGetInputFocus(dis, &win, &rev);
  XWithdrawWindow(dis, win, snum);
  XFlush(dis);
  run_command(argv);
  XMapWindow(dis, win);
  XCloseDisplay(dis);

  (void)argc;
  return 0;
}
```

**Comment by steveonlinux** [comment]
> This is because devour uses XUnmapWindow which is not a send_event, and currently we don't handle these events.
> Heres a fix to devour using XWithdrawWindow (which is a send_event):
> 
> ```c
> /*
>  * devour
>  * X11 window swallower
>  */
> 
> #include <X11/Xlib.h>
> #include <stdlib.h>
> #include <string.h>
> 
> #define UNSAFE_CHARS "`\"'()[]& "
> 
> void run_command(char **argv) {
>   char arg_char;
>   char *arg;
>   char cmd[1024] = {0};
> 
>   while ((arg = *++argv)) {
>     while ((arg_char = *arg++)) {
>       if (strchr(UNSAFE_CHARS, arg_char))
>         strcat(cmd, "\\");
>       strncat(cmd, &arg_char, 1);
>     }
>     strcat(cmd, " ");
>   }
>   system(cmd);
> }
> 
> int main(int argc, char **argv) {
>   int rev;
>   Window win;
>   Display *dis = XOpenDisplay(0);
>   int snum = DefaultScreen(dis);
> 
>   XGetInputFocus(dis, &win, &rev);
>   XWithdrawWindow(dis, win, snum);
>   XFlush(dis);
>   run_command(argv);
>   XMapWindow(dis, win);
>   XCloseDisplay(dis);
> 
>   (void)argc;
>   return 0;
> }
> ```

Oh wow, that's a relatively simple and interesting fix. Thanks!

**Comment by VuiMuich** [comment]
This is nice! Thanks @AethanFoot

For future reference here is the diff to the original devour code:
```diff
diff --git a/devour.c b/devour.c
index 39d7907..5385799 100644
--- a/devour.c
+++ b/devour.c
@@ -29,9 +29,10 @@ int main(int argc, char **argv) {
   int rev;
   Window win;
   Display *dis = XOpenDisplay(0);
+  int snum = DefaultScreen(dis);

   XGetInputFocus(dis, &win, &rev);
-  XUnmapWindow(dis, win);
+  XWithdrawWindow(dis, win, snum);
   XFlush(dis);
   run_command(argv);
   XMapWindow(dis, win);
```
