### ISSUE TITLE
Improvement: Add arrays to keybinds und config

### ISSUE THREAD

**Issue by VuiMuich** [leftwm/leftwm#355]
Probably this needs to go along #292, but it might be so helpful we actually want to implement this early, therefore I dedicate this it's own issue.

The Problem:
Keybinds for `GoToTag` and `MoveToTag` are quite a large section in the config and are annoying to maintain/configure.

The Proposal:
We could allow the value field and/or the 'keyboard-key' field to also take an array of strings. 
The parser would then have to differentiate the following possibilities:
- both hold a single string: this is our status quo
- both hold an array of matching length: parser assigns keybinds by ordinal position 
- `value` has a single string, `key` has an array of strings: bind multiple keybinds to the Same command (this might make arrays I the `modifyer` field necessary as well)
- `value` has any array, `key` has a single string: this would cycle through to rebound this key along with executing the current command
- arrays of mismatched length: this should probably error

The benefits (non exhaustive list):
- change the modifier key for `MoveToTag`
- Set up keybinds to `MoveToTag` and `GoToTag` in a single key combo
- add more tag features like #354 without bloating `config.toml`

**Comment by rigoletto-freebsd** [comment]
You may also want to see how bspwm (in practice [sxhkd](https://github.com/baskerville/sxhkd)) does it, in fact quite compact.

**Comment by VuiMuich** [comment]
I actually had a brief look at the archcraft live iso a few weeks ago and really liked how sxhkd works.
I took loose inspiration by it, what I remembered of the top of my head.

**Comment by Syudagye** [comment]
I check, it just doesn't parse the keybindings part at all and falls back to the default keys.

Here is the `leftwm-check -v` output both cases:
[leftwm-check-current-config.txt](https://github.com/leftwm/leftwm/files/7375926/leftwm-check-current-config.txt)
[leftwm-check-shortened-config.txt](https://github.com/leftwm/leftwm/files/7375927/leftwm-check-shortened-config.txt)

**Comment by Syudagye** [comment]
After testing it, it works correctly apparently, so i don't know what is causing it to fallback to default keys.

**Comment by VuiMuich** [comment]
Great find!

Now the questions is: how do we get serde to serialize this format from our default config?

**Comment by VuiMuich** [comment]
With `lefthk` this will be obsolete.
