### ISSUE TITLE
Change direction of layout

### ISSUE THREAD

**Issue by geri1701** [leftwm/leftwm#357]
How is it possible, e.g. with the fibonacci layout, to have the main window instead of the left on the right side?

**Comment by AethanFoot** [comment]
Currently we have https://github.com/leftwm/leftwm/wiki/Config#rotatetag, which will flip the layout if supported. With fibonacci layout you can flip in all direction. However this isn't permanent past a reload, it will probably be added with greater window and workspace customisation with #292.
Thanks.

**Comment by geri1701** [comment]
Thank you, that's exactly what I was missing.
