### ISSUE TITLE
[Feature] New Windows as Master

### ISSUE THREAD

**Issue by jooooscha** [leftwm/leftwm#358]
Is there a way to make a new window automatically the master?
If I missed something, please point me there :)

Thanks :)

**Comment by AethanFoot** [comment]
Currently not, however this would easy enough to implement a switch for this.
For future reference I would say this could be an option per tag/layout once greater configuration is implemented.

**Comment by VuiMuich** [comment]
> For future reference I would say this could be an option per tag/layout once greater configuration is implemented.

Agreed, having this option at least configurable per layout is quite important as there probably might be very different opinions on the preferred behavior.

**Comment by nblxxx** [comment]
Just installed Leftwm and love it already! but this is the only confusing thing about it for me, coming from xmonad, where new windows spawn in the previously focused tile, so if you're in master they go there (so not always, like requested by @jooooscha here)

**Comment by kid** [comment]
I think one feature that would be nice would be the option to insert the window relative to the current window, and not just the top/bottom of the stack

**Comment by VuiMuich** [comment]
These are some great ideas.
So basically the the switch could be a `new_window_mode` with options `Top`, `Bottom`, `InsertBeforeCurrent`, `InsertAfterCurrent` and `Replace`.

**Comment by nblxxx** [comment]
That would be perfect!

> So basically the the switch could be a `new_window_mode` with options `Top`, `Bottom`, `InsertBeforeCurrent`, `InsertAfterCurrent` and `Replace`.

**Comment by kid** [comment]
Not sure what would be the behavior of `Replace` though, what did you have in mind @VuiMuich ?

**Comment by VuiMuich** [comment]
I guess in most scenarios it would end up being the same as `InsertBeforeCurrent`. I thought there might be a corner case where they might be a bit different, but not sure anymore. :shrug:

**Comment by VuiMuich** [comment]
Implemented in #710
