### ISSUE TITLE
Can't set the gap to the screen border to 0

### ISSUE THREAD

**Issue by MarkuBu** [leftwm/leftwm#359]
Hi,
I have an old Netbook with 1024x600px screen size and I want to be able to use as much as possible, but even if I set the margin to 0 I still have a gap between the border of a window and the screen.

How can I minimize this gap?

Regards
Markus

![2021-05-26-201802_1024x600_scrot](https://user-images.githubusercontent.com/16163058/119711346-b99a4d80-be5f-11eb-90b0-65d87ff9b560.png)

**Comment by AethanFoot** [comment]
May best guess is there is still a workspace_margin (we need to improve this area of the wiki). Setting ```workspace_margin = 0``` should disable this.

**Comment by MarkuBu** [comment]
Perfect, thanks

**Comment by paulhersch** [comment]
Please add the key somewhere in the docs or in one of the example configs, some people think this is still an issue because it is not documented
