### ISSUE TITLE
[Feature] Global up script

### ISSUE THREAD

**Issue by mfdorst** [leftwm/leftwm#362]
Currently the only way to do setup or run custom programs in the background is to use the `~/.config/leftwm/theme/current/up` script. This is really inconvenient if you want to be able to switch between themes - you have to edit each theme's `up` script to do what you need.
I propose a global up script (`~/.config/leftwm/up`) which can remain the same while you switch between themes.

**Comment by mautamu** [comment]
Tagging #292 as this would need to be considered therein.
