### ISSUE TITLE
leftwm.desktop doesn't use dbus-launch

### ISSUE THREAD

**Issue by paulhersch** [leftwm/leftwm#364]
Hello,
I have just looked into the desktop file provided with the leftwm install via the leftwm-git package, and there it executes with just `leftwm` as command. Shouldn't it be `dbus-launch leftwm` instead?

**Comment by ReneganRonin** [comment]
nope

**Comment by paulhersch** [comment]
Ah didn't know that display managers would use the dbus, thanks for the information
