### ISSUE TITLE
lxsession started via "up" script loses track of leftwm

### ISSUE THREAD

**Issue by paulhersch** [leftwm/leftwm#365]
**Describe the bug**
Started lxsession in my up script for Polkit and GTK theming. Around 2 seconds after session start I don't have my theming anymore and also Polkit isn't working but lxsession ist still running (confirmed via htop).Oddly, this only happens on initial startup, when i HardRestart via a keybind this problem is gone.

**To Reproduce**
1. put this line in the up script of your theme `lxsession -s leftwm -e leftwm -a &` (delete the "&" if at the end)
2. start via lightdm (i use it, don't know if that happens with other login managers too) (also i changed the exec command in the desktop file to `dbus-launch leftwm`
3. optionally set a theme on running lxsession so you see the change quicker
4. watch lxsession decouple from leftwm

**Expected behavior**
lxsession still manages my leftwm session

**Screenshots**

**Environment:**
 - OS/Distro:  Manjaro
 - Output of `leftwm-check`
 `leftwm-check
:: LeftWM version: 0.2.8
:: LeftWM git hash: 545af63
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK`

**Additional context**
htop tree mode shows that lxsession was really started from the start script after the HardRestart with child processes, while there was only one on initial startup.

**Comment by VuiMuich** [comment]
welcome and thanks for sticking with the Bug-report template!

I am not very familiar with `lxsessions` but just to be clear th `up` script in step 1. is not referring to the one in `~/.config/leftwm/theme/current` right? But it is the one of `lxsessions` itself, right?

**Comment by paulhersch** [comment]
no the `up` script in the `~/.config/leftwm/theme/current` folder

**Comment by paulhersch** [comment]
Do you have any recommendations for session management with leftwm tho? maybe something else works better for now and I sure can spare the disk space

**Comment by VuiMuich** [comment]
I am using `lightdm` wich if I remember this correctly, also handles the session-management.

**Comment by paulhersch** [comment]
So session start via lightdm? Or lightdm session?

**Comment by VuiMuich** [comment]
I'm not sure what you exactly mean with 'Lightdm session'. 

On my system I started with Manjaro XFCE edition, which has Lightdm as default DM. From there I switched to i3 then xmonad and finally to leftwm, but always kept Lightdm.
Lightdm starts the X-Server, and via the the greeter (I believe in the background using loginctl) handles the user-Sessions. 
But as stated bevor I have shallow expertise in session management.

**Comment by AethanFoot** [comment]
How are you using lxsession? If you are using for its "complete" use, you need to change the Exec line in the desktop file with ```exec /usr/bin/lxsession...``` with the options you showed before. They have a good example in their readme https://github.com/lxde/lxsession. If you are not really using it as a session manager and to autostart programs,  you can just start without options and use it or remove it and use something like mate polkit to manage privilege elevation (which will save some memory usage). Hope this is clear, currently on mobile.
Thanks.

**Comment by paulhersch** [comment]
Well I was using it before without the options, but it still crashed, thats why i set the options originally
I also need lxsession for my GTK themes, starting polkit in the background works with the authentification
Tried putting a desktop file in my `.config/autostart` folder and it still crashes (but doesn't give me a blackscreen for now at least)

**Comment by paulhersch** [comment]
lxsession is still running when i start it via autostart but it just doesn't do its job. So its running and polkit is also running but I can't make use of it smh.
![grafik](https://user-images.githubusercontent.com/74120050/120163273-a4277980-c1f9-11eb-9c9f-4acf3c37f0dd.png)

**Comment by AethanFoot** [comment]
> you need to change the Exec line in the desktop file (*leftwms desktop file) with `exec /usr/bin/lxsession...` with the options you showed before. They have a good example in their readme https://github.com/lxde/lxsession. 

Have tried this, as for lxsession to work correctly it should be starting leftwm itself, rather than leftwm starting it. If that makes sense.
Thanks

**Comment by paulhersch** [comment]
Can you please provide your .desktop files from xsession and lxsession? I have put in the lxsession line in the Xsession folders leftwm.desktop and then put in leftwm as Window manager in the lxsession config for leftwm, but it doesn't start leftwm

**Comment by paulhersch** [comment]
Ok Session related problems are solved by this, still have problems with the themes but that's another problem and probably not leftwm related

**Comment by AethanFoot** [comment]
If you need help with the themes we are always happy to help.
Thanks

**Comment by VuiMuich** [comment]
Thats great, now starts the adventurous fun.
If you want some help with your theme issues we are glad to help..

**Comment by paulhersch** [comment]
Well i solved the theming issues by just deleting some scripts and .desktop files in the autostart folder, one was resetting the xsettings at said timepoints so i got rid of it and its friends and now everything inside leftwm works
