### ISSUE TITLE
Single window in full-screen leaves tag "empty"

### ISSUE THREAD

**Issue by VuiMuich** [leftwm/leftwm#366]
**Describe the bug**
When a tag holds a single window and this window is put in full-screen it renders the tag (in `leftwm-state`) as empty (or `"busy":false`)

**To Reproduce**
It is easy to observe in any status bar but thie following command show this also very clear:
```shell
$ leftwm-state -w 0 -q -s '{% for tag in workspace.tags %}{{ tag.index}}: busy:{{ tag.busy }} {% endfor %}'
```
Output:
```shell
0: busy:true 1: busy:false 2: busy:false 3: busy:false 4: busy:false 5: busy:false 6: busy:false 7: busy:false 8: busy:false
```
**Expected behavior**
As the window is still just displayed on a specific tag it should keep this tag  as `"busy":true`

**Comment by lex148** [comment]
Awesome work, but I did find a little weirdness in this PR when going in and out of fullscreen mode. 

If you `Mod+w` to swap windows around and then toggle fullscreen mode, The bar on the workspace that originally had the window is hidden not the workspace that the window is currently in.
