### ISSUE TITLE
leftwm started to consume too many resources after the last time I updated it

### ISSUE THREAD

**Issue by 0al3x** [leftwm/leftwm#371]
I have been using leftwm for just over a year. I update it every 2-3 months, and the last time I updated `leftwm-worker` it used around 90% from one thread, and Xorg uses around 60% from another thread (before updating leftwm that was not happening), it is also occupying enough memory, after a few hours of use the RAM gets full and slow and when reloaded with `mod + shift + r` the ram is cleaned but the processor is still too busy

I'm not sure what exact version happened because I update every 2 or 3 months but before updating this last time everything worked very well

**Environment:**
 - OS/Archlinux

**Additional context**
for update i use `git pull` and `cargo build --release --features=journald`

**Comment by VuiMuich** [comment]
I am on an up-to-date Manjaro, with leftwm built from the latest git-version (though built without the `--release` flag).
For me the Ram use is: 2M `leftwm`, 8M `leftwm-worker` and each instance of `leftwm-state` has 9m, CPU-Usage is insignificant, with `leftwm-worker` peaking at 2% of the core its running on. 

Can you try if this happens in a 'debug' build as well? 
Any chances it is actually a child-process, like a theme related program who causes this? Since a soft reload (wich is default bound o `mod+ shift + r`) kills the processes launched by the theme, this would explain why the memory gets cleared.

**Comment by AethanFoot** [comment]
Other than the theme it could be something that this run and killed by the up and down scripts, e.g.  polybar. If you have time can you gather some numbers of the usage of programs run in the up script and/or killed by the down (including leftwm), these number through htop or using the ps command and greping the relevant programs (would give an example but currently on mobile).
Will also do some testing later.
Thanks.

**Comment by MarkuBu** [comment]
This happens to me with Xmobar. When I use polybar everything in fine

**Comment by AethanFoot** [comment]
Hmmmm strange, I am not too familiar with xmobar to be too helpful sorry. Will keep searching and if I find anything I will be sure to add it here.
Thanks.

**Comment by VuiMuich** [comment]
> This happens to me with Xmobar. When I use polybar everything in fine

possibly stupid question, but is it possible, that xmobar might be broken? When I was using xmonad with xmobar I regularly screwd up to recompile them after ther haskell packages got an update and was puzzled why everything broke.
Also do you happen to have another WM installed you could use to check if xmobar is running fine there?

**Comment by 0al3x** [comment]
I just ran the theme's `down` script, and in effect` leftwm-worker` goes from 90% of the thread to about 1.6% and Xorg still goes from about 60% to about 0.6% - about 1%.

I guess the problem must be in xmobar.

**Comment by 0al3x** [comment]
I uninstalled xmobar and reload leftwm, and apart from the fact that I don't have a status bar everything is fine, then I think that if the problem is in xmobar

**Comment by mautamu** [comment]
I wonder what the issue is. I wonder if mayhaps xmobar is trying to cache leftwm-state output or something? 

Possibly related (?), depending on how often you update Xmobar: https://github.com/jaor/xmobar/pull/423
