### ISSUE TITLE
bigger workspace has height of a smaller one

### ISSUE THREAD

**Issue by Oreolek** [leftwm/leftwm#374]
I have two monitors: one 1920x1080, another 1024x768. LeftWM can properly find them but limits all windows on the bigger one to 768px height. There's a lot of unusable vertical space.

```
OS: ubuntu 20.04

❯ leftwm-check
:: LeftWM version: 0.2.8
:: LeftWM git hash: 1694b6a
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK 

[[workspaces]]
x = 0
y = 0
width = 1920
height = 1080

[[workspaces]]
x = 1920
y = 0
width = 1024
height = 768
```

**Comment by Oreolek** [comment]
It was a polybar issue. The `Coffee` theme calls polybar on all monitors, it can't handle different sizes.

**Comment by VuiMuich** [comment]
Welcome Adventurer,
If you are willing to contribute a PullRequest on the theme repository to fix this surely would be welcomed.

**Comment by Oreolek** [comment]
I didn't fix it, just turned off calling polybar on all monitors. Now it calls the bar on the main monitor and that's it.

**Comment by VuiMuich** [comment]
Oh, I see.
There seem to be regular hickups with polybar and different sized workspaces, so a fix would have been welcome.
