### ISSUE TITLE
Some keybind commands doesn't work.

### ISSUE THREAD

**Issue by rigoletto-freebsd** [leftwm/leftwm#379]
Some `keybind` actions doesn't work. I have not tried all possible commands but I can list some that simply doesn't work for me:

`FocusWorkspacePrevious`,` FocusWorkspaceNext`, `MoveToLastWorkspace`.

The keyboard have an ABNT-2 layout, but ever changing the keybinding to some key already previously tested with a working command doesn't help at all. 

**Environment:**

FreeBSD

**Side issue:** I still have not found a way to have `focus_manager` working in here. I have `focus_manager = "ClickTo"` on `config.toml` but the behavior still is the default one (Sloppy).

```
:: LeftWM version: 0.2.8
:: LeftWM git hash: 10-eol-88773-g0bac49595e04-modified
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK (has XDG_RUNTIME_DIR)
```

Thank you!

**Comment by VuiMuich** [comment]
Just to exclude a possible misconception:
You are actually using multiple `workspaces` as in multiple monitors or have configured a multi-workspace desktop in `config.toml`, right?
And you are not on a single monitor single workspace setup trying to switch `tags` with these commands. 
Sorry if asking this back sounds stupid, but mixing up `workspaces` and `tags` in leftwm is kind of a common pitfall.

Currently on mobile, but could check on this (and your side issue) later today.

**Comment by AethanFoot** [comment]
The focus issue is because it is ``` focus_behaviour``` 
Thanks.

**Comment by rigoletto-freebsd** [comment]
> Just to exclude a possible misconception:
> You are actually using multiple `workspaces` as in multiple monitors or have configured a multi-workspace desktop in `config.toml`, right?
> And you are not on a single monitor single workspace setup trying to switch `tags` with these commands.
> Sorry if asking this back sounds stupid, but mixing up `workspaces` and `tags` in leftwm is kind of a common pitfall.
> 
> Currently on mobile, but could check on this (and your side issue) later today.

I understand I have one workspace with multiple tags, with one monitor.

Thanks.

> The focus issue is because it is ` focus_behaviour`
> Thanks.

Fixed, thank you!

[config.txt](https://github.com/leftwm/leftwm/files/6604352/config.txt)

**Comment by rigoletto-freebsd** [comment]
Now it works using `FocusPreviousTag`, `FocusNextTag`. \o/
I can't use `[` and `]` as keybinding. :-(

**Comment by VuiMuich** [comment]
I'm not familiar with your `ABNT-2` keyboard layout, does it have [ and ] directly on the top layer, same as lower-key-characters?
If it is on a higher layer which is accessed by `Shift` or any other mod-key you would need to use the mod-key plus the base-keys of where [ and ] are located.

So on a QWERTZ Keyboard as mine this would be `ALTGR+8` for [ and `ALTGR+9` for ]
In the `config.toml` this would resemble to
```toml
[[keybind]]
command = "FocusPreviousTag"
modifier = ["Mod5"] #I believe this was AltGr
key = "8" # [
```
Another thing worth noting is that leftwm seems to be agnostic of the X11 keyboard (not sure how that translates to bsd?) but relies on the layout defined for the tty. I am not sure about the actual mechanics at this point, but I have obsoerved that my keybinds persist on the same keys invariant if I am using `de(T3)` layout or `de(bone)`.

**Comment by rigoletto-freebsd** [comment]
ABNT-2 is the Brazilian keyboard. Besides this is QWERTY, except by some specific extra keys this is mostly the same as the US one, and the `[` and `]` keys are on the lower-keys, without need of using shift.

![abnt2](https://user-images.githubusercontent.com/43918328/120932653-2aeec180-c6e6-11eb-8c1e-20c774381f0f.png)

Xorg in FreeBSD is the same Linux Xorg just with some patches to make it work in here. This is in fact using `evdev` now too.

PS. Interesting I realized now none of the last keys (before Enter, `[` `]` `/` `=`) work for keybinding.

**Comment by VuiMuich** [comment]
Oh, this reminds me of something..

[Here](https://github.com/leftwm/leftwm/blob/master/src/utils/xkeysym_lookup.rs) have a look at lines 274 and 276 you should use the `bracketleft` and `bracketright` keywords in `config.toml` as pointed out in [the wiki](https://github.com/leftwm/leftwm/wiki/Config#keybind).

**Comment by rigoletto-freebsd** [comment]
Yeah, that worked! Thanks!
