### ISSUE TITLE
I have a few questions.

### ISSUE THREAD

**Issue by Phate6660** [leftwm/leftwm#38]
Is it possible to either remove the gaps between borders, or reduce the size of the gaps?

----

Is it possible to bind multimedia keys like "XF86AudioPlay", and can I bind it without using the modifier?

----

Is it possible to remove borders from a fullscreen application? For example, I just tried to watch a video with mpv in fullscreen (and it worked perfectly), however I noticed that either the full border or a partial border will stay on screen.

----

Is it possible to stretch the current window to the size of the screen if it is the only window in that workspace?

----

Is it possible to go/move to "Next Workspace" or "Previous Workspace" instead of specifying one?

----

This probably sounds stupid, but how do you actually exit the WM. Is there a command or default keybinding for it?

----
I just noticed something else. This ~~only~~ mostly happens with Firefox, but sometimes with other windows. Every once in a while, it's almost like there's a ~~invisible window~~ strange vertical line or something in the center of ~~Firefox~~ the screen that forces the mouse position to the center of the screen. It'll last for around 5 seconds before I can actually use my mouse again. Is this a known issue? Or something on my end?

----

I'm sorry if these have already been covered somewhere. I've looked around but couldn't find anything regarding my questions. 

I have just switched over to LeftWM from XMonad today, and have been enjoying it so far. Everything is noticably faster and I don't have to deal with 10+ not-very-helpful Haskell error messages everytime I change something in my config.

I apologize for the very long issue, and I thank you for reading it.

**Comment by lex148** [comment]
Phate6660,

Thanks for your questions / issues some of these are simple tweaks in a config and some are a bit more. 

1) You will have to use a theme to get no margin, but it should be simple. open up the file 
~/.config/leftwm/themes/current/theme.toml and set margin to 0
If you aren't using a theme I would recommend copying one from the main repo folder

2) yes for multimedia buttons but you must use a modifier currently. This sounds like a very useful ability, so look for this in the next release. I'm moving this to a new ticket to help me track it better 

3) full screen borders - I will absolutely fix this. I moved it to a new ticket to help me track it better 

4) I'm not sure exactly what you mean with the stretching of a single window. A feature I have been thinking about adding is the ability to toggle full screen mode for any window at any time. For example if i'm in firefox and press Mod+f it would be toggled into full screen mode. Would this solve your problem?

5) For workspace navigation try (Mod + ⬆️⬇️) and (Mod + Shift + ⬆️⬇️) If this isn’t what you are looking for let me know and maybe I can still help.

6) For exiting I have the following command in my config. I really should add this to the default 
~/.config/leftwm/config.toml

[[keybind]]
command = "Execute"
value = "pkill leftwm"
modifier = ["modkey", "Shift"]
key = "x"

7) I haven't seen the firefox issue that you are describing, but I would like to look into it. Any more information you could provide would be very useful. Specifically:
What version of firefox are you running (stable / beta / dev / nightly ) 
What graphic stack are you using (nvidia / AMD ) (proprietary / open source) drivers
Do you have two monitors
What version of LeftWM are you running


I’m glad to hear you are enjoying left and very much appreciate you reporting these bugs / issues your having. I want to make the WM better, and the only way I can do that is to get good feedback like this.

-Lex Childs

**Comment by lex148** [comment]
I just realized you said workspace not window for #5 

This feature is there but apparently I set it up incorrect in the default config.

in the file: ~/.config/leftwm/config.toml
look for the section FocusWorkspaceNext and FocusWorkspacePrevious
They will run when (Shift + Left/Right) is pressed but I will be changing the default to:

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey", "Control"]
key = "Right"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey", "Control"]
key = "Left"

**Comment by Phate6660** [comment]
> You will have to use a theme to get no margin, but it should be simple. open up the file
~/.config/leftwm/themes/current/theme.toml

Do I have to exit the WM instead of soft reloading to get the theme to load? Because editing that file and reloading didn't work.

> I'm not sure exactly what you mean with the stretching of a single window.

Here's what I meant. In this screenshot I have 1 terminal open and nothing else, however there is still a border. It would be nice if the termianl size would stretch to a pseudo-fullscreen since it's the only program open. Unless this is related to my first question of removing gaps.

![Screenshot from 2019-05-20 15-20-11](https://user-images.githubusercontent.com/44369810/58046367-134e3b80-7b13-11e9-9730-b727d2f0a469.png)

> I haven't seen the firefox issue that you are describing, but I would like to look into it. Any more information you could provide would be very useful.

Firefox: Nightly
Graphics: Proprietary Nvidia drivers, version 390xx

Here's is a quick video of what happens. My mouse will get stuck in the center of the screen, and when I try to move it various things will flash and my mouse will go back to the center. Happens sometimes with other windows, but mostly with Firefox. I noticed it happens whenever I switch tags, and whenever I launch another program on the same tag as Firefox. For some reason, it want to happen for that long when I was recording it, but it does desfinitely happen for longer than that.

[Imgur - mp4 link](https://i.imgur.com/CzrqtXM.mp4)

> look for the section FocusWorkspaceNext and FocusWorkspacePrevious

Turns out I was mistaken. I had gotten the terms "workspace" and "tag" mixed up. I was looking for a way to go/move to next/previous tag.

----

I'm sorry for responding so late. I've been pulling some all-nighters and ended up crashing this morning from lack of sleep. And thank you for helping me.

**Comment by lex148** [comment]
Phate6660,

Would you please give my very basic theme a try. I set it to 0 margin.
https://drive.google.com/file/d/1HMPshH7geFF1CPK25DIQq8CaqEetK5KC/view?usp=sharing

**Comment by Phate6660** [comment]
I just got it to work. I didn't realize there was a command required for loading the theme.

**Comment by pratik-devkota** [comment]
I'd just like to add one more question to the original:
Is there any way to have a keybinding which cycles through _tags_ without having to explicitly give it the number? For example, `Mod+Shift+N` for next __tag__ and `Mod+Shift+P` for previous __tag__. I know there's a keybinding to **focus** the next **workspace** but I'm looking for cycling through tags; I find having to reach out to the number row quite annoying.

**Comment by mautamu** [comment]
> I'd just like to add one more question to the original:
> Is there any way to have a keybinding which cycles through _tags_ without having to explicitly give it the number? For example, `Mod+Shift+N` for next **tag** and `Mod+Shift+P` for previous **tag**. I know there's a keybinding to **focus** the next **workspace** but I'm looking for cycling through tags; I find having to reach out to the number row quite annoying.

Good afternoon,

Indeed there is, this ought to be added to the documentation and maybe given a default, but here is how to go next and previous tags using your method (requires LeftWM >= 0.2.4 (maybe 0.2.5):
```toml
[[keybind]]
command = "FocusNextTag"
modifier = ["modkey", "Shift"]
key = "n"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey","Shift"]
key = "p"
```

Best,
Mautamu
