### ISSUE TITLE
Workspaces behave weird when using Polybar at the top of a screen where another screen is above

### ISSUE THREAD

**Issue by paulhersch** [leftwm/leftwm#380]
Kinda hard to explain so i will just show you images

Polybar on top of bottom screen

![broken](https://user-images.githubusercontent.com/74120050/121190784-ac239100-c86b-11eb-898a-9c71f32e1fef.png)

Polybar at the bottom of bottom screen

![notbroken](https://user-images.githubusercontent.com/74120050/121190810-b2197200-c86b-11eb-9efc-7ce622bede9c.png)

basically one window from the top screen is moved partially to the bottom screen and displayed incorrectly. I hardly believe that this is that big of an issue as you just have to move the bar to the bottom to make it work. More of an issue if someone finds themselves in the situation shown above not knowing what to do
(polybar version is polybar-git btw, shown scenario doesnt apply for other WMs for me)

**Comment by AethanFoot** [comment]
Tag #229. We couldn't find exactly what was causing this, however you have given me some more ideas of what to look at and I think I know where the issue is now.
Hopefully have a fix soon.
Thanks!!
