### ISSUE TITLE
Creating a new window while in fullscreen mode results in weird floating 

### ISSUE THREAD

**Issue by lex148** [leftwm/leftwm#383]
**To Reproduce**
1. full screen a window (open terminal, run `leftwm command ToggleFullScreen`)
2. 'mod+Shift+Enter' to open a second window. 

**Expected behavior**
Expected the new window to be visible. Perhaps we should un-fullscreen the first window

**Comment by VuiMuich** [comment]
I agree, that creating a new window should probably exit the fullscreen.

Maybe with an exception for `monocle` layout, where we could expect the fullscreen behave exactly as the windowed layout.
