### ISSUE TITLE
Arm Build failed

### ISSUE THREAD

**Issue by Hero9909** [leftwm/leftwm#389]
**Describe the bug**
on building odroid xu4 the build fails with [Error-Log](https://haste.cosmos-ink.net/owawesuwup.rs)

**To Reproduce**
1. paru -Sy leftwm
2. wait
3. See error

**Expected behavior**
A clean build

**Environment:**
 - OS/Distro: Arch arm

**Comment by VuiMuich** [comment]
Ooof, this looks like a tough one.
I don't know if there is an easy or at least somewhat feasible option to help the compiler to build a 32bit binary from otherwise 64bit code? From a brief glance there are no values where we actually would need to have 64bit necessarily.
But manually keeping everything downwards-compatibly seems like a heavy burden.

**Comment by Hero9909** [comment]
the last error doesnt seems to match the others as a u32 were found but u 64 were expected...

```
src/display_servers/xlib_display_server/xwrap.rs:1496:31
     |
1496 |             self.grab_pointer(cursor);
```

**Comment by VuiMuich** [comment]
Yes you are right. Is It possible, that this one is missing in the hastebin? I can't see it there..

**Comment by Hero9909** [comment]
oh, i see, its one of the build of leftwm-git, illupload its log later if im back at my workmachine.

**Comment by AethanFoot** [comment]
As all of these are interactions with xlib, I think we might be able to replace them with c_ulong/c_long which will change depending on system. This should then remove all u64's, fixing the problem, but I would have to check that when I'm not tired.

**Comment by lex148** [comment]
@Hero9909 I tried to get this working about 6 months ago and was never successful. I just tried again and this time no errors. I remember reading something about rust improving its compatibility with arm. I wonder if this has just been fixed somewhere deep in the compiler. 
 
Would you mind running a `rustup update` and trying with the latest stable version of rust. 

Please let me know success or failure, we don't get many people testing on arm :) 

A couple notes:
- alacritty does not work for me on arm.
- polybar-git will complain about the wrong architecture, but will work  

![Screenshot at 2021-06-12 18-20-29](https://user-images.githubusercontent.com/442031/121791222-2c6c2e00-cbad-11eb-92a0-229e1d7494e3.png)

**Comment by Hero9909** [comment]
sadly, same error as before. ive tried a build directly from git with nightly and stable toolchain same errors as before. aswell ive tried install from cargo. what kind of setup do you have?

**Comment by lex148** [comment]
I have a vanilla install of Manjaro from [here](https://manjaro.org/download/#pinebook-pro) 

Looking back add your build log, It looks more like a 32bit vs 64bit OS issue not Arm. Are you running a 32bit OS? 

My guess is that you are running a 32bit OS on a 64bit arm CPU
