### ISSUE TITLE
[bug] soft reload: scratchpad lost, fullscreen windows are in a wacky state

### ISSUE THREAD

**Issue by VuiMuich** [leftwm/leftwm#390]
**Describe the bug**
This is a two in one:
1. when there is a scratchpad window created and a soft reload is initiated we lose the scratchpad in a way that the window lives on a 'ghost tag' and the `ToggleScratchPad` command creates a new scratchpad instead of showing the existing one. Only a hard reload can 'unghost' this window and restore it as a common tiled window.
2. when during a soft reload a window is in fullscreen mode it afterwards is restored with a few wacky properties. E.g. the border is still omitted, sometimes it won't position itself well in the layout (ignoring margins etc.). This is also only salvageable with a hard reload.

**To Reproduce**
see above

**Expected behavior**
1. Scratchpads should be restored as scratchpad windows during a soft reload
2. fullscreen windows should be restored in fullscreen
3. as with #387 a soft reload should ideally restore the size and position of floating windows (in this case especially scratchpad windows)
4. If the size and position of a floating window couldn't be recreated we should fallback to a sane default

Bonus: at some point we might want to add a `PushPopScratchPad` command, so we can send arbitrary windows to the scratchpad and release them again to tiling mode.

**Comment by AethanFoot** [comment]
Restoring fullscreen after reload is not possible with #386. As the window get minimised while adding the windows.

**Comment by VuiMuich** [comment]
as far as I can tell this is closed by #391
