### ISSUE TITLE
Focus suddenly switch to master.

### ISSUE THREAD

**Issue by rigoletto-freebsd** [leftwm/leftwm#392]
Hello,

I've noticed these days if the focus is not on the master window, after some time[1] it suddenly switch to the master window. The first few times I've noticed this behavior, I thought I may had did something without realizing but now I'm sure this is happening by its own, specially after it switched while I was writing an e-mail. ^^

FreeBSD, LeftWM: e55355851ef6afd40d94414347cacc01197ab2e3.

`focus_behaviour = "Driven"`

[1] I couldn't figure out exactly.

Thank you!

**Comment by VuiMuich** [comment]
Just briefly testing with `sloppy` focus on layout `MainAndDeck` I can not confirm this.
Am a bit reluctant of a recofnigure and reload rn, but might have a deeper look at it later today.

Do you have a rough estimate of the duration it takes before the focus switches?
Is this time random or constant?
Have you tried different layouts?

**Comment by rigoletto-freebsd** [comment]
I have not tested with other focus switches, I may try today; however I feel I will not be able to reproduce with `Sloppy` given the focus following the mouse pointer .

In regards to the time I have not managed to get the time yet because it seems random. Sometimes a few seconds, sometimes it feels to take more time.

Thank you.

**Comment by AethanFoot** [comment]
The only thing that should trigger focus constantly is when we verify focus in leftwm-worker, is the mouse cursor on the window when this happens (Side note we should probably exclude when focus is not sloppy). If this isn't the case I'll need to do some more testing when I have time.
Thanks.

**Comment by VuiMuich** [comment]
Just started to test this and found another issue:
as this issue suggested I have `focus_behaviour = "Driven"` and `focus_new_windows = true`.
When closing a scratchpad, the focus is not returned to the tiled windows. This leaves them in an unfocusable state which can only be reverted with a soft reload.

**Comment by VuiMuich** [comment]
This is weird, the focus switch always triggers, when I use my `<leader>-P` (paste from system clipboard) in `nvim` with `<leader>` being `;`

**Comment by rigoletto-freebsd** [comment]
This commit brought a minor issue: when LeftWM is _SoftReloaded_ there is no window focused. Happens with "ClickTo" and "Driven", and this is not clear it if happens with "Sloppy".

Thanks!

**Comment by AethanFoot** [comment]
@rigoletto-freebsd Does a window still not get focus after reload. I was getting this as well, but now I have time to fix it it hasn't reappeared.
Thanks.

**Comment by rigoletto-freebsd** [comment]
> @rigoletto-freebsd Does a window still not get focus after reload. I was getting this as well, but now I have time to fix it it hasn't reappeared.
> Thanks.

Yeah, its looks like the problem is gone now!
