### ISSUE TITLE
Leftwm does not run correctly on x86_64 musl Void Linux

### ISSUE THREAD

**Issue by ReneganRonin** [leftwm/leftwm#396]
**Describe the bug**
Leftwm does not run correctly even though I installed it per README instructions

**To Reproduce**
1. `cargo build --release` in repository directory
2. `sudo install -Dm755 ./target/release/leftwm ./target/release/leftwm-worker ./target/release/leftwm-state  ./target/release/leftwm-command  ./target/release/leftwm-check -t /usr/bin/`
3. `echo 'exec dbus-launch leftwm > $HOME/.xinitrc`
4. Runs but no respond to my keybindings. Only blackscreen when I have a theme `leftwm-soothe` in `.config/leftwm/theme/current`

**Expected behavior**
It should run with no weird behavior. I recently installed Void Linux (musl) yesterday. Before that I was using the glibc version of voidlinux and that worked.

**Environment:**
 - OS/Distro: Void Linux (x86_64-musl)
- leftwm-check output:
```
[0;94m::[0m LeftWM version: 0.2.8
[0;94m::[0m LeftWM git hash: f84ec87
[0;94m::[0m Loading configuration . . .
[0;92m    -> Configuration loaded OK [0m
[0;94m::[0m Checking keybinds . . .
[0;92m    -> All keybinds OK[0m
[0;94m::[0m Checking environment . . .
[1;91mERROR: XDG_RUNTIME_DIR not set and elogind not found.
See https://github.com/leftwm/leftwm/wiki/XDG_RUNTIME_DIR for more information.[0m
```
Do I really need elogind? I have not installed elogind before and only seatd and it worked from my previous installation of void. I also have XDG_RUNTIME_DIR like the content of this script that I wrote:

```dash
#!/usr/bin/env dash

export XDG_CURRENT_DESKTOP=leftwm
export MOZ_ENABLE_WAYLAND=0
export XDG_DESKTOP_SESSION=x11

# Runtime Directory
if test -z "${XDG_RUNTIME_DIR}"; then
	export XDG_RUNTIME_DIR=/tmp/`id -u`-runtime-dir
	if ! test -d "${XDG_RUNTIME_DIR}"; then
		mkdir "${XDG_RUNTIME_DIR}"
		chmod 0700 "${XDG_RUNTIME_DIR}"
	fi
fi

# Start leftwm	
startx
```
Going to try install elogind. I will update if it worked.

Update. Same behaviour after installing elogind.

leftwm-check output:
```sh
[0;94m::[0m LeftWM version: 0.2.8
[0;94m::[0m LeftWM git hash: f84ec87
[0;94m::[0m Loading configuration . . .
[0;92m    -> Configuration loaded OK [0m
[0;94m::[0m Checking keybinds . . .
[0;92m    -> All keybinds OK[0m
[0;94m::[0m Checking environment . . .
[0;92m    -> Environment OK [0;92m
```

leftwm-worker is showing this:
![image](https://user-images.githubusercontent.com/66054069/123024482-b1581280-d40b-11eb-8dde-a5faddbe598d.jpeg)

**Comment by VuiMuich** [comment]
If you wouldn't have stated that under `glibc` it ran without issues I'd blame `dbus` being missing as AFAIK it is a dependcy of of `systemd`.
You probably did the same is in [this instructions](https://wiki.voidlinux.org/Post_Installation#Seat_management) for your seatmanagement, right?

I guess that's as far as I could provide help for void.

**Comment by ReneganRonin** [comment]
yup i did. i have dbus running and polkitd with elogind. i still am confused because it worked on the previous installation of void (glibc) with just seatd, dbus, and polkitd running.

**Comment by VuiMuich** [comment]
As my next guess I'd blame `musl`
Maybe you could try [this](https://doc.rust-lang.org/edition-guide/rust-2018/platform-and-target-support/musl-support-for-fully-static-binaries.html):
```
$ cargo build --target x86_64-unknown-linux-musl
```
adding the `--release` flag of course

**Comment by ReneganRonin** [comment]
@VuiMuich i forgot to mention that the target architecture is already for x86_64-unknown-linux-musl. I guess it is musl's
