### ISSUE TITLE
[Feature Request] Sharing single Windows for screen share

### ISSUE THREAD

**Issue by paulhersch** [leftwm/leftwm#397]
A the title says, I'd like to be able to share single Windows for screensharing. I would also try to make this myself if this is planned to be implemented.

I use leftwm-git from the AUR right now

**Comment by AethanFoot** [comment]
Any features like this are always welcome, if you feel like you can implement it that's great. If you have any questions feel free to post them here (from getting ready to where things are in the code base) and I will try to help anyway I can.
Thanks!

**Comment by VuiMuich** [comment]
@paulhersch can you specifiy a bit more what you are actually missing?
I tried to grab some windows with `OBS` using the `window capture (Xcomposite)` source and I can select basically any existing window, including hidden windows, or windows from unfocused tags.
Or would you like to share a single window via VNC or a meeting software like zoom?

**Comment by paulhersch** [comment]
@VuiMuich yeah for meeting softwares. OBS works fine for me as well, but working with my colleagues is hard because i have to switch Window Managers if I want to show them a special window
do you know how something like this can be implemented? I would try it myself if you don't want to work on it

**Comment by thapakazi** [comment]
> do you know how something like this can be implemented? I would try it myself if you don't want to work on it

Anyone looking at this ?
btw, i am interested to learn and build it.

**Comment by VuiMuich** [comment]
A attempt at this would surely be welcome.

Now that you pulled this one up again, I remember I wanted to ask @paulhersch which WM he is using, where this appears to be working, so we have a reference to look up how they handle things.

**Comment by hertg** [comment]
Just found out about that issue, it's kind of a big deal for me, because I'd like to use LeftWM for work too and I share windows quite a lot in meetings. Because I work on ultra-wide monitors, sharing the entire screen is not an option most of the time, because it's just too big of a resolution.

I can start looking into that to try and find out how to implement it.

> I wanted to ask @paulhersch which WM he is using, where this appears to be working, so we have a reference to look up how they handle things.

@VuiMuich 
I used dwm before, and the window sharing works there. Maybe that could be easy to find as they don't have a lot of code. I'll start looking into that. I hope to have enough time to get anywhere, because my holidays end today :stuck_out_tongue_closed_eyes:

**Comment by VuiMuich** [comment]
That's great.
I'll dig a bit in DWM as well, good opportunity to improve on my shitty C knowledge 🤣

**Comment by hertg** [comment]
> Was this working natively, or was this in a patch?

I think it was natively. I did install patches, but nothing related to screen-capturing or screen-sharing...
It would probably be best to find out how the window selection is implemented in chromium/firefox? Maybe that would give some hints...

**Comment by hertg** [comment]
If it really was due to a patch, then you could also dig through my version of dwm, where this worked:
https://github.com/hertg/dwm

**Comment by hertg** [comment]
@VuiMuich 
This looks promising: https://chromium.googlesource.com/external/webrtc/+/master/modules/desktop_capture/linux
Especially: https://chromium.googlesource.com/external/webrtc/+/master/modules/desktop_capture/linux/window_list_utils.cc

**Comment by hertg** [comment]
I think they are using the [XQueryTree](https://www.x.org/releases/X11R7.7/doc/libX11/libX11/libX11.html#XQueryTree) method. Can somebody test if that works with LeftWM?
