### ISSUE TITLE
Click on empty screen and then spawn windows there

### ISSUE THREAD

**Issue by AeroNotix** [leftwm/leftwm#416]
I am trying to click on an otherwise empty screen, then open a window there.

It seems to open the window on the screen I was previously focused on.

Is there some configuration I am missing, or is this not possible. Workaround I am using right now is to spawn the window I want on any screen which lets me, then push the window around until its on the correct screen.

**Comment by VuiMuich** [comment]
Currently we don't have this behaviour, as we don't move workspace focus by mouse.
The only ways the workspace focus changes is by focusing a window on a workspace or by the [commands](https://github.com/leftwm/leftwm/wiki/Config#focusworkspacenext) `FocusWorkspaceNext`/`FocusWorkspacePrevious`.

**Comment by AeroNotix** [comment]
Thanks for the information @VuiMuich

**Comment by VuiMuich** [comment]
You are very welcome.
