### ISSUE TITLE
Feature Request: Set margins conditionally for each workspace or screen

### ISSUE THREAD

**Issue by stevensonmt** [leftwm/leftwm#426]
Leftwm currently places windows above my polybar instance on only the second screen. I have addressed this "successfully" in two ways:
1) Define workspaces in `.config/leftwm/config.toml` for each screen with the second screen offset vertically by `y = 10` or whatever number is required.
2) Define margins in `.config/lefwm/themes/my_polybar_theme/theme.toml` with `margin = [20, 8, 8, 8]` or whatever values you like. 

The first is probably the better solution but I suspect would lead to other issues I haven't discovered yet with the actual screen space not matching the representation of that screenspace. I also don't understand why this vertical offset only affects the windows and not the placement of the polybar instance or the background image from `feh`.
The second is easier to reason about but leads to a larger gap above the windows on the first screen, which I don't like.

My request is to have `theme.toml` accept values for `margin` by screen or workspace identifier OR to have `config.toml` accept a `margin` setting within the workspace definitions. I think the latter is preferable and might actually allow for interesting customization of specific workspaces for specific workflows.

**Comment by stevensonmt** [comment]
I'm actually trying to work on implementing this myself. Can you help me figure out where the theme settings get applied to the actual workspace? My approach is to simply have the theme struct contain a set of Margin rather than a single Margin. To keep backwards compatibility the MarginSet will be an enum that parallels the Margin enum. A single number given as the setting means all margins are equal on all workspaces. 1 or more numbers given in an array means the same as it does now, applied to all workspaces equally. 1 or more arrays of numbers will be processed as individual Margin instances and applied to each corresponding Workspace by index. If more Workspaces exist than Margins then the last valid Margin will be applied to all remaining Workspaces. If more Margins exist than Workspaces the excess Margins are ignored.

I just can't quite figure out how to implement it in the loop. Somewhere in Nanny::boot_current_theme()?

**Comment by mautamu** [comment]
Take a look at #292, most of its changes will point you to where the theme settings propagate through the code.

**Comment by mautamu** [comment]
https://github.com/leftwm/leftwm/commit/e60503d57362fab2e17a6e6edd772f99ff661d8b

Here's another commit that affects the old Margin settings as well.

**Comment by AethanFoot** [comment]
Id say the best place to start would be adding to the gutters to allow the user to set a specific workspace for using the relevant id. The reason polybar is not affected as we allow it to decide where it is placed. 
Thanks.

**Comment by stevensonmt** [comment]
Adding a gutters setting to my theme.toml does not seem to have any effect on this issue for me.

**Comment by stevensonmt** [comment]
Looks like using a workspace specific gutter setting will be the way to go. Planning to just add a workspace_id field to the Gutter struct. The field will take an Option<i32> so there won't be any problems with backwards compatibility. It will treat Gutters with workspace_id of None as global settings and override them for workspaces with an explicit gutter setting for the same side as the global setting. 
It looks like workspace IDs get set here: https://github.com/leftwm/leftwm/blob/2b6e9cf8688984a03a0396c045a7f671800f942a/src/handlers/screen_create_handler.rs
```
pub fn process(manager: &mut Manager, screen: Screen) -> bool {
    let tag_index = manager.workspaces.len();

    let mut workspace = Workspace::new(screen.bbox, manager.tags.clone(), manager.layouts.clone());
    workspace.update_for_theme(&manager.theme_setting);
    workspace.id = tag_index as i32;
```
So the only thing to change there would be setting the workspace.id before running `update_for_theme`, yeah? Then in `update_for_theme` I'll handle setting the gutters for any global settings or for the specific workspace id.

That seems a little brittle as the workspace ID seems to depend on the order it's defined in the config.toml. Should I add an ID field to the workspace configuration settings and only fallback to iterating if there is no assigned ID?

**Comment by AethanFoot** [comment]
I agree that an optional ID field should be added to the workspace configuration, and yes this would need to be set before updating for the theme.
One check that will need to be added will be when we select the tag to be shown on the workspace (on line 17 of screen_create_handler). I'm not sure of the best way to handle when the id is greater than the number of tags, one way is to tell the user they can't have a workspace with id >= number of tags, I feel a clear error would be appropriate.

Thanks.

**Comment by stevensonmt** [comment]
Is it too much to have Workspace include both an ID and something like assigned_tag fields? That way gutters and margins can be applied based on the workspace.id but tags are displayed according to workspace.assigned_tag, which would be handled in `screen_create_handler` the way workspace.id is handled currently. I may be missing some layers of complexity in how workspace.id gets used that would make this a bad move.

**Comment by VuiMuich** [comment]
> I'm not sure of the best way to handle when the id is greater than the number of tags, one way is to tell the user they can't have a workspace with id >= number of tags, I feel a clear error would be appropriate.

I'd say when there are more workspaces then tags (whether by ID or by iteration) `leftwm-check` should error.
For the `worker` to log a panic and fallback to default would be a same way to handle this, I guess?
Never tried what currently is happening in this scenario.
The trickiest case might be if there are more monitors the tags, what happens to the last monitor?

**Comment by VuiMuich** [comment]
I'm on mobile so excuse my vague code terms. 

If we add a field `gutters: Gutter` to the workspace this might simplify the possible scenarios IMO:
We once apply the gutters to the relevant workspaces on `theme load`, this one should be able to panic as mentioned above.
We have three cases where we need to apply the gutters: `window create`, `window move` and `tag_swap` in all of these cases we already have the workspace(s) already handed to the functions so we also can read the gutters field, right?

**Comment by stevensonmt** [comment]
If users are setting workspace ID in the config, how would you enforce uniqueness of IDs? If I define 2 workspaces and give them ids `3` and `1` but have 3 monitors, won't that lead to the third workspace attempting to have the ID `3` based on `manager.workspaces.len()`? Or if the user just defines ids that are not unique to start with.

**Comment by stevensonmt** [comment]
I still need to write some tests, but would you mind taking a peek at [this commit](https://github.com/stevensonmt/leftwm/commit/4c34091d1afc8a6e43afef39a937373d245c8d72) and letting me know if it seems on the right track. When I run all the current tests it still passes so I don't think I've broken anything.

**Comment by AethanFoot** [comment]
Looks good so far, I gonna have a think if there is a nicer way to deal with overriding global gutters (with the current implementation I will atleast say it would be nicer the find instead of position as you are using the element). Other than that I would check clippy for any niggly bits.
Thanks.

**Comment by stevensonmt** [comment]
I used position instead of find because in the case where the current gutter is global you want to override it with the workspace specific setting. The easiest way to do that seemed to be replacing the global gutter at the index with the new gutter. I could use `.enumerate().find()` so that the index is available if replacement needs to happen.

**Comment by stevensonmt** [comment]
Still haven't written the tests but running it locally with different settings for global and workspace id specific gutters is working correctly using the last commit from my fork. Would probably be worth mentioning that workspace id's are zero-indexed by default.

**Comment by stevensonmt** [comment]
Sorry for being so dense, but I can't seem to figure out where the workspace attributes from `leftwm/config.toml` are being applied. The reason the workspace ID is being ignored now is that in `screen_create_handler` the `process` function creates a new workspace, which by default has `None` as the ID. Since the other parameters passed to `Workspace::new()` are a `screen.bbox`, vec of tags and vec of layouts, I assume the workspace config settings are applied at the screen.bbox creation. I just can't find where that happens.

**Comment by stevensonmt** [comment]
I'm not sure but I think I may have stumbled upon another issue related to this. When workspaces are defined with ids but out of sequence in `config.toml` polybar gets wrong information about which workspace is showing which tag. I see an error message from the `template.liquid` script but only partially and when I try to screenshot it disappears upon activating the screenshooter. This happens in the last release as well as on my fork. Of course the official release is ignoring the workspace ID specified in the config so it makes sense that it will be out of order if the workspaces are defined out of order. I think this can be fixed by sorting the vec of workspaces by ID, but I'm not sure how efficient that is or if it will be the expected behavior. Maybe users will expect the order of definition to be the order of application regardless of what the assigned ID is. Maybe workspaces should have both an ID, which could be any string like tags are, and an index field, which is usize or i32 and assigned by order of definition in `config.toml`.

**Comment by NicTanghe** [comment]
Bump,
although in the end, this is just a way for me to get around the full-screen window spawning windows behind itself.

**Comment by stevensonmt** [comment]
I think this should be closed as implemented in https://github.com/leftwm/leftwm/pull/432

**Comment by VuiMuich** [comment]
Thanks @stevensonmt, I had some faint memory of that myself, but wasn't sure anymore so just wanted to start digging...

**Comment by stevensonmt** [comment]
That was my fault for not referencing the issue in the pull request.

**Comment by VuiMuich** [comment]
No worries.
