### ISSUE TITLE
polybar module only displaying for a second before reloading

### ISSUE THREAD

**Issue by H-mate** [leftwm/leftwm#434]
I've split up the output of my leftwm-state with the template.liquid for a vertical polybar.
the templat.liquid looks like this

`% for tag in workspace.tags %}`
`{% if tag.mine %}`
`%{O-8}%{F#dfdfdf}%{B#00af09}  {{tag.name}}   `
`{% elsif tag.visible  %}`
`%{O-8}%{F#dfdfdf}%{B#E60053}  {{tag.name}}   `
`{% elsif tag.busy %}`
`%{O-8}%{F#00af09}%{B#99222222}  {{tag.name}}   `
`{% else tag.visible %}`
`%{O-8}%{F#dfdfdf}%{B#99222222}  {{tag.name}}   `
`{% endif %}`
`{% endfor %}`

and my polybar modules for eachworkspace look like this

`[module/left1]`
`type = custom/script`
`exec = leftwm-state -w 0 -t .config/leftwm/themes/hmate-sidebar/sidebar.liquid | awk 'BEGIN{FS="%" ; OFS="%"} { for(i=2; i<=28; i++) print "%"$i}' | sed 'N;N; s/\n/ /g' | awk 'NR==1'`
`tail = true`

I have one bar per tag and all of them have one module like this.
After loading the theme it loads the bars and all of them that have workspace modules are empty, if I reload the numbers flash for a second and the it reloads back to the empty bars.

I tried using `interval = num` for updating the modules but that resulted in countles numbers of leftwm-wo processes opening that would fill up the max number of xclients so I couldn't open windows and had to run `pkill leftwm-wo` every few minutes in the tty

**Comment by VuiMuich** [comment]
Welcome adventurer!
I don't really get why you would want a complete polybar instance per tag? Maybe there is a little misconception of our workspace/tag concept. Workspaces are kind of virtual screens that usually (exception ultra wide monitors) align with the actual hardware monitors. Tags are desktops, but they are shared among workspaces in leftwm, whereas in i3 or dwm each screen has its own set of desktops.
So usually you would have one instance of polybar per workspace.
Is this possibly the cause of your trouble?

**Comment by H-mate** [comment]
> I don't really get why you would want a complete polybar instance per tag? 

I use all of them on one screen and workspace but all of them are 27x27 pixel squares displaying info about only one tag so I can put together a seemingly vertical polybar

**Comment by stevensonmt** [comment]
What information are you trying to display about each tag? It looks like just color-coding the tag ID based on its status, correct?

**Comment by VuiMuich** [comment]
I also was just about to suggest EWW but was a bit reluctant, as it feels always a bit like letting one down, when you need to suggest them to use a different tool. Especially, when one found a creative possible solution.
The upside is, EWW is great, I use it as my taskbar since few months now (currently testing their config rework branch) and it comes with plenty of opportunities for creativity!

**Comment by H-mate** [comment]
Both of you suggested eww and I've tried it already but I didn't like the look of it and didn't understand the config so I've stayed with polybar since then. I f there's no other way I will go to eww but first I would try to fix polybar.

> What information are you trying to display about each tag? It looks like just color-coding the tag ID based on its status, correct? Also, how many bars do you end up trying to open?

It's correct and I open the main vertyical bar 9 workspace bars and one placeholder with an empty module to fill in the gap between the workspace bars and the bottom of my screen

**Comment by stevensonmt** [comment]
What is the output if you just run that exec command in a terminal? Also what version of polybar are you on?

**Comment by H-mate** [comment]
> but adding the `sed` command leads to an empty return.
I checked it and got the same. 
If I add the -q flag to leftwm-state it works. The problem with that was that it spawned a bunch of leftwm-wo processes I try to do it with timeout.

**Comment by stevensonmt** [comment]
Yeah, the awk process was hanging, not actually returning. Adding the -q flag it does return, but I suspect your bars would not update correctly after you do that. 

I actually think this arrangement does not make a lot of sense. Your template is printing out all the tags, but then you're having to parse out just the tag for the current bar. I don't have much experience with liquid templates, but I think you should have a template for each bar. That template captures a variable with the index of the current bar and passes it to the template that checks workspaces.tags for the tag matching the bar index and then applies the formatting based on the tag status as `mine`, `busy`, `visible`, or none of the above.

**Comment by VuiMuich** [comment]
Hmm `leftwm-wo` seemed odd to me from the beginning, sure it was not `leftwm-worker`? What did you use to monitor processes?
The `-q` flag should quit `leftwm-state` after one line and looking at the code it should definitely not instance any other workers.

BTW: what is the output of your `leftwm-check`

**Comment by H-mate** [comment]
I tried it with 
`interval = 0.1`
`exec = timeout 0.1 leftwm-state ...`

it now produces random amount of leftwm-wo processes ranging from 3-4 to more than 20 and after some time thenumbers on the polybar turn into error messages.


>I think you should have a template for each bar. That template captures a variable with the index of the current bar and passes it to the template that checks workspaces.tags for the tag matching the bar index and then applies the formatting based on the tag status as `mine`, `busy`, `visible`, or none of the above.

I don't have much experience either I just deleted some things from the original template.liquid so I have no idea how to do that

**Comment by H-mate** [comment]
> Hmm `leftwm-wo` seemed odd to me from the beginning, sure it was not `leftwm-worker`? What did you use to monitor processes?
> The `-q` flag should quit `leftwm-state` after one line and looking at the code it should definitely not instance any other workers.
> 
> BTW: what is the output of your `leftwm-check`

I used `lsof -U` and I'm not sure either if this is directly causing it but it doees not happen without the bars running
the output of leftwm-check is
`::LeftWm version: 0.2.8`
`::LeftWm git hash: 3c80a4a`
`:: Loading configuration . . .`
`    -> Configuration loaded OK` 
`:: Checking keybinds . . .`
`    -> All keybinds OK`
`:: Checking environment . . .`
`    -> Environment OK `

**Comment by VuiMuich** [comment]
We have this [wiki-article](https://github.com/leftwm/leftwm/wiki/Customizing-Themes-with-%60liquid%60-templates) about `.liquid` and at the end is a link to a more in depth guide the liquid language.
We also have the `leftwm-state -s` flag where you can directly put the liquid-literal like `leftwm-state -w 0 -s "{{ workspace.layout }}"`. This might help you to compose your liquid string with a script, so each instance only checks for one tag.

I see, `lsof -U` truncates names to 9 characters. I prefer `procs leftwm` or `bpytop` (filtered to leftwm).
I still have no idea, why you get so many workers, this looks like there is still something else happening which tries to launch further instances of leftwm. Have you seen anything sus in the polybar logs?
I am fairly certain, that `leftwm-state` shouldn't instance any workers, but simply reads the state from the socket-file.

Ok, the git hash is recent enough, that you should have sub commands available so `leftwm state` (with ' ' instead of '-') does not try to launch another leftwm instance but executes the sub command `state`. Besides you are using the former variant anyways..

**Comment by H-mate** [comment]
I wrote the nine `.liquid` files for the nine bar and it works like a charm thanks for the help.

**Comment by stevensonmt** [comment]
Do you mind posting one of the bar templates?

**Comment by H-mate** [comment]
> Do you mind posting one of the bar templates?

`{% for tag in workspace.tags%}`
`{% if tag.name=="1" %}`
`{% if tag.mine %}`
`%{F#dfdfdf}%{B#00af09}  {{tag.name}}   `
`{% elsif tag.visible  %}`
`%{F#dfdfdf}%{B#E60053}  {{tag.name}}   `
`{% elsif tag.busy %}`
`%{F#00af09}%{B#99222222}  {{tag.name}}   `
`{% else tag.visible  %}`
`%{F#dfdfdf}%{B#99222222}  {{tag.name}}   `
`{% endif %}`
`{% endif %}`
`{% endfor %}`

here it is and I'm planning on posting the whole theme on the [community themes repo](https://github.com/leftwm/leftwm-community-themes)

**Comment by stevensonmt** [comment]
That's great. One thing you could do rather than iterating through the tags array with a for loop is to access by index:
```
{% assign tag = workspace.tags[0] %}
```
