### ISSUE TITLE
Theme is not applied

### ISSUE THREAD

**Issue by winston0410** [leftwm/leftwm#436]
**Describe the bug**
I have followed the wiki to create a minimal theme, but it is not applied to leftwm.

**To Reproduce**
1. Structure your leftwm config in the following structure:
```
.
├── config.toml
└── themes
    └── current
        ├── down
        ├── theme.toml
        └── up
```

2. Insert content into the `theme/current` directory
`down`

```
echo "UnloadTheme" > $XDG_RUNTIME_DIR/leftwm/commands.pipe
```

`up`

```
leftwm-command "LoadTheme $HOME/.config/leftwm/themes/current/theme.toml"
```

`config.toml`

```
border_width = 10
margin = 5
```

3. Make `down` and `up` executable

```
chmod +x down
chmod +x up
```

4. Restart leftwm

**Expected behavior**
I expect I am able to apply setting that I have made in `config.toml` to leftwm. But everything is unchanged.

**Environment:**
 - OS/Distro: [e.g. Manjaro] Nixos
 - Output of `leftwm-check`
 - 
```
:: LeftWM version: 0.2.8
:: LeftWM git hash: NONE
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
```

**Comment by mautamu** [comment]
Howdy! Thanks for opening this issue.

> Insert content into the `theme/current` directory

We should double check this, it should be `themes`, not `theme`.

>`config.toml`

These settings belong to theme.toml, not config.toml. You should either rename the config.toml file in `~/.config/leftwm/themes/current/config.toml` to theme.toml (`~/.config/leftwm/themes/current/theme.toml`).  or should move the theme settings (border_width, margin, etc) from `~/.config/leftwm/config.toml` to the aforementioned theme.toml file. 

Alternatively, you could use `~/.config/leftwm/themes/current/config.toml` but would need to change `up` and `down` to point to config.toml instead of theme.toml:

```
# up
leftwm-command "LoadTheme $HOME/.config/leftwm/themes/current/config.toml"
```

Hope this helps!

Best,
Mautamu

**Comment by winston0410** [comment]
Hi thank you for your reply. I think I have some typos(for the filename for snippet) up there, and I have structured my files the right way like this when I create this issue:

```
.
├── config.toml
└── themes
    └── current
        ├── down
        ├── theme.toml
        └── up
```

And I just found out that the setting is applied, when I execute `up`. Does that mean that I have to manually run it everytime, or leftwm will run it automatically for me?

**Comment by VuiMuich** [comment]
If everything is correct, the `up` script is run at startup, yes.
Maybe we should introduce a check for themes in `leftwm-check`

You might already know it is common practice to have all your theme files in `.config/leftwm/themes/mytheme` and symlink to it with `ln -s ~/.config/leftwm/themes/mytheme ~/.config/leftwm/themes/current`, right?

**Comment by winston0410** [comment]
Yes I do know that I should be using symbolic link there, just doing it the simple way for testing right now. I think it will be awesome if a check for themes is introduced, because right now I have no idea what I have missed.

**Comment by stevensonmt** [comment]
Can you check the permissions on your up script?

**Comment by VuiMuich** [comment]
> Yes I do know that I should be using symbolic link there, just doing it the simple way for testing right now. I think it will be awesome if a check for themes is introduced, because right now I have no idea what I have missed.

I'll give it a go, but I'm not as fast as AethanRocket and I have plenty of IRL distraction atm, so it might take a couple of days.

**Comment by winston0410** [comment]
@stevensonmt there you go:

```
~/.config/leftwm/themes/current
❯ ls -l
dr-xr-xr-x root root 4.0 KB Thu Jan  1 01:00:01 1970  .
dr-xr-xr-x root root 4.0 KB Thu Jan  1 01:00:01 1970  ..
.r-xr-xr-x root root  59 B  Thu Jan  1 01:00:01 1970  down
.r--r--r-- root root  49 B  Thu Jan  1 01:00:01 1970  theme.toml
.r-xr-xr-x root root  74 B  Thu Jan  1 01:00:01 1970  up
```

Should those script be owned by the `root`?

**Comment by stevensonmt** [comment]
They should be owned by the user I would think., Since the permissions are such that it is executable by users other than the owner the owner shouldn't matter in this case.

It is weird that you can call up directly and it works but that up is not being called on startup.

**Comment by winston0410** [comment]
Hm true I guess that is the reason. This is owned by the root and read-only because I am generating it from a [flake in NixOS](https://github.com/winston0410/nixos-dotfiles/tree/master/leftwm), so that all my changes can be reproduced.

But then it will be a dead end for me then I guess, as either I have to give up the flake thing or the theme. Let me think if there is any workaround.

**Comment by AethanFoot** [comment]
Could it be something as simple as not declaring #!/usr/bin/env bash at the top of the scripts, other wise I don't see why there is an issue. Whether it is related or not, it may be good to raise an issue with the devs about user files that are created in the users home tree should be owned be that user.
Thanks.

**Comment by VuiMuich** [comment]
So if we are ant to check if `up`and `down` have a shebang line which ones would we like to test for?
Only `#!/usr/bin/env bash`, or also `#!/bin/bash` and `#!/bin/sh`? Any others?
I might get a PR (possibly only as draft) for a additional check in `leftwm-check` ready by tomorrow.

**Comment by ixzh** [comment]
HI, I also have the promblem when running `leftwm-theme apply THEME`, but running `./up` from the innermost theme folder works...

**Comment by VuiMuich** [comment]
> HI, I also have the promblem when running `leftwm-theme apply THEME`, but running `./up` from the innermost theme folder works...

Welcome Adventurer!
Have you installed the theme with `leftwm-theme install`?
I believe `leftwm-theme` does not yet support "local themes".

**Comment by mautamu** [comment]
I see what the issue is with Soothe in particular. LeftWM-Theme needs to link to Soothe/theme/, not Soothe/. You can manually link in that case; otherwise we'll need to help LeftWM-Theme with a relative_directory tag.

**Comment by VuiMuich** [comment]
> I see what the issue is with Soothe in particular. LeftWM-Theme needs to link to Soothe/theme/, not Soothe/. You can manually link in that case; otherwise we'll need to help LeftWM-Theme with a relative_directory tag. 

Maybe `leftwm-theme` could look for the `up` script also in subdirectories?

**Comment by winston0410** [comment]
> So if we are ant to check if `up`and `down` have a shebang line which ones would we like to test for?
> Only `#!/usr/bin/env bash`, or also `#!/bin/bash` and `#!/bin/sh`? Any others?
> I might get a PR (possibly only as draft) for a additional check in `leftwm-check` ready by tomorrow.

Coming back to this issue after a while, is there any conclusion on this at the moment? Which one is preferred?

**Comment by VuiMuich** [comment]
> > So if we are ant to check if `up`and `down` have a shebang line which ones would we like to test for?
> > Only `#!/usr/bin/env bash`, or also `#!/bin/bash` and `#!/bin/sh`? Any others?
> > I might get a PR (possibly only as draft) for a additional check in `leftwm-check` ready by tomorrow.
> 
> Coming back to this issue after a while, is there any conclusion on this at the moment? Which one is preferred?

 We don't have any checks for the shebang in up/down scripts yet.

Probably would be best to "grep" the first line and match it against the most common shebang variants.
As theoretically it should be possible to use any shell (even POSIX-non-compliant, as long as the script executes properly) it would be impossible to handle all possible cases here.
Maybe one match arm could test for `#!/` and warn about a non-standard shell being used.

**Comment by winston0410** [comment]
I guess instead of grepping the first line, the last line should be grepped instead? There will be exception like this I guess: 

http://iam.travishartwell.net/2015/06/17/nix-shell-shebang/

I guess it is safe to just test for `#!/ `, thought it may not be very accurate. But at least there will be a warning.

**Comment by VuiMuich** [comment]
I may be mistaken, but I believe the shebang has to be the first line of a document, as the rest of the document basically is just arguments to the command following the shebang.

I would Test `#!/usr/bin/bash`, `#!/bin/bash` and `#!/usr/bin/env bash` and return `Ok` as this should suffice to indicate the script should work.
`#!/` for a shebang like `#!/usr/fish` will `WARNING: Usage of of non-standard shebang '#!/usr/bin/fish' in 'up' script. Proper execution cannot be checked.`
And if the script fails for other reasons, there's other places then leftwm-check to debug this IMO.

**Comment by winston0410** [comment]
Btw I have just tried out this issue again. I have added the shebang this time, but still it is not triggered.

```nix
#! /usr/bin/env nix-shell
#! nix-shell -i bash

leftwm-command "LoadTheme $HOME/.config/leftwm/themes/current/theme.toml"
```

Again my file is owned by the `root`, as I am using NixOS and I want this file to be managed by the root and to be reproducible:

```nix
❯ ls -l
dr-xr-xr-x root root   4.0 KB Thu Jan  1 01:00:01 1970  .
drwxrwxr-t root nixbld 2.9 MB Wed Sep 15 20:28:41 2021  ..
.r-xr-xr-x root root   107 B  Thu Jan  1 01:00:01 1970  down
.r--r--r-- root root    49 B  Thu Jan  1 01:00:01 1970  theme.toml
.r-xr-xr-x root root   122 B  Thu Jan  1 01:00:01 1970  up
```

and I have tried to execute the `up` manually in `.xsession`, but I got the error like this:

```nix
thread 'main' panicked at 'ERROR: Couldn't find commands.pipe', src/bin/leftwm-command.rs:29:10
```

I will try removing the `up` script from root and try again, hopefully it works.

**Comment by VuiMuich** [comment]
what's `ls -l $XDG_RUNTIME_DIR/leftwm/` on your system?
are you running `leftwm` also as root?

**Comment by winston0410** [comment]
`ls -l $XDG_RUNTIME_DIR/leftwm/`

```
❯ ls -l $XDG_RUNTIME_DIR/leftwm
drwxr-xr-x hugosum users  80 B Wed Sep 15 21:03:22 2021  .
drwx------ hugosum users 160 B Wed Sep 15 21:01:40 2021  ..
|rwx------ hugosum users   0 B Wed Sep 15 21:03:22 2021  commands.pipe
srwxr-xr-x hugosum users   0 B Wed Sep 15 21:03:22 2021  current_state.sock
```
The `pipe` is there, maybe it is not created yet when `.xsession` run?

`procs | rg leftwm`

```
 3811  hugosum          │       0.0 0.0 00:00:00 │ /nix/store/0mva6qs2fdip1d8n4k0qk9c8fg4iagkg-leftwm-0.2.8/bin/leftwm
 3812  hugosum          │       9.5 0.1 00:00:00 │ /nix/store/0mva6qs2fdip1d8n4k0qk9c8fg4iagkg-leftwm-0.2.8/bin/leftwm-worker
 5474  hugosum          │ pts/5 0.0 0.1 00:00:00 │ rg leftwm
```

And I have just tried again. This time I own the file.

```
~/.config/leftwm/themes/current
❯ ls -l
drwxr-xr-x hugosum users 4.0 KB Wed Sep 15 21:02:40 2021  .
drwxr-xr-x hugosum users 4.0 KB Wed Sep 15 21:01:30 2021  ..
.rwxr-xr-x hugosum users 107 B  Wed Sep 15 21:02:40 2021  down
.rw-r--r-- hugosum users  49 B  Wed Sep 15 21:02:29 2021  theme.toml
.rwxr-xr-x hugosum users 122 B  Wed Sep 15 20:48:38 2021  up
```

`pkill leftwm` and restart it, but the script is not called as well.

**Comment by VuiMuich** [comment]
I've tried to create a bare minimum theme my self now:
`up script`:
```bash
#!/usr/bin/env bash

leftwm command "UnloadTheme"

leftwm command "LoadTheme $HOME/.config/leftwm/themes/current/theme.toml"
```
*Note: as a convention unloading a theme should happen with a down-script that is copied to `/tmp/leftwm-down-theme` with the following snippet:*
```bash
# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $HOME/.config/leftwm/themes/current/down /tmp/leftwm-theme-down
```
`down` script:
```bash
#!/usr/bin/env bash

leftwm command "UnloadTheme"
```
`theme.toml`:
```toml
default_border_color = '#000000'
floating_border_color = '#000000'
focused_border_color = '#FF0000'
border_width = 10
margin = 5
```
**Important: it appears, that this is the absolute minimum a theme file needs to contain, otherwise parsing will fail.**

I'd like to hear some opinions, whether all fields in `theme.toml` should be optional, or if we want the above to stay the bare minimum.

**Comment by winston0410** [comment]
@VuiMuich Thank you for helping out, but unfortunately still it doesn't work.

File structure:

```
~
❯ tree .config/leftwm
.config/leftwm
├── config.toml
└── themes
    └── current
        ├── up
        ├── down
        └── theme.toml
```

And I have the same file content with you, according to the minimal config you have up there.

**Comment by winston0410** [comment]
> I've tried to create a bare minimum theme my self now:
> `up script`:
> 
> ```shell
> #!/usr/bin/env bash
> 
> leftwm command "UnloadTheme"
> 
> leftwm command "LoadTheme $HOME/.config/leftwm/themes/current/theme.toml"
> ```
> 
> _Note: as a convention unloading a theme should happen with a `down` script, which undos all of the things the upscript launches and that is symlinked or copied to `/tmp/leftwm-down-theme` with the following snippet:_
> 
> ```shell
> # Down the last running theme
> if [ -f "/tmp/leftwm-theme-down" ]; then
>     /tmp/leftwm-theme-down
>     rm /tmp/leftwm-theme-down
> fi
> ln -s $HOME/.config/leftwm/themes/current/down /tmp/leftwm-theme-down
> ```
> 
> `down` script:
> 
> ```shell
> #!/usr/bin/env bash
> 
> leftwm command "UnloadTheme"
> ```
> 
> `theme.toml`:
> 
> ```toml
> default_border_color = '#000000'
> floating_border_color = '#000000'
> focused_border_color = '#FF0000'
> border_width = 10
> margin = 5
> ```
> 
> **Important: it appears, that this is the absolute minimum a theme file needs to contain, otherwise parsing will fail.**
> If this does not solve the issue, I don't know what else could be the culprit.
> 
> I'd like to hear some opinions, whether all fields in `theme.toml` should be optional, or if we want the above to stay the bare minimum.
> 
> _I added those infos to the wiki_

Ok this is finally working now! Not the permission issue, but the shebang!!!. Even thought I don't have anything in my `/usr/bin/`, the `up` script is only running, if the `shebang` is either `#!/usr/bin/env bash` or `#!/usr/bin/env sh`

This is my `/usr/bin`:

```
❯ ls /usr/bin
 .   ..   env
```

Is this the expected behavior, where it is strictly requiring the shebang of bash or env?

Closing this as it is solved, but I think the discussion can go on.

**Comment by VuiMuich** [comment]
Glad we were able to help. 

On side of `leftwm` expected behavior would be, that any script that runs in a terminal emulator could be used as `up` script. Obviously it needs to `leftwm command "LoadTheme...`, but that's basically it.

Expacted behavior of the shebang is to run the command after the `#!`, so `#!sh` would most certainly work as well, but has no guarantee on portability, as some systems could have linked `sh` to some non posix compliant shell and the place where to find `bash` might vary as well therefore the `/usr/bin/env`.
