### ISSUE TITLE
Bug: Focus Next and Previous Tag command takes you to a tag which shouldn't exist

### ISSUE THREAD

**Issue by VoltaireNoir** [leftwm/leftwm#437]
I have set up keybindings for "FocusNextTag" and "FocusPreviousTag" and I have a total of 9 tags. Moving between tags works as intended using the keybindings, however, when I go to the previous tag from Tag 1, it takes me to a hidden tag which shouldn't exist. Same thing happens when I go to the next tag from Tag 9. It's as if there's a hidden Tag 10 which is only accessible through this the focus tag command.

**Steps to reproduce the behavior:**
1. Set up keybindings for "FocusNextTag" and "FocusPreviousTag" or execute `leftwm-command "FocusNextTag" / "FocusPreviousTag" ` from the terminal
2. Try going to the previous tag from your first tag or next from your last tag using the commands from the first step
3. You'll end up in a new tag which works but shouldn't exist

**Expected behavior**
When "FocusPreviousTag" is executed from the user's first tag, it should take the user to the last tag (Tag 9, in my case). 

When "FocusNextTag" is executed from the user's last tag, it should take the user to the first tag (Tag 1, in my case).

**Comment by AethanFoot** [comment]
Ah, that would be the tag that scratchpads go to when hidden. I will have a look a bit later into skipping it for these commands.
Thanks.

**Comment by VoltaireNoir** [comment]
> Ah, that would be the tag that scratchpads go to when hidden. I will have a look a bit later into skipping it for these commands.
> Thanks.

Great! Glad it was helpful.
