### ISSUE TITLE
Path for partial liquid  templates

### ISSUE THREAD

**Issue by stevensonmt** [leftwm/leftwm#439]
I have been unable to find any documentation on liquid that would help me understand the directory structure needed to use partial templates within liquid templates. I found one shopify specific thread that suggested templates need to be in a `templates` directory with a sibling `snippets` directory for partial templates. This does not seem to work for my polybar config.
```
my_theme/
               |_polybar.config
               |_templates/
               |          |_main_template.liquid
               |
               |_snippets/
                         |_partial.liquid
```
I have tried different syntax in main_template.liquid, such as: `{% include 'partial' %}`, `{% render 'partial' %}`, `{% snippet assign partial = 'partial' %}`, and replacing single quotes with double quotes. These return errors of `partial does not exist` for `include` or `unable to parse template ... Unknown tag` for the `render` and `snippet assign` version. Any suggestions?

**Comment by stevensonmt** [comment]
LOL. Of course five minutes after posting I stumble upon a method that works. The above directory structure is correct. the partial template requires the name be prepended with an underscore like `_partial.liquid`. In the main template I had success with:
```
{% assign partial = 'partial' %}
{{ partial }}
```
Might update the wiki with this info.

**Comment by VuiMuich** [comment]
This is a great find! Thanks!

**Comment by VuiMuich** [comment]
wait, what happened to your  find with `_partial_template.liquid`?

**Comment by stevensonmt** [comment]
It didn't actually work. It was just printing the assign variable. My test partial template was just `"partial"`, so I thought it was working. Dumb unit test was dumb.

**Comment by VuiMuich** [comment]
> It didn't actually work. It was just printing the assign variable. My test partial template was just `"partial"`, so I thought it was working. Dumb unit test was dumb. I undid the wiki misinformation but did fix a few typos.

Too bad, but thanks for fixing the typos.

**Comment by stevensonmt** [comment]
Yeah, this has been super frustrating not being able to find any information on something as simple as the project directory structure.

**Comment by stevensonmt** [comment]
I think I found the issue. In `leftwm-state` when building the template parser you need to register the available partials. So we would need
```
let template = liquid::ParserBuilder::with_stdlib()
.build()
.partials(partials)
.expect("Unable to build template")
.parse(&template_str)
.expect("Unable to parse template");
```
We could add a `-p` flag for specifying the partials directory path. Then the variable `partials` is set by iterating over the filenames in that directory before getting passed to `ParserBuilder::partials()`. Does that seem reasonable?

**Comment by stevensonmt** [comment]
If anyone wants to take a look at [this commit](https://github.com/stevensonmt/leftwm/commit/70caeda14b51be32662ce08a652be6956526cf42) and let me know what they think I'd appreciate it. It felt a little chaotic while writing it so I'm not putting it in a PR just yet.

**Comment by mautamu** [comment]
Looks pretty good! Didn’t run it or anything, but overall looks fine. Might want to run clippy and fmt on it (line 86 looks a bit long but idk for sure). Not sure if this impacts leftwm-check in any way but might be something to look into.

**Comment by stevensonmt** [comment]
Cool, thanks for looking. At some point clippy stopped getting run in vim with ALE for me, but I just fixed that. I thought about adding something to leftwm-check, but as it stands now that tool isn't checking anything to do with themes. Should I try to add that to leftwm-check?

**Comment by VuiMuich** [comment]
> Cool, thanks for looking. At some point clippy stopped getting run in vim with ALE for me, but I just fixed that. I thought about adding something to leftwm-check, but as it stands now that tool isn't checking anything to do with themes. Should I try to add that to leftwm-check?

I am about to add a PR for checking some minimal theme requirements. Though at this point I don't test for anything liquid related.
