### ISSUE TITLE
Highlight tags that are being used (Polybar)

### ISSUE THREAD

**Issue by VoltaireNoir** [leftwm/leftwm#441]
I am not sure whether this functionality already exists or that it doesn't, but I can't seem to figure out how to highlight tags that are in use (i.e contain running windows/programs but aren't currently focused/active) in Polybar. The tag/workspace indicator on the left only highlights the currently active tag. My current theme is based on the basic_polybar theme that is included in this repo.

I'll include the config lines that I think are responsible for the tag indicator in polybar in case the problem is with my config:

**template.liquid**
```
{% for tag in workspace.tags %}
{% if tag.mine %}
%{A1:$SCRIPTPATH/change_to_tag {{workspace.index}} {{tag.index}}:}
%{F#4c566a}%{B#88c0d0}  {{tag.name}}  %{B-}%{F-}
%{A}
{% elsif tag.visible  %}
%{A1:$SCRIPTPATH/change_to_tag {{workspace.index}} {{tag.index}}:}
%{F#ffffff}%{B#E60053}  {{tag.name}}  %{B-}%{F-}
%{A}
{% else tag.visible  %}
%{A1:$SCRIPTPATH/change_to_tag {{workspace.index}} {{tag.index}}:}
%{F#FFFFFF}  {{tag.name}}  %{F-}
%{A}
{% endif %}
{% endfor %}
%{c}
{{ window_title }}
```

**polybar.config**
```
[bar/mainbar0]
inherit = bar/barbase
modules-left = workspace0
[module/workspace0]
type = custom/script
exec = leftwm-state -w 0 -t $SCRIPTPATH/template.liquid
tail = true

[bar/mainbar1]
inherit = bar/barbase
modules-left = workspace1
[module/workspace1]
type = custom/script
exec = leftwm-state -w 1 -t $SCRIPTPATH/template.liquid
tail = true

[bar/mainbar2]
inherit = bar/barbase
modules-left = workspace2

[module/workspace2]
type = custom/script
exec = leftwm-state -w 2 -t $SCRIPTPATH/template.liquid
tail = true

[bar/mainbar3]
inherit = bar/barbase
modules-left = workspace3
[module/workspace3]
type = custom/script
exec = leftwm-state -w 3 -t $SCRIPTPATH/template.liquid
tail = true
```

**Comment by VuiMuich** [comment]
You can use `tag.busy` in an additional elseif to Style busy but not visible tags.

**Comment by VoltaireNoir** [comment]
> You can use `tag.busy` in an additional elsif in the `template.liquid` to style busy but not visible tags.

Ah that worked perfectly! Thank you so much.

**Comment by VuiMuich** [comment]
You are very welcome!
