### ISSUE TITLE
Theme isn't applying

### ISSUE THREAD

**Issue by JacobHin2** [leftwm/leftwm#442]
Using a symlink to enable a (locally made) theme
Not made an 'up' script yet, just running:
`leftwm-command "LoadTheme ~/.config/leftwm/themes/current/theme.toml"`

My changes don't seem to apply and I'm not quite sure why 😕

**Comment by stevensonmt** [comment]
Does your script have `#!/bin/bash` or some similar line appropriate for your system at the top?

**Comment by ivohulsman** [comment]
Just pitching in; I had the same issue. Making `up` executable fixed it for me!

**Comment by VuiMuich** [comment]
> Does your script have `#!/bin/bash` or some similar line appropriate for your system at the top?
> 
> Also make sure your `up` script is executable.

Might also want to check the `down` script as well 😉

**Comment by JacobHin2** [comment]
thanks, sorry haven't checked github past few days, will close the issue now thanks for your help :)
