### ISSUE TITLE
[Question] Is leftwm extensible ?

### ISSUE THREAD

**Issue by kronolynx** [leftwm/leftwm#449]
Is there any way to extend leftwm like xmonad in haskell or awesomewm in lua ?

**Comment by AethanFoot** [comment]
There currently isnt an implemented way of doing this, however if you know some rust and download the source adding different functionality is simple enough. We do need to add more code documentation (which Im hopefully gonna try and tackle soon), but we are always happy and willing to help if you jave any issues.
Thanks.
