### ISSUE TITLE
Random freezing issues, hard to troubleshoot 

### ISSUE THREAD

**Issue by JacobHin2** [leftwm/leftwm#454]
**Describe the bug**
Getting random cases of leftwm freezing, not responding to keyboard input, perhaps its a picom issue I'm not too sure.

**To Reproduce**
Normally using my computer. Seems to freeze, I then have to use tty to restart lightdm and login again. 

**Expected behavior**
LeftWM (or otherwise) to not freeze my PC.

**Screenshots**
[Example is here](https://imgur.com/rl5dX4j)

**Environment:**
 - OS/Distro: Arch Linux, using kernel 5.10 lts
 - Output of `leftwm-check`

`
:: LeftWM version: 0.2.9
:: LeftWM git hash: 771cc98
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
`

**Additional context**
WM doesn't seem to respond to any shortcuts. Happens very often, I am using the latest GitHub commits for the bleeding edge version, however no one else seems to be reporting any issue like this that I know of , so could be something else causing this.

*Sorry if the issue is unclear, it's a bit of a fleeting problem that keeps coming and going*

**Comment by VuiMuich** [comment]
Welcome Adventurer!

Let me ask you a few things back:
- have you compiled leftwm yourselfe, or did you get the AUR package? If you compiled it yourself you could rebuild it with `cargo b --features=journald` and look if you find something in journald, when leftwm appears to freeze.
- when leftwm freezes and you have open windows, are these still responsive?
- when leftwm freezes, can you use the tty to still launch a terminal (e.g. `DISPLA=:0 alacritty`) or use `leftwm command NextLayout` (or any other command which should show any response)?
- which picom fork are you using?

**Comment by JacobHin2** [comment]
> Welcome Adventurer!
> 
> Let me ask you a few things back:
> 
> * have you compiled leftwm yourselfe, or did you get the AUR package? If you compiled it yourself you could rebuild it with `cargo b --features=journald` and look if you find something in journald, when leftwm appears to freeze.

I compiled from source using cargo. I'll try rebuilding with journald and let you know what I get.

> * when leftwm freezes and you have open windows, are these still responsive?

No, I can just see my desktop. All windows are hidden and my keyboard shortcuts don't want to work.

> * when leftwm freezes, can you use the tty to still launch a terminal (e.g. `DISPLA=:0 alacritty`) or use `leftwm command NextLayout` (or any other command which should show any response)?

I never thought to do that, I just opened a TTY and logged out to lightdm.

> * which picom fork are you using?

[This one. It come with rounded corners and other experimental features.](https://github.com/jonaburg/picom)

One small not, most of this freezing behavior occurs when I do a soft restart.

**Comment by stevensonmt** [comment]
I'm using [this picom fork from AUR](https://aur.archlinux.org/packages/picom-ibhagwan-git/) which has rounded corners and the dual kawase blur. I haven't had any issues with it, but not sure if picom is likely to be the source of your problem. If picom crashed you would expect just to not have compositor features like transparency and shadows rather than a total freeze.

**Comment by VuiMuich** [comment]
> > * when leftwm freezes and you have open windows, are these still responsive?
> 
> No, I can just see my desktop. All windows are hidden and my keyboard shortcuts don't want to work.

> One small not, most of this freezing behavior occurs when I do a soft restart.

 Are you trying to rename your tags? If so, you are probably experiencing #207

> > * when leftwm freezes, can you use the tty to still launch a terminal (e.g. `DISPLA=:0 alacritty`) or use `leftwm command NextLayout` (or any other command which should show any response)?
> 
> I never thought to do that, I just opened a TTY and logged out to lightdm.

Another thing you could try from tty is to kill `leftwm-worker` wich is basically the same as a ` HardReload`.
Maybe your `down` script is somehow broken so at a restart of leftwm some wonky things are happening?
 
> > * which picom fork are you using?
> 
> [This one. It come with rounded corners and other experimental features.](https://github.com/jonaburg/picom)

I am using the same fork. And tbh I am not sure if the conky issues I have are actually related to that picom fork.
I use jonaburg-picom-git from the aur, and I installed it for it's fade animation to slide windows in.

**Comment by VuiMuich** [comment]
Oh, this is interesting:
I did `killall picom` and `picom --experimental-backends` but forgot to add a ` &` at the end.
This left my WM frozen (but the scratchpad window and my `eww` windows stayed there).
a simple `killall picom` from tty didn't work, only when I killed picom from `bpytop` (htop would work probably as well) freed my system.
Killing `leftwm-worker` didn't help.

So maybe you are missing the ` &` in your upscript? It should be `picom -experimental-backends &` or `  picom --experimental-backends &> /dev/null &`

**Comment by JacobHin2** [comment]
> Oh, this is interesting:
> I did `killall picom` and `picom --experimental-backends` but forgot to add a ` &` at the end.
> This left my WM frozen (but the scratchpad window and my `eww` windows stayed there).
> a simple `killall picom` from tty didn't work, only when I killed picom from `bpytop` (htop would work probably as well) freed my system.
> Killing `leftwm-worker` didn't help.
> 
> So maybe you are missing the ` &` in your upscript? It should be `picom -experimental-backends &` or ` picom --experimental-backends &> /dev/null &`

Using default (no theme) right now.
I was using a script in xprofile

nitrogen --restore && picom -b -i 0.8 -f --experimental-backends --round-borders 1 &
sxhkd &
xrandr --newmode "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync &
xrandr --addmode HDMI-A-1 "1920x1080_60.00"
xrandr --output HDMI-A-1 --mode "1920x1080_60.00"
xrandr --output HDMI-A-1 --left-of DVI-D-0

I removed the soft restart hotkey because it seemed to cause me issues.
It's weird, because when this bug occurs I can still use my rofi menus which are using sxhkd.
Not sure how to fix?

Another question, I have 2 1080p monitors side by side, although I added this
`[[workspace]]
x = 0
y = 0
width = 1920
height = 1080

[[workspace]]
x = 1920
y = 0
width = 1920
height = 1080`

to config.toml to set them up, I don't think I am doing this correctly though.

**Comment by JacobHin2** [comment]
> to config.toml to set them up, I don't think I am doing this correctly though.
Nevermind, I managed to fix that issue.

**Comment by VuiMuich** [comment]
> > to config.toml to set them up, I don't think I am doing this correctly though.
> 
> 
> 
> Nevermind, I managed to fix that issue.

Let me guess you still had the `workspaces = []` line?

**Comment by VuiMuich** [comment]
> Using default (no theme) right now.
> 
> I was using a script in xprofile
> 
> 
> 
> nitrogen --restore && picom -b -i 0.8 -f --experimental-backends --round-borders 1 &
> 
> sxhkd &
> 
> xrandr --newmode "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync &
> 
> xrandr --addmode HDMI-A-1 "1920x1080_60.00"
> 
> xrandr --output HDMI-A-1 --mode "1920x1080_60.00"
> 
> xrandr --output HDMI-A-1 --left-of DVI-D-0
> 
> 
> 
> I removed the soft restart hotkey because it seemed to cause me issues.
> 
> It's weird, because when this bug occurs I can still use my rofi menus which are using sxhkd.
> 
> Not sure how to fix?

I have my pic on configured in `~/.config/picom/picom.conf` as I have plenty of exceptions from various effects, but I don't believe this is related. 
But maybe you try to separate nitrogen and picom into individual lines, the `&&` here looks a bit sus.

**Comment by JacobHin2** [comment]
> > > to config.toml to set them up, I don't think I am doing this correctly though.
> > 
> > 
> > Nevermind, I managed to fix that issue.
> 
> Let me guess you still had the `workspaces = []` line?

No I just had to logout/in again.

**Comment by JacobHin2** [comment]
> > Using default (no theme) right now.
> > I was using a script in xprofile
> > nitrogen --restore && picom -b -i 0.8 -f --experimental-backends --round-borders 1 &
> > sxhkd &
> > xrandr --newmode "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync &
> > xrandr --addmode HDMI-A-1 "1920x1080_60.00"
> > xrandr --output HDMI-A-1 --mode "1920x1080_60.00"
> > xrandr --output HDMI-A-1 --left-of DVI-D-0
> > I removed the soft restart hotkey because it seemed to cause me issues.
> > It's weird, because when this bug occurs I can still use my rofi menus which are using sxhkd.
> > Not sure how to fix?
> 
> I have my pic on configured in `~/.config/picom/picom.conf` as I have plenty of exceptions from various effects, but I don't believe this is related.
> But maybe you try to separate nitrogen and picom into individual lines, the `&&` here looks a bit sus.

Okay

**Comment by VuiMuich** [comment]
> > > > to config.toml to set them up, I don't think I am doing this correctly though.
> 
> > > 
> 
> > > 
> 
> > > Nevermind, I managed to fix that issue.
> 
> > 
> 
> > Let me guess you still had the `workspaces = []` line?
> 
> 
> 
> No I just had to logout/in again.

I see. Usually we use the soft reload to put changes to `config.toml` to work.

**Comment by JacobHin2** [comment]
> > > > > to config.toml to set them up, I don't think I am doing this correctly though.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Nevermind, I managed to fix that issue.
> > 
> > 
> > > 
> > 
> > 
> > > Let me guess you still had the `workspaces = []` line?
> > 
> > 
> > No I just had to logout/in again.
> 
> I see. Usually we use the soft reload to put changes to `config.toml` to work.

That seemed to cause the bug for me. I'll try clearing my themes directory as you mentioned it earlier and checking that seemed to help me

**Comment by JacobHin2** [comment]
The issue has seemedly resolved itself, thanks for the help

**Comment by VuiMuich** [comment]
Always happy to help.
