### ISSUE TITLE
cant logout

### ISSUE THREAD

**Issue by pigasspig** [leftwm/leftwm#457]
**Describe the bug**
The bug is that i cant log out 

**To Reproduce**
1. nano into .config/leftwm/config.toml
2. go to the bottom
3. and put 
 
 [[keybind]]
command = "Execute"
value = "loginctl kill-session $XDG_SESSION_ID"
modifier = ["modkey", "shift"]
key = r

**Expected behavior**
i expected it to log me out of leftwm but it didnt it logs me out when i tpe in terminal

**Screenshots**

**Environment:**
 - OS/Distro: arch linux
 - Output of `leftwm-check` configuration failed. Reason: LeftError { inner: TomlParse(Error { inner: ErrorInner { kind: UnquotedString, line: Some(158), col: 6, at: Some(2425), message: "", key: [] } }) }

**Additional context**
yes also the rofi dont work

**Comment by VuiMuich** [comment]
Your are simply missing quotes around you key.
Should be:
`key = "r"`

**Comment by pigasspig** [comment]
> Your are simply missing quotes around you key.
> Should be:
> `key = "r"`

i did that but it still didnt work

**Comment by VuiMuich** [comment]
Is leftwm-check now reporting OK?

**Comment by pigasspig** [comment]
> Is leftwm-check now reporting OK?

yes

**Comment by pigasspig** [comment]
> What is your binding for `SoftReload`?
> 
> Plus, have you checked your command is actually working? I mean it basically looks ok.

i dont have soft reload in the yoml

**Comment by pigasspig** [comment]
toml*

**Comment by VuiMuich** [comment]
But you need to SoftReload in order to get changes to config.toml to work.

**Comment by pigasspig** [comment]
> But you need to SoftReload in order to get changes to config.toml to work.

oh

**Comment by VuiMuich** [comment]
I wish you a pleasant adventure discovering more of leftwm!

I updated the [wiki](https://github.com/leftwm/leftwm/wiki/Config#configuring-leftwm) to clarify that relaods are necessary.
