### ISSUE TITLE
Not EWMH compliant?

### ISSUE THREAD

**Issue by Phate6660** [leftwm/leftwm#46]
I like to use [`XWinMosiac`](https://github.com/soulthreads/xwinmosaic) as my window switcher, and I can't use it due to this error:

`Error: your WM does not support EWMH specifications.`

I know that I can just use Rofi as my Window switcher since I already have it installed, but XWinMosiac just looks really nice.

**Comment by lex148** [comment]
This has been fixed but there are two gotchas. 

1) You really need to use the -S option so I would recommend adding a line like this in your config

~/.config/leftwm/config.toml
[[keybind]]
command = "Execute"
value = "xwinmosaic -S"
modifier = ["modkey"]
key = "Tab"

2) XWinMosiac still doesn't work with floating windows. I'm about to start working on some tweaks / improvements for floating windows, so stay tuned for a fix for them.
