### ISSUE TITLE
The theme is not working.

### ISSUE THREAD

**Issue by amarakon** [leftwm/leftwm#467]
I am using the basic_polybar theme, and the first time I tried it, it worked fine. But now that I switched back to LeftWM, it doesn't work anymore. It's just using the basic default leftwm theme. I set it up exactly how the instructions asked me to.

**Comment by VuiMuich** [comment]
Welcome Adventurer!
Can you post the output of `leftwm-check`
By "switched back" you mean you have used another WM for some time, or did you just log off and back in again?

**Comment by amarakon** [comment]
> Welcome Adventurer!
> Can you post the output of `leftwm-check`
> By "switched back" you mean you have used another WM for some time, or did you just log off and back in again?

By switched back I mean I switched to i3-wm, then I switched back to leftwm.
Output of leftwm-check:
:: LeftWM version: 0.2.9
:: LeftWM git hash: 0375604
:: Loading configuration . . .
    -> Configuration loaded OK
WARN: The file loaded was the default. Your configuration is likely invalid
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
Error: LeftError { inner: IoError(Custom { kind: Other, error: "File: 'up' not found." }) }

I am on Gentoo Linux, if that helps.

**Comment by amarakon** [comment]
It says that file up is not found, but my up file is in ~/.config/leftwm/themes/basic_polybar/ which is symlinked with the "current" folder in the same directory.

**Comment by amarakon** [comment]
> It says that file up is not found, but my up file is in ~/.config/leftwm/themes/basic_polybar/ which is symlinked with the "current" folder in the same directory.

Additionally, my config.toml file works but my theme doesn't work.

**Comment by VuiMuich** [comment]
Can you double check you symlink is correct and `ls -l ~/.config/leftwm/themes/current`?
I believe it needs to be at least relative to `$HOME` or `~` if it is just relative to the themes direcotry it would not work, iirc.
Also could you please post the theme-related snippet of `leftwm-check -v`

**Comment by amarakon** [comment]
ls -l ~/.config/leftwm/themes/current:
total 0
lrwxrwxrwx 1 amarakon amarakon 13 Sep  4 16:01 basic_polybar -> basic_polybar

leftwm-check -v:
:: Checking theme . . .
WARN: Found `current` theme folder: "/home/amarakon/.config/leftwm/themes/current". Use of a symlink is recommended, instead.
Error: LeftError { inner: IoError(Custom { kind: Other, error: "File: 'up' not found." }) }

**Comment by amarakon** [comment]
I just realized I didn't create the symlink correctly. I recreated the symlink and now it works. Thanks so much.

**Comment by VuiMuich** [comment]
Glad to help!
Hope you'll be able to enjoy your adventures in leftwm :smiley:
