### ISSUE TITLE
How do I remove the gaps on the outer edge of my screen?

### ISSUE THREAD

**Issue by amarakon** [leftwm/leftwm#468]
So I set the margin to 0 in my theme.toml file, and that removed the spaces between the windows. However, I also want to remove the extra space on the outer edges of the windows so that they are fully maximized. How do I do that?

**Comment by VuiMuich** [comment]
You can use `workspace_margins` for this (https://github.com/leftwm/leftwm/wiki/Theme-Config#margins)

**Comment by amarakon** [comment]
It worked, thanks.
