### ISSUE TITLE
How do I make an application launch only at boot and not when I'm restarting leftwm?

### ISSUE THREAD

**Issue by amarakon** [leftwm/leftwm#469]
Sorry I keep opening up issues, but I have another one.

These lines in my "up" file launches nitrogen to set my wallpaper every time I restart leftwm:
#set background
if [ -x "$(command -v nitrogen)" ]; then
  nitrogen --restore
fi

Let's say I want a certain application to launch only at boot but not every time I restart leftwm, how would I do that?

**Comment by mautamu** [comment]
Generally you want to put that in your auto start folder instead:

~/.config/autostart

leftwm obeys standard autostart convention.  


If you want to keep it in the up file, I don’t think there’s a way of putting something in up that just does that, but perhaps setting an environmental variable that gets checked could work.

**Comment by mautamu** [comment]
You can also have a generic up in the leftwm root, see https://github.com/leftwm/leftwm/pull/363

**Comment by amarakon** [comment]
If I don't have an autostart directory in my .config folder, do I just have to do mkdir ~/.config/autostart?

**Comment by VuiMuich** [comment]
I'm not sure how close this relates also to gentoo, but basically this is it:
[Xdg autostart](https://wiki.archlinux.org/title/XDG_Autostart)

**Comment by amarakon** [comment]
Okay so all I had to do was create the autostart directory in my .config folder, then I create the proper .desktop files.
