### ISSUE TITLE
[Enhancement] "-git" aur package?

### ISSUE THREAD

**Issue by Phate6660** [leftwm/leftwm#47]
Would you consider making a "-git" aur package? I noticed that you've added some things like "disabled borders while in fullscreen" and it would be great to be able to have that stuff as soon as you push it to the repo. Currently, I'm using the aur package you have set up which means I have to wait until you decide that you added/edited enough stuff to update the pkgbuild.

It's perfectly fine if you don't want to make a "-git" package, I'll just have to start building from source (which is a bit tedious to clone the repo every time), but it'd be worth it in my opinion.

Hope you consider it. :)

**Comment by lex148** [comment]
"-git" version of the package is up
https://aur.archlinux.org/packages/leftwm-git/
