### ISSUE TITLE
Intellij/Brave pop-up exits fullscreen mode

### ISSUE THREAD

**Issue by lkadalski** [leftwm/leftwm#497]
**Describe the bug**
Another thing with Intellij/Brave ;) When I'm in fullscreen mode inside intellij or Brave a new popup is forcing leftwm to enter the tile mode.
Pop-up is kind of Dialog window so it's not tiled. It happens with one intellij/brave on workspace as well with multiple. 

**To Reproduce**
1. Open Intellij/Brave
2. Get into leftwm's Full screen mode
3. Trigger any pop-up (File/Settings)(Brave -> r click save link as)
4. Intellij/Brave returns to tile mode(error)

**Expected behavior**
I tested it with other application like Slack and their pop-ups doesn't change the mode.

**Environment:**
 - ArcoLinux
 - Output of `leftwm-check`
 ```
:: LeftWM version: 0.2.9
:: LeftWM git hash: 6d635d1-modified
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```
 
 Is it expected behaviour?

**Comment by lkadalski** [comment]
I'm investigating issue. But honestly I'm not sure how it should behave?
New (dialog) window should be focus and fullscreened ?
I'm not sure if it's possible to have a focused dialog window before fullscreened window.

**Comment by VentGrey** [comment]
In i3 the popups just get "ignored" and those Popups appear over the fullscreen taking a small space where it should be on the screen 🤔

**Comment by lkadalski** [comment]
I was able to set in such way that new pop-up is fullscreened in front of fullscreened main window. 
It weird at beginning but I think I may get use to it. 
Ignoring pop-ups or hiding it under fullscreened window is not expected behavior from my perspective. 
What do you think?

**Comment by VuiMuich** [comment]
"Ignored" in sense of "not being handled by WM for tiling" I believe. 

So ideally a pop up is in front of a fullscreen window, but floating so size is as desired by the window.

So, what did you do to achieve what you got so far?

**Comment by lkadalski** [comment]
Yes @VuiMuich in that sense.
Agree, that'd be ideally. I was not sure but it looks like it's by [design in the code](https://github.com/leftwm/leftwm/blob/f643aafbc45d1d7911d2d300122110bf32a176fc/leftwm-core/src/handlers/window_handler.rs#L264).
I tried to play with it a bit, but without much success. I hammer out one solution when new window is full-screened whenever parent is and has higher precedence (in front of parent). But as you mentioned is not an ideal one.
Nevertheless @AethanFoot found a solution I think.

**Comment by VuiMuich** [comment]
I just checked vlc player quickly and this one works now as expected. :+1:

**Comment by lkadalski** [comment]
Great,
what I'm waiting for ? :rofl: 
Will check it out tomorrow :+1:
