### ISSUE TITLE
URXVT Scratchpad Issue

### ISSUE THREAD

**Issue by FranLMSP** [leftwm/leftwm#502]
**To Reproduce**
When I try to use `urxvtc` as a scratchpad, it will spawn as a regular tiled Window like this

![pic-select-211003-0806-19](https://user-images.githubusercontent.com/32037942/135755214-6dcb34a8-46b0-4cb4-9928-a041c8fd76fa.png)

And if I use `urxvt` instead, it does spawn as a scratchpad but very small like this

![pic-select-211003-0807-12](https://user-images.githubusercontent.com/32037942/135755251-008a48ad-4a5a-40b1-9a23-a62b474d3375.png)

It works fine with Alacritty tho

![pic-select-211003-0808-43](https://user-images.githubusercontent.com/32037942/135755293-3a27717d-7719-466c-93c4-4b89e56c8cd1.png)

But I want to use `urxvtd` + `urxvtc` to optimize a bit more of RAM on my system, I like to have a bunch of terminals open and Alacritty uses ~76MB per instance

**Environment:**
 - OS/Distro: I use Arch btw
 - Output of `leftwm-check`
 ```
 :: LeftWM version: 0.2.9
:: LeftWM git hash: b7297f3
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
 ```
 - My config for the scratchpad:
 ```
modkey = "Mod4"
mousekey = "Mod4"
workspaces = []
tags = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]
layouts = ["MainAndVertStack", "MainAndHorizontalStack", "MainAndDeck",
 "GridHorizontal", "EvenHorizontal", "EvenVertical", "Fibonacci", "Cent
erMain", "CenterMainBalanced", "Monocle", "RightWiderLeftStack", "LeftW
iderRightStack"]
# scratchpad = []
disable_current_tag_swap = true
focus_behaviour = "Sloppy"
focus_new_windows = true

[[scratchpad]]
name = "Calculator"
value = "urxvtc -e calc"

[[keybind]]
command = "ToggleScratchPad"
value = "Calculator"
modifier = ["modkey"]
key = "equal"
 ```
 - And the `~/.Xresources`
 ```
 URxvt.perl-ext-common: default,tabbed,matcher,resize-font,-tabbed
URxvt.foreground: white
URxvt.depth: 32
!!URxvt*background: black
URxvt.background: [67]#000000
URxvt.font: xft:mono:size=13:antialias=true
URxvt.cursorBlink: true
URxvt.scrollBar: false
URxvt.keysym.C-minus:     resize-font:smaller
URxvt.keysym.C-plus:      resize-font:bigger
URxvt.keysym.C-equal:     resize-font:reset
URxvt.keysym.C-question:  resize-font:show
 ```

**Comment by VuiMuich** [comment]
As a first wild guess I'd say `leftwm` has a hard time to distinguish the scratchpad instance of `urxvtc` from regular instances as they both are children of `urxvtd`?

Maybe I can triage this later this evening.

**Comment by VuiMuich** [comment]
Did a quick test and as expected, the pid of the `urxvtc` instances are the same as the `urxvtd` daemon.

Do you have a working example of another WM which is handling this correctly, so we have a reference how they handle such a situation?

**Comment by AethanFoot** [comment]
I thought that exact thing, @VuiMuich , when I saw this earlier. The only thing I can think of would be falling back to or allow the user to select how scratchpads are found. This wouldn't be too difficult as I had already implemented the other main [solution](https://github.com/leftwm/leftwm/pull/315/commits/d46c7653ea8ea3b81ba367916b8ed70c641eb95b), where we find it by the user setting the windows name in its startup.

**Comment by FranLMSP** [comment]
> Do you have a working example of another WM which is handling this correctly, so we have a reference how they handle such a situation?

@VuiMuich I tried with i3wm and it has the same issue, it works with `urxvt` but not with `urxvtc`.
I don't mind using normal `urxvt` for scratchpads tho, but I still have the issue with the window becoming very small on LeftWM (didn't happen on i3)

**Comment by AethanFoot** [comment]
As you are on the lastest, #493 should be available (I have now just realised we need to add this to the wiki). The window shouldn't be defaulting that small, but check whether setting custom values fixes it. If not Ill start digging.

**Comment by VuiMuich** [comment]
> I thought that exact thing, @VuiMuich , when I saw this earlier. The only thing I can think of would be falling back to or allow the user to select how scratchpads are found. This wouldn't be too difficult as I had already implemented the other main [solution](https://github.com/leftwm/leftwm/pull/315/commits/d46c7653ea8ea3b81ba367916b8ed70c641eb95b), where we find it by the user setting the windows name in its startup.

What do you think about a [custom state](https://specifications.freedesktop.org/wm-spec/wm-spec-1.3.html#idm45643490848448) `scratchpad`?

**Comment by AethanFoot** [comment]
That might make scratchpads easier to register and deal with, however the issue with client-server(?) applications would still be apparent. In terms of that issue we may not be able to adapt to this, unless the spawned windows have different names.

I will have a look at the custom state thing as it will allow the current solution to be cleaner, nice find!
Thanks.

**Comment by VuiMuich** [comment]
> That might make scratchpads easier to register and deal with, however the issue with client-server(?) applications would still be apparent. In terms of that issue we may not be able to adapt to this, unless the spawned windows have different names.
> 
> 
> 
> I will have a look at the custom state thing as it will allow the current solution to be cleaner, nice find!
> 
> Thanks.

Ah, yes. I thought we could set this state explicitly, when first launching the scratchpad, but haven't really looked how we actually catch this window in the first place…

**Comment by FranLMSP** [comment]
@AethanFoot I tried setting those parameters and unless I leave the defaults (`width = 51`, `height = 80`, `x = 49`, `y = 20`) sometimes it has no effect and sometimes all scratchpads looks like this

![pic-select-211003-1405-42](https://user-images.githubusercontent.com/32037942/135768692-71600b8e-f314-4671-872c-cac3c4a2391e.png)

The behavior on the screenshot is not consistent so I'm not sure how to replicate it exactly. It happens with either Alacritty, URXVT or a graphical program like Pcmanfm and if I change any parameter to any value. And when I remove the parameters everything comes back to normal. I have two monitors if that's relevant.

**Comment by AethanFoot** [comment]
I seem to have found a repeatable method (it doesn't necessarily make sense), but if I have a terminal open, then reload leftwm, then pkill picom (also worked pkill pcmanfm when one was already open), and then open the scratchpad without doing anything else it happens and seems to stick. This is a bit elaborate but allow me to hopefully find a cause.

**Comment by AethanFoot** [comment]
Ok, I seem to have fixed the consistency. So when values are set they come up consistently. (FYI the smallness seems to to the settings as 80x51 is really small, but it wasn't always applied). Ill put up a pr if you can test it works the same everytime.
Thanks.

**Comment by FranLMSP** [comment]
Ok! let me give it a try

**Comment by FranLMSP** [comment]
@AethanFoot  Seems to be consistent now! I managed to change the size of some scratchpads. Just a couple of things:
- Are the values in pixels? or percentage?
- `urxvt` is still becoming small, but I noticed that for a fraction of a second the window takes the size that I specify and then it becomes small, like `urxvt` trying to take its own size

**Comment by VuiMuich** [comment]
> * Are the values in pixels? or percentage?

Unitless and `px` should be pixels `%` percentage iirc

**Comment by AethanFoot** [comment]
If you want to use pixels use an integer e.g. width = 300. For a percentage use a float between 0 and 1, e.g width = 0.5.
