### ISSUE TITLE
add 0.1.10 tag

### ISSUE THREAD

**Issue by stevensonmt** [leftwm/leftwm#51]
AUR package not building b/c no tag for latest release:

> fatal: '0.1.10' is not a commit and a branch 'makepkg' cannot be created from it
> ==> ERROR: Failure while creating working copy of leftwm git repo

alternatively this could be considered an AUR maintainer's issue and they should change the PKGBUILD to not use the tag in the source.

**Comment by lex148** [comment]
Thanks for spotting this one. fixed now
