### ISSUE TITLE
Flaky test: utils::command_pipe::test::read_command

### ISSUE THREAD

**Issue by cecton** [leftwm/leftwm#514]
**Describe the bug**

Build log: https://github.com/leftwm/leftwm/runs/3846536737

Pretty sure I'm seeing this test failing often on CI. Clearly it is a flaky test. We should address this at some point.

**To Reproduce**

Trigger the CI multiple times?

**Expected behavior**

The test should always succeed. CI or not.

**Screenshots**
:no_entry_sign: 

**Environment:**
 - OS/Distro: GitHub Actions
 - Output of `leftwm-check`: :no_entry_sign: 

**Additional context**
:no_entry_sign:

**Comment by AethanFoot** [comment]
We could just split it into read_good_command and read_bad_command, or something like that.

**Comment by cecton** [comment]
If we don't have a good solution we could use a retry loop. What do you think?

**Comment by AethanFoot** [comment]
This does seem to be actually resolved so closing for now.
