### ISSUE TITLE
multiple master windows

### ISSUE THREAD

**Issue by hertg** [leftwm/leftwm#516]
This feature request is inspired by the same feature from `dwm`.

**Feature**
Allow users to have multiple master windows instead of just a single one, and allow changing the amount of master windows via command/keybinding.

Right now, most of the layouts consist of a single master window and a "stack" with all the other windows (Monocle and CenterMain obviously being a little bit different, but they still have a single "master" window). The master window is always the one on top of the stack of all windows.

My suggestion is to allow to increase and decrease the amount of windows considered "master" windows via command/keybing.

![master-stack](https://user-images.githubusercontent.com/3533648/136689350-dc9997e8-73ac-453b-b281-00355823ca35.png)

**Reasoning**
Similar to the feature where the master window width can be changed dynamically, this introduces even more flexibility to all the layouts. A user could specify keybindings like <kbd>mod + i</kbd> (increase) and <kbd>mod + d</kbd> (decrease) to dynamically adjust how many windows appear in the "master zone" of the layout.

I only really understood how much I've actually used this feature in `dwm` after I switched to LeftWM completely :stuck_out_tongue_closed_eyes:. Below you see some examples on how that behaves in `dwm`.

*Example in CenterMain layout (master on the left)*
![output1](https://user-images.githubusercontent.com/3533648/136688933-7e8e0916-3556-4bef-a1dd-4352e86e46a2.gif)

*Example in VertAndStack layout (master in center)*
![output2](https://user-images.githubusercontent.com/3533648/136688944-60f90fa0-ccdc-444f-9ed2-a1b94735e970.gif)

**Comment by AethanFoot** [comment]
Not quite, it doesn't do anything to aid the current layout files. It currently just holds the layout mode and selected layouts, and holds functions that require the layout list (just new_layout, and next/prevoius_layout). I am currently trying to make things a bit cleaner while waiting on lex to be able to it again.

**Comment by hertg** [comment]
Implemented with #1000
