### ISSUE TITLE
[bug] focus_behaviour 'ClickTo' doesn't change focus when clicking a window while still pressing the mod key

### ISSUE THREAD

**Issue by hertg** [leftwm/leftwm#518]
**Describe the bug**
The `focus_behaviour` ClickTo behaves a bit rough when pressing and holding the mod key.
When creating multiple floating windows and arranging them, I usually do so by pressing and holding down the mod key, then resizing and moving the windows to where I want them to be, without ever letting go of the mod key.

This may be related to #517 

**To Reproduce**
1. Toggle some windows to be floating
2. Press and hold mod key
3. Move/Resize the windows without letting go of mod key

**Expected behavior**
When clicking or resizing an unfocused window, the focus should probably change to this window (?). Right now, it is possible to move a window that isn't focused, but it's not possible to resize a window that's out of focus. Also, clicking on a window should change focus to it, even when the mod key is held down.

**Screenshots**
*None*

**Environment:**
 - OS/Distro: Arch
 - Output of `leftwm-check` -> latest master
    ```
    :: LeftWM version: 0.2.9
   :: LeftWM git hash: b4a0686
   :: Loading configuration . . .
       -> Configuration loaded OK
   :: Checking keybinds . . .
       -> All keybinds OK
   :: Checking environment . . .
       -> Environment OK
   :: Checking theme . . .
       -> Theme OK
   ```

**Additional context**
*None*

**Comment by AethanFoot** [comment]
Well to start debugging and maybe fix one issue, starting looking at mouse_combo_handler (To make the window get focus while the mod key is down you can move around the if statements). The other that could be causing issues maybe replay_click in xwrap, called in event_translate ButtonPress. Those would be the first places Id start with, as any other place is just blocking focus being taken on hover (and is the same for Driven focus so shouldn't be the issue).
