### ISSUE TITLE
[meta] cleaning up and categorizing issues

### ISSUE THREAD

**Issue by hertg** [leftwm/leftwm#519]
Hi @lex148 

I've already asked on the discord if we maybe should clean up the issues a bit, because it has become a bit messy :stuck_out_tongue_closed_eyes:. I know that you're probably too busy to read through all that, so I'll try to summarize it here:

My proposal is to create a clear set of labels to differentiate between the types, severity, and complexity of issues. I started using the labels below in my own projects at work and always felt it was worth it.

![image](https://user-images.githubusercontent.com/3533648/136693985-f6b7d491-8710-4227-96bf-e77ce92431b6.png)

I'm positive that this would give the contributors, as well as the (potential) users a better overview about where the project stands and where it's going. The `complexity` label would also provide a clearer entrypoint for new contributors.

What's your opinion on that?

---

btw. thanks for inviting me and giving me the `triage` permission. I'm motivated to start categorizing some issues, after receiving your feedback and approval of course.

**Comment by VuiMuich** [comment]
I added the suggested labels (spare the `discussion` as we have the discussion function enabled, so I felt this would be a bit redundant), though I added `poll/opinion` as I thought this might be relevant for some posts.

Will tune the colours a bit tomorrow, just wanted to add them so you could start right away if you'd like.

Also thanks from my side for the invite and elevated permissions!

**Comment by hertg** [comment]
Great, thanks a lot :)
I'll send you the exact texts and colors from my image below, if you want to tweak it from there.
I don't have any strong opinions on those colors or something, I just found the default ones that github suggests really ugly.

I usually also get rid of some of the default labels github automatically adds to every repo, some of them overlap the ones I use, and others are a bit pointless in my opinion (for example `invalid` doesn't make a lot of sense to me, invalid issues should probably get closed instead of labelled 'invalid' :smile:). But do whatever you feel is right.

I'll probably start going through issues tomorrow, I'm heading to bed now :crescent_moon: 

```
bug 
Something isn't working as expected
#D93F0B

complexity: advanced
Requires deep knowledge of project structure, far reaching implications, a lot of code changes
#0052CC

complexity: easy
Requires only few, self-contained code changes
#C5DEF5

complexity: intermediate
May require some more code changes and a good understanding of the project
#1D76DB

discussion
Feedback, discussions, anything unspecific
#FBCA04

enhancement
Enhancement for an already existing feature
#D4C5F9

feature
A new feature or request
#C2E0C6

optimization
Optimization for an already existing feature
#D4C5F9

severity: criticall
Requires immediate attention
#B60205

severity: high
Requires attention in the next few days or weeks
#E99695

severity: low
Requires attention eventually, might be dismissable
#FEF2C0

severity: moderate
Requires attention in the next few weeks or months
#F9D0C4
```

**Comment by hertg** [comment]
I'm closing this.
I think we have addressed this pretty well :)
