### ISSUE TITLE
Some new feature

### ISSUE THREAD

**Issue by og900aero** [leftwm/leftwm#522]
I use bspwm, and try leftwm. Not bad, but missing some important features:

- Swallow function
- Move focused window and move focus left and right (now only up and down)
- key bindings not enough. Not work Space, Print keybindings
- Not working window resize in Fibonacci layout 
- Options/rules for start application with keybindings in fix tag (example when I start chromium, it will open only tag 2, not focused tag)
- cannot find option to change focused window border width, color
- cannot find option for border gap

**Comment by hertg** [comment]
I think most of the issues you report are already being tracked or implemented.

- Swallow function
  Not sure about that one, but #351 seems to be about the same?
  
- Move focused window and move focus left and right (now only up and down)
  I think that's probably not possible, LeftWM doesn't order windows in a B-Tree like bspwm, but inside a list (`Vec`)

- key bindings not enough. Not work Space, Print keybindings
  Sorry, I don't understand this one

- Not working window resize in Fibonacci layout
  duplicate. already tracked in #96 

- Options/rules for start application with keybindings in fix tag (example when I start chromium, it will open only tag 2, not focused tag)
  duplicate, already tracked in #427 

- cannot find option to change focused window border width, color
  Take a look at the wiki ([here](https://github.com/leftwm/leftwm/wiki/Theme-Config)), and look into themes. You can change window border width and color via the theme config.

- cannot find option for border gap
  Same as above, you can specify `margin` and `workspace_margin` in the theme settings.

**Comment by og900aero** [comment]
Space with lower case working fine, thx.

Theme...so it is complicated. Yay -S leftwm-theme-git, then I created themes directory, then leftwm new myconfig and place theme.toml in the myconfig directory: 

border_width = 100
margin = 100
default_border_color = "#111111"
floating_border_color = "#111111"
focused_border_color = "#111111"

But nothing happens. Same border color (red), same border width than without themes etc. I think it's too complicated. Why is it not defined in a config file in the root directory?

**Comment by mautamu** [comment]
`leftwm-theme apply myconfig` might be necessary if you haven’t run it already. Do you get the right file when cat ~/.config/leftwm/themes/current/theme.toml

**Comment by AethanFoot** [comment]
The creator of arcolinux has some great videos on theming/creating themes for leftwm, https://www.youtube.com/watch?v=mdx9LDRRAPY. He speaks a bit slow so made need to up the speed of the video :smile: .

**Comment by VuiMuich** [comment]
>  `leftwm-theme apply myconfig` might be necessary if you haven’t run it already. Do you get the right file when `cat ~/.config/leftwm/themes/current/theme.toml` ?

Ooh, I like this test!

**Comment by VuiMuich** [comment]
To me it still looks like the theming issues you are experiencing are some minor detail being set up wrongly.
If you are willing to explore this and find the issue be welcome to re-open this issue, as I am closing this for now.

For reference: the only actual feature request I could extract here is 'resizing for main window in Fibonacci layout' which is tracked in #96) .
