### ISSUE TITLE
Version Bump `0.2.10` Plans and Changelog

### ISSUE THREAD

**Issue by VuiMuich** [leftwm/leftwm#525]
This issue is meant to track our plans on what we want to be done before the next version bump.

### PRs te be merged:
- [x] #430
- ~~#508~~ moved to `0.2.11`
- [x] #524
- [x] #526 
- [x] #528
- [x] #532
- [x] #531 
- [x] #533
- [x] #537
- [x] #538 
- [x] #539
- [x] #541
- [x] #548
- [x] #557
- [x] #563
- [x] #565
- [x] #566
- [x] #567
- [x] #568
- [x] #573
- [x] #576 
- [x] #583
- [x] #584 

### Issues to get closed:
- ~~#486~~ moved to `0.2.10`
- [x] #497
- ~~#516~~ moved to `0.2.10`
- ~~#517~~ moved to `0.2.11`
- [x] #518 
- [x] #525
- [x] #546
- [x] #549
- [x] #564 

---
_Please feel free to add wishes for `0.2.10` in the comments and we'll keep this top post updated._

**Comment by mautamu** [comment]
Will `leftwm` and `leftwm-core` be moved to Rust 2021 edition once this merges?

**Comment by VuiMuich** [comment]
> Will `leftwm` and `leftwm-core` be moved to Rust 2021 edition once this merges?

The question is, would we want to 
A) bump to Rust2021 and implement optimizations later
B) bump directly with a PR that brings optimizations possible with the new features.

Building against 1.56.1 is working fine anyways.

**Comment by mautamu** [comment]
Hmm, what optimizations are now possible? I don't see much in the [migration guide](https://doc.rust-lang.org/edition-guide/rust-2021/index.html) that would be a huge change for LeftWM off the top of my head.

Otherwise, I'm all for (B).

**Comment by VuiMuich** [comment]
:joy: I didn't see much myself, but deemed myself to inexperienced to actually judge the potential. I was hoping that some of you guys might have a better educated guess :man_shrugging: 

On a first quick check not even some new clippy pedantic lints come around..

**Comment by mautamu** [comment]
> Will `leftwm` and `leftwm-core` be moved to Rust 2021 edition once this merges?
Linking https://github.com/leftwm/leftwm/pull/594 for future adventurers.

**Comment by VuiMuich** [comment]
I'll close this now, as we are really close to releasing `0.2.10` now. Eventually will update with all merged PRs post release for completeness sakes.

As stated in another place, with `0.2.11` we will take another approach and keep the pinned issue purely as a wishlist for issues tackled in this release and track the actual issues and PRs only in the milestone.
