### ISSUE TITLE
error: found a virtual manifest at...

### ISSUE THREAD

**Issue by rigoletto-freebsd** [leftwm/leftwm#527]
Hello!

`LeftWM 0.2.9` is failing to build with:  

```error: found a virtual manifest at `/home/rigoletto/Dev/FreeBSD/ports/x11-wm/leftwm/work/leftwm-0.2.9/Cargo.toml` instead of a package manifest```

Any idea of what is going on?

Thanks!

**Environment:**
FreeBSD

**Comment by AethanFoot** [comment]
This will be due to the splitting of leftwm, where the main cargo uses workspaces. When using cargo install the path to the leftwm folders cargo.toml, e.g. ```cargo install --path ./leftwm/```.
Thanks.

**Comment by rigoletto-freebsd** [comment]
Done! Thanks!
