### ISSUE TITLE
MoveToTag and focus

### ISSUE THREAD

**Issue by PeterDauwe** [leftwm/leftwm#529]
The keybind MovetoTag does its work but I stay on the original tag.
Then i have to use the keybind for GoToTag to follow the application.

Is there a "MoveToTag and focus on that tag" possibility?

**Comment by PeterDauwe** [comment]
Tried these but none are working. Is it possible?

[[keybind]]
command = "Execute"
value = "leftwm-command "SendWindowToTag 9" "SendWorkspaceToTag 0 8"
#value = "leftwm-command "SendWindowToTag 9" && "SendWorkspaceToTag 0 8"
#value = "leftwm-command SendWindowToTag 9 SendWorkspaceToTag 0 8"

modifier = ["modkey", "Shift"]
key = "ccedilla"

**Comment by VuiMuich** [comment]
Please try
```
value = 'leftwm-command "SendWindowToTag 6" "SendWorkspaceToTag 0 5"'
# or
# value = "leftwm-command \"SendWindowToTag 6\" \"SendWorkspaceToTag 0 5\""
```
You need to put the whole command thats held by the value in quotes so either you use single quotes and double quotes (should not matter which one is inside and which one outsie) or you escape them.

**Comment by PeterDauwe** [comment]
Indeed , it works but only for one tag. If i try some more , it breaks. Can you explain the 'SendWorkspaceTotag 0 8'
What is the 0 doing?

[[keybind]]
value = 'leftwm-command "SendWindowToTag 7" "SendWorkspaceToTag 0 6"'
modifier = ["modkey", "Shift"]
key = "egrave"

[[keybind]]
command = "Execute"
value = 'leftwm-command "SendWindowToTag 8" "SendWorkspaceToTag 0 7"'
modifier = ["modkey", "Shift"]
key = "exclam"

[[keybind]]
command = "Execute"
value = 'leftwm-command "SendWindowToTag 9" "SendWorkspaceToTag 0 8"'
modifier = ["modkey", "Shift"]
key = "ccedilla"

**Comment by PeterDauwe** [comment]
YES ! This should be standard keybinds for Leftwm. 

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 1\" \"SendWorkspaceToTag 0 0\""
modifier = ["modkey", "Shift"]
key = "1"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 2\" \"SendWorkspaceToTag 0 1\""
modifier = ["modkey", "Shift"]
key = "2"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 3\" \"SendWorkspaceToTag 0 2\""
modifier = ["modkey", "Shift"]
key = "3"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 4\" \"SendWorkspaceToTag 0 3\""
modifier = ["modkey", "Shift"]
key = "4"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 5\" \"SendWorkspaceToTag 0 4\""
modifier = ["modkey", "Shift"]
key = "5"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 6\" \"SendWorkspaceToTag 0 5\""
modifier = ["modkey", "Shift"]
key = "6"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 7\" \"SendWorkspaceToTag 0 6\""
modifier = ["modkey", "Shift"]
key = "7"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 8\" \"SendWorkspaceToTag 0 7\""
modifier = ["modkey", "Shift"]
key = "8"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 9\" \"SendWorkspaceToTag 0 8\""
modifier = ["modkey", "Shift"]
key = "9"

**Comment by PeterDauwe** [comment]
Working like a charm!!!
