### ISSUE TITLE
Not all keybindings in config.toml work

### ISSUE THREAD

**Issue by stevensonmt** [leftwm/leftwm#53]
In particular, I am having a hard time launching anything with mod-p. Here is the entry in config.toml:
```
[[keybind]]
command = "Execute"
value = "rofi -show run" //I've also tried "alacritty" without success
modifier = ["modkey"]
key = "p"
```
I'm certain this is user error but can't seem to figure out what I've got wrong. The whole config is attached.
[config.txt](https://github.com/leftwm/leftwm/files/3316474/config.txt)

**Comment by lex148** [comment]
stevensonmt, 

If the config.toml file is malformed leftwm will revert back to the default config.toml that is auto generated. I'm certain that is what is happening here. I see a couple of lines that would cause this to happen.

Line: 2 ) you defined workspaces here and at the bottom
Line: 22) there is a extra quote flotting at the end of this line
Line: 203) a workspace doesn't have a value that can be set. this should be removed
Line: 199) a workspace doesn't have a value that can be set. this should be removed

One more helpful hint.  Most people shouldn't have to define workspaces at all. By default leftwm will create a workspace for every screen automatically. You only need to add them if you want to treat an extra wide monitor as two monitors or treat several small monitors as one big one. I would recommend trying your config without them.

Here is the config I am recommending you try 

[config.txt](https://github.com/leftwm/leftwm/files/3316773/config.txt)

**Comment by stevensonmt** [comment]
Thanks, don't know where that extra quote came from as I never edited that line intentionally. Is there some further documentation on working with workspaces in leftwm? But the workspaces lines seemed to be the culprit.
