### ISSUE TITLE
Workspace tags get overwitten or show incorrect data.

### ISSUE THREAD

**Issue by VentGrey** [leftwm/leftwm#530]
**Describe the bug**
When ussing a settings daemon such as `xfsettingsd` this daemon may save workspace tags defined in your `config.toml` file, this causes a config conflict between the window manager and the settings daemon, who cannot manage unicode tag names properly (such as NerdFonts or FA icons), resulting in glitched graphics or unordered tags.

**To Reproduce**
1. Install `leftwm`
2. Install `xfce4-settings`
3. Run `xfsettingsd` run in the background
4. Define (or have already defined) tags in your `config.toml`
5. For more info check `xfce4-settings-manager` and click on the "configuration" options (the one that looks like `dconf-editor`, under the `xfsettingsd` there should be a "tags" option which is our culprit.

**Expected behavior**
`leftwm` tags take precedence.

**Screenshots**
![image](https://user-images.githubusercontent.com/24773698/137298358-23096ec3-5e39-42b9-92cc-452ac397bff3.png)

**Environment:**
 - OS/Distro: Debian (Should be able to reproduce in any)
 - Output of `leftwm-check`:
 
![image](https://user-images.githubusercontent.com/24773698/137298461-b6117029-a96d-4161-9ef1-355b5253625a.png)

**Additional context**
Don't run a settings manager if possible, if not, make sure to delete the tags key / dconf schema to avoid conflicts with leftwm.

**Comment by VentGrey** [comment]
Both cause an issue, either in `up` or under autostart folder.

**Comment by VuiMuich** [comment]
Sorry, that was a bit unspecific, I was aiming for this:

> `Autostart Entry` will be ignored when:
> 1. the `.desktop` file has the `Hidden` key set to true.
> 2. string identifying the desktop environments not in `OnlyShowIn`
> 3. string identifying the desktop environments in `NotShowIn`

_for more on this look for the doc comments in `leftwm-core/src/utils/childprocess.rs`_

**Comment by VentGrey** [comment]
I opened this issue as a "documenting" help for some users. Should I close this and add this "tip" to the wiki? 😄
