### ISSUE TITLE
[BUG] polybar only showing last occupied tag as occupied. 

### ISSUE THREAD

**Issue by blackdragon2447** [leftwm/leftwm#535]
**Describe the bug**
when having windows open on multiple tags polybar will only show the last one as occupied. (havent had it 100% consistent, sometimes it only shows the first one).

**To Reproduce**
1. run a new session of leftwm
2. open windows on multiple tags
3. close a window on one tag
4. polybar will only show one tag as occupied

**Expected behavior**
polybar should show every tag that has a window on it as occupied.

**Environment:**
 - OS/Distro: Arch Linux
 - Kernel: linux-xanmod-cacule 5.14.13-1

[leftwm-state-broken.txt](https://github.com/leftwm/leftwm/files/7368107/leftwm-state-broken.txt)
[leftwm-state-working.txt](https://github.com/leftwm/leftwm/files/7368111/leftwm-state-working.txt)
[leftwm-state-diff.txt](https://github.com/leftwm/leftwm/files/7368110/leftwm-state-diff.txt)

**Comment by AethanFoot** [comment]
Adding context from discord. The issue is with ewmh compliance, with setting the parameters needed for polybars auto workspace detection.

**Comment by AethanFoot** [comment]
@blackdragon2447 Can you check if #571 has improved this situation much? (If you still have the config).

**Comment by blackdragon2447** [comment]
I'll test this some time soon tho any confing usig the polybar buildin ws module should do.

**Comment by blackdragon2447** [comment]
ok did a quick compile and run and the ewmh polybar module seems to work again.
