### ISSUE TITLE
keystrokes are sometimes grabbed by an unfocused window

### ISSUE THREAD

**Issue by hertg** [leftwm/leftwm#549]
**Describe the bug**
Sometimes when a new window opens or when the focus changes, the keystrokes aren't grabbed by the newly focused window but rather the previously focused one. Occurs when using focus behavior `Sloppy`.

**To Reproduce**
I don't have a reliable way to reproduce that issue yet.

**Expected behavior**
The focused window should always be the one grabbing the keystrokes.

**Additional context**
I'm on the latest `master`. While I don't know how to reproduce it right now, the issue was also confirmed by @mautamu in the `#dev` channel on Discord. I didn't have that issue for long, so it is probably a regression of a recent commit (last 1-2 weeks?).

It happens around 1-2 times a day on my machine, and is mostly just an annoyance. I don't look forward to the day where I'm focused on a password prompt and send my password in a Discord channel though :wink:

**Comment by hertg** [comment]
I found a way to reproduce the issue on my machine.

1. Set focus-behavior to `Sloppy`
1. Open two windows, one of them must be Firefox the other one can be anything, I use Alacritty in my example.
1. Make sure Firefox is the master and Alacritty the secondary window
1. Move the mouse over Alacritty, so it's focused
1. Press `mod + enter` (or whatever keymap you have for `MoveWindowTop`)
1. Now Alacritty and Firefox swap places, Alacritty is the master window now and is focused (indicated by focused-border-color) but the keypresses on the keyboard are still grabbed by Firefox, despite it being the secondary/unfocused window.
  The mouse cursor automatically moved over the new master window, you can move the cursor on it and click stuff, but the keys will be grabbed by Firefox until you move the mouse cursor out of the master window and back in, or change the window order/focus in any other way.
  
It may also happen with other applications than Firefox. It doesn't occur when using two instances of Alacritty.

**Comment by AethanFoot** [comment]
Repeatable with libre office

**Comment by VuiMuich** [comment]
I'll try blender, when I'm home.

**Comment by mautamu** [comment]
Also works with libreoffice calc and libreoffice writer open in the same tab. Focus on a cell and start typing then switch to writer and behaviour occurs until you unfocus the cell.

**Comment by VuiMuich** [comment]
With blender it not fully "working" in the broken way, as I doesn't seem to process the keyboard input, but it's definitely also not going to the seemingly focused alacritty window either.
