### ISSUE TITLE
Refreshing too many times in a short timespan sends all windows to first workspace.

### ISSUE THREAD

**Issue by VentGrey** [leftwm/leftwm#550]
LeftWM sends all windows to the first workspaces when the "Refresh" keybind is pressed by a couple seconds.

**To Reproduce**
1. Open a few windows on multiple workspaces.
2. Keep your reload keybind pressed for a few refreshes for a second or two.
3.  All windows will be moved to the first workspace.

**Expected behavior**
Keep all windows in their place.

**Screenshots**
None atm.

**Environment:**
 - OS/Distro: [Debian 11 - Stable]
 - Output of `leftwm-check`:
```
:: LeftWM version: 0.2.10
:: LeftWM git hash: caa3ec5
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK 
:: Checking theme . . .
    -> Theme OK 
```

**Additional context**

None.

**Comment by VuiMuich** [comment]
It most certainly is the case that the too many refreshes leave no time for the `state-file` to be de-/serialized and written/read, so the `SoftReload` just ends up being a `HardReload` effectively.

**Comment by VentGrey** [comment]
I don't know the code of leftwm all to well, so i'll ask for your help here, what exactly is responsible for managing the `state-file` serialization and de-serialization. If the complexity is simple I think a small timer made with the already included `chrono` dependency should suffice, however I'm a bit lost on how to help here, I believe if i'm pointed in the right direction I think I can open a PR to help solve this :)

**Comment by TornaxO7** [comment]
This bug doesn't work on my machine anymore could you please retry this?

**Comment by TornaxO7** [comment]
@hertg could you please close this for the time being until this problem pops up again?
