### ISSUE TITLE
Menu/History... in Brave disappear when is cover second window

### ISSUE THREAD

**Issue by mkubasz** [leftwm/leftwm#552]
**Describe the bug**
Menu/History... in Brave disappear when is a cover second window

**To Reproduce**
Open two brave's windows on the same screen
On the left window click "Customize and control Brave"
After the menu appear click "History|
Move the mouse to some item on the list which is covered right window

**Expected behavior**
Should be still selected left window and possibility item from the menu

**Screenshots**
https://drive.google.com/file/d/1PDYBqJR-6Nsftr2hN94JAaVpdA-T5yx2/view?usp=sharing

**Environment:**
 - OS/Distro: Arch
 - Output of `leftwm-check`
`:: LeftWM version: 0.2.9
:: LeftWM git hash: a6326ae
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
`
**Additional context**

**Comment by AethanFoot** [comment]
This seems to be a side affect from #262, maybe a different approach is needed.
