### ISSUE TITLE
latest commit 10168dfdf4c5851c2af59fc644e58aec92118ac2 breaks scratchpad

### ISSUE THREAD

**Issue by tramhao** [leftwm/leftwm#553]
**Describe the bug**
With commit 10168dfdf4c5851c2af59fc644e58aec92118ac2, scratchpad  become tiled instead of floating.

**To Reproduce**
1. Update to latest commit. 
2. Activate scratchpad by the hotkey you defined.
3. The scratchpad is not floating, but tiled. 

**Expected behavior**
Scratchpad should always be floating.

**Screenshots**

**Environment:**
 - OS/Distro: Arch
 - Output of `leftwm-check`

**Additional context**

**Comment by AethanFoot** [comment]
I slipped a fix for this in #548 :wink:
