### ISSUE TITLE
[Steam] Child Windows suffer from input issues

### ISSUE THREAD

**Issue by staccato** [leftwm/leftwm#554]
Steam has various child windows (game settings, offers, friends menu) etc. Trying to interact with these results in:

- Input delay
- Missed inputs
- Not recognizing cursor position

1. Open Steam
2. Go to Library -> a game -> right click and select Properties
3. Try to interact

Demonstration:
https://streamable.com/ik0wbf - CS:GO properties menu
https://streamable.com/sarfvf - CS:GO launch attempt

OS: NixOS 21.11 (Porcupine)

`leftwm-check` output:

:: LeftWM version: 0.2.8
:: LeftWM git hash: NONE
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK

**Comment by VuiMuich** [comment]
tagging @winston0410 as I believe you are the only other known nixos user among us leftwm adventurers.
Would you mind to help a bit out with this issue?

**Comment by staccato** [comment]
https://github.com/NixOS/nixpkgs/blob/2deb07f3ac4eeb5de1c12c4ba2911a2eb1f6ed61/pkgs/applications/window-managers/leftwm/default.nix#L9

It appears nixpkgs does not have the latest version of leftwm. I will upgrade from 0.2.8 to 0.2.9 and report if it had any affect on this.

**Comment by winston0410** [comment]
@staccato Yes and make sure you use the unstable channel to get the latest leftwm.

**Comment by staccato** [comment]
I've upgraded the package to 0.2.9 - it appears to have fixed the issue.
https://streamable.com/mfstj3

Hot Fix:
```nix
  nixpkgs.overlays = [
    (self: super: {
      leftwm = super.callPackage <nixpkgs/pkgs/applications/window-managers/leftwm> {
        rustPlatform = super.rustPlatform // {
          buildRustPackage = args:
            super.rustPlatform.buildRustPackage (args // {
              version = "0.2.9";

              src = super.fetchFromGitHub {
                owner = "leftwm";
                repo = "leftwm";
                rev = "0.2.9";
                sha256 = "sha256:0w4afhrp2cxz0nmpvalyaxz1dpywajjj2wschw8dpkvgxqs64gd5";
              };

              cargoSha256 = "sha256:0r0smpv50gim2naaa0qf6yhvqvsa2f40rkgiryi686y69m5ii7mv";
            });
        };
      };
    })
  ];
```

I'll make a PR to the nixpkgs repository bumping the version.
