### ISSUE TITLE
[bug] focus gets lost in focus mode `Driven`

### ISSUE THREAD

**Issue by VuiMuich** [leftwm/leftwm#560]
**Describe the bug**
I reported this already when reviewing #538, but the details are still a bit obscure.
In some situations when switching tag or when hiding a scratchpad window focus does not follow along.

I have seen this on both `Monocle` and `MainAndDeck` layouts with focus mode `Driven` I switched now to `ClickTo` to see if this happens there and with other layouts as well.

One suspicion is, that this happens when a scratchpad is still open on a hidden tag, but I can't confirm that yet.

Most of the time it is recoverable by un-hiding a scratchpad and moving focus away from it, then hiding it again, but sometimes this get the windows completely detached from the manager and is only recoverable by `SoftReload`.

So far my findings, will update as I gain more insight.

**To Reproduce**
still unclear, if I find reprocuible steps I'll update.

**Expected behavior**
Focus should never be lost when switching tags or un-/hiding scratchpad windows

**Environment:**
 - OS/Distro: Manjaro (but I believe this is issue is disro agnostic)
 - Output of `leftwm-check` should be irrelevant

**Comment by hertg** [comment]
I've fixed some focus issues in #568. This issue might be related. Can you keep an eye on it and see if this issue here still occurs?

**Comment by VuiMuich** [comment]
I believe I have steps to reproduce now:

1. configrue focus mode to `Driven`
2. Open some window
3. Open a scratchpad
4. go to another tag
5. call scratchpad to this tag by using the `ToggleScratchPad` command
6. got to the previous tag

Now the window of the previous tag is unfocused. 

7. Creating a new window and moving focus brings this window back
8. as well as calling the scratchpad back again
9. in some situations, still unclear on the condition, the window gets completely detached and only a `SoftReload` brings it back.

**Comment by brownjohnf** [comment]
I'm seeing what seems like very similar behavior to this when using sticky windows. When switching between tags, focus just seems to go... nowhere. Launching a new window will restore focus to the new window, and then focus can be shifted around normally. Switching tags causes the same problem again. It doesn't seem to matter whether the layout is filled up, or there's only a single window.

I've also got 

```
focus_behaviour = 'ClickTo'
focus_new_windows = true
```

set in my config, but I'm unable to click-to-focus on a window. The behavior seems more like what's described by `Driven`, other than the issue above. I'm not sure if the 2 are related or not. I'm happy to file a new issue, if that makes more sense.

I'm on Arch linux, leftwm 0.3.0 from the AUR.
