### ISSUE TITLE
Allow disabling the window-snap feature

### ISSUE THREAD

**Issue by hertg** [leftwm/leftwm#561]
I generally don't use the window-snap feature, mostly because of its rough behavior described in #486.
Sometimes I'd like to position floating windows at the edge or even beyond the edge of the screen, the snap feature makes that a bit awkward because all windows jump around when I move the window over the edge.

My proposal is to add a config key to disable that feature, similar to `disable_current_tag_swap`, eg. `disable_window_snap` or something similar.

**Comment by akosfekete** [comment]
I also had similar problems with snapping, I was surprised to see that there is no option to disable it. I created a fork that adds the `disable_window_snap` config key, the change seems trivially simple (unless I'm overlooking something), it works fine for me. Could there be a reason for not simply adding this config key (like avoiding bloated config)? Or are you planning to add it in #569?

**Comment by hertg** [comment]
No you probably didn't miss anything, it should be fairly straight forward. Maybe open a PR with your change? It will most probably get merged :)

*My PR #569 came to a halt, because I wasn't able to figure out the position where the window would end up after it snaps, so the snapping-display is still not very user-friendly with my changes. It fixes the snap flickering, but while it is in "snapping" mode, the window gets displayed over the whole workspace, rather than where it actually ends up if you let go of it. I'm currently working on a new layout-system that should allow us to determine future window positions without re-positioning any actual windows.

**Comment by akosfekete** [comment]
Thanks for the heads-up! I created a PR ( #754 )

**Comment by hertg** [comment]
Was implemented in #754
