### ISSUE TITLE
Configure behaviour of windows. Wants to include. Like xmonad

### ISSUE THREAD

**Issue by mohsin-gous** [leftwm/leftwm#562]
We want a feature to configure window behaviour like xmonad. Because some windows are not work like expected (example gmrun). Your rust based WM is super..!!!
Thank you.

**Comment by VuiMuich** [comment]
Welcome Adventurer!

Could you get a bit more specific on the details, what config options you would expect?

Also some screenshots of how gmrun looks in leftwm and how you expected it to look (maybe in xmonad)? And posting `xprop` output for the gmrun window might be helpful.

**Comment by mohsin-gous** [comment]
In leftwm
![gmrun_leftwm](https://user-images.githubusercontent.com/52144864/140519072-c03196ef-04af-4ee5-9e48-61b83a6d83a4.png)
In xmonad (We expect like this)
![gmrun_xmonad](https://user-images.githubusercontent.com/52144864/140519079-7b4774b8-07d8-4e42-a2b3-f6f7de1288f8.png)

Gmrun xprop
_NET_WM_USER_TIME(CARDINAL) = 176101389
_NET_WM_DESKTOP(CARDINAL) = 2
WM_STATE(WM_STATE):
		window state: Normal
		icon window: <field not available>
_NET_WM_STATE(ATOM) = 
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		window id # of group leader: 0x2e00001
XdndAware(ATOM) = BITMAP
_MOTIF_DRAG_RECEIVER_INFO(_MOTIF_DRAG_RECEIVER_INFO) = 0x6c, 0x0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10, 0x0, 0x0, 0x0
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x2, 0x0, 0x0
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 48234501
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x2e00004
WM_CLIENT_LEADER(WINDOW): window id # 0x2e00001
_NET_WM_PID(CARDINAL) = 367298
WM_LOCALE_NAME(STRING) = "en_GB.UTF-8"
WM_CLIENT_MACHINE(STRING) = "mohsin-Inspiron-3542"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		program specified minimum size: 1008 by 51
		program specified maximum size: 1008 by 51
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "gmrun", "Gmrun"
WM_ICON_NAME(STRING) = "Execute program feat. completion"
_NET_WM_ICON_NAME(UTF8_STRING) = "Execute program feat. completion"
WM_NAME(STRING) = "Execute program feat. completion"
_NET_WM_NAME(UTF8_STRING) = "Execute program feat. completion"

**Comment by mohsin-gous** [comment]
I think this prop **WM_CLASS(STRING) = "gmrun", "Gmrun"**  based configurations.
In config.toml
We want window class based configuration to do such as float or anything to set window behaviour.
Thank you

**Comment by VuiMuich** [comment]
What is the configuration in xmonad for the window? Is it forced to be floating?

Eventually we should add some config options making use of `WM_CLASS(STRING)`, such as forced floating, tag to spawn on etc.

**Comment by mohsin-gous** [comment]
Xmonad window rule
![image](https://user-images.githubusercontent.com/52144864/140591410-8af0d310-f522-4f5f-82a0-7871fe7c7a42.png)

I think this is rule mention on xmonad. But not explicitly not mentioned on this gmrun.
**, resource  =? "desktop_window" --> doIgnore**
this line of code may be effect on gmrun. Anyway xmonad show window we expected on "gmrun".
i think can we add "doIgnore" like command for specific window class? before leftwm sets any rule on that class of windows?

**Comment by VuiMuich** [comment]
Have you any clue what the `ressource` is actually referring to?
I believe we are using some kind of `ignore` for type `Desktop` windows like the actual desktop background.

It would be interesting to learn more about the implications of the `ignore` in xmonad.

**Comment by mohsin-gous** [comment]
![image](https://user-images.githubusercontent.com/52144864/140604067-ba9ff838-6d41-4a13-bd8d-829453838429.png)
![image](https://user-images.githubusercontent.com/52144864/140604077-87f41669-338e-4fe4-a30c-465e5c7d2c15.png)
Is this help full?

**Comment by mohsin-gous** [comment]
in our WM have a feature to snap floated window to tile region. Can we set a option for to on and off this feature?. may be this feature's side effect are like gmrun window problem. i think. what you think?

**Comment by hertg** [comment]
> in our WM have a feature to snap floated window to tile region. Can we set a option for to on and off this feature?. may be this feature's side effect are like gmrun window problem. i think. what you think?

This is already being tracked here: #561

**Comment by VuiMuich** [comment]
@mohsin-gous can you possibly test if #571 fixes `gmrun` sizes?

**Comment by VuiMuich** [comment]
@mohsin-gous at this point I consider this solved by #571. If the issue still occurs, feel free to reopen.

**Comment by Oreolek** [comment]
So how to configure this? I have an app that draws its dialogs as normal windows and they mess up everything.

**Comment by VuiMuich** [comment]
Can you spot any difference in the `xprop` of the main window and the dialog?
Maybe we could add a window rule selector `child` to enforce floating.
