### ISSUE TITLE
leftwm-check did not complain for lack of permissions

### ISSUE THREAD

**Issue by Qark-dev** [leftwm/leftwm#576]
**Describe the bug**
apparently, leftwm-check is supposed to complain whether up/down scripts for themes are lacking the permissions to run

**To Reproduce**
I was on gentoo and simply cloned the Red Moon theme, symlinked to ~/.config/leftwm/themes/current.

**Expected behavior**
leftwm-check is supposed to tell me that up/down scripts are lacking permissions.

**Screenshots**
![image](https://user-images.githubusercontent.com/80141845/142059036-ec9c4597-3e83-49a5-9bae-ddb8fe26fbc9.png)

**Environment:**
 - OS/Distro: Gentoo
 - Output of `leftwm-check`
 ```sh
:: LeftWM version: 0.2.9
:: LeftWM git hash: NONE
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```

**Additional context**
Users would be left wondering why leftwm wasn't loading their themes and this `leftwm-check` discrepancy fails to show the reason

**Comment by VuiMuich** [comment]
Can confirm this with LeftWM git hash ec7ebca
