### ISSUE TITLE
Send window to another screen?

### ISSUE THREAD

**Issue by tramhao** [leftwm/leftwm#577]
I use the following script to configure the external screen as main and internal screen of laptop to be a vertical side screen on the right

```
intern=eDP-1
extern=DP-2

if xrandr | grep "$extern disconnected"; then
    xrandr --output "$extern" --off --output "$intern" --auto
else
    xrandr --output "$extern" --mode 1920x1200 --primary --pos 0x0 --output "$intern" --auto --rotate right --right-of "$extern"
fi
```

The problem is, I can drag a window from main screen to side screen, but I cannot send it by keyboard. Is it possible in leftwm? I saw the configuration of workspaces, but no detail configuration is given. For example:
```
[[workspaces]]
y = 0
x = 0
height = 1200
width = 1920
id = 0

[[workspaces]]
y = 0
x = 1920
height = 1080
width = 1920
id = 1
```
When I configure it like this, I lose the tag icon I configured
```
tags = ["", "", "", "", "5", "6", "7"]
```

**Comment by tramhao** [comment]
I'm using basic_eww theme.

**Comment by VuiMuich** [comment]
🤔 
You could probably let your script `sed` your `config.toml` so you have

```
# if "external == disconnected
workspace = []

# else
workspace = [
{ 
```

_Gonna finish this in a minute on desktop_

**Comment by tramhao** [comment]
Basically I don't get the meaning of workspace. Seems it's like a region on screen, and I cannot put window on it, but when it has focus, I can grab window from other workspaces to it. Is this the correct understanding?

**Comment by VuiMuich** [comment]
I just noticed, I missed a hole lot of your post on mobile..
I'm editing my above post right now..

**Comment by tramhao** [comment]
Is there a way to configure, for example, tag 9 as workspace 1, so that I send a window to tag9, and it'll appear on 2nd monitor?

**Comment by tramhao** [comment]
I use your configuration of workspaces, and the tag name works fine with eww now.

**Comment by VuiMuich** [comment]
> Basically I don't get the meaning of workspace. Seems it's like a region on screen, and I cannot put window on it, but when it has focus, I can grab window from other workspaces to it. Is this the correct understanding?

You are right, the workspace is basically a 'virtual screen' in leftwm, but in most setups this matches with the actual screen, the exception being multiple workspaces on a ultrawide-screen.
Tags are what other WMs refer to as workspaces and are shared among all workspaces.
A tag can only be focused by (or be shown on) one workspace, So by default the `main` should start on the first tag, the `secondary` on the second and so on. So sending a window from `tag 1` to `tag 2` should _'move'_ it to the second screen.

**Comment by VuiMuich** [comment]
> I use your configuration of workspaces, and the tag name works fine with eww now.

Hey, that's great.
May I ask you if you configured a second bar for the secondary screen? If so did you just double the `bar` window?

**Comment by tramhao** [comment]
> 
> Hey, that's great. May I ask you if you configured a second bar for the secondary screen? If so did you just double the `bar` window?
> 

Yes, I just repeat the bar0 as bar1. Actually it's a little redundant because same info are displayed. But the up script need bar1.

> 
> You can focus the workspace of the second monitor, and then "open" tag nine, now Workspace 1 is on tag 1 and workspace 2 is on tag 9. We recently debated an config option on discord to instead of swaping tags between workspaces, to follow with the focus to the other workspace if you are on workspace 1 tag 1 and issue `GoToTag 9`
Interesting ideas. 

Also, I found a pr https://github.com/leftwm/leftwm/pull/432/commits/6539f20cd7a6f4ac873967a8d932b4b80922a7c8 was merged. But how to configure the margin depending on different workspaces? I didn't find any information on this configuration. Thanks!

**Comment by VuiMuich** [comment]
> Yes, I just repeat the bar0 as bar1. Actually it's a little redundant because same info are displayed. But the up script need bar1.

Yeah, you would probably double the variables as well so the state is evaluated for each workspace independently.

> Also, I found a pr https://github.com/leftwm/leftwm/pull/432 was merged. But how to configure the margin depending on different workspaces? I didn't find any information on this configuration. Thanks!

I am not sure and right now I'm on mobile again. But I guess you would add a `margin` field for each workspace.

**Comment by AethanFoot** [comment]
There are also commands to move to previous/next workspace, #509.

**Comment by tramhao** [comment]
> There are also commands to move to previous/next workspace, #509.

This work perfectly for me!

```
[[keybind]]
command = "MoveWindowToNextWorkspace"
modifier = ["modkey","Control"]
key = "w"
```

**Comment by VuiMuich** [comment]
Looks like I was wrong. I guess correct would be to add various gutters in the theme.toml and assign them the corresponding workspace ids

**Comment by tramhao** [comment]
How to add gutters? 
```
[[gutter]]
side = "Left"
value = 20
```
After I added this to my theme.toml, it's actually put a margin around 4 sides, not only left. Also, it's not workspace dependent. Thanks.

**Comment by VuiMuich** [comment]
> How to add gutters? 
> 
> ```
> [[gutter]]
> side = "Left"
> value = 20
> ```
> 
> After I added this to my theme.toml, it's actually put a margin around 4 sides, not only left. Also, it's not workspace dependent. Thanks.

For it being workspace dependent, it would need an `id` field that matches the id of the workspace. 
No idea rn why it is around all edges...

**Comment by tramhao** [comment]
Now my configuration is as below: 
```
> cat theme.toml
border_width = 3
margin = 5
workspace_margin = [5,0,5,20]
default_border_color = "#37474F"
floating_border_color = "#22ff55"
focused_border_color = "#ffd700"
[[gutter]]
side = "Left"
value = 20
id = 0
```

but the left gutter appears on both my main monitor, and my side monitor. 
My workspace is as below:
```
workspace = [
# only with internal screen
#{ x = 0, y = 0, width = 1920, height = 1080, id = 0 },

# external screen as main internal
{ x = 0, y = 0, width = 1920, height = 1200, id = 0 },
{ x = 1920, y = 0, width = 1080, height = 1920, id = 1 },
]
```

Thanks so much for your kind help.

**Comment by VuiMuich** [comment]
I'll have a deeper look into this later today. 

But let's ping @stevensonmt as he implemented gutters by workspace, maybe he sees at a glance what's wrong.

**Comment by stevensonmt** [comment]
I'll try to help but it will have to be tomorrow. In the meantime if you could post your full config and up script along with the version/branch you're using that might help me track it down. I'm pretty confused about why it would ignore the "left" setting.

**Comment by tramhao** [comment]
Sure, thanks in advance!
The left setting is working, but the id of workspace is ignored.
```
leftwm --version
LeftWM 0.2.10, Git-Hash: 26cc711
```
my up script is from basic_eww with minor modification to support two monitors as below:
```
leftwm/themes/current
> cat up
#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#if path to liblinkt is not not exported do so:
if [ -z "$LD_LIBRARY_PATH" ]; then
  export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
fi

. $SCRIPTPATH/autostart.sh

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# start eww daemon
eww daemon &

# Boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom --experimental-backends &> /dev/null &
  # picom &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
fi
dunst &
# Set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# Set background
# if [ -x "$(command -v feh)" ]; then
#   feh --bg-scale $SCRIPTPATH/background.jpg
# fi
#open eww 'bar' windows
#this is a bit of an uggly hack, a more elegant way will hopefully be possible with a future `eww` version
sleep 1
index=0
sizes=( $(leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' ) )
for size in "${sizes[@]}"
do
    eww open bar$index
  let index=index+1
done
# if [ $(hostname) = "XMLaptop" ]; then
sleep 10
eww reload
# fi

# if [ $(uname -n) = "lenovo-t480" ]; then
#     sleep 10
#     eww reload
# fi
```

my config.toml is as below:
```
modkey = "Mod4"
mousekey = "Mod4"
# workspaces = []

# [[workspaces]]
# y = 0
# x = 0
# height = 1200
# width = 1920
# id = 0
workspace = [
# only with internal screen
#{ x = 0, y = 0, width = 1920, height = 1080, id = 0 },

# external screen as main internal
{ x = 0, y = 0, width = 1920, height = 1200, id = 0 },
{ x = 1920, y = 0, width = 1080, height = 1920, id = 1 },
]

disable_current_tag_swap = true
tags = ["", "", "", "", "5", "6", "7"]
layouts = ["MainAndVertStack", "MainAndHorizontalStack", "MainAndDeck", "GridHorizontal", "EvenHorizontal", "EvenVertical", "Fibonacci", "CenterMain", "CenterMainBalanced", "Monocle", "RightWiderLeftStack", "LeftWiderRightStack"]
focus_behaviour = "Sloppy"
focus_new_windows = true

# [[workspaces]]
# y = 0
# x = 1920
# height = 1080
# width = 1920
# id = 1


[[scratchpad]]
name = "alacritty"
value = "WINIT_X11_SCALE_FACTOR=1 alacritty -o font.size=14"
x = 0.46
y = 0.20
height = 0.80
width =  0.54


[[keybind]]
command = "Execute"
value = "WINIT_X11_SCALE_FACTOR=1 alacritty -e nvim -c WikiIndex"
modifier = ["modkey"]
key = "n"


[[keybind]]
command = "Execute"
value = "dmenu_run"
modifier = ["modkey"]
key = "d"

[[keybind]]
command = "Execute"
value = "maimpick"
modifier = ["modkey"]
key = "Print"


[[keybind]]
command = "Execute"
value = "pamixer --allow-boost -d 5" 
modifier = ["modkey"]
key = "minus"

[[keybind]]
command = "Execute"
value = "pamixer --allow-boost -i 5"
modifier = ["modkey"]
key = "equal"



[[keybind]]
command = "Execute"
value = "setbg /home/tramhao/Pictures/wallpapers"
modifier = ["modkey","Shift"]
key = "w"

[[keybind]]
command = "Execute"
value = "WINIT_X11_SCALE_FACTOR=1 alacritty"
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey"]
key = "q"

[[keybind]]
command = "MoveWindowToNextWorkspace"
modifier = ["modkey","Control"]
key = "w"


[[keybind]]
command = "Execute"
value = "xdotool key Super_L+2 && brave"
modifier = ["modkey"]
key = "w"

[[keybind]]
command = "ToggleScratchPad"
value = "alacritty" # Name set for the scratchpad
modifier = []
key = "F12"

[[keybind]]
command = "ToggleScratchPad"
value = "alacritty" # Name set for the scratchpad
modifier = []
key = "Insert"


[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "Execute"
value = "~/.config/eww/scripts/sysact-leftwm"
# value = "~/.config/eww/scripts/powermenu.sh"
modifier = ["modkey"]
key = "BackSpace"


[[keybind]]
command = "Execute"
value = "loginctl kill-session $XDG_SESSION_ID"
modifier = ["modkey", "Shift"]
key = "x"

[[keybind]]
command = "Execute"
value = "slock"
modifier = ["modkey", "Control"]
key = "l"

# [[keybind]]
# command = "MoveToLastWorkspace"
# modifier = ["modkey", "Shift"]
# key = "w"

# [[keybind]]
# command = "SwapTags"
# modifier = ["modkey"]
# key = "w"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "Up"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "Down"

[[keybind]]
command = "MoveWindowTop"
modifier = ["modkey", "Shift"]
key = "Return"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "Up"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "k"


[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "Down"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "j"


[[keybind]]
command = "NextLayout"
modifier = ["modkey", "Control"]
key = "Up"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "Down"

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "Left"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "6"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "7"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "8"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "9"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "1"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "2"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "3"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "4"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "5"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = ["modkey", "Shift"]
key = "6"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = ["modkey", "Shift"]
key = "7"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = ["modkey", "Shift"]
key = "8"

[[keybind]]
command = "MoveToTag"
value = "9"
modifier = ["modkey", "Shift"]
key = "9"
```

my theme.toml is the same as posted above.

**Comment by stevensonmt** [comment]
Is it maybe just that your config.toml has `workspace` instead of `workspaces` here:
```
workspace = [
# only with internal screen
#{ x = 0, y = 0, width = 1920, height = 1080, id = 0 },

# external screen as main internal
{ x = 0, y = 0, width = 1920, height = 1200, id = 0 },
{ x = 1920, y = 0, width = 1080, height = 1920, id = 1 },
]
```
Also, what does autostart.sh look like?

**Comment by VuiMuich** [comment]
> Is it maybe just that your config.toml has `workspace` instead of `workspaces` here:

Ooh, that might be my bad. I have posted this typo earlier.

**Comment by tramhao** [comment]
sorry that computer is in office and I don't have another screen in home computer to test it. I'll check it monday and thanks so much.

**Comment by tramhao** [comment]
I changed workspace to workspaces but problem is the same, the gutter appears on both main monitor and also on side monitor.

My autostart.sh is as below:
```
#!/bin/bash

function run {
  if (command -v $1 && ! pgrep $1); then
    $@&
  fi
}

if [ $(hostname) = "XMLaptop" ]; then
  if [ `ifconfig wlp2s0 | awk '/inet /{ print $6;}'` = "192.168.186.255" ]; then
      # source ~/.xrandr
      run nextcloud --background
  fi
fi

# run remaps
# run xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources # Uncomment to use Xresources colors/settings on startup

# run picom -f -b --experimental-backends
# run dunst			# dunst for notifications
# run xset r rate 400 50 # Speed xrate up
# run unclutter		# Rmove mouse when idle
run fcitx5
run /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
run eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg)
# run /usr/lib/pam_kwallet_init
# exec /usr/lib/pam_kwallet_init &
run setbg ~/Pictures/wallpapers
# run emacs --daemon
if [ $(uname -n) = "lenovo-t480" ]; then
  if [ `ifconfig wlan0 | awk '/inet /{ print $6;}'` = "192.168.186.255" ]; then
      # source ~/.xrandr
      nextcloud --background --logfile ~/.cache/nextcloud.log --logdebug &
      # nextcloudcmd /home/tramhao/Nextcloud https://larryhao:zswd2*NC@nas.antarestec.com/remote.php/webdav
      # run autorandr -l docked
  fi
fi


```

**Comment by stevensonmt** [comment]
I believe the issue is in your theme.toml the gutter config needs `wsid` (for workspace ID) rather than `id`:
```
[[gutter]]
side = "Left"
value = 20
id = 0 <= should be wsid = 0
```
I thought this made sense because we're not specifying an ID of the gutter, but specifying an ID of the workspace on which to apply the gutter. I should put some effort into documenting this feature better.

**Comment by tramhao** [comment]
yes you're correct. I change it to wsid = 0 and everything works fine now! Thanks so much!

**Comment by VuiMuich** [comment]
> @VuiMuich do you mind checking the edit I made to the Wiki regarding Gutter config to see if it is clear?

Looks good to me.
Just wondering now, are workspace IDs implicitly set, when the field isn't set in `config.toml`?

**Comment by stevensonmt** [comment]
I don't believe the workspaces are assigned IDs implicitly. I will have to look more closely though because I don't exactly recall.

**Comment by VuiMuich** [comment]
Oh, right, that makes a lot of sense.
Now that you mention it, I guess we discussed this already in your PR, right?

Thanks for helping out!

@tramhao I guess this is solved, right? Feel free to reopen, if needed.
