### ISSUE TITLE
windows exit fullscreen when opening scratchpad

### ISSUE THREAD

**Issue by blackdragon2447** [leftwm/leftwm#578]
**Describe the bug**
When using a fullscreen and pulling up a scratchpad the window that was fullscreen will go back to tiling. 

**To Reproduce**
1. Open a window and put it in fullscreen mode
2. Open up a scratchpad
3. the window will exit fulscreen

**Expected behavior**
The fullscreen windows should stay in fullscreen.

**Environment:**
 - OS/Distro: Arch Linux
 - Output of `leftwm-check`: 
:: LeftWM version: 0.2.10
:: LeftWM git hash: ec7ebca
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK

**Comment by VuiMuich** [comment]
This is partially fixed, but the scratchpad is not on top of the fullscreen window.
Gonna open some stacking related issue later, then this can be closed.

**Comment by TornaxO7** [comment]
@SamClercky do you have a statement for this?

**Comment by VuiMuich** [comment]
This is not related to any of the recent scratchpad changes.
And as stated basically the issue described by OP is fixed. 

We left this open to remind for a fix of scratchpad stacking order.

A hacky fix might be to check in the window ordering, if any window is fullscreend to put scratchpads topmost.

I hope I'll manage to open the mentioned above issue for better stacking rules today.

**Comment by VuiMuich** [comment]
opened #864 to track improvement on stacking, so closing this one here.
