### ISSUE TITLE
Always float specified windows

### ISSUE THREAD

**Issue by patrikha** [leftwm/leftwm#582]
HI,

Is there also a possibility to setup rules for always floating some windows, like you can do in [i3](https://i3wm.org/docs/userguide.html#for_window) ?

Of course I can add a keybinding for this but it is very convenient to automatically float some pop-up windows.

**Comment by VuiMuich** [comment]
This is kind of a regular request. Specifically this is in #251.

We are still in need of a implementation to make configurable use of window classes.

In the mean time I can only serve you another workaround using scratchpads.
