### ISSUE TITLE
setting a layout that is not listed in `config.toml` breaks layout cycling

### ISSUE THREAD

**Issue by VuiMuich** [leftwm/leftwm#586]
**Describe the bug**
Assuming `config.toml` holds a list of layouts so `leftwm` is not using the default one.
When setting a layout that is not on this list, thy layout cycling with `PreviousLayout`/`NextLayout` breaks, presumably by overwriting `config.Layouts` with a `Vec<Layout>` holding only this one layout.

Unfortunately this is even `SoftReload` persistent.

**To Reproduce**
1. Configure in `config.toml`: `layouts = ["MainAndDeck", "Monocle", "CenterMainBalanced", "LeftWiderRightStack"]`
2. Use command `leftwm command "SetLayout EvenHorizintal"`
3. Use key bind or command for `NextLayout`/`PreviousLayout`
4. Layout won't change
---
5. `SoftReload`
6. layout is still not changable by `NextLayout`/`PreviousLayout`

**Expected behavior**
The `SetLayout` command should not remove the configured layouts from `config.Layouts`

The question ist, would we want this insertion to be semi-permanent until the next reload (then we would need to insert it into `config.Layouts` and make sure we reset correctly on reload) or would we want this to be temporary and on moving away from the layout it pops off from `config.Layouts`.

Personally I think it would be better if the command only would set the layout for the current scenario (depending if layout mode is `Tags` or `Workspaces`) and on `NextLayout`/`PreviousLayout` would return to the configured list. Not sure if it would be feasible to keep track what the layout previous in history was and return to it, or just start at the beginning of the list again.

**Comment by blackdragon2447** [comment]
the way it breaks changes with the layout that is set using `leftwm command`, setting `CenterMain` for example will allow me to cycle once before locking up.

**Comment by Sokom141** [comment]
Can I work on this issue?

**Comment by VuiMuich** [comment]
As of release `0.4.0` this is fixed by mystery commit.
