### ISSUE TITLE
[bug] hidden window's off-screen 'parking position' souldn't be affected by `MarginMultiplier`

### ISSUE THREAD

**Issue by VuiMuich** [leftwm/leftwm#591]
**Describe the bug**
when changing the margin multiplier to some big value, hidden windows protrude from the edge as it appears their 'parking position' is dependant on size of the visible windows.

**To Reproduce**
Steps to reproduce the behaviour (margins > 0 need to be configured in theme):
1. Open any two windows on layout `Monocle` (layout not specific, but this shows it the easiets)
2. issue `leftwm command "SetMarginMultiplier 20"`
3. see the hidden window protruding from the edge of the screen

**Expected behaviour**
The window parking position should be determined on the unaffected workspace and window size. so it is definitely off screen.

**Screenshots**
Margin Multiplier `1`![2021-11-30-210139_2560x1440_scrot](https://user-images.githubusercontent.com/4779365/144119408-1723a618-e817-4ab2-bb65-73273fa0efa5.png)
Margin Multiplier `13.5`
![2021-11-30-210154_2560x1440_scrot](https://user-images.githubusercontent.com/4779365/144119403-095e1910-aa8e-46a9-aad9-5956a0de9a52.png)

**Environment:**
should be irrelevant

**Additional context**
Sometimes it happens after `SoftReload`, that hidden windows protrude from the edge as well. I think this happens when the windows previously where on a different tag but are moved by 'restore logic' to the first tag.

**Comment by hertg** [comment]
unrelated to the issue: what browser is that?
btw, the amount of open tabs is making me anxious.

**Comment by hertg** [comment]
> [..] I think this happens when the windows previously where on a different tag but are moved by 'restore logic' to the first tag.

Does that still happen to you? That windows move to tag `1` after a `SoftReload`? Because I haven't had that problem in the past few weeks. I know that windows may move to Tag `1` if they were on a tag that no longer exists (should only happen if you remove tags from the config and `SoftReload`).

**Comment by VuiMuich** [comment]
> unrelated to the issue: what browser is that? btw, the amount of open tabs is making me anxious.

Thats qutebrowser/qutebrowser, really love it. Renders either with webengine or webkit, keyboard-driven, configured in python, in my experience runs rock solid (even though the web-engine eats 7.5 of 8 GB ram :joy:).
And yes, I am a tag-hog in browsers. I tend to forget things, when I bookmark them, so things I feel I might need later I keep open :man_shrugging: 

> Does that still happen to you? That windows move to tag `1` after a `SoftReload`? Because I haven't had that problem in the past few weeks. I know that windows may move to Tag `1` if they were on a tag that no longer exists (should only happen if you remove tags from the config and `SoftReload`).

Yea, I did some tests. when checking out your tag PR, when I got the occasional #560 or #517 and when the state file is broken due to switching branches.
