### ISSUE TITLE
EWMH tag _NET_WM_NAME not compliant

### ISSUE THREAD

**Issue by il-mich** [leftwm/leftwm#60]
`_NET_WM_NAME(CARDINAL): Type mismatch: assumed size 8 bits, actual size 32 bits.`

I'm guessing the tag is expecting a string in ascii, but the WM is setting it in Unicode

**Comment by lex148** [comment]
Congrats you found an interesting one.  Any info on how you were able to find this?

**Comment by il-mich** [comment]
Neofetch and Screenfetch both don't recognize the WM
The snippet in the OP is from Screenfetch

**Comment by lex148** [comment]
I just pushed a fix for this. If you are building from master you should see an update. I am out of town right now so I can't update aur. You can still get the updated but just reinstalling "leftwm-git"

**Comment by il-mich** [comment]
Wow nice, now I'll switch to the git version! I was looking for a solution myself but you're clearly a lot faster hahah
Thanks for the quick fix!
