### ISSUE TITLE
Resuming Neovim to foreground from XTerm in Leftwm freezes for a few seconds

### ISSUE THREAD

**Issue by cecton** [leftwm/leftwm#607]
**Describe the bug**

I run leftwm and use xterm and neovim. When I'm using neovim I often send the process to background using CTRL+z to go back to my shell. Then I type `fg` to resume neovim and get it in foreground again.

This work normally on i3 with xterm and neovim but it freezes for a few seconds in leftwm with xterm and neovim.

**To Reproduce**

1. Run leftwm
2. Run xterm
3. Open a file with neovim
4. Press Ctrl+z, you should see the shell again
5. Type `fg`, you will see the terminal freezing for a few seconds, then you will see neovim again

**Expected behavior**

No freeze.

**Screenshots**

I'll maybe post a video if this description wasn't clear enough.

**Environment:**
 - OS/Distro: ArchLinux
 - Logs: (will share later)
 - neovim: v0.6.0 (same issue on v0.5.1)
 - xterm: 370-1

**Additional context**

Related to #225 
Related to #587

**Comment by cecton** [comment]
:disappointed: I almost had switch to leftwm

**Comment by AethanFoot** [comment]
For me it seems to do only on the first time and vim still responds to input (just not visible). Is this the same for you or is it every time?

**Comment by AethanFoot** [comment]
It also seems to be what I suspected it to be. It is similar to before where it is stalling on a configure request.

**Comment by AethanFoot** [comment]
@cecton Does #610 work for you?
