### ISSUE TITLE
Feature request - Allow to rotate GridHorizontal

### ISSUE THREAD

**Issue by gitwipo** [leftwm/leftwm#612]
Hello, 

is it possible to add the rotate tag command for the Layout `GridHorizontal`.

The main window is always on the left side. Therefore it is only useful for the left workspace in a dual workspace configuration. On the right workspace the main window is on the far right of the vision.

Thanks,

**Comment by VuiMuich** [comment]
Sure, this should be relatively easy. I think we simply didn't see your use case, when we decided to spare this layout from this function.

**Comment by TornaxO7** [comment]
Shouldn't we close this issue?

**Comment by VuiMuich** [comment]
Yeah, thanks.
