### ISSUE TITLE
Polybar not starting properly

### ISSUE THREAD

**Issue by Trek3** [leftwm/leftwm#62]
On every startup or reload of leftwm, my polybar is invisible, as if it is rendered outside of the window.
![2019-12-17-163808_1920x1080_scrot](https://user-images.githubusercontent.com/4323569/71010262-dddef000-20eb-11ea-9b1a-7d387a5115a2.png)

You can see in the upper-left corner a little green square. But as soon as I press ModKey + # to change tag, the bar is displaying correctly
![2019-12-17-163829_1920x1080_scrot](https://user-images.githubusercontent.com/4323569/71010548-52b22a00-20ec-11ea-9142-c2935e39b764.png)

This is my up script concerning polybar:
```
if [ -x "$(command -v polybar)" ]; then
	pkill polybar
	leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' |
	while read -r w x y; do
		export OFFSETX=$x
		export OFFSETY=$y
		export WIDTH=$w
		export MONITOR="$(polybar -m | sed s/:.\*// | tac)"
		polybar -c $SCRIPTPATH/polybar.config mainbar &> /dev/null &
	done
fi
```

and this is my mainbar config of polybar

```
[bar/mainbar]
monitor = ${env:MONITOR}
offset-x = ${env:OFFSETX}
offset-y = ${env:OFFSETY}
width = ${env:WIDTH}
height = 40
fixed-center = false
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 5
line-color = ${colors.primary}
border-size = 0
border-color = ${colors.foreground}
padding-left = 0
padding-right = 0
module-margin-left = 0
module-margin-right = 2
font-0 = Hack:pixelsize=12;2
font-1 = Hack:pixelsize=18;2
font-2 = FontAwesome:size=12;2
font-3 = Monofonto:pixelsize:18;2

modules-left = ewmh
modules-center = xwindow
modules-right = alsa backlight-acpi wlan battery date powermenu
;tray-position = right
;tray-padding = 2
cursor-click = pointer
cursor-scroll = ns-resize
wm-name = LeftWM
bottom = false
```

do you have any idea why is this happening?

**Comment by lex148** [comment]
I Think this is a timing issue in LeftWM and xlib. Give me a bit to do a little research and I should be able to come up with a fix.

**Comment by lex148** [comment]
Ok, there is a fix up on master.
I also pushed the update to aur/leftwm-git if you are using that.
