### ISSUE TITLE
Unable to find configuration documentation

### ISSUE THREAD

**Issue by aengelas** [leftwm/leftwm#63]
Is there a place that documents all of the available commands which can be bound to keys? I see the default config file generated when first run, but It's unclear what else can go in there.

Same goes for things like configuring displays.

**Comment by lex148** [comment]
I did a quick write up of the configuration options. You can find them here
[https://github.com/leftwm/leftwm/wiki/Config](https://github.com/leftwm/leftwm/wiki/Config)

If anything is confusing please let me know I want to make it as clear as I can.
