### ISSUE TITLE
[Feature Request] LeftWM should have an option to remember the latest application size and layout

### ISSUE THREAD

**Issue by federicotorrielli** [leftwm/leftwm#632]
Hi,
As the title says, it would be cool for LeftWM to have an option to remember the latest layout and application size the app was set in. For now the default one is to set fullscreen the current application but I want certain application to remember that they were floating and of a certain size.

This is what I get:
![image](https://user-images.githubusercontent.com/31370059/147127451-86672ffd-4222-4d8a-b89c-11eb99c99cd4.png)

VS this is what I want them to be when I open this app:
![image](https://user-images.githubusercontent.com/31370059/147127531-9ff917d4-dd72-4828-b222-cb63a5839125.png)

Thanks in advance for the support and patience,
Federico.

**Comment by AethanFoot** [comment]
This in theory isn't too difficult, however we would need consider how we can optimise this. Do we want this to remember past a reload or past a restart? How many windows would we want to remember in memory? If we go past the amount of windows we want in memory, do we start storing them in a file (preferably in chunks to reduce constant writing)? Do we want to match the windows by class or by name? Do we only save a window if it is closed while floating?

This could be thought as an extensions to window rules (window rules needs to have more options to support this, but they are planned), where we dynamically add the known rules as floating windows are closed. I would say these should last past leftwm being completely killed (e.g. logout), I am not sure whether they should go past soft reload. I do think this should be specifically enabled in config (maybe a build flag? might be a bit awkward though), as this would make the wm more resource intensive.

Thanks for the request and sorry for the delay on replying to it.

**Comment by federicotorrielli** [comment]
> Do we want this to remember past a reload or past a restart?
From my perspective, past a restart. I would like to have an option to always remember the size of the window if it was in floating mode.

> How many windows would we want to remember in memory?
Does it really have to be a fixed number? In that case, I don't want to choose it. Let it be like 5 or 6.

> If we go past the amount of windows we want in memory, do we start storing them in a file (preferably in chunks to reduce constant writing)?
I would always store them in a file, because of the restart policy.

> Do we want to match the windows by class or by name?
I would prefer it to be a name match, and if not possible, a class (like OBS recording does!)

> Do we only save a window if it is closed while floating?
Yes. That is perfect!

> maybe a build flag?
Sheesh. No, that would be gross.

> I do think this should be specifically enabled in config
Agreed.

**Comment by hertg** [comment]
I think adding the possibility to specify resolutions+position in the window_rules might tackle something similar, has that been proposed before? Would certainly be less user-friendly though.

**Comment by VuiMuich** [comment]
Following up on #674 and #677 maybe remembering the last used tag might be something someone might be interested in as well...

**Comment by marcelarie** [comment]
This will be cool, any progress ?

**Comment by VuiMuich** [comment]
I don't think anyone took a stab on this yet.
Unfortunately most of the regular contributors appear to experience heavy real life interference these days.
So if someone wants to take the opportunity to step up on this, feel welcome to do so.
