### ISSUE TITLE
Freeze and mess up the layout

### ISSUE THREAD

**Issue by M-Mabrouk1** [leftwm/leftwm#633]
The window manager freeze and doesn't get my click to activate any window and it doesn't work again until I press the super key and when the super key is pressed it selects any random window and puts it in floating mode.

**Environment:**
 - OS/Distro: Arco linux
 - Output of `leftwm-check`
:: LeftWM version: 0.2.11
:: LeftWM git hash: 399345b
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK

**Comment by arcolinuxz** [comment]
I know what happens here.
Super + left click mouse will change a window to float. 
Would like to turn that off if possible?

**Comment by M-Mabrouk1** [comment]
Hey Erik, I would like to take this as a chance to thank you and your team for all your effort and your work.
but no this is not the case I know super + left click gets window into a floating mode.
What actually is it freezes out of nowhere it doesn't change focus even if I click into any window it doesn't accept any key presses but the super key and when the super key is pressed it gets a random window into a floating mode.

**Comment by arcolinuxz** [comment]
Opened up a new issue for my question #634

**Comment by AethanFoot** [comment]
What focus behaviour are you using and are you able to provide more steps to reproduce or steps that lead to the situation.
Thanks.

**Comment by M-Mabrouk1** [comment]
I use ClickTo focus behaviour,
what happens most of the time that I am on a window like a browser and I want to change tabs using the mouse, the mouse moves freely but it doesn't select any tab if there is maybe a terminal beside the browser the mouse can hover over it but it doesn't change focus it's like the focus is forzen on that window and on it's state I can't even change it's state. the only things that breaks this is pressing the super key without even pressing the mouse button it chooses one of the windows in this tag put it into floating mode.
I can then put everything into tiling.
it happens also frequently.

**Comment by VentGrey** [comment]
An easy way to trigger this "freezing" stage is the Debian Spotify Package, just exit it with the default keybbinds and only the mouse will work. Opening telegram images seems to trigger a similar issue but Telegram freezes only.

**Comment by M-Mabrouk1** [comment]
I don't have spotify or telegram , it happens a lot this freezing issue I tried to take a screenrecord using peek when it happens but peek also freezes.

**Comment by M-Mabrouk1** [comment]
I think the issue is related to the clickto focus behavour,
I changed to sloppy and I haven't had the issue once for now , I will keep updating also.

**Comment by arcolinuxz** [comment]
mine is set to 
focus_behaviour = "Sloppy"

for the last weeks

**Comment by AethanFoot** [comment]
@M-Mabrouk1 could you give #663 a test and see if you can beat leftwm into freezing again.

**Comment by M-Mabrouk1** [comment]
Yes Sure, I will get back to the same focus behaviour and test it and I will keep you updated or close the issue If I didn't encounter it.

**Comment by marcelarie** [comment]
I think this is what happens to me too. I created an issue here https://github.com/leftwm/leftwm/issues/655

**Comment by M-Mabrouk1** [comment]
unfortunately the issue still exitsts with the ClickTo focus behaviour, still the same freeze and then it only gets unfrozen if I press alt or super and then when I press it puts a random window in floating mode.

**Comment by marcelarie** [comment]
> unfortunately the issue still exitsts with the ClickTo focus behaviour, still the same freeze and then it only gets unfrozen if I press alt or super and then when I press it puts a random window in floating mode.

For me what worked best to fix this is to have different keys for mod and mouse keys.

```toml
modkey = "Mod4"
mousekey = "Mod1"
```

**Comment by M-Mabrouk1** [comment]
I tried that and it didn't solve it.

**Comment by kid** [comment]
Just a thought, but I'm wondering if the issues does not come from this code:
https://github.com/kid/leftwm/blob/c244805a4ab1e4b7ea52915bb7fc477536aa7ca6/leftwm-core/src/handlers/mouse_combo_handler.rs#L57-L62
the `focus_window` method is called regardless of any modkey pressed

**Comment by VuiMuich** [comment]
> the `focus_window` method is called regardless of any modkey pressed

This is basically the desired behaviour: click on a window without any mod key pressed to move focus to this window.
Maybe this being more explicit could help:
```rust
 xlib::Button1 | xlib::Button3 
     if (self.focus_manager.behaviour == FocusBehaviour::ClickTo && !is_mouse_key) => 
 { 
     self.focus_window(&window); 
     None 
 } 
```

**Comment by AethanFoot** [comment]
@M-Mabrouk1 can you give #696 a test (currently only left click if fully enabled)

**Comment by M-Mabrouk1** [comment]
> @M-Mabrouk1 can you give #696 a test (currently only left click if fully enabled)

how can I test it ?! 
do I need to clone checkout the pull request and build?

**Comment by VuiMuich** [comment]
> > @M-Mabrouk1 can you give #696 a test (currently only left click if fully enabled)
> 
> how can I test it ?! do I need to clone checkout the pull request and build?

Correct.

**Comment by M-Mabrouk1** [comment]
> > > @M-Mabrouk1 can you give #696 a test (currently only left click if fully enabled)
> > 
> > 
> > how can I test it ?! do I need to clone checkout the pull request and build?
> 
> Correct.

Ok I build it on another machine and I will test it,
is there is a way to copy the binaries or the executables to another machine withour building?

**Comment by VuiMuich** [comment]
Sure you can. You find them in `<leftwm-repo-dir>/target/release` (or `<leftwm-repo-dir>/target/debug` if you build without the `--release` flag, but actually there is no need for a debug build here). Just copy them (`leftwm`, `leftwm-check`, `leftwm-command`,  `leftwm-state`, `leftwm-worker`) to `/ust/bin` or to any place of your liking and symlink to `/ust/bin`.

**Comment by M-Mabrouk1** [comment]
ok thanks I am testing the #696 fix now on two machines and I will update you.

**Comment by M-Mabrouk1** [comment]
> @AethanFoot
### Ok I I didn't encounter the issue with this fix, however there was two things with that built .
- First after some time I am not able to scroll over polybar modules such as moving between workspaces or adjusting volume, it usually needs soft reload to work and then it stops again.
- Second usually I used to be able to middle click on a tab when the browser is unfocused and it works, it wasn't working with that built like the next image, the terminal was focused and I was pressing the middle click to close the tab and it wasn't working ![Peek 2022-02-08 01-09-github](https://user-images.githubusercontent.com/76488499/152945422-57404b6b-f8cc-45fe-a066-23bb80697cf3.gif)

**Comment by marcelarie** [comment]
> > @AethanFoot
> ### Ok I I didn't encounter the issue with this fix, however there was two things with that built .
>     * First after some time I am not able to scroll over polybar modules such as moving between workspaces or adjusting volume, it usually needs soft reload to work and then it stops again.
>     * Second usually I used to be able to middle click on a tab when the browser is unfocused and it works, it wasn't working with that built like the next image, the terminal was focused and I was pressing the middle click to close the tab and it wasn't working ![Peek 2022-02-08 01-09-github](https://user-images.githubusercontent.com/76488499/152945422-57404b6b-f8cc-45fe-a066-23bb80697cf3.gif)

This happens to me to without the  https://github.com/leftwm/leftwm/pull/696 feature. Sometimes the mouse disappears and I need to reload.This happen with my past `ArcoLinux` distro and with the actual one (`nixos`). I have a fork of the `smooth` theme so I will look if that is the problem. But it seem more related to the bug that you comment here.

**Comment by VuiMuich** [comment]
Took the liberty to edit the formatting, I hope you don't mind.

**Comment by AethanFoot** [comment]
The middle mouse click thing should be fixed now.
