### ISSUE TITLE
Windows key + Right mouse click on window makes it floating - change behavior

### ISSUE THREAD

**Issue by arcolinuxz** [leftwm/leftwm#634]
**Describe the bug**
How to change the behavior to either not be floating witht that keycombo or go back into tiling when clicked a second time - so toggle modus.

Super + left click mouse will change a window to float. 
Would like to turn that off if possible?

A video to show what happens on our end

https://youtu.be/Gtvwz8RxuIQ

**To Reproduce**
See video

**Expected behavior**
Either no change in window or change from floating to tiled.

**Environment:**
 - OS/Distro: ArcoLinux 
 - Output of `leftwm-check`
`[erik@ArcoLinux-IsoBuilder ~]$ leftwm-check
:: LeftWM version: 0.3.0
:: LeftWM git hash: 55bae63-modified
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
[erik@ArcoLinux-IsoBuilder ~]$`

**Additional context**

**Comment by AethanFoot** [comment]
I have a couple ideas we could use to improve this:
1. We could make it so ```mousekey``` can be a list of modifiers.
2. We could only switch a window to floating mode once the first movement event comes in.
3. We can add a separate mod binding which combines with a mouse click to call ```FloatingToTile```.
4. Having it so a single mouse click without any movement re-tiles a window would be possible but may be awkward and would be a more complex solution to point 3.

All of these points could be implemented together (except 4 would make 3 redundant).

**Comment by arcolinuxz** [comment]
How about changing option to FloatingToggle
