### ISSUE TITLE
Can't bring a window with wmctrl.

### ISSUE THREAD

**Issue by juansegaes** [leftwm/leftwm#637]
**Describe the bug**
The command `wmctrl -i -R <WIN>` does nothing

**To Reproduce**
Get any window id with the command `wmctrl -l`
Type the command `wmctrl -i -R <WIN> `.
The command `wmctrl -i -a <WIN>` is working as intended to  switch to the desktop containing the window `<WIN>`, raise the window, and give it focus,  so I know the problem is not the window id.

**Expected behavior**
As stated in the wmctrl manpage:
Move the window `<WIN>` to the current desktop, raise the window, and give it focus. 
Which should work in any  EWMH compliant window manager

**Environment:**
 - OS/Distro: Arcolinux
 - Output of `leftwm-check`:
```
:: LeftWM version: 0.3.0
:: LeftWM git hash: 55bae63-modified
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```

**Comment by VuiMuich** [comment]
I think this is an issue of `leftwm`'s concept of `Tags` colliding with `EWMH` definition of a `DESK`

When I do:
```
$ wmctrl -lG
0x01c00029  0 5349 129  1248 1363 manjobook benwilliamgraham/tree-sitter-llvm: Tree sitter parser for LLVM - qutebrowser
0x05200002  0 7909 129  1248 1363 manjobook fish /home/vuimuich/Git/helix
0x0a200002  0 7909 129  1248 1363 manjobook hx leftwm-core/src/handlers/command_handler.rs /home/vuimuich/Git/leftwm
0x04800002  0 5349 129  1248 1363 manjobook fish /home/vuimuich/Git/nushell
0x06600002  0 -2531 129  1248 1363 manjobook fish /home/vuimuich
0x01200002  0 -5091 129  1248 1363 manjobook v /home/vuimuich
0x02800004  0 5349 129  2528 1363 manjobook leftwm-theme - Discord
0x01e00002  1 283  133  2272 483  manjobook wmctrl -lG /home/vuimuich
0x03e00002  0 6601 721  1248 1398 manjobook Alacritty
0x00c020d6  7 42   26   320  44   manjobook Eww - left
0x00c020da  7 2062 26   498  44   manjobook Eww - tags
0x00c020de  7 3982 26   548  44   manjobook Eww - right
```
I appears that any window is on the same `DESK` (0) except the `Dock` windows (on 7) of my `eww` bar and the `scratchpad` (on 1). I'll try to get a better understanding, how we are actually exposing the relevant `EWMH` parameters and how we could possibly get better compliance here.
Maybe @AethanFoot might be able to give a better insight as he probably would have a better understanding of this area of our code.

**Comment by VuiMuich** [comment]
Looks like we also have a bug, that we loose the window's desktop information on `SoftReload`, that's why almost all had `0` in my above test. But I am not sure if this is related to OP's issue.
Also no pointers yet, why the `-a` flag works and the `-R` one doesn't though.

**Comment by AethanFoot** [comment]
For the initial issue we need to add a case to event_translate_client_message.rs NetCurrentDesktop message type to handle when this is called on the root window and a specified window. When the message has the root window we need to switch to the desktop, e.g. what is working now with the -a flag. When we have a specific window we instead need to call a MoveToTag on that window, this may require a new command to act upon a specified window rather than the focused window.

On the new point it appears at some point we lost the action SetWindowTags in the restore state I added a while back (Can't remember if it got replaced or something).

**Comment by hornyjailfish** [comment]
issue still here
`wmctrl -i -R` and `wmctrl -i -a ` give focus but leftwm dont switch tag

```
leftwm-check
:: LeftWM version: 0.3.0
:: LeftWM git hash: c002da7
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```
