### ISSUE TITLE
Feature request: Scratchpad window support

### ISSUE THREAD

**Issue by aengelas** [leftwm/leftwm#64]
I'd love to see a feature like i3's scratchpad (https://i3wm.org/docs/userguide.html#_scratchpad). Do you have any plans to support something like that? Is there a roadmap or TODO list anywhere for the project?

**Comment by lex148** [comment]
I really like this idea. I will have to put some thought into it.

**Comment by murlakatamenka** [comment]
i3's scratchpad allows having a self-made "dropdown" terminal (think Yakuake / Guake), so essentially it's a terminal that's always at your fingertips. Extremely useful!
