### ISSUE TITLE
FocusWorkspace(Next|Previous) always reset the focus to the first window

### ISSUE THREAD

**Issue by kid** [leftwm/leftwm#641]
**Describe the bug**

When calling FocusWorkspace(Next|Previous) the focus always set reset to the first window on the workspace

**To Reproduce**

With at least 2 workspace defined
1. Create 2 windows on the first workspace
2. Focus the second window
3. Call `FocusWorkspaceNext
4. Call `FocusWorkspacePrevious

**Expected behavior**

The second window should have the focus

**Actual behavior**

The focus get reset to the first window

**Environment:**
 - OS/Distro: NixOS
 - Output of `leftwm-check`
```
❯ leftwm-check             
:: LeftWM version: 0.3.0
:: LeftWM git hash: fd42fe8bff163aa9b383e946f2062f33ab5500be
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK 
:: Checking theme . . .
    -> Theme OK 
```

**Additional context**

Tested with `focus_behavior` `Driven` and `ClickTo`

**Comment by VuiMuich** [comment]
Hi,
may I ask you back a few questions, as I am not able to reproduce.
Have you tested different layouts? (I tried `MainAndDeck`, `CenterMainBalanced` and `LeftWiderRightStack` and I always get the last focused window when returning to this workspace.)
When switching workspaces by other means you get the correct behaviour, right?

**Comment by kid** [comment]
I actually discovered it using my own branch that includes #636 and #640, and didn't use any other layout there other than `LeftMain`, but I then tested on master with I think the default layout `MainAndVertStack`.

What other means of switching workspace is there? with the mouse the focus would follow the mouse, or would switch to a window you click to with `ClickTo`

I did try switching between tags and there the focused is restored.

For the the hash, I'm using a Nix overlay, so it was actually NONE and I replaced it with the commit I use (nix's build process actually removes the .git folder)

I did manage to write a test case for it in the command handler. so I can try to fix it.

Are you using `focus_behavior = Sloppy` by any changes?
Because I think [this code](https://github.com/leftwm/leftwm/blob/main/leftwm-core/src/handlers/command_handler.rs#L602-L610) could restore the focus in that case by moving the cursor? Otherwise I think the code would find the first window on the workspace no?

**Comment by VuiMuich** [comment]
Oh, I'm sorry, I mixed up `FocusNext/PreviousTag` and `FocusWorkspaceNext/Previous`. (I am using `ClickTo` as well btw.)

You are right, this is indeed a bug of the workspace focus behaviour.
A fix would indeed be welcome. I think a good startingpoint might be the `goto_tag_handler` I guess, as the behaviour when changing tags is correct.
