### ISSUE TITLE
XDG autostart not working properly

### ISSUE THREAD

**Issue by nblxxx** [leftwm/leftwm#644]
Hi there fellow adventurers!
It seems line 55 should come before 48 here, as the env var is queried inside the call to autostart.
This currently causes autostart to launch everything and to even ignore the "Hidden=true" in desktop entries for some reason.
https://github.com/leftwm/leftwm/blob/acf2407bc48286ff5388a3d301b5adef59150d52/leftwm/src/bin/leftwm.rs#L47-L55

**Comment by VuiMuich** [comment]
Welcome adventurer!
Good catch.
Would you have a chance to checkout #646? I'm currently blocked from exiting my session for at least the next 24h..

**Comment by nblxxx** [comment]
Sure! I just did, checked my desktop entries against running procs and the rules seem to apply properly this time.
