### ISSUE TITLE
Theme doesn't apply on HEAD (97de790).

### ISSUE THREAD

**Issue by rigoletto-freebsd** [leftwm/leftwm#652]
Hello,

After moving to HEAD (97de790) the theme doesn't apply anymore. Does it need some modification somewhere?

```
:: LeftWM version: 0.3.0
:: LeftWM git hash: 11-eol-10161-gc09e8a9dfbff-modified
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK (has XDG_RUNTIME_DIR)
:: Checking theme . . .
    -> Theme OK
```

Thank you.

**Comment by VuiMuich** [comment]
Unfortunately #643 was a little bit of a breaking change.
Please use either `leftwm command "LoadTheme <ThemePath>"` or when you want to stick to the `echo to commandpipe` method please change `command.pipe` to `command-0.pipe` (or any other display id you can get from `echo $DISPLAY`)

**Comment by rigoletto-freebsd** [comment]
Adapting the command.pipe to command-0.pipe worked as expected. I had previously tried `leftwm command "LoadTheme <ThemePath>"` and that wasn't worked.

Thanks!

**Comment by VuiMuich** [comment]
That's great!

The most common pitfall with `leftwm command` in general is, when using commands that take arguments that the command and the argument need to be inside the same string. We intend to change this with an upcoming config breaking release.
