### ISSUE TITLE
Add init command that generates default config

### ISSUE THREAD

**Issue by NChechulin** [leftwm/leftwm#658]
Currently the config is only generated when `leftwm` is being launched for the first time. It is not obvious that the config will be created by the wm, and searching for default config does not give any results.

It's a small problem,  but it would be great to fix it.

**Comment by VuiMuich** [comment]
Welcome Adventurer!

I have recently been thinking about a new sub-command `leftwm config` that opens the config.toml in `$EDITOR`. It could have a flag `-n | --new` that writes the default config. This could then be used with an install-hook by package-maintainers.

**Comment by mautamu** [comment]
(As a temporary fix for package maintainers, running leftwm-check will also create a new file).

**Comment by Mifom** [comment]
Hi
Can I pick this issue?
