### ISSUE TITLE
Building leftwm on the basis of commit 569 will end in a broken Leftwm

### ISSUE THREAD

**Issue by erikdubois** [leftwm/leftwm#659]
Is there a command I can run that can gather all the data you need to debug and set it to termbin or any other online service?

Now working on this release - r567.e93422f-1

The rest of ArcoLinux is working on this release - r563.9296179-1

**Comment by VuiMuich** [comment]
This is most likely the same issue as in #652 if you are relying on `echo <some command> > $XDG_RUNTIME_DIR/leftwm/command.pipe` method.
You could either change to `leftwm command` or insert `-0` before the `.pipe`

**Comment by erikdubois** [comment]
Found the solution
code can be found on ArcoLinux github lateron

**Comment by VuiMuich** [comment]
@erikdubois could you please link the blob when it's in the repo?

**Comment by arcolinuxz** [comment]
https://github.com/arcolinux/arcolinux-leftwm/commit/93320bb020d5998ae1efe2548b74f33df9508603

**Comment by arcolinuxz** [comment]
Am I correct that leftwm-theme upgrade does not work yet?
That would be now very handy with all these changes to our themes?
Ps I will ask the other github too.
