### ISSUE TITLE
window_rules ignored.

### ISSUE THREAD

**Issue by rigoletto-freebsd** [leftwm/leftwm#661]
Hello, this is me again!

I'm on da3089f trying the new `window_rules` feature and it doesn't work for me. ^^

This is what I added to `config.toml`:
```
window_rules = [
{window_class = "Firefox", spawn_on_tag = 2},
]
```
What am I missing?

FreeBSD 13.0R

Thank you again!

**Comment by rigoletto-freebsd** [comment]
_Downgrading_ to 9e1644b didn't help.

**Comment by kid** [comment]
According to `xprops`, it should be in small caps:
```
WM_CLASS(STRING) = "Navigator", "firefox"
```
Can you try that?

**Comment by rigoletto-freebsd** [comment]
> According to `xprops`, it should be in small caps:
> 
> ```
> WM_CLASS(STRING) = "Navigator", "firefox"
> ```
> 
> Could you try that?

I tried `small caps` but didn't work either. Anyway, `xprop` tell different in here:

`WM_CLASS(STRING) = "Navigator", "Firefox"`

Otherwise, I tested now adding other windows and the ones using `window_title` are working, except WeeChat but maybe because it should be "WeeChat 3.4" (I'm suposing the space may be a issue)

**Comment by rigoletto-freebsd** [comment]
More tests. 

`WM_CLASS(STRING) = "texstudio", "TeXstudio"`

if I use "texstudio" it works but "TeXstudio" not. Same for some others I tested, the first option tends to work but the second not, except Firefox, none of the WM_CLASS options work.

**Comment by rigoletto-freebsd** [comment]
Btw, it would be intersting if we could use something like this:

`{window_title = "keepassxc", spawn_floating = true},`

for windows whose we don't need/want to spawn on a specific tag but should always be floating. My personal user case are those living on the icon tray.

Thank you.

**Comment by AethanFoot** [comment]
Can you check if #666 fixes the issues (hopefully we don't summon satan)

**Comment by rigoletto-freebsd** [comment]
> Can you check if #666 fixes the issues (hopefully we don't summon satan)

Apparently **yes** except the "WeeChat 3.4" isn't working. I had no time to test extensively but I later I will rename the WeeChat window title to something with just a single word to try out (didn't work before this patch, as reference).

Thanks!

**Comment by rigoletto-freebsd** [comment]
Unfortunately ever changing the WeeChat title to a single word doesn't work.

Thanks!

**Comment by AethanFoot** [comment]
Hmm strange, it seems to work for me. However the default _NET_WM_NAME is "weechat".

**Comment by carrascomj** [comment]
Running

```shell
alacritty -t weechat -e weechat
```

with config

```toml
window_rules = [
  {window_title = "weechat", spawn_on_tag = 3},
]
```

works as expected.

How are you setting the title? The problem may be that it is being set right **after** the window is spawned.

**Comment by rigoletto-freebsd** [comment]
The title is set on WeeChat configuration otherwise, with default, I get "terminal" as title:

`/set weechat.look.window_title "sometitle"`

**Comment by rigoletto-freebsd** [comment]
I've set the title to default and started runnig `alacritty -t weechat -e weechat` and WeeChat starts but not show up.

I suppose it should be something local...

**Comment by AethanFoot** [comment]
It might not be showing up as the tag numbers start at 1.

**Comment by rigoletto-freebsd** [comment]
> It might not be showing up as the tag numbers start at 1.

I'm using "0" to tag "10" on the config. The others are opening correctly.

`Should I use {window_title = "WeeChat 3.4", spawn_on_tag = 10},`

I'm confused, now. ^^

**Comment by AethanFoot** [comment]
Ye 10 would be used. Currently it requires the tags index starting from 1 e.g. 1, 2, 3, ..., 10, 11,...

**Comment by rigoletto-freebsd** [comment]
Yes, using

`tags = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]`

worked. 

Thank you.
