### ISSUE TITLE
Dialogue windows getting cut-off

### ISSUE THREAD

**Issue by 0323pin** [leftwm/leftwm#668]
**Describe the bug**
Dialogue windows get cut-off when tiling client size is smaller than the dialogue window.
![2022-01-18-091558_1366x768_scrot](https://user-images.githubusercontent.com/90570748/149902498-caae19a3-6c14-4b04-a128-70307c04f11b.png)

![2022-01-18-091620_1366x768_scrot](https://user-images.githubusercontent.com/90570748/149902534-7458462f-0906-4813-a883-a3137ca14ee3.png)

![2022-01-18-091708_1366x768_scrot](https://user-images.githubusercontent.com/90570748/149902571-37fc51a5-3fc3-4b92-a95c-18b85fa85e2d.png)

**To Reproduce**
Any action that triggers a dialogue window on a small tile.

**Expected behavior**
Dialogue window is placed in such way that it doesn't get cut or, it's resized to fit available screen state.

**Environment:**
 - OS/Distro: NetBSD-current
 - Output of `leftwm-check`
```
2022-01-18 09:18 > leftwm check
:: LeftWM version: 0.3.0
:: LeftWM git hash: 5e1ccc94d1
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK (has XDG_RUNTIME_DIR) 
:: Checking theme . . .
    -> Theme OK 

```

**Additional context**
Not a major issue and probably something you are already aware of.

**Comment by AethanFoot** [comment]
I think the best approach here would be to center the dialog on the workspace when it breaches the edge of its workspace.

**Comment by 0323pin** [comment]
@AethanFoot I agree with that. As said, this is a minor improvement, nothing critical. Usually, I have only two clients _per_ tag or, rarely three but, thought I'd just bring it up for discussion.
Thanks for considering it.

**Comment by cesarFuhr** [comment]
@AethanFoot can I fix this?
I checked the code, made some simple changes and tested locally... seems to have solved the problem.

**Comment by AethanFoot** [comment]
@cesarFuhr of course. Open up a pr!
