### ISSUE TITLE
Xlib vs XCB?

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [leftwm/leftwm#67]
I'm curious why you guys choose xlib over xcb. I thought xcb was supposed to be the newer, better, faster xlib. Does xlib offer something that xcb can't deliver?

**Comment by lex148** [comment]
When leftwm was first created there was significantly better support in rust wrapping xlib. At the time it appeared the XCB crate was abandoned.  This is no longer the case, there is no reason why leftwm couldn't be converted to use XCB. It would just take time.
