### ISSUE TITLE
Sublime-text-4 opens only on workspace 4

### ISSUE THREAD

**Issue by arcolinuxz** [leftwm/leftwm#674]
**Describe the bug**
Sublime-text-4 or subl only opens on workspace 4

**To Reproduce**
1.Doubleclick any file and open with sublime text 4

**Expected behavior**
Open on the workspace I am (was previous so)

**Environment:**
 - OS/Distro: ArcoLinux - leftwm-dev-git r579.52e340b-1
 - Output of `leftwm-check`
```
[erik@ArcoLinux-IsoBuilder ~]$ leftwm-check
:: LeftWM version: 0.3.0
:: LeftWM git hash: 52e340b
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
[erik@ArcoLinux-IsoBuilder ~]$
```

**Additional context**
I have seen you are working on code to tell a particular application to go to a particular workspace. 
I guess this is a test and the test is still in the code.

Would like to learn what code needs to go in the configuration file to be able to assign an application to a workspace? Or unassign...

**Comment by arcolinuxz** [comment]
Closing for now.
Needs further investigation on my part.

**Comment by VuiMuich** [comment]
> **Describe the bug** Sublime-text-4 or subl only opens on workspace 4
> 
> **To Reproduce** Steps to reproduce the behavior: 1.Doubleclick any file and open with sublime text 4

This seems odd, would you mind to report your findings back here? This might be helpful in support situations, even if it's not a bug of ours.

> Would like to learn what code needs to go in the configuration file to be able to assign an application to a workspace? Or unassign...

The [Window Rules](https://github.com/leftwm/leftwm/wiki/Config#window-rules) got merged a couple of days ago.
You can use them like this in your `config.toml`:
```toml
window_rules = [
  # windows whose WM_CLASS is "Navigator" will be spawn on tag 2 (by position, 1-indexed)
  {window_class = "Navigator", spawn_on_tag = 2},
  # windows whose window title is "Pentablet" will be spawned floating on tag 9
  {window_title = "Pentablet", spawn_on_tag = 9, spawn_floating = true},
]
```

**Comment by arcolinuxz** [comment]
.config/sublime-text - started with a new config...
removed openbox from my system

everything works back as usual

**Comment by arcolinuxz** [comment]
"remember_workspace": false,

add this line to your personal sublime settings
