### ISSUE TITLE
Window disappears after launch

### ISSUE THREAD

**Issue by guigot** [leftwm/leftwm#676]
**Describe the bug**
After launch, the window disappears. It just happens with the game Binding of Isaac from Steam. The process is still here, the sound of the game continues but any window is present.

**To Reproduce**
1. Start the game
2. Game's window appears for few seconds and disappears.

**Expected behavior**
The window stays present.

**Environment:**
 - OS/Distro: Debian sid
```
:: LeftWM version: 0.3.0
:: LeftWM git hash: 52e340b
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK 
:: Checking theme . . .
    -> Theme OK 
```

**Additional context**
the command line 'wmctrl -l -G' displays the window during the time where it displayed but not when it disappeared.

Thanks for your amazing work !

**Comment by AethanFoot** [comment]
Hmmm thats weird. It loads for me using proton and native. If you are using proton what version are you on?

**Comment by guigot** [comment]
I was not very precise about the game : it is with all DLC so with Repentance which is Windows only.
Proton experimental. Same behaviour with 6-3.

I just tried without the last DLC Repentance and it's working fine.

**Comment by AethanFoot** [comment]
It seems to be working for me on experimental and glorious eggrolls's 7.0rc2-ge-1. Are you launching it in fullscreen?

**Comment by guigot** [comment]
In windowed. 

I tried with GE 7.0rc6 and it's working. With Proton experimental too now. I don't know what happens there, maybe a specific local problem.

**Comment by AethanFoot** [comment]
Ye that is weird

**Comment by hertg** [comment]
Issue became stale and couldn't be reproduced. 
Reopen if still an issue :)
