### ISSUE TITLE
Sublime-text-4 and others open in wrong/different tag.

### ISSUE THREAD

**Issue by PeterDauwe** [leftwm/leftwm#677]
Sublime-text-4 only opens on the same place it opens the first time.
After i delete the config of Sublime-text  , it now stays on the tag where it opens initially.

With firefox : went to AUR to download a snapshot - the save window appeared on a different tag.

Did not change any code in config.toml.
Did not add any window rules.

Update : leftwm-git has this problem. Installed leftwm 0.2.11 no problem

**Comment by arcolinuxz** [comment]
This is related to this issue - https://github.com/leftwm/leftwm/issues/674

**Comment by arcolinuxz** [comment]
I just created a new package on our code of today.
https://github.com/leftwm/leftwm/commit/c244805a4ab1e4b7ea52915bb7fc477536aa7ca6

Sublime-text opens on a specific workspace (that sometimes switches).
```

 ╭─erik@ArcoLinux in ~
 ╰─λ leftwm-check
:: LeftWM version: 0.3.0
:: LeftWM git hash: c244805
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK

 ╭─erik@ArcoLinux in ~ took 12ms
 ╰─λ
```

https://youtu.be/N1ghf1S_ubI

**Comment by VuiMuich** [comment]
Hi Erik,
I just installed `sublime-text-4-4.4126-1` from the AUR to test this and I found this:
sublime seems to keep track on its own on which tag it has been last and always reproduce this. I managed even to have two windows on different tags and they restored in the exact way after closing and opening again.

**Comment by arcolinuxz** [comment]
Finally found the setting of sublime text 4
It had nothing to do with leftwm.

https://youtu.be/ChAQHhBqut0
@PeterDauwe you can close this one

**Comment by VuiMuich** [comment]
Nice!
Thanks for reporting this.

**Comment by Kibouo** [comment]
I had this issue with Firefox. As only a solution for Sublime has been posted, I'll add the one for Firefox.

1. Access FF's advanced config via `about:config` in the address bar. Then, set `widget.disable-workspace-management` to `true`.
2. Close FF.
3. Find and delete the `xulstore.json` file under `~/.mozilla/firefox/`.
4. Restart FF.

Source: https://askubuntu.com/questions/1231650/stubborn-firefox-on-ubuntu-18-04-4-lts-gnome
