### ISSUE TITLE
Windows get foreign input under heavy system load.

### ISSUE THREAD

**Issue by VentGrey** [leftwm/leftwm#684]
I still haven't been able to make clear steps on how to reproduce this, but I've been experiencing this bug when my system is under heavy load and the UI starts "lagging" a bit.  My clearest example is with neovide.

1. Make your system work heavily (Brave + rust-analyzer should suffice, it did for me :b)
2. Open a new neovide window on a different workspace
3. Switch workspaces and type something in any other thing that lets you type.
4. I even got the bug going when writing this bug report, see for yourself:
![bug](https://user-images.githubusercontent.com/24773698/151650257-98158f7c-a096-4374-bf7c-e84ebe8fb04c.png)

**Environment:**
 - OS/Distro: Debian Stable (11)
 - Output of `leftwm-check`
```
:: LeftWM version: 0.3.0
:: LeftWM git hash: f3dbda7-modified
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK 
:: Checking theme . . .
    -> Theme OK 
```

**Additional context**
Maybe this is a state error? :thinking: I don't know but it's the weirdest leftwm bug I've ever had xD

**Comment by AethanFoot** [comment]
What focus behaviour are you using, could this be related to https://github.com/leftwm/leftwm/pull/563.

**Comment by VentGrey** [comment]
I haven't touched the focus behaviour, the value shown in my config file is `Sloppy`.

**Comment by VuiMuich** [comment]
![2022-02-08-072034_2560x1440_scrot](https://user-images.githubusercontent.com/4779365/152932980-b206da77-8532-4a0b-a9f4-8146bb54a7dd.png)

I tried to reproduce it but I can't. In addition to the above screenshot I also installed `neovide-bin 0.7.0-3` from the AUR and played some random twitch stream in brave, but my system always remained responsive enough to handle the input correct.

Is it possible that you might maxout RAM+Swap or are I/O limited with the swap?

**Comment by VentGrey** [comment]
About the swap idk, i follow the RAMx2 rule on that one. I do get "max" RAM usage when combining those pieces of software above. 

🤔 Now i'm curious as of what triggers this.

**Comment by VuiMuich** [comment]
What drive is your swap on? SSD with decent write speed? If not I suspect it might indeed be I/O speed that causes the lag.
Or Wizzard Aethan fixed it somehow with #682 :grin: (if you want to check this PR out just make sure you don't have a standalone `lefthk` instance running as this would break `SoftReload`)

BTW: tried `Sloppy` now, no difference..

**Comment by VentGrey** [comment]
It is on an SSD with decent write speed indeed. I might use that PR (I don't have lefthk installed anywhere). Now I'm even more curious to see what is the actual source of the bug. It could be either X or Neovide o.o

I'll try that patch and report my findings later.

**Comment by AethanFoot** [comment]
If you haven't set it up already, you may benefit from [zram or zswap](https://wiki.archlinux.org/title/Improving_performance#zram_or_zswap). How much RAM do you have, as I would have thought it shouldnt be using that much memory (on my system with steam, brave with 6 tabs with youtube vids/amazon streams, while compiling with cargo I only used like ~2.6GB, why am I considering getting another 32GB of RAM :rofl:).

**Comment by VuiMuich** [comment]
I have 8gig as well, and my 50+ tabs in qutebrowser eat at least 6gigs of it my swap in the test was about 2.7gig.

Neovide indeed is running quite sluggish, but that could as well be an issue with spacevim+plugins.

**Comment by VentGrey** [comment]
#682 does seem to help the case. It happens less often, however I think this might be a neovide drawing issue. What I cannot explain is how is it managing to get the input of other windows. 🤯
