### ISSUE TITLE
Scratchpad breaks configuration

### ISSUE THREAD

**Issue by lieskjur** [leftwm/leftwm#685]
**Describe the bug**
config does not pass `leftwm-check` after adding a scratchpad to it.

**To Reproduce**
1. Add lines to `config.toml`
```
[[scratchpad]]
name = "Alacritty"
value = "alacritty"
x = 0.46
y = 0.20
height = 0.80
width =  0.54

[[keybind]]
command = "ToggleScratchPad"
value = "Alacritty" # Name set for the scratchpad
modifier = ["modkey"]
key = "t"
```
2. save `config.toml`
3.
```
~> leftwm-check
:: LeftWM version: 0.2.11
:: LeftWM git hash: 399345b
:: Loading configuration . . .
Configuration failed. Reason: duplicate field `scratchpad` at line 332 column 1
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```

**Environment:**
 - OS/Distro: Manjaro

**Comment by AethanFoot** [comment]
What else is in your config, adding it to mine doesn't seem to produce the same error.

**Comment by lieskjur** [comment]
Here is the full config [https://github.com/lieskjur/leftwm-config/blob/44751498083908afa9cbd02b55c23253cd7f71e8/config.toml](url)

**Comment by AethanFoot** [comment]
Ah it is because of `scratchpad = []` at line 8.

**Comment by lieskjur** [comment]
just noticed it as well when I fixed the link -_-. Thanks for bearing with me
