### ISSUE TITLE
leftwm panics on writing new default config.toml

### ISSUE THREAD

**Issue by manor-one** [leftwm/leftwm#692]
Hi.
If I start leftwm with a missing config.toml (fresh install),leftwm is trying to write a new config file with default values, which fails with a panic

Error Msg.
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ValueAfterTable', leftwm/src/config/mod.rs:140:45
stack backtrace:
   0: rust_begin_unwind
             at /data/pkgmk/work/rust/src/rustc-1.57.0-src/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /data/pkgmk/work/rust/src/rustc-1.57.0-src/library/core/src/panicking.rs:100:14
   2: core::result::unwrap_failed
             at /data/pkgmk/work/rust/src/rustc-1.57.0-src/library/core/src/result.rs:1616:5
   3: leftwm::config::load
   4: leftwm_worker::main::{{closure}}
   5: leftwm_worker::main
```
leftwm-check output
```
:: LeftWM version: 0.3.0
:: LeftWM git hash: c244805
:: Loading configuration . . .
Configuration failed. Reason: No such file or directory (os error 2)
:: Checking environment . . .
    -> Environment OK (has XDG_RUNTIME_DIR) 
:: Checking theme . . .
ERROR: No theme folder or symlink `current` found. 
```
The theme Error is expected because ./config/leftwm is empty

After diging around in leftwm/src/config/mod.rs I found a workaround 

 Patch:
```
--- leftwm/leftwm/src/config/mod.rs	2022-01-30 20:55:39.211958231 +0100
+++ leftwm-patch/leftwm/src/config/mod.rs	2022-01-30 22:29:32.664119177 +0100
@@ -98,9 +98,9 @@
     pub focus_new_windows: bool,
     pub keybind: Vec<Keybind>,
     pub state: Option<PathBuf>,
-    pub window_rules: Vec<WindowHook>,
 
     #[serde(skip)]
+    pub window_rules: Vec<WindowHook>,
     pub theme_setting: ThemeSetting,
 }
```

I'm not quiet sure if it is the root cause of the problem.

**Comment by VuiMuich** [comment]
At a glance this definitely seems reasonable, as there should be no `window_rule` necessary in the default config.
Would you like to open a PR for the patch?

**Comment by VuiMuich** [comment]
Nah, I guess we can include this easily in some other PR.
#690, maybe..
Just didn't want to deny you the chance to personally contribute.

**Comment by manor-one** [comment]
No problem. just stick it in there.  I'm sure there are lot of opertunities to contribute some code. Looking forward to it

**Comment by VuiMuich** [comment]
> No problem. just stick it in there.  I'm sure there are lot of opertunities to contribute some code. Looking forward to it 
> 
> 

Just have a look around we have a bunch of `good-First` issues, would be awesome to get some of them ticked for 3.0.0

**Comment by stevensonmt** [comment]
Was this reverted on 46e2294? I'm getting the same error after having to reinstall.

**Comment by VuiMuich** [comment]
> Was this reverted on [46e2294](https://github.com/leftwm/leftwm/commit/46e2294578ee2aa398eab5cf68cd82052fefb8e9)? I'm getting the same error after having to reinstall.

Would you by any chance have the exact error?
It does not seem to me to be related to the hash you mentioned, but probably some other recent commit that introduced a config parameter that does not (de)serialise when writing the initial config.

**Comment by stevensonmt** [comment]
I'll have to wait until I get home to see if there are any other details in the error message but it is the same "'called `Result::unwrap()` on an `Err` value: ValueAfterTable'" message.

**Comment by VuiMuich** [comment]
Indeed looks like the patch suggested by OP got reverted at some point, but probably by accident. I'll investigate and open a PR, but probably not before tomorrow.

**Comment by stevensonmt** [comment]
Full error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ValueAfterTable', leftwm/src/config/mod.rs:144:45
```

**Comment by VuiMuich** [comment]
Thanks @stevensonmt.
If you like, you could checkout #791, this should fix it.
