### ISSUE TITLE
PR #690 breaks clicking on workspaces from Polybar

### ISSUE THREAD

**Issue by lex148** [leftwm/leftwm#699]
**Describe the bug**
Clicking on workspaces in polybar no longer changes to that workspace. Other polybar mouse events are still working.

**To Reproduce**
1. run a theme with polybar
2. click on a workspace that is not active.

**Expected behavior**
the correct workspace to change to that workspace

I have tracked this bug down to the commit 661e2b9
I have been digging over the changes but haven't been able to find the cause. 
My hunch is its a focus issue (polybar can NEVER take focus or bad things)
or 
its an EWMH compliance issue

these are just guesses...

**Comment by VuiMuich** [comment]
This might be related to #637 as they report `wmctrl -a <window id>` is still not working and I tested `wmctlh -s <desktop id>` right now, which is not working as well.
Given that I tend to the EWMH compliance issue.

Also polybar is window type `dock` right? So if it is a focus issue this should happen on other `dock` typed windows as well I guess, but my eww setup works just fine.
