### ISSUE TITLE
dbus-launch is not needed in xinitrc 

### ISSUE THREAD

**Issue by n1s** [leftwm/leftwm#705]
I just did a fresh Arch install.
> Linux 5.16.8-arch1-1 #1 SMP PREEMPT Tue, 08 Feb 2022 21:21:08 +0000 x86_64 GNU/Linux

Spend few hours trying to debug why some of my services like gnome keyring don't work 

I found out that below is wrong. 
```
# .xinitrc
exec dbus-launch leftwm
```

removing dbus-launch fixed my issue.

I could be specific to Arch but I think dbus is launched by systemd by default?

**Comment by VuiMuich** [comment]
I might be wrong, but I thought this is telling `dbus` to launch `leftwm` and therefore do the session handling.

I don't know if gnome keying is expecting a `gnome` session of sorts.

You definitely can launch `leftwm` without dbus, but logging out, or some other x-server-session related events might end in unexpected and odd behavior it self.

**Comment by kid** [comment]
Did you use `/etc/X11/xinit/xinitrc` as a starting point for `~/.xinitrc` as advised by the Arch docs? if your `.xinitrc` sources the files in `/etc/X11/xinit/xinitrc.d` then you do not need `dbus-launch` as all the environment variables should already be set.

**Comment by n1s** [comment]
> Did you use `/etc/X11/xinit/xinitrc` as a starting point for `~/.xinitrc` as advised by the Arch docs? if your `.xinitrc` sources the files in `/etc/X11/xinit/xinitrc.d` then you do not need `dbus-launch` as all the environment variables should already be set.

yes that's what I did. Just posting here for others if someone faces similar issue, not sure if the README should be updated.

**Comment by VuiMuich** [comment]
Ahh, now it makes sense to me.

If you like, you could propose the addition to the `README` as a PR.
