### ISSUE TITLE
Package `leftwm 0.2.10` on nixpkgs 

### ISSUE THREAD

**Issue by marcelarie** [leftwm/leftwm#706]
I just installed NixOS with `leftwm`. I use the main package from [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/window-managers/leftwm/default.nix) and I wanted to know if that version is up to date. I have seen the same bugs that where commented in https://github.com/leftwm/leftwm/issues/633. If those are fixed already maybe updating that package will fix them. 

idk if you are the one handling that package. 

I have seen too a `flake.nix` on the repository. It's that one more up to date than the the one from `nixpkgs` ? 

This questions maybe go to the nixpkgs repo but I wanted to try here first :)
Thanks!

**Comment by VuiMuich** [comment]
Welcome adventurer!

That is basically our latest `stable` release. Iirc the nix package got some patch applied though (or was it the `void` one?).

If I get the functionality correct, the `flake.nix` in the repo would install the latest git version. But tbh I have no real experience with nix packages.

**Comment by marcelarie** [comment]
Thanks!

Ok I will learn `flakes` then and screen record the bug to post it on #633. Just to be sure that is the same.

really cool energy on this project. cheers.

**Comment by MatthieuBarthel** [comment]
Hi,

I recently switched to NixOS and LeftWM (my first tiling window manager, I love it), and I've just figured how to override nixpkgs to use the repo's flake. Here is a basic flake if it can help beginners like me:

```nix
{
  description = "System config";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    leftwm.url = "github:leftwm/leftwm";
    leftwm.inputs.nixpkgs.follows = "nixpkgs"; # not sure if this is a good practice
  };

  outputs = { nixpkgs, leftwm, ... }:
  let
    system = "x86_64-linux";

    pkgs = import nixpkgs {
      inherit system;
      config = { allowUnfree = true; };
    };

    lib = nixpkgs.lib;

  in {
    nixosConfigurations = {
      oryx = nixpkgs.lib.nixosSystem {
        inherit system;
	modules = [
          { nixpkgs.overlays = [ leftwm.overlay ]; }
          ./hosts/oryx/configuration.nix
        ];
      };
    };
  };
}
```

Thanks for the awesome work

**Comment by marcelarie** [comment]
Yep after learning a little bit I got something slightly different to your `flake.nix`:

```nix
{
# ...
let
    username = "marcel";
    system = "x86_64-linux";
    pkgs = import nixpkgs {
      inherit system;
      config = { allowUnfree = true; };
      overlays = [
         leftwm.overlay # <- you can directly put the overlays here
         neovim-nightly-overlay.overlay
      ];
    };
  in {
    nixosConfigurations = {
      nixos = nixpkgs.lib.nixosSystem {
        inherit pkgs system; 
	modules = [
          ./configuration.nix
          # other modules here.
          # for example home-manager will inherit the overlays too
        ];
      };
}
```
