### ISSUE TITLE
copyq doesn't work when autostarted, but works fine when started manually

### ISSUE THREAD

**Issue by torhovland** [leftwm/leftwm#715]
Not sure if this is a bug in LeftWM, but when I autostart `copyq` using the following in `~/.config/leftwm/up`, it doesn't work.

```
#!/bin/bash
copyq &
```

The `copyq` process starts, but it doesn't show up in the tray bar in `polybar`, my keyboard shortcuts don't work, and what's worse, it makes my Ctrl key stop working althogether.

If I don't autostart copyq, but run `copyq &` as soon as LeftWM has started, everything is fine.

 - OS/Distro: Arch
 - Output of `leftwm-check`:
 
 ```
:: LeftWM version: 0.2.11
:: LeftWM git hash: 399345b
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```

**Comment by VuiMuich** [comment]
You could try to start it with a minimal `copyq.desktop` file in `~/.config/autostart`.

Does `copyq` possibly rely on some environment variables that get set in your interactive terminal, but the `up` script uses a different shell that hasn't those accessible?

Another idea would be to try `copyq &>`.

**Comment by torhovland** [comment]
An autostart file doesn't seem to help, unfortunately. Will try the other suggestion.

**Comment by torhovland** [comment]
Unfortunately, `copyq &>` in my `up` script doesn't seem to help either. Not even with `sleep 10` on the line before.

The only way I know to get `copyq` working is to start it manually after LeftWM is up.

**Comment by mautamu** [comment]
Does it perhaps need some environmental variable we’re not providing? Maybe try an auto start while piping output to a file and see if that gives hints.

**Comment by hertg** [comment]
Closing because it became stale and may be an issue of copyq.
Please reopen if there is more information that pins the problem to LeftWM.
