### ISSUE TITLE
Remove border from single window

### ISSUE THREAD

**Issue by ksevelyar** [leftwm/leftwm#726]
Hi, thank you for leftwm. I'm migrating from xmonad, it has feature to not show borders if I have only one window open, is it possible to disable borders for one window with leftwm?

![2022-03-03-20-39-16-full](https://user-images.githubusercontent.com/725959/156620719-fe6afdf7-8381-4ae4-8d98-8fbdc267916a.png)

**Comment by VuiMuich** [comment]
Welcome adventurer!
This is already tracked in #343 so I'd like to close this to avoid duplicate issues.
Feel free to reopen if I got this wrong and have lots of fun in ̀`leftwm`
