### ISSUE TITLE
No GotoTag external command 

### ISSUE THREAD

**Issue by jmetz** [leftwm/leftwm#727]
**Almost all commands present as external commands but not `GotoTag`**

Tried both the commands pipe as well as `leftwm-command`

**Comment by VuiMuich** [comment]
The external command equivalent is `SendWorkspaceToTag <WS index> <Tag index>` with 0-based indices.
We intend to unify this along a future breaking update.

**Comment by jmetz** [comment]
Thanks @VuiMuich - ya this `SendWorkspaceToTag` is slightly odd naming for this functionality, but good to hear that the capabilities are nonetheless present (and will possibly be renamed to something a little more obvious soon!
