### ISSUE TITLE
leftwm-state template file checking seems to be broken.

### ISSUE THREAD

**Issue by VentGrey** [leftwm/leftwm#729]
**Describe the bug**
`leftwm-state` doesn't find a `.liquid` file in the same directory (or anywhere)

**To Reproduce**
1. Create a `template.liquid` file.
2. Run `leftwm-state -w 0 -t <file>` where `<file>` is the `.liquid` file you just created.
3. Try adding a `./` to the `.liquid` file just to see a panic.
4. Write all that liquid inline instead (?)

**Expected behavior**
`leftwm-state` checks for current directory and reads the file.

**Screenshots**
![brokenleftwm](https://user-images.githubusercontent.com/24773698/157592274-5e2cdf33-3c0e-47ec-afe3-2fe9f5489d66.png)

1. First line `ls` is to show the file exists.
2. You can try giving `rw` permissions to liquid file. Even 777 doens't work.

**Environment:**
 - OS/Distro: Void Linux (also happened on Debian)
 - Output of `leftwm-check`:
 ```
:: LeftWM version: 0.3.0
:: LeftWM git hash: 557d09c
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK 
:: Checking theme . . .
    -> Theme OK 
 ```

**Additional context**
Not much else. This is what's keeping me to use liquid from epitaph. One thing I cannot explain is why does it work when basic_lemonbar is selected as a theme but not with "standalone" environments.

**Comment by VuiMuich** [comment]
:thinking: for me it works just fine:

```fish
~ >>> leftwm check
:: LeftWM version: 0.3.0
:: LeftWM git hash: 557d09c
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK

~ >>> leftwm state -q -w0 -t ~/.config/leftwm/themes/floaters/template.liquid
(box :orientation "h" :class "workspaces" :space-evenly "true" :halign "center"   (button :class "ws-button-mine" :onclick "leftwm-command \"SendWorkspaceToTag 0 0\"" ``) (button :class "ws-button-busy" :onclick "leftwm-command \"SendWorkspaceToTag 0 1\"" ``) (button :class "ws-button-busy" :onclick "leftwm-command \"SendWorkspaceToTag 0 2\"" ``) (button :class "ws-button" :onclick "leftwm-command \"SendWorkspaceToTag 0 3\"" `·`) (button :class "ws-button" :onclick "leftwm-command \"SendWorkspaceToTag 0 4\"" `·`) (button :class "ws-button" :onclick "leftwm-command \"SendWorkspaceToTag 0 5\"" `·`) (button :class "ws-button" :onclick "leftwm-command \"SendWorkspaceToTag 0 6\"" `·`) (button :class "ws-button-busy" :onclick "leftwm-command \"SendWorkspaceToTag 0 7\"" `ﭮ`) (button :class "ws-button" :onclick "leftwm-command \"SendWorkspaceToTag 0 8\"" `·`))

~ >>> leftwmthemecd
on  master [!]
current >>> ../floaters/

leftwm/themes/floaters >>> leftwm state -q -w0 -t template.liquid
Error: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })

leftwm/themes/floaters >>> leftwm state -q -w0 -t ./template.liquid
(box :orientation "h" :class "workspaces" :space-evenly "true" :halign "center"   (button :class "ws-button-mine" :onclick "leftwm-command \"SendWorkspaceToTag 0 0\"" ``) (button :class "ws-button-busy" :onclick "leftwm-command \"SendWorkspaceToTag 0 1\"" ``) (button :class "ws-button-busy" :onclick "leftwm-command \"SendWorkspaceToTag 0 2\"" ``) (button :class "ws-button" :onclick "leftwm-command \"SendWorkspaceToTag 0 3\"" `·`) (button :class "ws-button" :onclick "leftwm-command \"SendWorkspaceToTag 0 4\"" `·`) (button :class "ws-button" :onclick "leftwm-command \"SendWorkspaceToTag 0 5\"" `·`) (button :class "ws-button" :onclick "leftwm-command \"SendWorkspaceToTag 0 6\"" `·`) (button :class "ws-button-busy" :onclick "leftwm-command \"SendWorkspaceToTag 0 7\"" `ﭮ`) (button :class "ws-button" :onclick "leftwm-command \"SendWorkspaceToTag 0 8\"" `·`))
```
I believe the second to last attempt with `leftwm state -q -w0 -t template.liquid` always has been broken due to a lack of path processing in Rust standard library.

**Comment by VentGrey** [comment]
Also tried replacing localtime but to no avail.  The `template.liquid` file needs to be in ` ~/.config/leftwm/themes/something` to be read? 🤔 

I did make a workaround by using inline liquid but the script looks dirty :s

**Comment by VuiMuich** [comment]
I believe absolute paths should work:
```fish
>>> leftwm state -q -w0 -t /home/vuimuich/Git/leftwm/themes/basic_lemonbar/template.liquid
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: InnerError { msg: Singleton("Unknown variable"), user_backtrace: [Trace { trace: None, context: [(Singleton("requested variable"), Inline("localtime"))] }], cause: None } }', leftwm/src/bin/leftwm-state.rs:180:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Regarding the `localtime` I guess a reimplementation of the old behaviour should be possible by adding the `time-fmt` package.
Didn't you look for an opportunity to get your hands rusty :stuck_out_tongue_winking_eye:
jk – I might have a chance to look into this next week, but any takers to solve this are welcome...

**Comment by VentGrey** [comment]
:thinking: I'm trying to reproduce the success but to no avail. I keep getting the  same panic error. Maybe this is an external error?

**Comment by mindforrest** [comment]
Running 0.3.0 and leftwm-theme 0.1.1, I believe post #723 ?
Removing the {{ localtime }} call fixed it, it's mentioned in the disscussion over there.

**Comment by hertg** [comment]
Seems resolved
