### ISSUE TITLE
Flickering Android Emulator and blank Android Studio.

### ISSUE THREAD

**Issue by mkubasz** [leftwm/leftwm#73]
Hi, I have one issue with using java windows as in the title. Before that, I tried to set wnmane LG3D in .xinitrc and in console `set _JAVA_AWT_WM_NONREPARENTING 1
wmname LG3D &`. There is it possible to set 'wmname LG3D' to the new java window?

**Comment by lex148** [comment]
hey mkubasz,

If you really want to set the wmname you should be able to using a program like this one
https://tools.suckless.org/x/wmname/
but I'm not sure that is your issue. 

LeftWM also already sets _JAVA_AWT_WM_NONREPARENTING=1 so I don't think that is your issue either. 

Are you seeing this on all java apps or just the android emulator? what emulator are you using?

**Comment by mkubasz** [comment]
@lex148 Only test Android Studio and Android Emulator from Arch repository. I will check Webstorm later. Yeap, I have this program so it should work after that. I tried run from console with wmname LG3D; and android-studio. After that run window without any texture and only with progress bar. After that I can't find window and it's empty place. So to disable it required CTR+C from console and rerun WM. No issue message in console after disable LeftWM.

**Comment by mkubasz** [comment]
So Webstorm is working perfectly. So only real issue is that Android Emulator is flickering. That was same issue in xmonad and only best solution is put window in floating layer. Maybe that can be some similar possibility in LeftWm?

**Comment by lex148** [comment]
@mkubasz are you using a compositor like picom, compton, or xcompmgr-dana? I ask because I have noticed that some Java apps do not render right without one, and LeftWM does not composite. I'm struggling to reproduce this issue over here :(

**Comment by mkubasz** [comment]
@lex148 I will try to use one of them :+1: thx to clarify that sth like that exist

**Comment by mkubasz** [comment]
With composition works.
