### ISSUE TITLE
Obsidian freezes while file is opened from it in another app

### ISSUE THREAD

**Issue by clay53** [leftwm/leftwm#733]
**Describe the bug**
I'm having the same issue as described on the obsidian forums (https://forum.obsidian.md/t/opening-attachments-in-external-program-freezes-interface/24195). The developers claim that this is a bug with the window manager but I'm not sure. When one opens a file in Obsidian "in default app" the file successfully opens into the newly opened app but Obsidian become unresponsive until that newly opened app is closed.

**To Reproduce**
1. Put a file in your vault
2. Right click it in Obsidian and click "open in default app"
3. Try to interact with Obsidian, it's frozen.
4. Close the pdf
5. Obsidian no longer frozen

**Expected behavior**
Obsidian is interactive while the PDF app is open

**Environment:**
 - OS/Distro: Arch
 - Output of `leftwm-check`
```
:: LeftWM version: 0.2.11
:: LeftWM git hash: 399345b
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```

**Additional context**
I'm mostly focused on PDFs and I have mine opening in llpp but it does happen with other file types/programs. Restarting Leftwm does not fix the problem. Using `obsidian 0.13.31-1` from the official Arch repo.

**Comment by VuiMuich** [comment]
Welcome adventurer!
Have you tried the [workaround ](https://forum.obsidian.md/t/open-in-default-app-on-linux-renders-obsidian-unusable/26934/4) mentioned on their forums?

**Comment by clay53** [comment]
> Welcome adventurer!
> Have you tried the [workaround ](https://forum.obsidian.md/t/open-in-default-app-on-linux-renders-obsidian-unusable/26934/4) mentioned on their forums?

Didn't see that. Tried it out and it worked.

**Comment by VuiMuich** [comment]
Although this is not really fixed I like to close this as long as it is not clearly the WM's fault.
Feel free to reopen if necessary.
