### ISSUE TITLE
IncreaseMainWidth and DecreaseMainWidth should not apply to all tags on the screen

### ISSUE THREAD

**Issue by nloyola** [leftwm/leftwm#744]
## Describe the bug
I've built leftwm from commit 20bfab3. When I use `IncreaseMainWidth` and `DecreaseMainWidth` it is applied to the windows on **all** tags on the screen. If I switch tags on the screen, then the windows have the same size as in my previous tag where I used the IncreaseMainWidth and DecreaseMainWidth keybindings.

The description in the Wiki for this command says:

> Increases the width of the currently focused window.

Then, why is it then applied through all tags?

## To Reproduce
Use commands `IncreaseMainWidth` and `DecreaseMainWidth` via key bindindgs.

## Expected behavior
Windows should be resized only in currently selected tag.

## Screenshots
N/A

## Environment
 - OS/Distro: Debian 11

 - Output of `leftwm-check`
    ```    leftwm-check
    :: LeftWM version: 0.3.0
    :: LeftWM git hash: 20bfab3
    :: Loading configuration . . .
        -> Configuration loaded OK
    :: Checking keybinds . . .
        -> All keybinds OK
    :: Checking environment . . .
        -> Environment OK
    :: Checking theme . . .
        -> Theme OK
    ```      

## Additional context
N/A

**Comment by VuiMuich** [comment]
Welcome adventurer!
This may be an unintended side effect when using [`layout_mode = "Workspace" # Can be Workspace or Tag`](https://github.com/leftwm/leftwm/wiki/Config#layout-mode). Can you try, if setting this to `Tag` changes the behaviour?

**Comment by nloyola** [comment]
Yes! That was it. Thank you.

I changed it to `layout_mode = "Tag"`.
