### ISSUE TITLE
leftwm becomes unresponsive after closing spotify-client.

### ISSUE THREAD

**Issue by VentGrey** [leftwm/leftwm#746]
**Describe the bug**
After closing a single instance of the `spotify-client` leftwm becomes unresponsive to any commands.

**To Reproduce**
1. Go to an empty workspace
2. Open `spotify-client` using dmenu / rofi / shortcut
3. Close the window using a shortcut
4. Only the mouse moves but leftwm becomes unresponsive to any keybinds

**Expected behavior**
Continous functionality(?)

**Screenshots**
no way to take them atm. The entire wm becomes unresponsive :c

**Environment:**
 - OS/Distro: Tested and this happens in Debian 11, Void and Ubuntu (20.04)
 - Output of `leftwm-check`
```
:: LeftWM version: 0.3.0
:: LeftWM git hash: 557d09c
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK 
:: Checking theme . . .
    -> Theme OK 
```

**Additional context**
Idk if a floating window wants to be opened and leaves the wm stuck but doesn't seem to be the case as switching windows doesn't work. Also it is not possible to kill the session so this hangs the wm in some unknown way

**Comment by 0323pin** [comment]
Any hints in `/var/log/Xorg.0.log`?

**Comment by VentGrey** [comment]
Nothing out of the ordinary (checked on a TTY, dumped to a .txt and copied here after reboot):

```
[ 47539.373] (II) event3  - Power Button: is tagged by udev as: Keyboard
[ 47539.373] (II) event3  - Power Button: device is a keyboard
[ 47539.374] (II) event4  - Video Bus: is tagged by udev as: Keyboard
[ 47539.375] (II) event4  - Video Bus: device is a keyboard
[ 47539.375] (II) event1  - Power Button: is tagged by udev as: Keyboard
[ 47539.376] (II) event1  - Power Button: device is a keyboard
[ 47539.377] (II) event12 - ov9734_azurewave_camera: ov9734: is tagged by udev as: Keyboard
[ 47539.377] (II) event12 - ov9734_azurewave_camera: ov9734: device is a keyboard
[ 47539.378] (II) event10 - ELAN2204:00 04F3:3109 Mouse: is tagged by udev as: Mouse
[ 47539.378] (II) event10 - ELAN2204:00 04F3:3109 Mouse: device is a pointer
[ 47539.380] (II) event11 - ELAN2204:00 04F3:3109 Touchpad: is tagged by udev as: Touchpad
[ 47539.381] (II) event11 - ELAN2204:00 04F3:3109 Touchpad: device is a touchpad
[ 47539.382] (II) event5  - Huawei WMI hotkeys: is tagged by udev as: Keyboard
[ 47539.382] (II) event5  - Huawei WMI hotkeys: device is a keyboard
[ 47539.383] (II) event0  - AT Translated Set 2 keyboard: is tagged by udev as: Keyboard
[ 47539.383] (II) event0  - AT Translated Set 2 keyboard: device is a keyboard
[ 47849.960] (EE) event11 - ELAN2204:00 04F3:3109 Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.20.0/touchpad-jumping-cursors.html for details
[ 47849.960] (EE) event11 - ELAN2204:00 04F3:3109 Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.20.0/touchpad-jumping-cursors.html for details
```

**Comment by VentGrey** [comment]
> I don't think that's your issue, but just in case: Do you have a notification-daemon installed on your system? I ran without one for a while and had issues with Spotify freezing because it tried to trigger a notification (and the code probably blocked while it waited for that to succeed). But your issue seems to be that the whole WM freezes, not just one application, so I doubt that this is the issue here... just in case :)

I do have xnotifyd do you think that might be the case? :o

**Comment by VuiMuich** [comment]
> > I don't think that's your issue, but just in case: Do you have a notification-daemon installed on your system? I ran without one for a while and had issues with Spotify freezing because it tried to trigger a notification (and the code probably blocked while it waited for that to succeed). But your issue seems to be that the whole WM freezes, not just one application, so I doubt that this is the issue here... just in case :)
> 
> 
> 
> I do have xnotifyd do you think that might be the case? :o

If the systemd service is running well, this should be ok then and then he cause would be something else. I remember reports, where a missing notification daemon and running discord froze the whole xsession.

**Comment by VentGrey** [comment]
:thinking: well I don't have systemd anyome. I switched distros a lil while ago.

**Comment by 0323pin** [comment]
🤔 what does `systemd` have to do with it? A running `dbus` session should be enough as far as notifications are concerned.

**Comment by VuiMuich** [comment]
> 🤔 what does `systemd` have to do with it? A running `dbus` session should be enough as far as notifications are concerned.

True I just remembered that VentGrey had been on Debian in the past, so I thought systemctl might be the fastest way to check the status of the daemon.

But apparently this is no longer valid information. How dare you to switch distro without telling us? JK!

**Comment by VuiMuich** [comment]
> Maybe a long shot but, found [this](https://github.com/JLErvin/berry/blob/778bce4ed468e6cea11a6602605663a3e2ec4034/wm.c#L842) on `berry` wm, 

Nice find!

**Comment by ealtun21** [comment]
I am also having this issue, however, I have come up with a temporary fix. I made a clickable application launcher in polybar (dmenu or rofi both work), and when keybindings being unresponsive I open a application via the mouse based launcher in polybar and once that application is open, it seems that the window manager becomes responsive again.

**Comment by gekoke** [comment]
I don't have the time currently to provide any diagnostics but would like to chime in to say that I am experiencing the same behavior and that, like ealtun21 mentioned, swapping workspaces by *clicking* on polybar returns everything back to normal.
