### ISSUE TITLE
Borders always render as width 1 and color #FF0000

### ISSUE THREAD

**Issue by blackdragon2447** [leftwm/leftwm#748]
**Describe the bug**
Window borders always render as width 1 and color #FF0000 regardless of what is actually in the `theme.toml`.

**To Reproduce**
1. Start LeftWM
2. Open a window
3. Observe the border

**Expected behavior**
The window borders should render as specified in `theme.toml`

**Screenshots**
![20220409-153414](https://user-images.githubusercontent.com/56592338/162576417-6b738629-7262-454b-84ae-7682edace2c8.png)

**Environment:**
 - OS/Distro: 
     Both on Arch Linux and Artix Linux OpenRC
 - Output of `leftwm-check`
:: LeftWM version: 0.3.0
:: LeftWM git hash: eaf531d
:: Loading configuration . . .
   -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK

**Additional context**
Related to #735?

**Comment by jakejones** [comment]
I had the same problem, It seems a breaking change was made, Issue #652 helped me. 
All I had to do was update the "up" script in the theme to use this:
` leftwm command "LoadTheme $SCRIPTPATH/theme.toml `
instead of this:
` echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe `

**Comment by mautamu** [comment]
Huh, that's weird that leftwm-check didn't catch that.

**Comment by jakejones** [comment]
Actually, in my case, leftwm-check did catch it:
```
:: LeftWM version: 0.3.0
:: LeftWM git hash: eaf531d
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK 
:: Checking theme . . .
ERROR: `commands.pipe` is deprecated. See https://github.com/leftwm/leftwm/issues/652 for workaround. 
```

**Comment by mautamu** [comment]
Oh good to hear!

**Comment by blackdragon2447** [comment]
For me it turned out that I needed to have `leftm-command LoadTheme "$SCRIPT_PATH" ` instead of `leftm-command "LoadTheme $SCRIPT_PATH" `, tho the discussion if the first one is also correct syntax is a diffirent discussion.

**Comment by VuiMuich** [comment]
> For me it turned out that I needed to have `leftm-command LoadTheme "$SCRIPT_PATH" ` instead of `leftm-command "LoadTheme $SCRIPT_PATH" `, tho the discussion if the first one is also correct syntax is a diffirent discussion.

Might be that there is a difference if you use `leftwm command` or `leftwm-command`. Wild guess is that this might come from splitting the string on the first space character.
