### ISSUE TITLE
Cargo install fails

### ISSUE THREAD

**Issue by anoraktrend** [leftwm/leftwm#749]
**Describe the bug**
attempting to install via cargo fails 

**To Reproduce**
1. attempt to install via cargo (``cargo install leftwm``)
2. wait
3. build fails (due to leftwm)

**Expected behavior**
it builds and installs normally

**Screenshots**

**Environment:**
 - OS/Distro: Debian 11 (dietpi) aarch64 raspberry pi 400

**Additional context**
able to build via git quite easily, it was really just the crates.io source that had this issue
```error[E0308]: mismatched types
   --> /home/dietpi/.cargo/registry/src/github.com-1ecc6299db9ec823/leftwm-core-0.2.11/src/display_servers/xlib_display_server/xwrap/getters.rs:578:46
    |
578 |             if let Ok(s) = CString::from_raw(text_prop.value.cast::<i8>()).into_string() {
    |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*mut u8`
               found raw pointer `*mut i8`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `leftwm-core` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `leftwm v0.2.11`, intermediate artifacts can be found at `/tmp/cargo-installSTebML`

Caused by:
  build failed

**Comment by mautamu** [comment]
Tagging https://github.com/leftwm/leftwm/issues/660. Given latest discussion in https://github.com/leftwm/leftwm/issues/598, I think this will be fixed soon.

**Comment by hertg** [comment]
I'm assuming this was fixed, since there was a crates.io release on Apr 25.
Please reopen if I'm wrong.
