### ISSUE TITLE
Why is leftwm called leftwm?

### ISSUE THREAD

**Issue by JamesClarke7283** [leftwm/leftwm#750]
Hello, i am a bit concerned about the name leftWM and what the left entails.

Does it mean all windows are on the left side of the screen? if so, will i get eye strain or go boss eyed.

Or be frozen in a left leaning posture forever, from leaning left to the screen too long.
That also might be a privacy issue as Government would be able to identify leftwm users based on left posture and left eyeness.

And if i use it, will i need a bigger screen to fit all my windows on the left side. How much will it cost to buy such a monitor? How would it fit?(maybe by cutting it in half and throw the right side away, seems wasteful but maybe the situation calls for it)

Or does it mean its a liberal WM with left wing ideologies?
And if the Green party uses it, will you release a rightwm version for UKIP?
And maybe the US version too.

And what in the world would anarchists use?

I am all for politicians using WMs.

Although i hear Boris Johnson still uses unity DE, eck. Maybe we should recommend this to him.

Anyway, would love to know more about the origin of this name.

Thanks for reading.

**Comment by lex148** [comment]
None of the above. 

The main idea I wanted to convey when naming LeftWM and its tag line "A window manager for adventurers" was Using left was a Journey, an adventure, A game to be played. Another words you choose LeftWM because you want to play with it and see were it takes you. Who knows who you will meet along the way and what interesting things you will learn. 

[https://www.google.com/search?q=Good+Adventurers+Go+Left](https://www.google.com/search?q=Good+Adventurers+Go+Left)

**Comment by JamesClarke7283** [comment]
> None of the above.
> 
> The main idea I wanted to convey when naming LeftWM and its tag line "A window manager for adventurers" was Using left was a Journey, an adventure, A game to be played. Another words you choose LeftWM because you want to play with it and see were it takes you. Who knows who you will meet along the way and what interesting things you will learn.
> 
> https://www.google.com/search?q=Good+Adventurers+Go+Left

I see, so its about a journey and you just happen to select left as the direction to symbolize that. Correct?
Would also like to hear what other people think, so i wont close the issue just yet.

Thanks for your great answer, ive not used leftwm yet but i plan to, a friend recommended it to me.
