### ISSUE TITLE
Move to next/previous tag

### ISSUE THREAD

**Issue by alvaro17f** [leftwm/leftwm#751]
There's no way to move a window to the next or previous tag.
Something like MoveWindowToNextTag or MoveWindowToPreviousTag instead of workspace would be very useful.

Thanks in advance.

**Comment by VuiMuich** [comment]
Welcome adventurer!
We don't have this command, but I see how this might indeed useful and would match nice with `MoveWindowToNextWorkspace` and `MoveWindowToPreviousWorkspace`.

**Comment by Zwo1in** [comment]
Hi,
I'd like to give this one a try :)
Do you think that when moving window to previous / next tag, the focus should follow to this tag? It could allow for some sort of walking with window, I used to use something like this in awesome-wm.

**Comment by alvaro17f** [comment]
Hi @Zwo1in 
very good point, I think both options should be implemented as well.
IMO both (user deciding to follow the tag after switching or not) are very important :)
