### ISSUE TITLE
A few issues with leftwm (system update)

### ISSUE THREAD

**Issue by Dev380** [leftwm/leftwm#758]
**Describe the bug**
I used leftwm with the basic_polybar template. After a system update, a lot of things broke. What it should do is load everything correctly, with polybar being transparent and allowing me to click on workspaces in polybar to use them. However, I can only use keybinds to switch workspaces, and polybar is black and not transparent. I have not touched polybar config.  Also, the new updates made leftwm only connect to my moniter (I have a moniter and a laptop screen) but it might not be related to leftwm.
This part of `up` seems to have caused an error about "command-0.pipe" not being found even though I used grep to find all instances of it and it did not show up anywhere in the theme directory.
```shell
#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down
```
**Expected behavior**
Polybar is transparent, you can click on the workspace numbers and it'll go to that workspace, computer moniter working.
**Screenshots**

Has this red border, I think this means it failed to load something?
![img-2022-05-06-164449](https://user-images.githubusercontent.com/49997896/167224530-bf174746-a944-460f-8783-fd20f9dac248.png)

![img-2022-05-06-183534](https://user-images.githubusercontent.com/49997896/167224449-05805f5f-20ba-4196-875e-92023775f0e5.png)

**Environment:**
 - OS/Distro: [e.g. Manjaro]
 Debian
 - Output of `leftwm-check`
```:: LeftWM version: 0.3.0
:: LeftWM git hash: NONE
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK 
:: Checking theme . . .
    -> Theme OK 
```

**Comment by VuiMuich** [comment]
Welcome adventurer!
I am sorry about your issues, I'll try to separate them a bit:
- transparency might be related to a broken compositor, which one do you use, can you confirm it's running properly, are other windows (like alacritty i.e.) rendered with transparency
- 'red border` is the default and may mean that your theme failed loading, yes. Which theme are you using? Can you verify manually the symlink is correct
- polybar not being clickable might have various reasons can you post your complete `up` script, pleasa?
- can you check with 'xrandr', 'arandr' or something similar that your monitors are both active?

**Comment by kthomas422** [comment]
I also had the workspaces not being clickable in polybar (everything else on polybar was working). The solution for me was to have the `change_to_tag` script in the theme directory match the git repo (https://github.com/leftwm/leftwm-contrib/tree/main/examples/basic_polybar).

Old:
```
echo "SendWorkspaceToTag $1 $2" > $XDG_RUNTIME_DIR/leftwm/commands.pipe
```

New:
```
leftwm-command "SendWorkspaceToTag $1 $2"
```

**Comment by Dev380** [comment]
@VuiMuich 
The major issues (transparency, moniters) were actually not related to leftwm but was caused by a driver blacklist that got auto-added for some reason, so now the only issues are red border and unclickable polybar.

Here's up:

```
#!/bin/bash

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


#boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
fi

#set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/background.webp
fi


index=0
monitors="$(polybar -m | sed s/:.*//)"
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  let indextemp=index+1
  monitor=$(sed "$indextemp!d" <<<"$monitors")
  barname="mainbar$index"
  monitor=$monitor offset=$x width=$width polybar -c $SCRIPTPATH/polybar.config $barname &> /dev/null &
  let index=indextemp
done
```

@kthomas422 don't think that's the issue:
```
❯ cat change_to_tag

#!/bin/bash
leftwm-command "SendWorkspaceToTag $1 $2"
```

**Comment by VuiMuich** [comment]
🤔
Can you please add your `theme.toml`?
And what do get for `ls -l ~/.config/leftwm/theme`?

**Comment by Dev380** [comment]
```
ls -l ~/.config/leftwm/theme
ls: cannot access '/home/me/.config/leftwm/theme': No such file or directory
```
However, with .config/leftwm/themes/current
```
lrwxrwxrwx 1 me me 44 May  6 18:05 /home/me/.config/leftwm/themes/current -> /home/me/leftwm/themes/basic_polybar//
```
theme.toml:
```
border_width = 1
margin = 20
default_border_color = "#222222"
floating_border_color = "#005500"
focused_border_color = "#FFB53A"
```

**Comment by VuiMuich** [comment]
🤦🏼‍♂️ missing the `s` at the end of the path was stupid.

What looks odd to me now is the additional `/` in your symlink, if this isn't some copy-paste error/typo.

**Comment by Dev380** [comment]
I dunno why that happens, I created the symlink with Dolphin, and recreated it when I started having this problem, both times this happens. I dunno if it's because the theme failed to load, my background image and polybar config is working fine.

**Comment by Dev380** [comment]
```
❯ cd ~/.config/leftwm/theme/
cd: The directory “/home/me/.config/leftwm/theme/” does not exist
```
So I used .config/leftwm/themes
```
.config/leftwm/themes 
❯ rm ./current
```
works
```
.config/leftwm/themes 
❯ ln -s ~/leftwm/themes/basic_polybar/ ~/.config/leftwm/themes/current
```
and
```
.config/leftwm/themes 
❯ ls
current@

.config/leftwm/themes 
❯ ls -l current
lrwxrwxrwx 1 me me 44 May 25 13:18 current -> /home/me/leftwm/themes/basic_polybar//
```
unfortunately it still does this

**Comment by VuiMuich** [comment]
But this should be:
```diff
- ln -s ~/leftwm/themes/basic_polybar/ ~/.config/leftwm/themes/current
+ ln -s ~/.config/leftwm/themes/basic_polybar/ ./current
```
with your `pwd == /home/me/.config/leftwm/themes`

**Comment by hertg** [comment]
Seems like a configuration issue to me, closing it now.
Please reopen if there's an actual underlying LeftWM issue
