### ISSUE TITLE
Firefox Picture-In-Picture Issues

### ISSUE THREAD

**Issue by hertg** [leftwm/leftwm#766]
I use the [Picture-In-Picture](https://support.mozilla.org/en-US/kb/about-picture-picture-firefox) (will shorten it to PIP) feature of Firefox quite a lot, but it has some very weird behaviors. I'm not sure whether LeftWM or Firefox is to blame for that, but I will list them here. Sorted from most annoying to least annoying.

1. The PIP window always  jumps to first position when a new window opens.
   1.1 ~See the gif below, this is the `CenterMain` layout. When I open a new terminal, the PIP window jumps to the main position.~ -> This was fixed by #863 i think
     ![output](https://user-images.githubusercontent.com/3533648/168686653-66d46219-1e4f-4240-ae2a-5da1dd057c94.gif)
   
   1.2 *Btw. It also happens when you move a floating window, as soon as you let go.*
   ![output](https://user-images.githubusercontent.com/3533648/168687287-99cb5ff2-11be-44da-9f23-3e970a6f64e6.gif)

2. The PIP window is always in front of everything, even when it is tiled.
    ![output](https://user-images.githubusercontent.com/3533648/168687483-5d5ad735-8deb-416b-b253-795c5bec8a4f.gif)

3. Window is larger than it should be, it seems to not respect the paddings.
    ![out](https://user-images.githubusercontent.com/3533648/168688843-e2457277-f344-4480-9b2d-097046ddfdc8.png)

5. The PIP window shows no borders. It's hard to figure out whether it is focused.

**Additional context**
Slightly related to #220

**Comment by AethanFoot** [comment]
Okay Ill download firefox to check, as the brave pip seems to work as expected in those situations.

**Comment by AethanFoot** [comment]
Okay, this seems to be related to our poor support of window type Utility. It is moved up by sort_windows in state.rs with dialogs. To solve this we should properly implement the requirement of the window type as vlc has a floating utility window for media controls when the video is fullscreen, which has very inconsistent behaviour.

**Comment by Sokom141** [comment]
I'm working on this issue
