### ISSUE TITLE
How would I minimize a window?

### ISSUE THREAD

**Issue by copypasteonly** [leftwm/leftwm#772]
I've scrolled through the github pages and haven't found a command to minimize a window, is this possible on LeftWM? If not are there any workarounds for this using external tools?

**Comment by VuiMuich** [comment]
Welcome Adventurer!
Honestly I don't know any tiling window manager that supports a minimizing feature. (There might be patches or libraries though for some like dwm or xmonad, that I am not aware of.)

A very basic workaround would be to dedicate one Tag as your "Parking Lot". If you don't want to go to this tag to get a window back there are some `wmctrl` and `rofi` scripting possibilities to achieve this. I'll have to look it up if I have some helpful links for this.

**Comment by 0323pin** [comment]
@VuiMuich `awesome` has this functionality enabled by default (check `rc.lua`, https://awesomewm.org/apidoc/sample%20files/rc.lua.html#). Not saying this should be implemented in `leftwm`, just pointing out that it exists.

**Comment by copypasteonly** [comment]
> A very basic workaround would be to dedicate one Tag as your "Parking Lot".

I know that qtile  also has one as that's what I've used before, but yeah I might just implement this workaround for now it's not really a big deal.
