### ISSUE TITLE
Floating windows have no functionality

### ISSUE THREAD

**Issue by devraza** [leftwm/leftwm#775]
**Describe the bug**
I can successfully convert a tiling and back again using the toggle, but the window has no functionality; resizing or moving it is impossible.

**To Reproduce**
1. Make a window floating using the toggle
2. Try to do anything with it (such as resizing or moving)
3. Bug. Nothing happens (cursor icon changes as it should though.)

**Expected behavior**
The window moves and resizes.

**Environment:**
 - OS/Distro: Void Linux
- Output of `leftwm-check`:

```
:: LeftWM version: 0.3.0
:: LeftWM git hash: NONE
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK (has XDG_RUNTIME_DIR)
:: Checking theme . . .
    -> Theme OK
```

**Additional context:**
The LeftWM binary at `/usr/bin/leftwm` was compiled from the last release.

**Comment by 0323pin** [comment]
Something is not right. This is on NetBSD, https://ufile.io/u4f8x6yq

But, I use `leftwm` on Void also and there are no issues there either.
Can you share your `config.toml`?

**Comment by devraza** [comment]
I guess I should also add that I'm using Void on a Raspberry Pi 4.

The config.toml should be found [here](github.com/devraza/dotfiles-leftwm/tree/main/config/leftwm/config.toml)

**Comment by 0323pin** [comment]
Here's from my `config.toml` on Void,

```
modkey           = "Mod4"
mousekey         = "Mod1"
layout_mode      = "Tag"
layouts          = [
    "MainAndVertStack",
    "CenterMainBalanced",
    "EvenVertical",
]

focus_behaviour  = "ClickTo"
focus_new_window = true
tags             = ["1", "2", "3", "4", "5", "6"]
```

Resize = 'Alt' + right click and drag
Move = 'Alt' + left click and drag

**Comment by devraza** [comment]
Sorry, looks like I made a small mistake. I tried moving the windows using the super key instead of Alt. Thanks for the information!

**Comment by 0323pin** [comment]
@devraza All good than? If so, glad I could help.

**Comment by devraza** [comment]
Yep, all good. Thanks for taking your time with this issue.
