### ISSUE TITLE
Increase/Decrease[Main]Width for floating windows

### ISSUE THREAD

**Issue by patrikha** [leftwm/leftwm#777]
Perhaps more of a feature request but is it possible to also support IncreaseMainWidth & DereaseMainWidth for floating windows?
When on a laptop with track pad its really cumbersome to resize a floating window so setting up a keyboard hook would help tremendously.

cheers
Patrik

**Comment by VuiMuich** [comment]
Welcome adventurer!

Generally I like this idea. The question though is, if we would like to apply the existing command to the current window if it is a floating one, or should we add a dedicated command for floating windows?
The latter might be beneficial for scripting, the former is easier on the keybinds.

**Comment by patrikha** [comment]
I would prefer the same command for easier keybindings, seems to me like a dedicated command would fit better in the windowrules section in the config file to set a desired size in pixels or percentatage.

**Comment by hertg** [comment]
Slightly related to #809

**Comment by hertg** [comment]
I'm closing this, as the same request is tracked in #520
