### ISSUE TITLE
Theme not loading on startup

### ISSUE THREAD

**Issue by seabassapologist** [leftwm/leftwm#778]
**Describe the bug**
When I start up Leftwm my selected theme doesn't appear to be loading automatically. I have a symlink created in `~/.config/leftwm/themes` as shown in the wiki, but leftwm doesn't appear to be loading it. If I run the `up` script manually the theme applies just fine

```
$ pwd
/home/matt/.config/leftwm/themes
$ ls -l
total 8
lrwxr-xr-x  1 matt  matt   38 Jun 16 16:43 current -> /home/matt/.config/leftwm/themes/basic_polybar
drwxr-xr-x  2 matt  matt  512 Jun 16 16:11 basic_polybar
```

**To Reproduce**
1. Run `ln -s $(pwd)/basic_polybar current` inside `~/.config/leftwm/themes`
2. Exit out of leftwm
3. Log back into leftwm

**Expected behavior**
My theme to be applied automatically on startup

**Environment:**
 - OS/Distro: OpenBSD 7.1
 - Output of `leftwm-check`
 
```
$ leftwm-check
:: LeftWM version: 0.3.0
:: LeftWM git hash: NONE
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK (has XDG_RUNTIME_DIR) 
:: Checking theme . . .
    -> Theme OK
```

**Additional context**
Installed 0.3.0 from Crates.io with cargo and being launched from .xsession file like so `exec dbus-launch /home/matt/.cargo/bin/leftwm`

Also, leftwm-theme tool doesn't build on OpenBSD 7.1 so I cannot use it to set the theme

Edit:

Also tried just renaming basic_polybar to current and got the same result

**Comment by seabassapologist** [comment]
Ok, so I built Leftwm from the latest git code instead of the crates.io build, and now my theme is automatically loading just fine...

```
leftwm-check                                                                                                                                                      @ ~
:: LeftWM version: 0.3.0
:: LeftWM git hash: 4f765b4-modified
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK (has XDG_RUNTIME_DIR) 
:: Checking theme . . .
    -> Theme OK
```

No changes other than the version I had installed, so is there maybe something wrong with the crates.io package?

**Comment by VuiMuich** [comment]
I'll have a look at this soonish.
Also tagging @lex148 as he maintains the crates.io packages.

**Comment by hertg** [comment]
It seems to me like whatever problems there was, it has been fixed in main.
Please re-open if I'm wrong. :)
