### ISSUE TITLE
Logging to syslog/journald

### ISSUE THREAD

**Issue by TatriX** [leftwm/leftwm#78]
Hi!
It would be awesome if one could configure LeftWM to log via syslog/journald.
I can send a PR if you find it useful :)

**Comment by lex148** [comment]
That is a great Idea. I would love a PR

**Comment by TatriX** [comment]
In general I'd like to make logging story as useful for the random user as it could be.
I've just started with `LeftWM` but I had the same issue I previously had with most wms: it's surprisingly hard to understand what you did wrong with your config.

For instance, I made a mess in the `themes/current` folder by copying files from 2 default themes. To debug it I had to add a hack to `Nanny::boot_current_theme` to write logs to a file.

Anyways, what I ideally want is to have useful logs from both wm and theme scripts in `journalctl -u leftwm` output. 

Implementation wise there is no support for `journald` in `flexi_logger` right now. Only experimental `syslog` support. As far as I know most distros now use `journald` and by default `syslog` compatibility is switched off. So instead I need to write directly to `journald`. And I have several options:
- `systemd-cat` executable to pipe logs
- use some crate (after quick lookup I haven't find a good one yet)
- roll custom made solution
- add required feature to `flexi_logger`.

I guess I'll go for the `systemd-cat` solution for now.

**Comment by TatriX** [comment]
BTW, how do you debug `LeftWM` itself and themes in particular? printf style?

**Comment by lex148** [comment]
Currently for me I log the mess out of everything. I have never really been happy with the whole development cycle. For themes I find myself constantly running the up/down scripts making small changes to avoid getting to the point where I really need to do some hard debugging. 

I am very open to ideas here. I would love to make the experience of creating a theme much more fun.
