### ISSUE TITLE
Add the ability to dinstinct between visible workspace and busy workspace with leftwm-state 

### ISSUE THREAD

**Issue by ArnaudValensi** [leftwm/leftwm#787]
I'm trying display the workspace on polybar on multiple screens. I have a bar on screen A and screen B. On screen B polybar I don't want to display what workspace is selected on screen A, I only want to display if there in a window or not on every workspace.
 To do so, I though that I could use the `busy` property from leftwm-state, but it also returns `busy == true` when a workspace is visible on any screen. Is it possible to have `busy == false` when a workspace is visible but there is no window in it?
We already have the `visible` property to check if a workspace is visible. 

```
        {
          "name": "6",
          "index": 5,
          "mine": false,
          "visible": true,
          "focused": false,
          "busy": true
        },
```

**Comment by noahdotpy** [comment]
Are you saying that `busy` should only be true if there is windows in that tag and false if no windows?

**Comment by VuiMuich** [comment]
Essentially, yes. Not counting all windows though. For example `dock` or `desktop` are ignored as these tend to be present everywhere.

**Comment by ArnaudValensi** [comment]
> Are you saying that `busy` should only be true if there is windows in that workspace and false if no windows?

Yes

**Comment by FelipeColona** [comment]
Hey @VuiMuich, even though this is kinda old, do you mind if I start working on it?

**Comment by mautamu** [comment]
@FelipeColona Feel free, that would be much appreciated! :slightly_smiling_face:
