### ISSUE TITLE
Virtual machine full screen rendering problems in virtualbox

### ISSUE THREAD

**Issue by 13minutes-yt** [leftwm/leftwm#799]
Upon starting a virtual machine (tried on artix and fedora) , the virtual machine will open the same as any normal window with the polybar. As soon as I press Host+f( which will trigger complete full screen for virtual machine), the window vanishes,and only the autohide virtualbox menu is there.
On the same system, I have openbox installed and I do not have any problems whatsoever.

**Comment by VuiMuich** [comment]
have you tried to soft reload after going full screen? My suspicion is, that virtual box changes the resolution of the virtual screen. `leftwm` does not automatically adjust to changed screen size and requires a reload.

**Comment by 13minutes-yt** [comment]
Yes, I tried reloading with no luck.

**Comment by VuiMuich** [comment]
Can you switch to tty in the VM, to try if xrandr and then reload would help?

**Comment by 13minutes-yt** [comment]
There is not even a window border on full screen.The only way to input is by using the VM input menu.My VM is windows 7. It should work fine since I also installed virtualbox additions.What I did is in the VM menu I reset the VM in full screen mode. I did not see anything. When I go out of full screen using Host+f , I see it is restarting.  I logged in with bspwm and the full screen is fine.

**Comment by AethanFoot** [comment]
Virtualbox has to be doing something we arent getting right. Is it possible to get a xprop of it. If another window is open next to it does it disappear as well (it should). A weird guess might be that the autohide menu is in "full screen" and the main window is being hidden as this menu is higher in the stack. We currently will show children of a full screen window above, but dont show a parent of a full screen window

**Comment by 13minutes-yt** [comment]
I did xprop for the autohide menu at fullscreen.
xprop
```
_NET_WM_DESKTOP(CARDINAL) = 2
WM_STATE(WM_STATE):
		window state: Normal
		icon window: <field not available>
_NET_WM_USER_TIME(CARDINAL) = 1067319
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_FULLSCREEN
_NET_WM_ICON_NAME(UTF8_STRING) = 
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = 
_NET_WM_NAME(UTF8_STRING) = "VirtualBoxVM"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x1, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x1a00008
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		window id # of group leader: 0x1a00008
		The urgency hint bit is set
WM_CLIENT_MACHINE(STRING) = "dhcppc1"
_NET_WM_PID(CARDINAL) = 5097
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 27265437
WM_CLASS(STRING) = "VirtualBoxVM", "VirtualBoxVM"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified size: 1366 by 768
		program specified minimum size: 1 by 1
		window gravity: Static


```

>  If another window is open next to it does it disappear as well (it should)
Yes all the windows next to it disappears. Also if it is full screen and I open a terminal, it will not show.

**Comment by AethanFoot** [comment]
Yeah looks like my suspicion was correct, it is strange that the autohidr window ends up higher in the stack (i wonder if using movewindowup/down on the autohide window will eventually cause the window to appear). Two strange things to me is that the autohide menu doesnt have the main one as a transient parent and that it is of type normal. Virtmanager seemed to work on my system (also has an autohide menu) so will check how the xprop is different when get home later

**Comment by 13minutes-yt** [comment]
I tried windowmove up down. no benefit
I did xprop for the invisible window.  These are the results
```
$ xprop
_NET_CLIENT_LIST(WINDOW): window id # 0xe00008, 0x1200003, 0x1600003, 0x60041a, 0x600418
_NET_WM_ICON_NAME(UTF8_STRING) = 
_NET_ACTIVE_WINDOW(WINDOW): window id # 0x600418
PULSE_COOKIE(STRING) = "eb5940184bc403033cf46c90e463fe865d29e5a408a908110e2797e5c1edbf77ea771a45d85e8676256c2a9d8e1a1ca2a38e0e182d085245023d4564cecd35cce92ac45f3644359cc141ddbf8bff51fe36ca7f24325e39b2cf0a6a786bfbcaec7382b1567526e7298c220f7edecbb550b580034fa269f74cce8712a37a8f4958440ddaffe3d060e9eaf5054c6fae3be2e80aa9256330c9af00a280e83d80c6404dc403da126c4dd82cf498ab164088f10c9c54ef1398cf0bbcde7dfb8ce0d1435435fb1cf01661e42b22ef6e6c4e72904556c45945da4791de518e931df9e7cc3b128b0afcd4fd60edfe0ec74e7bcb37bfb9695099842864855181e45882544e"
PULSE_SERVER(STRING) = "{416a186e750cedc288f3fd8e6265ea34}unix:/run/user/1000/pulse/native"
PULSE_SESSION_ID(STRING) = "3"
PULSE_ID(STRING) = "1000@416a186e750cedc288f3fd8e6265ea34/10927"
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0x6f
WM_CLASS(STRING) = "LeftWM"
**_NET_WM_NAME(UTF8_STRING) = "LeftWM"**
_NET_DESKTOP_NAMES(UTF8_STRING) = "1", "2", "3", "4", "5", "6", "7", "8"
_NET_CURRENT_DESKTOP(CARDINAL) = 0
_NET_NUMBER_OF_DESKTOPS(CARDINAL) = 8
_NET_SUPPORTED(ATOM) = _NET_ACTIVE_WINDOW, _NET_SUPPORTED, _NET_WM_NAME, _NET_WM_STATE, _NET_WM_ALLOWED_ACTIONS, _NET_WM_PID, _NET_WM_STATE_MODAL, _NET_WM_STATE_STICKY, _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_SHADED, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_HIDDEN, _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_ABOVE, _NET_WM_STATE_BELOW, _NET_WM_STATE_DEMANDS_ATTENTION, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_STICK, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_WM_WINDOW_TYPE, _NET_WM_WINDOW_TYPE_DESKTOP, _NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_TOOLBAR, _NET_WM_WINDOW_TYPE_MENU, _NET_WM_WINDOW_TYPE_UTILITY, _NET_WM_WINDOW_TYPE_SPLASH, _NET_WM_WINDOW_TYPE_DIALOG, _NET_SUPPORTING_WM_CHECK, _NET_CLIENT_LIST, _NET_DESKTOP_VIEWPORT, _NET_NUMBER_OF_DESKTOPS, _NET_CURRENT_DESKTOP, _NET_DESKTOP_NAMES, _NET_WM_DESKTOP, _NET_WM_STRUT_PARTIAL, _NET_WM_STRUT
RESOURCE_MANAGER(STRING) = 
ESETROOT_PMAP_ID(PIXMAP): pixmap id # 0xc00001
_XROOTPMAP_ID(PIXMAP): pixmap id # 0xc00001
XFree86_DDC_EDID1_RAWDATA(INTEGER) = 0, -1, -1, -1, -1, -1, -1, 0, 6, -81, -20, 53, 0, 0, 0, 0, 41, 22, 1, 4, -107, 34, 19, 120, 2, -69, -11, -108, 85, 84, -112, 39, 35, 80, 84, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -50, 29, 86, -30, 80, 0, 30, 48, 38, 22, 54, 0, 88, -63, 16, 0, 0, 24, -33, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, -2, 0, 65, 85, 79, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0, -2, 0, 66, 49, 53, 54, 88, 84, 78, 48, 51, 46, 53, 32, 10, 0, -40
_XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""
XFree86_has_VT(INTEGER) = 1
XFree86_VT(INTEGER) = 7
Xorg_Seat(STRING) = "seat0"

```

**Comment by M-Mabrouk1** [comment]
hello, You need to uncheck these options and it will work okay.
![image](https://user-images.githubusercontent.com/76488499/188144990-a5f2276e-5ef1-4a9c-919a-8c3d268a995f.png)

**Comment by 13minutes-yt** [comment]
Yes unchecking Fullscreen/seamless solved it !
