### ISSUE TITLE
Session closes when performing a SoftReload

### ISSUE THREAD

**Issue by FranLMSP** [leftwm/leftwm#801]
**Describe the bug**
When performing a `SoftReload`, instead of reloading Leftwm, it closes the session and it sends you to the login manager (Lightdm in my case),  and so closing all the programs

**To Reproduce**
Just soft reload with either `leftwm command SoftReload` or `$MOD + Shift + R`

**Expected behavior**
It shouldn't close the session ;-;

**Environment:**
 - OS/Distro: I use Artix Linux btw
 - Output of `leftwm-check`
 ```:: LeftWM version: 0.3.0
:: LeftWM git hash: cc5b1b1
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK 
:: Checking theme . . .
    -> Theme OK 
```

**Additional context**
It got fixed by downgrading to `8912c25`, so it may be related to either [this](https://github.com/leftwm/leftwm/pull/798) or [this](https://github.com/leftwm/leftwm/pull/788)

**Comment by VuiMuich** [comment]
Welcome adventurer!
Thanks for reporting this!
Can you please check if #802 solves the regression?

**Comment by FranLMSP** [comment]
@VuiMuich yup it's fixed! Thanks!
