### ISSUE TITLE
Multiple Issues with Citrix Applications 

### ISSUE THREAD

**Issue by stevensonmt** [leftwm/leftwm#808]
**Describe the bug**
When using an application through Citrix, the window cannot be moved from the workspace on which it originates. Doing so leads to a black window on the original workspace and nothing on the new workspace. Interestingly, using keybinds to move it back to the original workspace makes it reappear where a black window had been on the original workspace.

In the same vein, on a multi monitor setup moving the workspace the Citrix app is on from one monitor to another creates an unresponsive and poorly rendered window. Moving back to the original monitor reverts to a usable window most of the time.

If the Citrix application opens a child window, that child is tiled as a new window by leftwm but this geometry is not always conducive to interacting with the window. Changing layouts in leftwm causes the same unresponsive and poorly rendered windows as the above maneuvers.

**Screenshots**
I apologize for not including screenshots but the application in question is a healthcare app that I could get into a lot of trouble for posting on here.

**Environment:**
 - OS/Distro: Arch
 - Output of `leftwm-check`
```
:: LeftWM version: 0.3.0
:: LeftWM git hash: 43e31e7
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```
**Additional context**
I'm not sure if this is a leftwm issue as a previous Manjaro installation using leftwm did not have this issue, but another Arch install on a different system has had similar issues. I've tried all the graphics configurations I can think of in Arch to resolve this but have come up empty.

**Comment by VuiMuich** [comment]
Quite some time ago some similar behaviour was purposefully built as DRM measure in some video player software, or was this some feature of WinVista, idk anymore exactly. But that was tied to only rendering on the "main" display.

It seems you have tried to launch on different workspaces and monitors, right? So "moving" through `window_rule` would make no real difference.
Have you tried if you can make the window `floating`? Probably will result in the same as with changed layout.
Looks like this citrix app really hates to update its properties..

**Comment by stevensonmt** [comment]
Yeah making it floating didn't seem to help much.

**Comment by AethanFoot** [comment]
Are you able to test if something similar happens on bspwm, as that will check if it is the way we are hiding windows or not (as we unmap them to hide them)

**Comment by stevensonmt** [comment]
If anything bspwm is worse but similar.

**Comment by VuiMuich** [comment]
Thanks. And no worries for bringing up something not totally related. 
Imo it's always good to have a problem and it's solution bundled in one place, even if the place is not the ideal one. Someone might find help from it eventually.
