### ISSUE TITLE
zsh support for builtin themes

### ISSUE THREAD

**Issue by TatriX** [leftwm/leftwm#81]
Builtin themes use bash specific features, see https://superuser.com/questions/555874/zsh-read-command-fails-within-bash-function-read1-p-no-coprocess for example.
Thus some commands silently fail.

**Comment by lex148** [comment]
I think zsh should already be supported. Technically you should be able to write the up/down scripts in any language, python ruby c++ whatever. 

To use zsh try changing the Shebang line at the top of your up/down scripts 
from: #!/bin/bash
to: #!/usr/bin/zsh

hope this helps,
-Lex

**Comment by TatriX** [comment]
Hm, right, after having some sleep I can't understand why I came to that conclusion :crab:
