### ISSUE TITLE
Window borders flicker seemingly randomly

### ISSUE THREAD

**Issue by emeliagit** [leftwm/leftwm#810]
Window borders, regardless of application, seem to flicker randomly. It doesn't always happen, sometimes it's linked to my cursor (so whenever I move my cursor, it flickers), sometimes it's fixed when I move my cursor over onto the window whose border is flickering. It happens intermittently, I'm not sure what's causing it. I think it's a LeftWM issue, since this doesn't happen on other window managers like Awesome, DWM, BSPWM, i3, and others that I regularly use.

**To Reproduce**
Just use LeftWM for a bit, window borders will start flickering. It happens with Discord, Alacritty, (especially) Pcmanfm, Dolphin, Firefox, and other applications I regularly use. 

**Expected behavior**
Normally, I expect Windows borders to be purple (I'm using the Dracula Rounded theme) with the exception of the window focused having a pink border, changing only when I change my focus.

**Environment:**
OS is EndeavourOS, also happens on Fedora. Happens on both NVIDIA and AMD drivers.
Output of LeftWM-check is as follows: 
:: LeftWM version: 0.3.0
:: LeftWM git hash: eaf531d
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK

**Additional context**
Sometimes it seems to be linked to where my cursor is, like it'll stop flickering if I move my cursor, or it'll only flicker if my cursor is in certain places. However, it's not always related, and sometimes moving my cursor changes nothing. It's usually fixed for a little bit by restarting LeftWM, but then it happens again after a couple minutes. 

UPDATE: tried it on my old ROG Zephyrus G with a 3750H running Fedora, everything seems fine as well, but the same issue happens. Also, I accidentally closed this issue and then reopened it, sorry lol

UPDATE UPDATE: was just using DWM normally on my old ROG Zephyrus G again, and it just happened, but now on DWM. I'm uncertain as to what it could be if it's independent of drivers, Picom configurations, and even window managers. Maybe it's an X11 thing? Or perhaps an extremely similar bug that just so happens to be in both window managers? Uncertain.

**Comment by VuiMuich** [comment]
Welcome adventurer!
Guessing from your second update, I would suggest running for some while without `picom`,, as this would be my number one potential culprit anyways. Which fork are you using?

**Comment by emeliagit** [comment]
> 

Ah, this is... a good idea, thank you. And by "fork", I presume you mean fork of Picom? I'm just using stock Picom with Vsync enabled.

**Comment by emeliagit** [comment]
Oops I accidentally closed and reopened it again

**Comment by emeliagit** [comment]
Alright, I seem to have fixed it by using "xr_glx_hybrid" instead of "glx" in my Picom config.
