### ISSUE TITLE
The settings in "~/.config/leftwm/themes/catppuccin/theme.toml" don't work.

### ISSUE THREAD

**Issue by CalciteW** [leftwm/leftwm#819]
I'm in Arch and my 'theme.toml' is like this:
```
border_width = 0
margin = 15
default_border_color = '#1E1E28'
floating_border_color = '#F2CDCD'
focused_border_color` = '#C6AAE8'
```
They don't work and it's still look like the default（red）.

**Comment by VuiMuich** [comment]
Welcome Adventurer!
There seems to be a misplaced backtick at the end of `focused_border_color`. If it's not that, could you please do a `leftwm-check` to possibly get a hint what exactly is broken?

**Comment by CalciteW** [comment]
> Welcome Adventurer! There seems to be a misplaced backtick at the end of `focused_border_color`. If it's not that, could you please do a `leftwm-check` to possibly get a hint what exactly is broken?

I do a 'leftwm-check' and :
```
:: LeftWM version: 0.3.0
:: LeftWM git hash: e2517de
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
ERROR: `commands.pipe` is deprecated. See https://github.com/leftwm/leftwm/issues/652 for workaround.
```
I'm studying how to solve it

**Comment by CalciteW** [comment]
I ran `leftwm command "LoadTheme ~/.config/leftwm/themes/Catppuccin/theme.toml"` and it solved!

Thank you for your help!
