### ISSUE TITLE
Is there a startup script? / Stopping autosarting programs.

### ISSUE THREAD

**Issue by xircon** [leftwm/leftwm#82]
I make a lot of changes, to my keyboard for example, currently I have put my changes in the theme's up script, which is not ideal.  Is there anywhere else I can put them?

I have installed alongside my Plasma install and the standard method of "NotShowIn" in the autostart .desktop file does not work as "XDG_SESSION_DESKTOP" is not set.  

Really enjoying LeftWM.

Distro Manjaro (Unstable branch).

**Comment by lex148** [comment]
Yes, LeftWM will auto run all desktop files in 
~/.config/autostart/

I am currently using it in my config to change my background every 5 minutes.
Here is what is in my ~/.config/autostart/

Background.desktop
`
[Desktop Entry]
Name=Background
GenericName=Background
Exec=/home/lex/.wallpaper_random.sh
Terminal=false
Type=Application
StartupNotify=false
X-GNOME-Autostart-enabled=true
`

Please note these desktop files only get ran when LeftWM boots up at login. They don't get ran when you reload ( Mod + Shift + r )

**Comment by xircon** [comment]
I have variety wallpaper changer running and working.

Any ideas how to stop an autostart entry from running?
