### ISSUE TITLE
floating windows spawn top-left instead of centered

### ISSUE THREAD

**Issue by M-Mabrouk1** [leftwm/leftwm#824]
Any app that requests a floating window or a floating prompt it opens in the (0,0) coordinates.
![Peek 2022-09-02 14-34](https://user-images.githubusercontent.com/76488499/188146568-2be3c234-9477-46ba-b79e-77ab7b12b544.gif)

This is an example in blueberry, also encountered in vs-code.

Before that these windows used to open in the middle of the screen.

**Environment:**
 - OS/Distro: ArcoLinux
 - ![image](https://user-images.githubusercontent.com/76488499/188147517-492ddf7a-d243-438f-b449-3e40dd41136f.png)

**Comment by VuiMuich** [comment]
This is a little regression introduced recently and no one found it annoying enough to fix it yet :see_no_evil: 
I am sorry for the inconvenience.

**Comment by M-Mabrouk1** [comment]
It's okay, I just wanted to help tracking this bug, if I know rust a little bit I would have helped.

**Comment by VuiMuich** [comment]
I feel just a little sorry as this should have surfaced during review and now this is lingering longer then I am comfortable with.

**Comment by 0323pin** [comment]
Just to add to the weirdness, this only happens to when uploading files through the firefox dialogue. like when uploading the screenshot bellow.

I've tried in Gtk2, Gtk3 and Qt apps but, it doesn't happen there.

![2022-09-06-113255_1366x768_scrot](https://user-images.githubusercontent.com/90570748/188604451-5e3f9196-2451-4530-8d40-39b76e7cba43.png)

**Comment by TornaxO7** [comment]
I'm claiming this issue here.
