### ISSUE TITLE
No keyboard inputs when using the nix flake on NixOS

### ISSUE THREAD

**Issue by Syudagye** [leftwm/leftwm#842]
### Describe the bug

Since the addition of lefthk as the hotkey daemon for leftwm, my leftwm keybindings are no longer working.
LeftWM boots fine (it boots the theme as well with no issue), but no keybindings is being processed

### Expected behavior (optional)

Working keyboard inputs.

### Steps to reproduce (optional)

I'm building leftwm with home-manager, passing it as an input in a nix flake and then adding it as a package.

### Relevant log output (optional)

```text
After building leftwm with systemd logs i found this:

lefthk-worker[430103]: Exiting due to error: Xlib error: opening library failed (opening library failed (libX11.so.6: cannot open shared object file: No such file or directory); opening library failed (libX11.so: cannot open shared object file: No such file or directory)).
```
```


### OS / Distro

NixOS

### Additional System Information (optional)

```text
Starting leftwm with lightdm.
leftwm is installed through home-manager by passing it as an input with a nix flake (this means it is using the result of `nix build`)
```

### LeftWM Check

```text
:: LeftWM version: 0.3.0
:: LeftWM git hash: dirty
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
WARN: TOML as config format is about to be deprecated.
      Please consider migrating to RON or contact the theme creator about this topic.
      Note: make sure the `up` script is loading the correct theme file.
ERROR: File not found: theme.ron
```

**Comment by AethanFoot** [comment]
This weird as lefthk doesnt have any dependencies that leftwm hasnt

**Comment by AethanFoot** [comment]
@kid, any ideas here? (hopefully they are still active).

**Comment by kid** [comment]
🤔 I'll have a look over the week-end, as I'm still using an older version with some custom changes

**Comment by AethanFoot** [comment]
Ah, I thought it might have something to do with how it was built. But I have no idea how they work :laughing:. I presume that bit forces the marked binaries to be built against the libraries?

**Comment by AethanFoot** [comment]
@Syudagye can u test that pr

**Comment by kid** [comment]
> Ah, I thought it might have something to do with how it was built. But I have no idea how they work 😆. I presume that bit forces the marked binaries to be built against the libraries?
It simply patch the existing binaries so they look for libraries in the correct place

**Comment by Syudagye** [comment]
It seems to fix the issue.
I haven't noticed that it builds `lefthk-worker` as a separate binary, i thought it was embeded inside other leftwm binaries.
Thanks for helping !
