### ISSUE TITLE
leftwm wont startup due to missing `lefthk-worker` in AUR `leftwm-git` package

### ISSUE THREAD

**Issue by patrikha** [leftwm/leftwm#854]
### Describe the bug

After updating to latest leftwm-git the display will no longer startup.
leftwm 0.3.0, Git-Hash: ee918a7

Any suggestions?

### Expected behavior (optional)

No display and exit back to lightdm.
Reverting back to use latest release works fine!
yay -S leftwm

### Steps to reproduce (optional)

yay -S leftwm-git

### Relevant log output (optional)

```text
thread 'main' panicked at 'failed to start lefthk: Os { code: 2, kind: NotFound, message: "No such file or directory" }', leftwm/src/bin/leftwm.rs:195:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Sep 24 06:58:00.355 INFO leftwm-worker booted!
thread 'main' panicked at 'Null pointer in display', leftwm-core/src/display_servers/xlib_display_server/xwrap/mod.rs:143:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Sep 24 06:58:00.361 ERRO Completed with error: Any { .. }
```

### OS / Distro

Manjaro Sikaris 22.0.0

### Additional System Information (optional)

```text
cat /etc/lsb-release
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=22.0.0
DISTRIB_CODENAME=Sikaris
DISTRIB_DESCRIPTION="Manjaro Linux"

xdpyinfo | grep version
version number:    11.0
X.Org version: 21.1.4
```

### LeftWM Check

```text
eftwm-check
:: LeftWM version: 0.3.0
:: LeftWM git hash: ee918a7
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
WARN: TOML as config format is about to be deprecated.
      Please consider migrating to RON or contact the theme creator about this topic.
      Note: make sure the `up` script is loading the correct theme file.
ERROR: File not found: theme.ron

Please note that leftwm-check -m will not migrate themes.toml
```

**Comment by VuiMuich** [comment]
Welcomche adventurer!

Have you been on the git release before? Or did you switch from `stable` to `git`, when this appeared?
Can you check, what you get reported on `which lefthk-worker`? It should be in the same path as the rest of the leftwm binaries.

**Comment by patrikha** [comment]
I have been on `git` for a long time and updating weekly. There has been no updates on Manjaro since it stopped working so I would guess a very recent commit.

But no `lefthk-worker` on the system so I guess its a packaging error in `AUR`!?

**Comment by VuiMuich** [comment]
Maybe. I just checked the `PKGBUILD` script and that looks alright to me. Could you please try to reinstall, possibly you package wasn't pulled correctly.
Gonna edit the title as this most certainly is related to the package, imo.

**Comment by patrikha** [comment]
I clean build resolved the issue, funny thing it happened on all my (three) Linux boxes at the same time.

Closing the issue, thanks

**Comment by VuiMuich** [comment]
You are welcome.
Not sure if this is a general AUR issue then, or just related to `yay`.
