### ISSUE TITLE
Leftwm failed to run on startup

### ISSUE THREAD

**Issue by opakholis** [leftwm/leftwm#857]
### Describe the bug

Leftwm fails to run after update the latest version from AUR package.

### Expected behavior (optional)

work as usual 😛

### Steps to reproduce (optional)

1. paru leftwm-git
2. reboot
3. and my screen goes blank which is where leftwm should be running

### Relevant log output (optional)

```text
thread 'main' panicked at 'Couldn't setup journald-logger. Are you sure journald is running?: Os { code: 2, kind: NotFound, message: "No such file or directory" }', leftwm/src/utils/log/journald.rs:15:10
```

### OS / Distro

Linux artixlinux 5.19.10-zen1-1-zen

### Additional System Information (optional)

```text
using OpenRC instead of Systemd
```

### LeftWM Check

```text
:: LeftWM version: 0.3.0
:: LeftWM git hash: f7cfb9b
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```

**Comment by VuiMuich** [comment]
Welcome adventurer!

This looks basically the same as #854. 
Can you try to manually reinstall, seems like when updating the AUR package `lefthk-worker` is missed to get placed in the bin path.

**Comment by opakholis** [comment]
I have reinstalled manually or using paru, the results are still the same. For now, I am using in hash 03a7ac9 and everything is working fine

just guessing, as mentioned in the error log, this happens because it doesn't find `journald-logger`, which is only available in systemd.

**Comment by AethanFoot** [comment]
This would be due to the recent logging changes, where artix was a bit of an oversight. To get you going before there is a solution manually build leftwm with the `--no-default-features` flag and manually add lefthk (and maybe syslog back in) `--features lefthk,sys-log`. Hopefully thats correct currently on mobile.

For a solution we either want a non-systemd aur package or to log the fail instead of panicking (and maybe go down to syslog on failure)

@VuiMuich, @TornaxO7

**Comment by VuiMuich** [comment]
Oopsie, sorry.

It should be possible to check in the `PKGBUILD` if systemd is on the system and set buildflags accordingly, right?

**Comment by VuiMuich** [comment]
I updated the `PKGBUILD`, @opakholis can you please check, if it works now?

**Comment by opakholis** [comment]
ya I think this issue has been resolved and can be closed. thanks @VuiMuich  @AethanFoot 🍺

**Comment by VuiMuich** [comment]
You are very welcome and thanks for reporting! :beers:
