### ISSUE TITLE
leftwm-check -m dont migrate scratchpads correctly

### ISSUE THREAD

**Issue by patrikha** [leftwm/leftwm#860]
### Describe the bug

Migrating from config.toml to config.ron handle scratchpad elements incorrect

### Expected behavior (optional)

Having the following config.toml structure:
```
scratchpad = [
    { name = "Mousepad", value = "mousepad", x = 200, y = 300, height = 600, width = 800 },
]
```
and the running `leftwm-check -m` will generate this block in the config.ron file:
```
    scratchpad: [
        (name: ("Mousepad"), value: "mousepad", x: 200, y: 300, height: 600, width: 800),
    ],
```
Simply removing the tuple definition for name will fix the problem

### OS / Distro

Manjaro 22.0.0

### LeftWM Check

```text
leftwm-check
:: LeftWM version: 0.3.0
:: LeftWM git hash: d4fae27
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
WARN: TOML as config format is about to be deprecated.
      Please consider migrating to RON or contact the theme creator about this topic.
      Note: make sure the `up` script is loading the correct theme file.
ERROR: File not found: theme.ron
```

**Comment by AethanFoot** [comment]
This would be due to the recent logging changes, where artix was a bit of an oversight. To get you going before there is a solution manually build leftwm with the `--no-default-features` flag and manually add lefthk (and maybe syslog back in) `--features lefthk,sys-log`. Hopefully thats correct currently on mobile.

For a solution we either want a non-systemd aur package or to log the fail instead of panicking (and maybe go down to syslog on failure)

@VuiMuich, @TornaxO7

**Comment by AethanFoot** [comment]
To get access to ron you need to be built of the git branch, in the aur it is `leftwm-git`

**Comment by AethanFoot** [comment]
This actually appears to be because of a struct rapper around the name value, which isnt serialising in the proper way. @SamClercky

**Comment by SamClercky** [comment]
Hi @AethanFoot,

I found the culprit and made a PR that fixes the issue :smile:!

The issue was with a newtype `ScratchPadName` that was introduced at the end of PR #768 to improve code readability and only implemented deserialisation (`String` to `ScratchPadName`) and not the other way around.

**Comment by VuiMuich** [comment]
Now that you mention, I believe there is an extension in Ron, just as the `implicit_some` for newtypes as well.

**Comment by SamClercky** [comment]
I see. However this would probably not eliminate the need for the convertion between `String` and `ScratchPadName` as `TOML` is still currently supported and still needs to be parsed.

Would you want me to add `unwrap_newtypes`-extension to the reading of `RON` files in PR #861? I could do it, but it is getting late for me now, so probably tomorow is the soonest I can work on this again.

**Comment by VuiMuich** [comment]
Good point on the toml serialization.
Keep the PR as is. Thanks!
