### ISSUE TITLE
Crash on un launching leftwm fedora after updating to 4.0

### ISSUE THREAD

**Issue by NicTanghe** [leftwm/leftwm#884]
### Describe the bug

Crash after updating to 4.0

Uninstalled theme
Installed diferent theme.

Same problem

Run dnf reinstall leftwm

same problem 

### Expected behavior (optional)

i try to login and it works

### Steps to reproduce (optional)

install version 3.0 with garden theme.
update to 4.0

### OS / Distro

fedora 35

### Additional System Information (optional)

```text
5950 amd
3070 Nvidia
```

### LeftWM Check

```text
❯ leftwm-check
:: LeftWM version: 0.4.0
:: LeftWM git hash: NONE
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK

~
```

**Comment by NicTanghe** [comment]
Im not sure how to troubleshoot his since it just doesnt start and puts me back in the login schreen.

**Comment by VuiMuich** [comment]
I am not really familiar with `copr`, but what breaks this is that the `lefthk-worker` binary gets installed.
Idk if there is some way to "manually do a local build" of a package, or how you would fork a copr package to edit the install script.

But as mentioned in the other issue, the maintainer is supposed to have been contacted yesterday, so hopefully he can update this asap.

**Comment by NicTanghe** [comment]
didn`t c the reply sorry for my being blind.

**Comment by VuiMuich** [comment]
No worries, I think it was just overlapping us both writing at the same time

**Comment by NicTanghe** [comment]
Hmm just saw this reply.

No idea how to edit rpm files
```
rpm2cpio leftwm-0.4.0-1.el9.src.rpm | cpio -iv --to-stdout /usr/bin/testleft > ./testleft
```

Just agave me a blank file.
But I`m nolonger on this route> I`m using cargo to isntall but i think the problem there might also be that lefthk worker is not installed or configured or whatever autamatically

**Comment by NicTanghe** [comment]
If i excecute lefthk-worker nothing happens.
annything i can do to check if it is installed ?

**Comment by VuiMuich** [comment]
You can use `which lefthk-worker` for checking if the binary can be found by the system.

I believe you can't run this binary on its own, it needs either `leftwm` or `lefthk` to setup the environment for it to run.

**Comment by NicTanghe** [comment]
does it need to be in launched in from the up file or does it run automatically ?

**Comment by VuiMuich** [comment]
The `leftwm` binary runs it automatically.
