### ISSUE TITLE
fixed autostart programs by leftwm

### ISSUE THREAD

**Issue by elyashivhazan** [leftwm/leftwm#899]
Hi, I just switched form dwm to leftwm and its been greet, the one thing I could not understand is some "features" (e.g bluetooth notification with dunst, and redshift is disabled on startup with xinit) been added.
I am running on manjaro xfce (I am not running any programs from the xfce project) without DM (I am starting x11 only with xinit).

**Comment by Eskaan** [comment]
About the bluetooth notifications: I think leftwm does not provide an notification server, you can try sending notifications using `notify-send "Test title"`. See the [Desktop Notifications](https://wiki.archlinux.org/title/Desktop_notifications) on the Arch wiki. Xfce seems to provide its own optional notification server.

**Comment by elyashivhazan** [comment]
Hi, I know it dosnt, Im using dunst and I wrote that. What i think it is its maybe something like dbus-launch that I never ran on my system so it may be the reason why Bluetooth can now send notifications. I wold love for confirmation.

**Comment by VuiMuich** [comment]
Welcome adventurer!
Do you have an items in `~/.config/autostart`? If there are any `.destop` files in it, `leftwm` will run those, `dwm` most certainly doesn't do this except patched for it. Iirc `manjaro xfce` usually places some items in this `XDG_AUTOSTARE_DIR`.

**Comment by elyashivhazan** [comment]
First of all good to know this feature but no Im so minimal nothing auto start except in the xinit file.

**Comment by VuiMuich** [comment]
Then you probably are also sure no systemd services are starting the bluetooth notifications? redshift has a `--user` level service that starts it.

**Comment by elyashivhazan** [comment]
I did not explained my self right, Bluetooth always running on my system but I never got any messages from it with qtile, dwm, berry but in leftwm I do and from some reason its also starts some manjaro tool in the background that has never been started.
The thing is I must know what and how things run on my system but I can not understand leftwm startup for some reason. I also thought to do a clean reinstall of Arch to but now i first want to know what cosign this.

If you know what info you need to understand what Im searching for pls tell me and I will send it. (like my packages installed, process running etc)

**Comment by elyashivhazan** [comment]
> Welcome adventurer! Do you have an items in `~/.config/autostart`? If there are any `.destop` files in it, `leftwm` will run those, `dwm` most certainly doesn't do this except patched for it. Iirc `manjaro xfce` usually places some items in this `XDG_AUTOSTARE_DIR`.

So Im stupid, I forgat about `/etc/xdg/autostart` and if leftwm starts `~/.config/autostart` then it will start `/etc/xdg/autostart` to.

How can I disable it? to be honest all I did is to go to `https://github.com/leftwm/leftwm/wiki/Config#autostart` and found nothing.
I did found a changeling that tells I can put `X-Gnome-Autostart` but I wold love to disable it to all

**Comment by VuiMuich** [comment]
Iirc you could put a line in the desktop files that exclude `leftwm`. I don't remember the exact keyword rn though.

**Comment by elyashivhazan** [comment]
Is that the only solution? I have them because of the package manager and I cant just every time do that and plus its require root and modifying files from a package.

**Comment by VuiMuich** [comment]
If I read [the specs](https://specifications.freedesktop.org/autostart-spec/autostart-spec-latest.html) right, it should be possible that you copy it to the user dir and add a `NotShowIn` line to it. This one should take precedance over the system wide autostart

**Comment by elyashivhazan** [comment]
Thanks a lot for the help. I will do that.

**Comment by VuiMuich** [comment]
You are very welcome!
