### ISSUE TITLE
Logs getting filled with error from the state socket

### ISSUE THREAD

**Issue by Syudagye** [leftwm/leftwm#903]
### Describe the bug

Some time after starting leftwm, it starts to spam log an error message, which fills logs in `journalctl` and `[state_directory]/leftwm/log.log`.

Here is the error:
```
2022-10-15T18:06:20.883015Z ERROR leftwm_core::utils::state_socket: accept failed = Os { code: 24, kind: Uncategorized, message: "Too many open files" }
```

This is a problem because it can fill disk space quickly.

Here after some hacking into leftwm's code base, and leftwm compiled with the `file-log` flag, i ended up with a 27G log file, almost completely filled with this error:
![Screeshot_2022-10-15_21-20-57](https://user-images.githubusercontent.com/44324659/196004428-f3340026-c58a-42f7-af59-ce08d8cab73d.png)

### Expected behavior (optional)

No errors, or at least no spamming if this error.

### Steps to reproduce (optional)

install/build leftwm with the `file-log` flag:
```bash
make install-dev # to symlink binaries, so we don't need to reinstall it everytime
cargo build --release --features=file-log
```

Let it run a bit, and after some time check `[state_directory]/leftwm/log.log` (usually this is `$HOME/.local/state/leftwm/log.log`)

### Relevant log output (optional)

```text
2022-10-15T18:06:20.883015Z ERROR leftwm_core::utils::state_socket: accept failed = Os { code: 24, kind: Uncategorized, message: "Too many open files" }
```

### OS / Distro

`Linux archbtw 5.19.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 28 Sep 2022 13:21:25 +0000 x86_64 GNU/Linux`

### LeftWM Check

```text
:: LeftWM version: 0.4.0
:: LeftWM git hash: 06e16e2
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
WARN: TOML as config format is about to be deprecated.
      Please consider migrating to RON or contact the theme creator about this topic.
      Note: make sure the `up` script is loading the correct theme file.
ERROR: File not found: theme.ron
```

**Comment by VuiMuich** [comment]
Can you check if your `ls $XDG_RUNTIME_DIR/left{wm, hk}` looks clean? There should be one `command-0.pipe` in each folder, the `leftwm` also has a `statefile.socket`.
Can you try to link any event to this happening?

**Comment by Syudagye** [comment]
> How long did it take to get to this size?

Well i think i tinkered for one hour here, but the error can appear really fast, sometime i barely have time to read the logs to find something and i get a wall of errors.


> Can you check if your `ls $XDG_RUNTIME_DIR/left{wm, hk}` looks clean? There should be one `command-0.pipe` in each folder, the `leftwm` also has a `statefile.socket`.

These directories are clean, no issues here.


I have tried to understand how it happens, and i found out it starts appearing after i left it idle for some time.
It looks like i can't use any keybindings while it is happening. I also can't use `leftwm-command`, it stay stuck and don't do anything. Only switching tag with polybar fixes this (my polybar is using the `internal/xworkspaces` widget).

I also noticed that is starts happening when i switch tty: 
When i work on `leftwm` i usually start a wayland session (for now i'm using `river`), and i switch to a tty and use `startx` to start leftwm. It looks like when I switch tty to leftwm, it starts doing the same thing, but this time my keybindings works, and doing anything stops the log spamming.


> Can you try to link any event to this happening?

here you will see a recording (just uploaded it, will be watchable soon): https://youtu.be/7p-xKfW6dGQ

1:49 -> The issue starts appearing
2:25 -> Trying to call `leftwm-comand` to see if anything happens
2:45 -> Clicking on my polybar to switch tag, which executes the `leftwm-command` it started on the obs window, and stops the issue.

From the time the issue started, all the way through the moment i switch tag, i was unable to use my keybindings. I wanted to use `showkey` to show i was clicking my keyboard, but it didn't work :laughing: (i think it has to do with me starting it with `startx`, or `river` running in the background.

**Comment by VuiMuich** [comment]
Just to suffice the stupid standard support questionnaire: Did you try switching it off and on again? - Oh you did that already? /jk

Actual question though, did this workflow work before `0.4.0`? Could you try if reverting #820, #821 (for this one building without any `loqqinq` features might be sufficient) or #832 changes the situation?

**Comment by rizumu** [comment]
I noticed the same behavior, unresponsive keybindings and log spamming. I swapped:
```
[module/layout]
type = custom/script
interval = 0.1[module/layout]
type = custom/script
interval = 0.1
label = " %output% "
exec = leftwm-state -q | jq -r .workspaces[0].layout
```
for
```
[module/layout]
type = custom/script
interval = 0.1[module/layout]
type = custom/script
interval = 0.1
label = " %output% "
tail = true
exec = leftwm-state | jq -r .workspaces[0].layout
```
However the polybar module no longer renders the layout name.

Probably because `leftwm-state | jq -r .workspaces[0].layout` hangs, I need to use the `-q` to realtime get the correct output for displaying the current layout. (I'm using symbols instead of layout names so my `config.ron` contains this:
```
    layouts: [
        "󱇙",  // Grid
        "󱒑",  // Even Vertical
        "󱒏",  // Even Horizontal
        "󰏠",  // Monocle
        "",   // MainAndHorizontalStack
        "󰮱",  // MainAndVertStack
        "󰯌",  // RightMainAndVertStack
        "󰞦",  // Fibonacci
        "󱒎",  // Dwindle
        "󰞞",  // MainAndDeck
        "󰀚",  // CenterMain
        "󰀥",  // CenterMainBalanced
        "󱤉",  // CenterMainFluid
    ],
    layout_definitions: [
        // Grid
        (name: "󱇙", flip: None, rotate: North, reserve: None,
         columns: (flip: None, rotate: North,
             main: None,
             stack: (flip: None, rotate: North, split: Grid),
             second_stack: None)),
         ...
    ]
```
What would be the correct way to describe the layout module?

This could be it's own issue but there should be a better way to use glyphs for representing a layout in the polybar if there isn't already. Instead of renaming the layout definitions to use a symbol, adding another key would be better, something like `glyph` or `display_name` to the `layout_definitions` could be helpful. 

Although the following would be ideal, because then we wouldn't of had to redefine the default `layout_definitions` in their entirety just to change the output:
```
    layouts: [
        ["Grid", "󱇙"],
        ....
    ],
```
