### ISSUE TITLE
Changing layout

### ISSUE THREAD

**Issue by stevensonmt** [leftwm/leftwm#91]
Is it possible to change layout from splitting vertically to splitting horizontally, i.e., one window on top of the other rather than side by side?

**Comment by lex148** [comment]
Absolutely the default keys to rotate between the layouts should be
Mod + Crtl + Up
and 
Mod + Crtl + Down

There are a couple layouts that look vertical with just two windows.
 It really helps to open 5+ windows to really see what the layout is.

**Comment by stevensonmt** [comment]
Thanks!
