### ISSUE TITLE
Is there a cli to configure leftwm dynamically?

### ISSUE THREAD

**Issue by phenax** [leftwm/leftwm#92]
I use sxhkd to manage my keybindings. I want to be able to switch to a particular workspace, resize focused window, move/swap windows, etc.

**Comment by lex148** [comment]
Left accepts command sent to it using a pipe file.
You wont be able to resize with it, but you can at least navigate around 
echo "SendWorkspaceToTag 1 2" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

LeftWM also is ewmh compliant so I would recommend checking out a tool like wmctrl

If these two options don't solve your issue please let me know. I'm always looking for ways to improve LeftWM.

**Comment by phenax** [comment]
That sounds pretty good. Thank you!
