### ISSUE TITLE
Blackscreen with cursor

### ISSUE THREAD

**Issue by Septias** [leftwm/leftwm#921]
### Describe the bug

When I start a session with leftwm, I only see a moving cursor on a black screen. 
I installed leftwm-git and leftwm-theme-git on a manjaro-gnome setup. I also picked a theme and `leftwm-check` does not show any errors.

What am I doing wrong?

### OS / Distro

Linux 5.19.16-2-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Oct 15 13:37:00 UTC 2022 x86_64 GNU/Linux

### Additional System Information (optional)

```text
I have an nvidia gpu and the latest linux515-nvidia drivers.
```

### LeftWM Check

```text
:: LeftWM version: 0.4.0
:: LeftWM git hash: dc87b0e
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK 
:: Checking theme . . .
    -> Theme OK
```

**Comment by Septias** [comment]
Yeah I can open one actully

**Comment by Septias** [comment]
Also, dmenu is no opening

**Comment by Septias** [comment]
Yeah somehow some default keybindings didn't work so I had to change them.

**Comment by VuiMuich** [comment]
Hmm that's odd that some default keybinds are not working..
Some keyboard layouts like `AZERTY` are not working out of the box though, iirc.

Regarding `dracula` you have `polyber` installed, right? I can apply this theme on my side, but I am not certain at this point if it is not a very old copy of it and if there might have been any changes to the one on the repo since I cloned it.

**Comment by Septias** [comment]
After some manual readjustments I got most of the stuff working :) I use Neo2.0 layout so I'm not too shocked, that some keybindings didn't work directly

**Comment by VuiMuich** [comment]
How have you set your neo layout?
I am using `vou` which is a custom variant to `koy` but I have set `de(t3)` as my primary layout and switch with `xkb-switch -s custom(vou)` via script after login, so the default binds match with the physical keyboard which is a standard `quertz`.

**Comment by Septias** [comment]
Actually manjaro supports it by default. You can just choose it under 'add keyboard'

**Comment by Septias** [comment]
What is the difference between vou and neo?
