### ISSUE TITLE
leftwm problem with sddm

### ISSUE THREAD

**Issue by adcdam** [leftwm/leftwm#924]
### Describe the bug

i packaged leftwm 0.4.0  for Slackware, problem is it does not start if i use SDDM , it start fine if i launch with tbsm or with startx.
when launching with SDDM it does nothing. Slackware does not use systemd.
what could be the problem?

### Expected behavior (optional)

leftwm should start with SDDM login manager

### OS / Distro

Slackware

### LeftWM Check

```text
leftwm-check
:: LeftWM version: 0.4.0
:: LeftWM git hash: NONE
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK 
:: Checking theme . . .
WARN: TOML as config format is about to be deprecated.
      Please consider migrating to RON or contact the theme creator about this topic.
      Note: make sure the `up` script is loading the correct theme file.
ERROR: File not found: theme.ron
```

**Comment by Eskaan** [comment]
Welcome Adventurer!

You can try compiling leftwm with the `file-log` or `sys-log` features to get the logs, that may help. I don't know if there are any known problems with ssdm.

**Comment by VuiMuich** [comment]
Awesome to hear, we even reach to slack now!
SDDM usese `.desktop` files independent of the init system, right? I guess tbsm is basically just wrapping startx, isn't it?

**Comment by adcdam** [comment]
Hi, to be able to launch leftwm i had to use `cargo build --release --no-default-features --features=lefthk,sys-log`
so i think i can not test it with sys-log, can you please test it if you can in a non systemd distro using sddm?
perhaps im missing something, the strange thing is that with tbsm or with startx it work nice even with theming.

**Comment by VuiMuich** [comment]
so when you build with `cargo build --release --no-default-features --features=lefthk` you can't get it running?
@0323pin has experience packaging for non-systemd. Also there is a Void package but I am not certain who the maintainer of that was.

**Comment by adcdam** [comment]
no if i build it with `cargo build --release --no-default-features --features=lefthk` i can get it runing using tbsm or startx, tbsm can read .desktop files, if i build it with just ` cargo build --release ` it doesnt start at all.

**Comment by adcdam** [comment]
perhaps the problem is SDDM?

**Comment by 0323pin** [comment]
@adcdam As expected, `default features` include `journald-log` which, is a `systemd` thing.

**Comment by VuiMuich** [comment]
> perhaps the problem is SDDM?

On the arch-wiki there is a [troubleshoot case](https://wiki.archlinux.org/title/SDDM#Hangs_after_login) where deleting `~/.Xauthority` and logging in without rebooting, should solve some cases of sddm hanging after login.
Just a wild guess, but might also be related.

Your buildflags are alright, I just was confused about your statement, that you can't use `sys-log` as this flag is specifically for systems without systemd.

**Comment by adcdam** [comment]
> I don't really like display managers. So, I'm sorry but, I can't help much here. I use automatic login from tty if, I'm the user and, only tty login if I'm root.

me neither but other people use them, and if i use one i use a terminal based one.

**Comment by adcdam** [comment]
Please don't kill me, leftwn is working fine with SDMM, i was expecting a black screen when launching i didn't test it with SDDM in my main pc that have Slackware current i tested in a laptop with Slackware 15 in that laptop, i didn't install theme in the laptop so i was expecting a black screen as i was seeing the image of SDDM i thought it didn't work until i hit super + shift + enter and a terminal started. So Leftwm doesn't have any problem with SDDM sorry!!!!!

**Comment by VuiMuich** [comment]
Glad it works for you now!
And really happy that leftwm is on slack now!

Also another case where #922 would have saved the day early on.

**Comment by adcdam** [comment]
Thanks!!
