### ISSUE TITLE
Exiting ToggleFullScreen sometimes does not return to previous layout

### ISSUE THREAD

**Issue by heisencoder** [leftwm/leftwm#927]
### Describe the bug

When running ToggleFullScreen twice (e.g., via a keyboard shortcut) if the current window was not previously the "Main" window, then when exiting full screen mode, the windows layout is switched so that the current window now occupies the "main" window slot.

### Expected behavior (optional)

The behavior of other windows managers that provide a full screen toggle is that pressing the toggle twice should result in exactly the same layout.

### Steps to reproduce (optional)

1. Select a layout with at least two windows.
2. Focus the window that is not the "main" window of the layout
3. Run ToggleFullScreen twice
4. Note that the current window has moved to the "main" window slot

### OS / Distro

Linux 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Additional System Information (optional)

```text
$ leftwm --version
leftwm 0.4.0, Git-Hash: 1cc3a4d
```

### LeftWM Check

```text
:: LeftWM version: 0.4.0
:: LeftWM git hash: 1cc3a4d
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK 
:: Checking theme . . .
ERROR: No theme folder or symlink `current` found.
```

**Comment by VuiMuich** [comment]
I have observed this as well at some point. Thanks for reporting.

**Comment by linde12** [comment]
Happening to me as well, v0.4.0 built from source on commit a631cfbc328d66538a06d401964dcfdc57a5b543

I will play around a bit, but i doubt i have the time to understand how this all works

**Comment by VuiMuich** [comment]
I had started to look into a fix and it seems that we should simply insert the window at the previous position where it was in the window list to fix this. I don't recall, what was not working with my patch though, but there was some issue I could not resolve then, so I didn't open a PR yet. 

If anyone interested in taking care of this, please go ahead and don't feel blocked by my attempt.
