### ISSUE TITLE
System crash with Visual Studio Code

### ISSUE THREAD

**Issue by uipoet** [leftwm/leftwm#93]
I normally use `dwm` as my window manager. Giving `leftwm` a try, most apps worked well, though Firefox had some crazy bugs where it would steal focus while I was typing in another window. I was all set to stick with `leftwm` and just use Brave instead when I experienced bizarre latency and ignored keys in Visual Studio Code which initially only locked up the editor itself, but eventually locked up my system to the point that holding down the power button was my only way to resolve. I like many things about this project, but can't make the switch until I am confident my editor will run without a hitch. Not sure how to begin debugging this locally to give you more to go on for reproducing.

**Comment by lex148** [comment]
Yikes, that is totally unacceptable! let me help you fix this one immediately!  Can you give me a little information about your setup. I want to try to reproduce the issue over here. 

Did you install LeftWM from source or did you use a package manager? 
What distro are you using?
Are you using a compositor like picom or compton?

**Comment by uipoet** [comment]
No worries, my setup let's me switch between `leftwm` and `dwm` pretty easily.

I use Arch Linux and I use `yay` to update periodically throughout the day.

Since `yay -S leftwm` failed to build without intervention and I'd love to learn Rust and contribute, I opted for forking and cloning locally to compile using the `master` branch. I added `~/.cargo/bin` to my `PATH` in `.zshenv`.

My `.xinitrc` is as follows: 

```sh
#!/bin/sh

# .xinitrc runs automatically when you run xinit or startx

# set display brightness to lowest value by default
xbacklight -set 0

# set background color
hsetroot -solid "#000000"
# Set monitor resolution and disable laptop display
xrandr --output DP-4 --mode 5120x1440 --output DP-3 --off

# Set background image
~/.fehbg

xrdb -merge ~/.Xresources

# keyboard model
setxkbmap -model thinkpad

# X11 keymap options found here: /usr/share/X11/xkb/rules/base.lst
# remap CapsLock key to Esc key, Shift+CapsLock for default
setxkbmap -option caps:escape_shifted_capslock

# keyboard repeat rate
xset r rate 300 50

# import environment variables into systemd users session
systemctl --user import-environment

# start systemd target for user services to follow
systemctl --user start graphical.target

#launch window manager
# exec dbus-launch leftwm
exec dbus-launch dwm
```

I wrote my own `systemd` user services that rely on that `graphical.target` and they are enabled so start up automatically without needing to pile up in the `.xinitrc` and can be restarted independently without leaving the window manager.

Services I used with `leftwm` are:
- `picom`
- `polkit-gnome`
- `polybar`
- `ssh-agent`
- `unclutter`

I've experienced the crashing with two separate ThinkPads (both quite new) using identical configuration.

**Comment by lex148** [comment]
@uipoet This sounds suspiciously like a bug we were having about 4 months ago. I have been testing the latest version of master for a good while for the next release. It is time, so I have gone ahead and pushed it. Would you please give yay an update and see if it resolves your issue. The AUR build should now work. 

I'm happy to keep debugging your issue, but this seams like the most logical place to start.

**Comment by uipoet** [comment]
@lex148 The AUR build does indeed work now and I haven't had any noticeable issues yet. Will report back here after a full day's use and close this issue. Thank you for your prompt attention on this!

**Comment by uipoet** [comment]
@lex148 Gratitude for the push. All was well running `lefwm` for a whole work day.
