### ISSUE TITLE
Latest commits break functionality

### ISSUE THREAD

**Issue by 0323pin** [leftwm/leftwm#933]
### Describe the bug

Until today I was running a build from 049a6b4a4f4881013c6f5029cbd057535332a370
Where, I've actually posted a question on the commit itself that has passed unnoticed.

Today, I did a rebuild from f4c45205f5558a0c9dfc3f2206f8b6b8c7c315da and hit several issues. Somethings are working but, most of it is not. Wallpaper is applied but, the bar is missing. Keybinding to launch programs work but, binding to switch from one window to another are not. Also window decorations, like borders are the default ones and not from my theme.

Not much but, see leftwm-check bellow

Any thoughts?

For now, I've reverted back to 049a6b4a4f4881013c6f5029cbd057535332a370 where I still have to figure out how to use the new leftwm-config command? But, priority to investigate what broke.

### OS / Distro

NetBSD-9.99.102, Rust-1.64.0

### LeftWM Check

```text
~ > leftwm check
thread 'main' panicked at 'ArgAction::Count is defaulted', /usr/pkgsrc/wip/leftwm/work/vendor/clap-4.0.18/src/parser/matches/arg_matches.rs:144:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exception: leftwm exited with 101
[tty 2], line 1: leftwm check

~ > RUST_BACKTRACE=1 leftwm check
deprecation: the legacy temporary assignment syntax is deprecated; use "tmp" instead
[tty 3], line 1: RUST_BACKTRACE=1 leftwm check
thread 'main' panicked at 'ArgAction::Count is defaulted', /usr/pkgsrc/wip/leftwm/work/vendor/clap-4.0.18/src/parser/matches/arg_matches.rs:144:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exception: leftwm exited with 101
[tty 3], line 1: RUST_BACKTRACE=1 leftwm check
```

**Comment by VuiMuich** [comment]
It's #920, with the bump of `clap` that broke things, pretty sure.
Sorry, I thought I tested it thoroughly enough, but obviously not.
Same thing got reported on discord.
I can look into it in about 4h from now. But if any one else wants to take a stab: go for it.

**Comment by Eskaan** [comment]
Will be fixed in #935

**Comment by 0323pin** [comment]
Please reopen, it's not fixed yet.
It's much, much better but, `lemonbar` does not load. `leftwm-check` reports no errors.
I'm again reverting to the commit from 3 days ago.

**Comment by Pyxels** [comment]
Can confirm, some eww widgets for me dont work:
Running `leftwm-state -w 1 -s {{workspace}}`
gives the following output:

```thread 'main' panicked at 'Mismatch between definition and access of `workspace`. Could not downcast to TypeId { t: 13834754221672687376 }, need to downcast to TypeId { t: 9611275717051495212 }
', /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.0.18/src/parser/error.rs:30:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

**Comment by 0323pin** [comment]
I do get the same thread panic reported by @Pyxels

**Comment by TornaxO7** [comment]
@0323pin @Pyxels fix incoming with https://github.com/leftwm/leftwm/pull/937/files

**Comment by Eskaan** [comment]
Also in #938 and #936 haha

**Comment by TornaxO7** [comment]
lmao xD

**Comment by 0323pin** [comment]
> @0323pin @Pyxels fix incoming with #937

Ops! Sorry for the thumbs-down, it of course a thumbs-up but, on mobile on a bus 😄

**Comment by 0323pin** [comment]
I'll rebuild in a few hours. Cheers.

**Comment by 0323pin** [comment]
Ok to close this now.
Thanks @TornaxO7 and @Eskaan 
Building from #937 fixes the remaining issues.
