### ISSUE TITLE
Repository information missing for theme when trying on rocky 9 vm

### ISSUE THREAD

**Issue by NicTanghe** [leftwm/leftwm#941]
### Describe the bug

When trying to apply one of my themes on my test install, I get repository information missing for theme

### Expected behavior (optional)

the theme just works.
(it's a copy of the folder currently in use on hoist system)

### Steps to reproduce (optional)

isntall on rockylinux. Using cargo
make simple theme and try to load it using leftm-theme

### Relevant log output (optional)

```text
Fetching themes . . .

Available themes:
   community/Ascent: A LeftWM theme
   community/Desire: A LeftWM theme
   community/Epitaph: A LeftWM theme
   community/Garden: A LeftWM theme
   community/Ocean-night: A LeftWM theme
   community/Serika: A LeftWM theme
   community/Zexanima: A LeftWM theme
   community/Blood-Moon: A LeftWM theme
   LOCAL/Tanhe-simp: A LeftWM theme-Installed
   LOCAL/Tanhe: A LeftWM theme-Installed
[tagnhe@localhost ~]$ leftwm-theme install "Tanhe"
Looking for theme . . .
Repository information missing for theme
```

### OS / Distro

rockylinux 9.0 (Blue Onyx) vm

### Additional System Information (optional)

```text
VM
```

### LeftWM Check

```text
[tagnhe@localhost ~]$ leftwm-check
:: LeftWM version: 0.4.0
:: LeftWM git hash: NONE
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
ERROR: No theme folder or symlink `current` found.
```

**Comment by VuiMuich** [comment]
How did you install the theme(s)? It might be, that `leftwm-theme` is looking for an entry in `~/.config/leftwm/themes.toml`. Have had a look at the `leftwm-theme` docs?

**Comment by NicTanghe** [comment]
hm cant open the vm,
wel i`m installing on metal today lets hopw all goe`s well

**Comment by NicTanghe** [comment]
I went to rhel8 and no longer going to troubleshoot this.
