### ISSUE TITLE
using sxhkd with leftwm

### ISSUE THREAD

**Issue by EmanuelBoehm** [leftwm/leftwm#95]
Coming from the bspwm side, I'd like to use my commonly used keybindings defined in sxhkd. Is there a practical way to use such external key daemons? If so it may be very useful to write a documentation for it.

**Comment by lex148** [comment]
Funny you should ask. 
LeftWM currently supports being controlled using EWMH calls or an external Pipe file. Currently the external pipe file has very limited support. I am in the process of updating it so you can send it significantly more commands. If you are just a little patient with this one, I think I will be able to help you out.

**Comment by lex148** [comment]
Ok, so I have been working to expand the list of external command LeftWM supports as well has having better documentation for it. 

Take a look at this. 
[https://github.com/leftwm/leftwm/tree/master/themes/controlling_leftwm](https://github.com/leftwm/leftwm/tree/master/themes/controlling_leftwm)

I would love your feedback if this was helpful in solving your issue.

**Comment by EmanuelBoehm** [comment]
Hey @lex148, 
the recent changes are pretty good as far as I can tell (played around with them for some time now).
Sorry if I wasn't clear in the first post but I've asked for an option to unbind the build in keyboard manager (already wrote a script which converts my sxhkd keybindings to the config.toml file).
I'd like to help but I fear that the project has already to much complexity to just drop in without fearing to break some things. It may be very helpful if you'd make a new post with current things I (or we) can help you with.

**Comment by lex148** [comment]
could you comment out all the keybind options in the config.toml file?
If there aren't any keybind options, LeftWM will just ignore the keyboard.
