### ISSUE TITLE
Issue trying to install leftwm from Gentoo GURU overlay 

### ISSUE THREAD

**Issue by senkowo** [leftwm/leftwm#954]
When I try to emerge leftwm on my Gentoo machine, it demands dev-lang/rust as a dependency. I already have dev-lang/rust-bin, a binary version of the former, installed. I wanna be able to use rust-bin instead, so I don't have to compile rust from source. I don't know a way to get around this unless I do some tedious hacking or alter the ebuild file. The ebuild file on the GURU Overlay includes dev-lang/rust but not dev-lang/rust-bin as an alternative dependency:
Package location: https://gpo.zugaina.org/x11-wm/leftwm/
Ebuild file: https://data.gpo.zugaina.org/guru/x11-wm/leftwm/leftwm-0.4.0.ebuild
```
DEPEND="
	x11-libs/libXinerama:0=
	x11-apps/xrandr:0=
	x11-base/xorg-server:0=
	>=dev-lang/rust-1.52.0
"
```
I'm not an expert in making ebuilds, but to have rust-bin as an alternative dependency to rust, I think this could be altered to:
```
DEPEND="
	x11-libs/libXinerama:0=
	x11-apps/xrandr:0=
	x11-base/xorg-server:0=
	|| ( >=dev-lang/rust-1.52.0 >=dev-lang/rust-bin-1.52.0 )
"
```
I haven't tested this updated ebuild on my machine locally, so I'm not completely sure this works.
  
I wasn't too sure whether to report this on Gentoo's Bugzilla or here.
And it's my first time submitting an issue on Github, so sorry if I did something silly.

Edit: I looked through the metadata.xml file on the overlay and found the maintainer's email:
degni.public@gmail.com Luciano Degni
Perhaps I should send them an email asking about this if they don't see this issue.

**Comment by VuiMuich** [comment]
Thank you for reporting this.

AFAIK none of the regular contributors uses Gentoo, so I'm not sure how much help we can provide from here. 
Nevertheless it is useful you brought this here, so others looking for help might find this.

Emailing the maintainers of the package is probably the best idea. You might want to mention to them that we are using rust 1.60 as our MSRV, so they should bump it to get all our deps compiled correctly.
Also might be worth to change the dependency away from `rust-bin` to `cargo`, as does the AUR package. Reasoning for this dep change can be found in the package comments.

**Comment by Eskaan** [comment]
Looking at the ebuild file, it does not seem to support the lefthk flag/feature.
Neither is it mentioned in the compile function nor does it try copying leftwm-worker at install.

**Comment by senkowo** [comment]
I sent an email to the package maintainer, so I'll put their reply here if I get one back.

In the meantime, I made a copy of the ebuild, modified it, and compiled it locally. It properly compiled, but when I try to run leftwm from a tty using startx, xorg closes and an error says:
```
thread 'main' panicked at 'failed to start lefthk: 0s { code: 2, kind: NotFound, message: "No such file or directory" }', leftwm/src/bin/leftwm.rs:209:10 
```
So perhaps the ebuild is broken due to the missing lefthk flag?


Note: I launched it from xinitrc using:
```
exec dbus-launch --sh-syntax --exit-with-session leftwm 
```

Also, here's the modified ebuild I compiled: https://github.com/senkowo/refract/blob/main/x11-wm/leftwm/leftwm-0.4.0.ebuild

**Comment by Eskaan** [comment]
The compiled lefthk binary is not being installed. I think `dobin lefthk-worker` in src_install() should do the trick.

**Comment by VuiMuich** [comment]
Interesting, I am pretty sure I read another `ebuild` the other day, where it says `dobin left*`...

**Comment by senkowo** [comment]
After some tinkering, I got it working!

I tried adding ``` dobin lefthk-worker ``` to the ebuild, which fixed the previous error. However, I was confronted by a new error:
```
thread 'main' panicked at 'Couldn't setup journald-logger. Are you sure journald is running?: 0s { code: 2, kind: NotFound, message: "No such file or directory" }', leftwm/src/utils/log/journald.rs:15:10
```
I'm running open-rc, not systemd, so I'm not sure why it expects journald. I then took a break from trying to get this one particular ebuild to work.

I instead began looking into the ebuild here: 
https://gitweb.gentoo.org/repo/proj/guru.git/tree/x11-wm/leftwm/leftwm-0.4.0.ebuild
It seems like this ebuild is by the same package maintainer, but this version is not upstream in the standard GURU repos yet. 
Compared to the one that is upstream, it now has a patch that fixes an issue with builds failing and a flag for lefthk implemented, among other things. I copied and pasted the ebuild + patch into my local overlay and tested it out. Everything seems to work perfectly so far. I did modify the ebuild to accept rust-bin as an alternative dependency to rust, but no other changes. I did notice some minor bugs and incomplete details with the ebuild, like a blank description in the lefthk flag, but those are rather insignificant and I'm sure they will be fixed by the maintainer in the future.

I would imagine that the ebuild linked above will be put upstream into the standard GURU repos in the near future, and perhaps some more changes will be made to it before then. 

But in the meantime, I'll be using this slightly-modified copy I'm storing in a local repo:
https://github.com/senkowo/refract/tree/main/x11-wm/leftwm

**Comment by senkowo** [comment]
I wouldn't recommend it, but if anyone can't get leftwm to compile and work on Gentoo no matter what they try, then perhaps they could add my overlay and install it using the ebuild there. 
```
eselect repository add refract git https://github.com/senkowo/refract
emaint sync -r refract
emerge -av leftwm
```
And to remove the overlay, once the ebuild in the standard guru repos start working:
```
eselect repository remove refract
```
I'm not too experienced with Gentoo so I can't guarantee that my repo will work perfectly.

**Comment by senkowo** [comment]
Update: the ebuild on the Guru overlay has been updated so it should be usable now. However, it doesn’t support rust-bin as a dependency, so if you really want that, then you can continue to use the ebuild in my overlay (if it works).

**Comment by senkowo** [comment]
Update: not using Gentoo anymore so the overlay is no longer maintained
