### ISSUE TITLE
Scratchpad spawns new window in layout; not scratchpad

### ISSUE THREAD

**Issue by bobossler** [leftwm/leftwm#958]
### Describe the bug

Same as closed issue #720
When I trigger the ScratchPad, it opens as if it was not a scratchpad but a normal window. When I trigger the keybinding again, It should disappear, but yet another terminal window.

### Expected behavior (optional)

Scratchpad should appear and disappear.

### Steps to reproduce (optional)

Here is my config.ron
```
//  _        ___                                      ___ _
// | |      / __)_                                   / __|_)
// | | ____| |__| |_ _ _ _ ____      ____ ___  ____ | |__ _  ____    ____ ___  ____
// | |/ _  )  __)  _) | | |    \    / ___) _ \|  _ \|  __) |/ _  |  / ___) _ \|  _ \
// | ( (/ /| |  | |_| | | | | | |  ( (__| |_| | | | | |  | ( ( | |_| |  | |_| | | | |
// |_|\____)_|   \___)____|_|_|_|   \____)___/|_| |_|_|  |_|\_|| (_)_|   \___/|_| |_|
// A WindowManager for Adventurers                         (____/
// For info about configuration please visit https://github.com/leftwm/leftwm/wiki

#![enable(implicit_some)]
(
    modkey: "Mod4",
    mousekey: "Mod4",
    workspaces: [],
    tags: [
        "Term",
        "Browse",
        "Misc",
        "Files",
        "Music",
        "6",
        "7",
        "8",
        "9",
    ],
    max_window_width: None,
    layouts: [
        MainAndVertStack,
        MainAndHorizontalStack,
        MainAndDeck,
        GridHorizontal,
        EvenHorizontal,
        EvenVertical,
        Fibonacci,
        LeftMain,
        CenterMain,
        CenterMainBalanced,
        CenterMainFluid,
        Monocle,
        RightWiderLeftStack,
        LeftWiderRightStack,
    ],
    insert_behavior: Bottom,
    scratchpad: [
        (name: "ScrTerminal", value: "alacritty", x: 860, y: 390, height: 300, width: 200),
    ],
    window_rules: [
      // spawn Firefox on tag 2
      ( window_class: "Firefox", spawn_on_tag: 2 ),
      ( window_class: "music", spawn_on_tag: 5 ),
    ],
    layout_mode: Workspace,
    disable_current_tag_swap: false,
    disable_tile_drag: false,
    disable_window_snap: true,
    focus_behaviour: Sloppy,
    focus_new_windows: true,
    single_window_border: true,
    sloppy_mouse_follows_focus: true,
    keybind: [
        (command: Execute, value: "rofi -show drun", modifier: ["modkey"], key: "x"),
        (command: Execute, value: "alacritty", modifier: ["modkey", "Shift"], key: "Return"),
        (command: CloseWindow, value: "", modifier: ["modkey", "Shift"], key: "q"),
        (command: SoftReload, value: "", modifier: ["modkey", "Shift"], key: "r"),
        (command: Execute, value: "loginctl kill-session $XDG_SESSION_ID", modifier: ["modkey", "Shift"], key: "x"),
        (command: Execute, value: "i3lock -c 898e8c -e -f && xset dpms force off", modifier: ["Alt", "Control"], key: "l"),
        (command: MoveToLastWorkspace, value: "", modifier: ["modkey", "Shift"], key: "w"),
        (command: SwapTags, value: "", modifier: ["modkey"], key: "w"),
        (command: MoveWindowUp, value: "", modifier: ["modkey", "Shift"], key: "k"),
        (command: MoveWindowDown, value: "", modifier: ["modkey", "Shift"], key: "j"),
        (command: MoveWindowTop, value: "", modifier: ["modkey"], key: "Return"),
        (command: FocusWindowUp, value: "", modifier: ["modkey"], key: "k"),
        (command: FocusWindowDown, value: "", modifier: ["modkey"], key: "j"),
        (command: NextLayout, value: "", modifier: ["modkey", "Control"], key: "k"),
        (command: PreviousLayout, value: "", modifier: ["modkey", "Control"], key: "j"),
        (command: FocusWorkspaceNext, value: "", modifier: ["modkey"], key: "l"),
        (command: FocusWorkspacePrevious, value: "", modifier: ["modkey"], key: "h"),
        (command: MoveWindowUp, value: "", modifier: ["modkey", "Shift"], key: "Up"),
        (command: MoveWindowDown, value: "", modifier: ["modkey", "Shift"], key: "Down"),
        (command: FocusWindowUp, value: "", modifier: ["modkey"], key: "Up"),
        (command: FocusWindowDown, value: "", modifier: ["modkey"], key: "Down"),
        (command: NextLayout, value: "", modifier: ["modkey", "Control"], key: "Up"),
        (command: PreviousLayout, value: "", modifier: ["modkey", "Control"], key: "Down"),
        (command: FocusWorkspaceNext, value: "", modifier: ["modkey"], key: "Right"),
        (command: FocusWorkspacePrevious, value: "", modifier: ["modkey"], key: "Left"),
        (command: GotoTag, value: "1", modifier: ["modkey"], key: "1"),
        (command: GotoTag, value: "2", modifier: ["modkey"], key: "2"),
        (command: GotoTag, value: "3", modifier: ["modkey"], key: "3"),
        (command: GotoTag, value: "4", modifier: ["modkey"], key: "4"),
        (command: GotoTag, value: "5", modifier: ["modkey"], key: "5"),
        (command: GotoTag, value: "6", modifier: ["modkey"], key: "6"),
        (command: GotoTag, value: "7", modifier: ["modkey"], key: "7"),
        (command: GotoTag, value: "8", modifier: ["modkey"], key: "8"),
        (command: GotoTag, value: "9", modifier: ["modkey"], key: "9"),
        (command: MoveToTag, value: "1", modifier: ["modkey", "Shift"], key: "1"),
        (command: MoveToTag, value: "2", modifier: ["modkey", "Shift"], key: "2"),
        (command: MoveToTag, value: "3", modifier: ["modkey", "Shift"], key: "3"),
        (command: MoveToTag, value: "4", modifier: ["modkey", "Shift"], key: "4"),
        (command: MoveToTag, value: "5", modifier: ["modkey", "Shift"], key: "5"),
        (command: MoveToTag, value: "6", modifier: ["modkey", "Shift"], key: "6"),
        (command: MoveToTag, value: "7", modifier: ["modkey", "Shift"], key: "7"),
        (command: MoveToTag, value: "8", modifier: ["modkey", "Shift"], key: "8"),
        (command: MoveToTag, value: "9", modifier: ["modkey", "Shift"], key: "9"),
        (command: ToggleScratchPad, value: "ScrTerminal", modifier: ["modkey"], key: "s"),
        (command: Execute, value: "powermenu.sh", modifier: ["modkey"], key: "p"),
        (command: Execute, value: "firefox", modifier: ["modkey"], key: "b"),
        (command: Execute, value: "kitty --class music ncmpcpp", modifier: ["modkey"], key: "m"),
    ],
    state_path: None,
)
```
Trigger the keybinding modkey+s (Super+s) and new windows will appear instead of toggling a scratchpad.

Note:  Super+s is not bound anywhere else

### Relevant log output (optional)

```text
Cannot find any log messages. Nothing appears in journalctl.
```

### OS / Distro

Linux system76-pc 6.0.6-76060006-generic #202210290932~1667401208~22.04~d2df702 SMP PREEMPT_DYNAMIC Wed N x86_64 x86_64 x86_64 GNU/Linux

### Additional System Information (optional)

I use OS/Distro - `Pop!OS 22.04`

I have `gdm3` as a session manager and run leftwm from my `/usr/share/xsessions/leftwm.desktop`

```text
[Desktop Entry]
Encoding=UTF-8
Name=LeftWM
Comment=A window manager for the adventurer
TryExec=leftwm
Exec=leftwm
Type=Application
Keywords=wm,tiling,rust
DesktopNames=LeftWM
```

### LeftWM Check

```text
~/.config/leftwm ➜ leftwm-check
:: LeftWM version: 0.4.0
:: LeftWM git hash: 6a9c9ce
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```

*Edit by mod: fixed a view minor formatting things*

**Comment by samuelabreu** [comment]
It happens also on my Ubuntu 22.10, moving scratchpad section up doesn't make any difference.

**Comment by VuiMuich** [comment]
Do you have any scripts that run after the terminal got created?
Can you try `wmctrl -l` to find the window?

**Comment by samuelabreu** [comment]
I've tried with alacritty, kitty, xterm and many others, nothing works.

wmctrl-l list all windows, and spawn ones only shows:
`0x09200002  2 hostname Alacritty`
among others 

My config:
```    
  scratchpad: [
        (name: "Scratch",
        value: "/home/samuel/.cargo/bin/alacritty",
        x: 10,
        y: 10,
        height: 400,
        width: 300 
        ),
    ],
    keybind: [
        (command: ToggleScratchPad, value: "Scratch", modifier: ["modkey"], key: "t"),
    ],
```

**Comment by bobossler** [comment]
I have no scripts running after Scratchpad opens. I ran wmctrl -l and the output for the new window is:
0x04000004  0 system76-pc Alacritty

For completeness, I tried the toggle again, and it opened another new window. The wmctrl -l output for the newest window is: 0x04a00004  0 system76-pc Alacritty

Like @samuelabreu , I have tried multiple terminals (alacritty, kitty, etc.) with no luck.

**Comment by VuiMuich** [comment]
> EDIT I have no scripts running after Scratchpad opens, meaning I am not running htop or any other terminal application or shell script. However, my .zshrc does run a fortune/cowsay, a colorscript for ascii art, and I use the Starship prompt. I did try disabling all three of those items within my .zshrc, but no change in behavior for the scratchpad.

`-cowsay` for me, and I use fish as my `chsh`

> I ran wmctrl -l and the output for the new window is: 0x04000004 0 system76-pc Alacritty
> 
> For completeness, I tried the toggle again, and it opened another new window. The wmctrl -l output for the newest window is: 0x04a00004 0 system76-pc Alacritty
> 
> Like @samuelabreu , I have tried multiple terminals (alacritty, kitty, etc.) with no luck.

When you get the second window, what happens to the first one? Is it still listed by `wmctrl`?

**Comment by bobossler** [comment]
> When you get the second window, what happens to the first one? Is it still listed by `wmctrl`?

Yes, the first 'scratchpad' is still listed by 'wmctrl'

Here are three complete wmctrl outputs:
1) Current state, no scratchpads
0x02800002  0         N/A polybar-mainbar0_DP-1
0x01e00002  0         N/A polybar-mainbar1_DP-2
0x02200004  0 system76-pc Alacritty
0x0340002c  1 system76-pc Scratchpad spawns new window in layout; not scratchpad · Issue #958 · leftwm/leftwm — Mozilla Firefox
0x03600004  0 system76-pc Alacritty
0x04200004  2 system76-pc Alacritty

2) After using Super+s to open a scratchpad - no scratchpad, just a new window
0x02800002  0         N/A polybar-mainbar0_DP-1
0x01e00002  0         N/A polybar-mainbar1_DP-2
0x02200004  0 system76-pc Alacritty
0x0340002c  1 system76-pc Scratchpad spawns new window in layout; not scratchpad · Issue #958 · leftwm/leftwm — Mozilla Firefox
0x03600004  0 system76-pc Alacritty
0x04200004  2 system76-pc Alacritty
0x04c00004  0 system76-pc Alacritty

3) After using Super+s to 'close' the scratchpad - another window opens
0x02800002  0         N/A polybar-mainbar0_DP-1
0x01e00002  0         N/A polybar-mainbar1_DP-2
0x02200004  0 system76-pc Alacritty
0x0340002c  1 system76-pc Scratchpad spawns new window in layout; not scratchpad · Issue #958 · leftwm/leftwm — Mozilla Firefox
0x03600004  0 system76-pc Alacritty
0x04200004  2 system76-pc Alacritty
0x04c00004  0 system76-pc Alacritty
0x05600004  0 system76-pc Alacritty

**Comment by samuelabreu** [comment]
While i was testing on a virtual machine with clean install, i notice on first ToggleScratchPad:

`no active scratchpad found for name ScratchPadName("Alacritty"). Creating a new one`

And hitting again i get:

```
Dead window in scratchpad found, discard: window PID: 115876
no active scratchpad found for name ScratchPadName("Alacritty"). Creating a new one
```

But i found a workaround, i first create an alacritty window normally, then i use this keybind:

`        (command: AttachScratchPad, value: "Alacritty", modifier: ["modkey", "Shift"], key: "t"),`

Then ToggleScratchPad works ok, but if i quit it (alacritty on scratchpad window), it stop working.

**Comment by bobossler** [comment]
> While i was testing on a virtual machine with clean install, i notice on first ToggleScratchPad:
> 
> 
> 
> `no active scratchpad found for name ScratchPadName("Alacritty"). Creating a new one`
> 
> 
> 
> And hitting again i get:
> 
> 
> 
> ```
> 
> Dead window in scratchpad found, discard: window PID: 115876
> 
> no active scratchpad found for name ScratchPadName("Alacritty"). Creating a new one
> 
> ```
> 
> 
> 
> But i found a workaround, i first create an alacritty window normally, then i use this keybind:
> 
> 
> 
> `        (command: AttachScratchPad, value: "Alacritty", modifier: ["modkey", "Shift"], key: "t"),`
> 
> 
> 
> Then ToggleScratchPad works ok, but if i quit it (alacritty on scratchpad window), it stop working.

Nice catch! What log did you find the messages in? I never found any messages. I'm also gonna try out your workaround later tonight.

**Comment by samuelabreu** [comment]
On my ubuntu is /var/log/syslog

**Comment by samuelabreu** [comment]
Further debugging, here: https://github.com/leftwm/leftwm/blob/2303e0fc7adec7c56ce674926aabc4d7db2cbc0f/leftwm-core/src/utils/child_process.rs#L334  it executes command using `sh -c`, after this 2 pids are running:

```
samuel    135624  0.0  0.0   2736   956 tty2     S+   23:12   0:00 sh -c /usr/local/bin/alacritty
samuel    135625  0.3  5.5 894652 113212 tty2    Sl+  23:12   0:00 /usr/local/bin/alacritty
```

And i found out it saves first pid on state.active_scratchpads, but when reach https://github.com/leftwm/leftwm/blob/2303e0fc7adec7c56ce674926aabc4d7db2cbc0f/leftwm-core/src/handlers/window_handler.rs#L366, window.pid is the second pid (coming from event_loop() i guess)

I'll have to sleep now, but i hope info above can help.

**Comment by bobossler** [comment]
The workaround works for me as well. This is good; I can work with this while the rest of it is debugged.

**Comment by VuiMuich** [comment]
> Then ToggleScratchPad works ok, but if i quit it (alacritty on scratchpad window), it stop working.

Well, when you quit alacritty, the process of course gets killed, so your scratchpad is gone. You would after attaching the scratchpad use `ToggleScratchPad` to toggle this scratchpad on and off.

It seems odd to me, that `exec_shell` is used to launch the scratchpad and not spawn the command directly. If you have time to test if adding a variant method `exec_direct` that skips the `sh -c` does better would be awesome.

**Comment by samuelabreu** [comment]
You will change this? If you can't i can try to make a pull request to get this exec command from config (and if don't exists use  `sh -c` as default.

**Comment by FranLMSP** [comment]
Reminds me to an issue I opened a while ago: #502 (which got closed because there was a fix for a latter issue I reported there as well).
I noticed that it also happens with Flatpak applications, they struggle to work as scratchpads, they are launched as normal windows instead.
Also: https://github.com/leftwm/leftwm/issues/502#issuecomment-932987432

**Comment by barkyq** [comment]
I also have this issue...
