### ISSUE TITLE
Changing main width doesn't work in fibonacci layout

### ISSUE THREAD

**Issue by mathias234** [leftwm/leftwm#96]
There seems to be no way to change the width of the main window in a (main and vert) layout. This functionality is present in most tiling WMs

**Comment by mathias234** [comment]
I did an implementation of this on my fork https://github.com/mathias234/leftwm/commit/7ecb1d23bd05ef89a0f79bea23260f8c21b0a4bf

**Comment by hertg** [comment]
Wait, this one isn't closed. It still doesn't work in the fibonacci layout
