### ISSUE TITLE
Strange bug with some themes

### ISSUE THREAD

**Issue by ChickenNuggetsK** [leftwm/leftwm#965]
### Describe the bug

When I try to use the theme "leftwm-arch-one-dark" after changing the toml file to a ron file with `leftwm-theme theme.toml` it only display the up bar with some strange text like `thread 'main' panicked at 'failled printing to stdout: Broken pipe (os error 32)', library/std/src` (and I can't read the rest) and I can't do anithing, except exit leftwm with ctrl+alt+f2

So I tried to downgrade to leftwm 0.3.x and install the theme with `leftwm-theme install arch-one-dark` and apply it with `leftwm-theme apply arch-one-dark` but it do the same thing

I've also tried to use the Ocean-night theme with leftwm 0.4.x but is don't even display something

Sorry for the possibly bad english

### Expected behavior (optional)

The theme should work

### Steps to reproduce (optional)

for both of the 2 way, install all depedencies of the theme with `sudo pacman -S picom dunst polybar playerctl` and `paru -S spotify`

1. install leftwm with `paru -S leftwm`
2. download the theme with `git clone https://github.com/jamesbaker1901/leftwm-arch-one-dark.git`
3. go to the right directory with `cd leftwm-arch-one-dark/`
4. update the theme with `leftwm-theme migrate theme.toml`
5. replace the line `leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"` of the `up` script with `leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"`
6. apply the theme with `mkdir -p ~/.config/leftwm/themes`, `cd ~/.config/leftwm/themes` and `ln -s PATH_TO_THE_THEME current`
7. reboot your computer and login

or

1. download leftwm 3.0.x with `git clone https://github.com/leftwm/leftwm.git --branch v0.3.x`
2. go to the right directory with `cd leftwm`
3. build it with `cargo build --release`
4. install it with `sudo install -s -Dm755 ./target/release/leftwm ./target/release/leftwm-worker ./target/release/lefthk-worker ./target/release/leftwm-state ./target/release/leftwm-check ./target/release/leftwm-command -t /usr/bin`
5. copy leftwm.desktop to the xsession folder with `sudo cp leftwm.desktop /usr/share/xsessions/`
6. download the theme with `leftwm-theme install arch-one-dark`
7. apply the theme with `leftwm-theme apply arch-one-dark`
8. reboot your computer and login

### OS / Distro

arch linux

### LeftWM Check

```text
:: LeftWM version: 0.3.0
:: LeftWM git hash: d9abb19
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking Keybinds . . .
    -> All keybinds OK
:: Checking environement . . .
    -> Environment OK
:: Checking theme . . .
Warn: TOML as config format is about to be depreceated.
      Please consider migrating to RON or contact the theme creator about this topic.
      Note: make sure the `up`script is loading the correct theme file
ERROR: File not found: theme.ron
```

**Comment by VuiMuich** [comment]
Welcome adventurer!

To fix the `panic` you most probably are missing the `jq` package (it is in the `community` package sources of arch).
I have yet to figure out what is wrong with the `tags` display, though.

Also the git hash is supposed to be of the `0.4.0` release, so something did not go right with your downgrade I guess.
I tested with:
```
~ >>> leftwm check
:: LeftWM version: 0.4.0
:: LeftWM git hash: 4ac9ddc
```

**Comment by ChickenNuggetsK** [comment]
Thanks you very much, it work better now!
