### ISSUE TITLE
Dont use systemd logging by default

### ISSUE THREAD

**Issue by linde12** [leftwm/leftwm#969]
### Describe the enhancement

I know there was an issue https://github.com/leftwm/leftwm/pull/508 which requested that systemd logging be used by default, but it makes no sense shipping e.g. a Void Linux binary which uses runit.

Idk the reasoning behind this, but wouldnt it be better to default to syslog? `sudo xbps-install leftwm` is useless to me, i have to build it myself with --featuers=syslog regardless

### How important is this enhancement to you?

My workflow is impaired without it

### How important do you think is this enhancement for the average LeftWM user?

Their workflow is likely impaired without it

**Comment by 0323pin** [comment]
> sudo xbps-install leftwm is useless to me, i have to build it myself with --featuers=syslog regardless

The default build on Void doesn't use the `journald-log` feature. Have a look at the **configure_args=** in the build template, `--no-default-features --features lefthk,sys-log`, https://github.com/void-linux/void-packages/blob/master/srcpkgs/leftwm/template

**Comment by linde12** [comment]
Thanks @0323pin, i was still having issues with the official image and i jumped to conclusions. I mightve gotten the error message mixed up with a custom build.

I still feel using syslog over journald is relevant, but closing this issue as it is misleading!
