### ISSUE TITLE
SwapTags without having visited a previous tag causes error

### ISSUE THREAD

**Issue by linde12** [leftwm/leftwm#971]
### Describe the bug

I'm getting some weird behavior when doing SwapTags without actually having visited another tag yet.

This swaps the main window with one of the windows in the right stack and gives some error message output above my polybar saying something like IoError ConnectionRefused.

### Expected behavior (optional)

No-op, should do nothing.

### Steps to reproduce (optional)

1. Start or reload LeftWM
2. Spawn some windows, e.g. browser and terminal
3. Do SwapTags (default modkey+w) without visiting any other tag first

### OS / Distro

Linux botnet 6.0.9_1 #1 SMP PREEMPT_DYNAMIC Fri Nov 18 16:45:48 UTC 2022 x86_64 GNU/Linux (Void Linux)

### Additional System Information (optional)

```text
Built from master v0.4.0 with --features=lefthk,syslog, running Void Linux. Added some traces to debug another issue (hence modified from leftwm-check) Using basic_polybar theme.
```

### LeftWM Check

```text
:: LeftWM version: 0.4.0
:: LeftWM git hash: a631cfb-modified
:: Enabled features: lefthk lefthk-core syslog-tracing sys-log
:: Checking feature dependencies . . .
    -> lefthk OK
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK (has XDG_RUNTIME_DIR)
:: Checking theme . . .
ERROR: Could not parse theme file: 1:16: Expected option
```

**Comment by VuiMuich** [comment]
:thinking: actually this method starts with exactly a check if the history is at least two items long:
https://github.com/leftwm/leftwm/blob/de88c4a5d8463f187c8b2ac7b1cea0aff85c1178/leftwm-core/src/handlers/command_handler/mod.rs#L361-L383

Can you possibly grab the exact error from polybar logs?

**Comment by linde12** [comment]
Ah, maybe its unrelated. I will try to find the logs for polybar once im home and post them here!

**Comment by linde12** [comment]
Unable to reproduce the error message right now, but the weird behavior with windows switching places still happens. Maybe you can reproduce this issue?

**Comment by VuiMuich** [comment]
Sorry for being a little late with my reply.
I forget to test this with a fresh session, but I just set up a new VR with Arch the other day, I can try to reproduce it there.
