### ISSUE TITLE
Increase/decrease main stack size

### ISSUE THREAD

**Issue by linde12** [leftwm/leftwm#972]
### Describe the enhancement

Using `MainAndVertStack` it would be sweet if we could increase/decrease the number of windows that are in the main stack vs the vert stack. I use this frequently in awesomewm and it would be sweet to see it in LeftWM as well.

E.g.
1 window in main stack, 3 windows in right vert stack

IncreaseMainStackSize => 2 windows in main stack, 2 windows in vert stack
IncreaseMainStackSize => 1 windows in main stack, 3 windows in vert stack again
IncreaseMainHeight => like IncreaseMainWidth but vertically
DecreaseMainHeight => like DecreaseMainWidth but vertically

Awesome will treat the "main" as any other stack, just with a fixed number of windows allowed.

### How important is this enhancement to you?

Would be nice to have

### How important do you think is this enhancement for the average LeftWM user?

Would probably be nice to have

**Comment by VuiMuich** [comment]
Very interesting idea. @hertg is working on some major changes to the layout engine, as soon as this gets live in the `main` branch, this enhancement could be added fairly easy, I suppose.

**Comment by linde12** [comment]
Sweet, yeah its a nice-to-have but a useful feature nonetheless. Not deal breaking ofc!

**Comment by hertg** [comment]
Is this a duplicate of #516?
Yes my layout lib has this feature already implemented :)

**Comment by linde12** [comment]
It sure is @hertg, sorry about that! Closing this☺️
