### ISSUE TITLE
Maximize window

### ISSUE THREAD

**Issue by linde12** [leftwm/leftwm#973]
### Describe the feature

Coming from awesomeWM there is the concept of fullscreen and maximized. Fullscreen covers the entire screen, maximized covers everything except the bar (gets rid of the useless gaps and other windows)

Not sure how this would be implemented in LeftWM but would be useful when doing focused work but still wanting to e.g. see the clock in polybar.

### How important is this feature to you?

Would be nice to have

### How important do you think is this feature for the average LeftWM user?

Would probably be nice to have

**Comment by VuiMuich** [comment]
This would indeed be nice and has been requested in the past (not sure if tracked in another issue though).
Any contributions in that direction welcome.

**Comment by NicTanghe** [comment]
My request was similar but slightly diferent.
I needed a combination of this maximised and also have the window be permanently sorted to the  back.
You replied to me, it had something to do with window sorting.

THe issue is tracked here https://github.com/leftwm/leftwm/issues/943

**Comment by VuiMuich** [comment]
Indeed you request in #943 is slightly different, as the `fullscreen` intends to be ontop of the bar (and any reserved space at all), but the `maximise` respects that. But if I get you linked request right, maximising the window while respecting its floating children would be a viable solution as well, right?

**Comment by NicTanghe** [comment]
I dont realy know what that means and i think that whould problably give allot more edgecases where it doesn`t work but that is just a gues.

**Comment by arpandaze** [comment]
Hi @VuiMuich I am trying to implement this feature. I am not completely familiar with the codebase but I have glossed over for an hour. Here are the few features that I think needs to be implemented along with this:

- NBFull (No Border + Full) Layout
- Toggle Layout Command (Maybe ?? Optional temp layout for each tag which takes precedence over main layout)
- Command to Toggle Dock/Bars

Implementing these will also fix multiple issues I think.
- NBFull with bars hidden will be similar to fullscreen and scratchpads can appear over NBFull unlike Fullscreen
- Common way to toggle different types bars

What do you think?
