### ISSUE TITLE
Use regex to match window_class

### ISSUE THREAD

**Issue by ExistingProgrammer** [leftwm/leftwm#977]
### Describe the feature

Allow using Regex strings as arguments for `window_class`.
This argument:
![image](https://user-images.githubusercontent.com/71560815/204812320-17e15bd8-9774-42e5-a006-19d89136471c.png)
Would match all of these:
![image](https://user-images.githubusercontent.com/71560815/204812630-3f43bcfb-3eff-4323-9c20-72a607718188.png)
So we can assign all of them to workspace 3 at once and not need to create a different rule just for a different version number. I believe currently it is looking for the exact `Minecraft.*` string therefore nothing gets assigned to workspace 3.

### How important is this feature to you?

Would be nice to have

### How important do you think is this feature for the average LeftWM user?

Would probably be nice to have

**Comment by VuiMuich** [comment]
Approve this.
Also might be a worthy `good first`.
