### ISSUE TITLE
Themes up/down not running automatically

### ISSUE THREAD

**Issue by cjgratacos** [leftwm/leftwm#98]
Began testing leftwm, so far I am loving it. I am using Arch and installed the leftwm-git from the aur community. I found an issue where leftwm is not running the up script, I have to run it manually.
The theme is the polybar theme inside the themes folder. It is inside leftwm and I also have the theme symlinked to leftwm/current.

It would be awesome if there was a post on hacking/developing on leftwm so people like me who are really interesting in helping out have an idea on the how to and contribute to the project ;)

**Comment by lex148** [comment]
@cjgratacos would you please double check that the symlink is setup correctly?
if you run a command like this 
```
ls -alh ~/.config/leftwm/themes
```
you should see a folder called current pointed to the polybar folder. 

This is what I see when running the same command 
```
lex@lex-desktop ~> ls -alh ~/.config/leftwm/themes
total 32K
drwxr-xr-x 8 lex lex 4.0K May 14 17:09 ./
drwxr-xr-x 3 lex lex 4.0K Mar 27 10:47 ../
lrwxrwxrwx 1 lex lex   41 May 14 17:09 current -> /home/lex/src/leftwm/themes/basic_polybar/
```

**Comment by cjgratacos** [comment]
@lex148 thanks man, closing it was an idiotic mistake from my end current was in the root leftwm directory not inside the themes folder.
